{
  "hash": "40eb856269be79f01d4a3fa8405496c3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Applied replication for data skills\"\nsubtitle: \"One day – an introduction to the statistical methods\"\nformat: revealjs\n# Optional runs that this deck carries in its main flow (core-runs.lua\n# strips their .deepdive mark); the others stay on the d toggle.\ncore-runs: [methods, multiverse]\n---\n\n\n\n## {#today .darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.todaymeta}\nA full-day workshop · four parts · the methods in the foreground\n:::\n\n:::: {.todaybox}\n::: {.nonincremental}\n1. The case, and the vocabulary – one paper, three verdicts, five analysts, and what 'replication' names\n2. The question underneath – the estimand, the causal graph, and what fixed effects can and cannot fix\n3. Reproduce, then take the model apart – every axis of the specification menu, and what each one does to an estimate\n4. The multiverse – reading a specification curve, what it establishes, and the one path you declare\n:::\n::::\n\n::: {.todaytake}\nYou leave with: a reproduced result · an estimand and a DAG of your own · a working knowledge of every estimator on the menu · a preregistered analysis and your dot on the class curve\n:::\n\n::: {.todaymeta}\nWork along in your IDE, or on the browser lab page – solo or in pairs\n:::\n\n::: notes\nWelcome. A full day in four parts of ninety minutes, with the statistical methods in the foreground. The first part sets the case and the vocabulary: one published paper, put through three different checks with three different verdicts, and five analysts who reanalysed it and disagreed. The second part asks the question underneath the models – what quantity the claim is about, and what a causal graph commits you to. The third part is the reproduction and then the menu, taken apart axis by axis: outcome, scale, family, predictor form, estimator, sample and weights, each one shown doing something to an estimate. The fourth part is the multiverse those choices generate, how to read the curve and what it cannot tell you, and the single analysis you declare before you run it.\n:::\n\n## Two kinds of aim {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.small}\n**What I want you to understand**\n\n- Why 'replication' names three operations, and what each one tests\n- What an estimand is, and why analysts who disagree are often answering different questions\n- What a causal graph commits you to, and what two-way fixed effects adjust for\n- What each axis of a specification – outcome, family, predictor, estimator, sample, weights – does to an estimate\n- What a specification curve establishes, why hundreds of estimates are not hundreds of tests, and what preregistration settles\n:::\n:::\n::: {.column width=\"50%\"}\n::: {.small}\n**What I want you to be able to do**\n\n- Reproduce a published result to the third decimal\n- Write an estimand in one sentence, and a graph whose adjustment set you derived\n- Fit the same claim under pooled, fixed-effects and random-effects estimators and read each output\n- Vary one axis at a time and say what changed and why\n- Declare one analysis before you run it, and place it among the alternatives\n:::\n:::\n::::\n\n::: notes\nTwo columns, and today the left-hand one is heavier than usual. The conceptual aims are the ones that a methods course is for: the estimand, the graph, what each modelling choice does, and what a set of results together can and cannot establish. The right-hand column keeps every aim tied to something you do with your own hands – a reproduction, a graph, a set of fits, a declaration.\n:::\n\n## What you do not need today\n\n::: {.none}\n- No git, and no GitHub account\n- No OSF account – we will read OSF, not log into it\n- The browser lab needs no install: the browser is the whole toolchain\n- Nothing to sign up for; nothing leaves your machine except the results you choose to submit\n:::\n\n::: {.fragment}\n**Do this now:** open your workspace folder in your IDE, and open the browser lab tab beside it and leave it loading; the engine warms while we talk.\n:::\n\n::: notes\nBefore anything else, the reassurance slide. You do not need git today, or a GitHub account, or an OSF account – we will look at OSF from the outside, like readers. If you did not install anything, that is fine: the browser lab runs R inside the page itself, and there is a task at the end of this part where we get everybody set up properly. One thing to do right now, while I talk: Workspace people, open the workspace folder in your IDE; browser lab people, open the browser-lab tab now and just leave it – the engine loads in the background, so it will be ready long before you need it. If you are on the call with one screen, the cheatsheet has a tip: put the meeting on your phone or a second window and keep the lab full-screen.\n:::\n\n# PART 1 – The case and the vocabulary {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\nPart 1 · 90 minutes\n:::\n\n::: notes\nPart one. Why social science is argued about at all, in short; the matrix that separates reproducing from replicating; the five analysts who reanalysed the claim we work on today; and then the tools we use, in one slide, and getting everybody running before the break.\n:::\n\n## What are we doing when we do social science?\n\n:::: {.none}\n::: {.fragment}\nMaking **claims about the world** that could turn out to be wrong – and saying how we would know.\n:::\n\n::: {.fragment}\nA claim is not private. It is offered to others so they can **check it, use it, argue with it, build on it**.\n:::\n\n::: {.fragment}\nThat handover is the whole enterprise. Everything today is about whether it works.\n:::\n::::\n\n::: notes\nStart with the obvious question that nobody asks out loud. What are we actually doing? We are making claims about the world – claims that could turn out to be wrong, and that come with some statement of how we would find out. And a claim is not a private possession. You publish it so that other people can check it, use it, argue with it, and build on top of it. That handover is the entire enterprise. A finding nobody else can examine is not a contribution, it is an assertion. So when we ask today whether social science is in trouble, the question is really quite specific: does the handover work? Can someone else pick your finding up and do anything with it?\n:::\n\n## Three arguments that made people nervous {.smaller}\n\n::: {.small}\n- **The theory, 2005.** With small studies, small true effects, flexible designs and many teams chasing the same question, most published findings in a field can be false with nobody breaking any rules [@Ioannidis2005WhyMostPublished]\n- **The demonstration, 2011.** Give researchers only the flexibility they legitimately have – which cases to drop, which covariates to keep, when to stop collecting – and a **false-positive rate of 5% becomes over 60%** [@SimmonsEtAl2011FalsePositivePsychology]\n- **The subtlety, 2014.** You do not need many tests. In a **garden of forking paths**, a single test *chosen after looking at the data* already has the wrong p-value [@GelmanLoken2014StatisticalCrisisScience]\n:::\n\n::: notes\nThree arguments, in order of how uncomfortable they are. Ioannidis in 2005 made the theoretical case: put together small studies, small true effects, flexible designs and lots of teams chasing the same question, and you can show that most published findings in a field will be false without anybody breaking a single rule. Then Simmons, Nelson and Simonsohn demonstrated it in practice – give researchers only the flexibility they legitimately have, and you can push a five per cent false-positive rate above sixty. They proved it by 'showing', with real participants and real statistics, that listening to a Beatles song makes you younger. And Gelman and Loken added the subtlety that I find hardest to shake: you do not have to run many tests for this to bite. If the one test you ran was chosen after you looked at the data, its p-value is already wrong.\n:::\n\n## And then people counted {.smaller}\n\n::: {.small}\n- **100 psychology experiments**, replicated with high power and the original materials: **97%** of the originals were significant, **36%** of the replications were, and effect sizes roughly **halved** [@OpenScienceCollaboration2015EstimatingReproducibilityPsychological]\n- **161 researchers, 73 teams, one hypothesis** on immigration and support for social policy: **1,253** models, and no convergence on either sign or significance [@BreznauEtAl2022ObservingManyResearchers]\n:::\n\n::: {.fragment .small}\nDifferent fields, different designs, and in both **the result depended on who ran the analysis.**\n:::\n\n::: notes\nAnd then people stopped arguing and counted. The Open Science Collaboration took a hundred psychology experiments and replicated them properly – high power, original materials, the original authors consulted where possible. Ninety-seven per cent of the original studies had reported a significant result. Thirty-six per cent of the replications did, and the effect sizes came back at about half the original size. That is the study that made 'replication crisis' a phrase outside methodology seminars. The second one is closest to home, because it is ours: seventy-three teams of sociologists and political scientists, one hypothesis about immigration and support for social policy, more than twelve hundred models between them, and no agreement on the sign, let alone the significance. Different fields, different designs, and the same uncomfortable conclusion. The finding depends on the finder.\n:::\n\n## It is not mostly fraud {.smaller}\n\n::: {.small}\nThe mechanism is **ordinary and structural**:\n\n- Journals reward novel, clean, significant results – so that is what gets written up\n- Every analysis contains dozens of small defensible choices, and the analyst makes them while looking at the data\n- Nobody publishes the twelve specifications that did not work; the reader sees one\n- Data and code are usually not available, so nobody can check any of it\n:::\n\n::: {.fragment .small}\nAsk researchers anonymously, with an incentive to answer truthfully, and a **majority admit** to at least one of these practices – not fraud, the ordinary kind [@JohnEtAl2012MeasuringPrevalenceQuestionable]\n:::\n\n::: {.fragment .small}\nNone of these steps requires a dishonest person. That is exactly why the problem is hard: you cannot fix it by hiring better people.\n:::\n\n::: notes\nNow the important qualification, and I want to be emphatic about it. This is not mostly a story about fraud. Fraud exists and it is spectacular when it surfaces, but it is rare and it is not what these numbers are measuring. The mechanism is ordinary and it is structural. Journals want novel, clean, significant results, so that is what gets submitted. Every analysis contains dozens of small, individually defensible choices, and the analyst makes them while looking at the data, because how else would you make them. Nobody writes up the twelve specifications that did not work, so the reader sees one path through a garden with hundreds. And in most cases neither the data nor the code are available, so nobody can check any of it. John, Loewenstein and Prelec went and asked researchers directly, anonymously, with a mechanism designed to make truthful answers worth giving – and a majority admitted to at least one of these practices. Not one of those steps requires a bad actor. Which is exactly why the problem is hard: you cannot solve it by hiring better people. [pause] So suppose you did hire the best people you could find, gave them all the same data and the same question, and watched. Somebody did exactly that.\n:::\n\n## Twenty-nine teams, one question {.smaller}\n\n::: {.small}\n**The question.** Are football referees more likely to give red cards to dark-skinned players than to light-skinned ones?\n\n**The data.** One dataset, sent to everyone: 2,053 players in the top divisions of England, Germany, France and Spain, the 3,147 referees they played under, and **146,028 player–referee pairs**. Skin tone rated from profile photographs by two coders who did not know the research question.\n\n**The design.** Twenty-nine teams analysed it independently. They reviewed each other's approaches *before* anyone had seen a result, revised, and only then compared answers.\n:::\n\n::: {.fragment .small}\nThis is the first many-analysts study. Every one since is a variation on it – including the one you are inside today.\n:::\n\n::: {.src}\n@SilberzahnEtAl2018ManyAnalystsOne\n:::\n\n::: notes\nSo let me show you the study that started all of this, because everything after it, including our own day, is a variation on its design. Silberzahn and colleagues, twenty eighteen. The question is deliberately concrete: are football referees more likely to give red cards to dark-skinned players than to light-skinned ones? The data went to everyone identically – two thousand and fifty-three players in the top divisions of England, Germany, France and Spain, the three thousand referees they had played under, and a hundred and forty-six thousand player-referee pairs, with skin tone rated from profile photographs by two coders who were not told the research question. And then the part that makes it a study rather than a survey: twenty-nine teams analysed it independently, reviewed each other's approaches before anybody had seen a single result, revised, and only then compared answers. Nobody could tune their method to get a number they liked, because nobody knew what number anyone was getting.\n:::\n\n## All twenty-nine, side by side\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/silberzahn-forest-1.png){width=921.6}\n:::\n:::\n\n\n::: {.src}\n@SilberzahnEtAl2018ManyAnalystsOne, Figure 3, rebuilt from the published values at osf.io/gvm2z.\n:::\n\n::: notes\nAnd here is what came back. Read it as a list of twenty-nine analyses of one dataset. The odds ratios run from nought point eight nine to two point nine three – the low end says dark-skinned players were red-carded slightly *less* often – and the median is one point three one. Twenty of the twenty-nine intervals exclude one; nine do not. So about two thirds found an effect and a third did not, on identical data. [pause] Now look at the left column, because that is where the day's real subject is. The teams are grouped by the response distribution they assumed – linear, logistic, Poisson, and two that fit none of the three. That is not a detail of implementation. It is a decision each team made, defensibly, before touching the data, and it is the same kind of decision you will be making after lunch. Hold on to that grouping; we come back to it twice.\n:::\n\n## 'Replication' crises\n\n:::: {.none}\n::: {.fragment}\nAnother 'replication' crisis – terminological confusion?\n:::\n::: {.fragment}\nThe term 'reproducibility' has been used as a synonym for a number of different characteristics – reproducibility, robustness, replicability, repeatability, credibility, and trustworthiness.\n:::\n[[Successfully rerun the same code on the same data?]{colour=\"#b22222\"}]{.fragment}\n[[Re-analyse the same data a different way?]{colour=\"#1C69A8\"}]{.fragment}\n[[Collect fresh data and analyse it in the same way?]{colour=\"#4D179A\"}]{.fragment}\n[[Using the same data and same analysis but asking a different question?]{colour=\"#3C6301\"}]{.fragment}\n[[Asking the same question but answering it with fresh data and a different analysis?]{colour=\"#3BB8DB\"}]{.fragment}\n::::\n\n::: notes\nSo: twenty-nine competent teams, one dataset, and no agreement. Now notice what I have carefully not said yet – what *kind* of failure that is. And that turns out to be the whole difficulty, because part of the problem is the word itself. For years 'replication' covered everything: rerunning someone's code, re-analysing their data a different way, collecting new data altogether. Those are three different operations, answering three different questions – but because we called them all 'replication', the crisis debates had people talking past each other for a decade. So before any numbers, we need vocabulary.\n:::\n\n## The data $\\times$ analysis matrix\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/matrix-1.png){width=1152}\n:::\n:::\n\n\n::: {.src}\n@AlipourfardEtAl2021SystematizingConfidenceOpen; @NosekEtAl2025BriefGlossaryTerms\n:::\n\n::: notes\nHere is the whole framework on one slide, and if you take a single thing home today, make it this grid. The question stays the same throughout; what varies is the data and the analysis. Same data, same analysis – reproducibility: if I rerun your recipe, do I get your number? Same data but a different, justifiable analysis – robustness: does your finding survive my defensible choices? New data, same question – replicability. The fourth cell, new data and new analysis, is really generalisation, and we set it aside today. Sit with this for a moment – everything that follows this morning hangs off it.\n:::\n\n## Credibility is not truth\n\n::: {.scaled style=\"--fs: 0.9; --lh: 1.15\"}\n**Repeatability** is used when referring to reproducibility, robustness, and replicability as a constellation of concepts intended to assess whether answers to scientific questions are unchanged when different steps of the research process are repeated.\n\n**Credibility** and **trustworthiness** refer to the confidence one can have in research findings. Because scientific knowledge claims are tentative, they are *not* synonymous with truth.\n\nFor example, credibility is advanced by addressing potential competing interests in the conducting and reporting of research, by taking existing knowledge into account, by using methods that have been validated, by controlling for biases in the research context, by pursuing precise and reliable evidence, and by calibrating the strength of the claims to the uncertainty of the evidence.\n:::\n\n::: {.src}\n@NosekEtAl2025BriefGlossaryTerms\n:::\n\n::: notes\nThe glossary is worth reading slowly, because it separates two things we routinely run together. Repeatability is the umbrella: reproducibility, robustness and replicability as a family, all asking whether the answer survives repeating some step of the process. Credibility and trustworthiness are about how much confidence a finding deserves – and note the sentence in the middle. Because scientific claims are tentative, credibility is not the same as truth. A credible finding can be wrong. What credibility is built from is the list at the bottom: declared interests, validated methods, precise evidence, and claims calibrated to the uncertainty behind them. That last one is the one we will keep coming back to.\n:::\n\n## Quick check: credibility in the wild {.questionslide transition=\"fade-in none-out\"}\n\n::: {.none}\nYou submit your paper and replication package. It goes out to reviewers.\n\n- 'Reviewer 1' wants to ensure that your results are [reproducible]{.fragment .bounceIn}, so she sources your R script to run the entire analysis. You're in luck – she hasn't yet updated her `dplyr`, so the code runs.\n- 'Reviewer 2' is very eager. He's unconvinced by your modelling choices, so he fits your data to another function to check if your findings are truly [robust]{.fragment .bounceIn}. You're in luck again – he recovers your point estimate to a reasonable precision, although the confidence intervals have widened.\n- 'Reviewer 3' takes a special interest because he's just working on a similar paper on data they published recently. Do your results [replicate]{.fragment .bounceIn} when your methods are applied to that state-of-the-art dataset?\n:::\n\n## Quick check: credibility in the wild {.questionslide transition=\"none-in fade-out\"}\n\n::: {.none}\nYou submit your paper and replication package. It goes out to reviewers.\n\n'Reviewer 2' just doesn't want to let go...\n\n- He tried a few alternative analyses of your data, including a fancy new regression method that he just released as an R package. His method gives results that are generally aligned to yours, but for the method to work, it would require a larger dataset; would your results really [generalise]{.fragment .bounceIn} to this new dataset published by 'Reviewer 3' that he just read about, if applying his new fancy method to it?\n:::\n\n## Open research: the practices {.smaller}\n\n::: {.small}\n| Practice | What it makes possible |\n|---|---|\n| **Open data** | Someone else can re-analyse your evidence |\n| **Open code** | Someone else can rerun your exact analysis |\n| **Open materials** | Someone else can run your study again |\n| **Open access** | Someone else can read the claim in the first place |\n| **Preregistration** | A dated record of the plan, before the results exist |\n| **Registered reports** | Peer review of the plan, with publication decided before results |\n:::\n\n::: {.fragment .small}\nEach one removes a specific obstacle. None of them is a general-purpose guarantee. The programme, set out at length: [@MunafoEtAl2017ManifestoReproducibleScience]\n:::\n\n::: notes\nSo what does open research actually propose? Not a philosophy – a list of practices, and each one removes a specific, identifiable obstacle. Open data means someone else can re-analyse your evidence rather than taking your word for it. Open code means they can rerun your exact analysis. Open materials means they can run the study again in a new sample. Open access means they can read the thing at all, which sounds trivial until you try to get a paper from outside a wealthy university. Preregistration produces a dated record of the plan before the results exist. And registered reports go further: the plan is peer-reviewed and the publication decision is made before anyone sees a result, which removes the incentive to find something. Each removes one obstacle. None is a general guarantee, and I want to be clear about that before we get enthusiastic.\n:::\n\n## Inside Multi100: what an analyst was sent {.smaller}\n\n::: {.small}\n- A **published paper**, in full – no blinding: I could see the original estimates\n- Its **central claim**, in one sentence, lifted from the abstract\n- A pointer to the **data** – in our case, sixteen Eurobarometer waves you fetch yourself from GESIS\n- No instructions on method. Analyse it any way you can defend\n:::\n\n::: {.fragment .small}\nAnd two things I could not see: **who the other analysts were**, and **what they were finding**.\n:::\n\n::: {.src}\n@AczelEtAl2026InvestigatingAnalyticalRobustness. Registered protocol: osf.io/7snkz\n:::\n\n::: notes\nLet me show you what this was like from the inside, because it shapes how you read the results. What arrived was a published paper – the whole thing, not blinded, so I could see the original estimates, and if anything that pulls you towards the original answer. With it came the paper's central claim in a single sentence, lifted from the abstract, and a pointer to where the data lived. In our case that meant sixteen Eurobarometer waves that I had to go and fetch from GESIS myself, under licence. What did not arrive was any instruction on method. Analyse it however you can defend. And two things stayed hidden throughout: who the other analysts were, and what any of them were finding. That isolation is the design – it is what makes the spread at the end mean something.\n:::\n\n## The paper, for now in one slide\n\n::: {.small}\n- Author: I will say **OA**, the original author, from here on\n- **Does the EU economic crisis undermine support for the EU?** – 16 Eurobarometer waves, **2004–2013**, about **390,000** respondents in **27 countries**\n\n::: {.claimcard}\n\"The results show, first, that *poor economic performances* **increase negative** and **decrease positive** *dimensions of EU framing*.\"\n:::\n\n- Macro predictors: **national unemployment** and **GDP growth**. Outcome: what people say the EU means to them, sorted into four framing scales\n:::\n\n::: {.src}\n@Teney2016DoesEUEconomic. The full methodological reading is Part 2.\n:::\n\n::: notes\nAnd here is the paper, briefly – we spend most of Part 2 inside it, so this is just enough to follow what happened. It is from 2016, in the European Sociological Review, and I will call its author OA, the original author, throughout the day. The question is whether the economic crisis undermined how people relate to the EU: sixteen Eurobarometer waves from 2004 to 2013, the crisis decade, about three hundred and ninety thousand respondents across twenty-seven member states. The claim we were handed is the sentence in the box. On the right-hand side sit two macro indicators, national unemployment and GDP growth; on the left, what people say the EU means to them personally, sorted into four framing scales. That is all you need for now. Part 2 opens by taking the whole thing apart.\n:::\n\n## Two tasks, months apart {.smaller}\n\n::: {.small}\n**Task 1 – free reanalysis.** Reanalyse the claim however you see fit. Record one categorical conclusion: does the evidence support it?\n\n::: {.fragment}\n**Task 2 – constrained reanalysis.** Months later, three instructions arrive that fix the question:\n\n- use the **cosmopolitan** framing dimension as the outcome\n- use the **unemployment rate** as the predictor\n- **disregard** the contextual variables\n:::\n:::\n\n::: {.fragment .small}\nTask 1 measures whether we agree. Task 2 makes our *numbers* comparable – you cannot average five answers to five different questions.\n:::\n\n::: notes\nThe study ran in two stages, and the distinction matters for everything that follows. Task one was complete freedom: reanalyse the claim however you see fit, and record one categorical conclusion – does the evidence support it or not. Then months later, task two arrived with three instructions that pinned the question down: use the cosmopolitan framing dimension as your outcome, use the unemployment rate as your predictor, and disregard the contextual variables. Now, why run it in that order? Because the two tasks measure different things. Task one asks whether independent analysts reach the same verdict. Task two asks whether they produce the same number – and you can only ask that second question once everyone is answering the same question, which is precisely what those three instructions manufacture.\n:::\n\n## How a hundred studies become one number {.smaller}\n\n::: {.small}\n- Every analyst reports their test statistic and its degrees of freedom, in whatever form their model produces – **t**, **z**, **F**, $\\chi^2$\n- Each is converted to a **partial correlation** *r* and a standardised **Cohen's *d***, so a Stata pooled model and an R multilevel model land on the same axis\n- A **peer panel** judges whether each pipeline is an appropriate analysis of the claim\n- Only then can you ask: how far apart are five defensible answers?\n:::\n\n::: {.fragment .small}\nStandardising is what makes comparison possible – and it quietly assumes the five are estimating **the same quantity**. Hold that thought until Part 2.\n:::\n\n::: notes\nSo how do you compare a hundred studies analysed five ways each? Everyone reports the test statistic that their model happens to produce, with its degrees of freedom – a t, a z, an F, a chi-squared. Those get converted onto a common scale: a partial correlation and a standardised mean difference, so that somebody's pooled Stata model and somebody else's R multilevel model can sit on the same axis and be read against each other. Alongside that, a peer panel judged whether each pipeline was an appropriate analysis of the claim at all – so the spread you are about to see is a spread among analyses that passed review, not a spread that includes nonsense. And notice the assumption hiding in the conversion: putting five numbers on one axis takes for granted that they estimate the same quantity. Hold on to that. Part 2 is largely about what happens when they do not.\n:::\n\n\n## Our five: one sign, very different sizes {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/forest5-1.png){width=912}\n:::\n:::\n\n\n::: {.small}\n- All five negative – same direction · partial *r* from **−0.45 to −0.006** · one not significant\n:::\n\n::: {.src}\nTask 2 results as recorded in the public Multi100 dataset (osf.io/q5h2c).\n:::\n\n::: notes\nAnd here are the five of us, on this one claim. All five found a negative effect – on direction, unanimity. On size, look at the spread: from essentially zero, and that one is not significant, out to a partial correlation of minus point four five. Two orders of magnitude apart, on the same data, for the same claim, with all three of Task 2's instructions obeyed. The orange dot is me, at minus point two four. Five competent people, one fixed question, and the answers scatter across half the available range. Now – before we go anywhere near why, which is Part 2's whole job, I want you to look at the labels down the left-hand side, because there is a column there I have not mentioned yet.\n:::\n\n## Look at the labels {.smaller}\n\n::: {.small}\n- Two of us worked in **Stata**, three in **R**\n- Within R, three different document formats: a plain `.R` script, an `.Rmd`, a `.qmd`\n:::\n\n:::: {.none}\n::: {.fragment .fadeInUp}\nThe software did **not** cause the spread. There is no Stata answer and no R answer to this claim.\n:::\n\n::: {.fragment .fadeInUp}\nBut because each of us submitted a document that somebody else could **open and run**, it became possible, afterwards, to find out what *did* cause it.\n:::\n\n::: {.fragment .fadeInUp}\nThat is what the toolchain is for, and it is what you spend this afternoon doing.\n:::\n::::\n\n::: notes\nTwo of the five worked in Stata, three in R – and within R, three different document formats: a plain script, an R Markdown file, a Quarto file. Now, the tempting reading of that column is the wrong one, so let me kill it straight away. The software did not cause the spread. There is no Stata answer and no R answer to this claim; every one of these models can be fitted in either. But here is what the column does tell you, and it is why the tooling is worth caring about. Because every one of us submitted a document that somebody else could open and run, it became possible afterwards to go and find out what actually did cause the spread. I have read all four of the others' code, line by line, and this afternoon you will work inside the same space they were working in. That is only possible because of what is in that column. So – the tools.\n:::\n\n## What we use today {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.small}\n**Your IDE and the workspace**\n\n- The workspace folder you downloaded, opened in your IDE (Positron, RStudio, VS Code, etc.)\n- Quarto renders your report; `fixest` fits your models\n- No git, no cloning, no configuration – it is just files\n- This is what I drive on the shared screen\n:::\n:::\n::: {.column width=\"50%\"}\n::: {.small}\n**The browser lab**\n\n- One web page. R is compiled to run **inside the browser**\n- Nothing installed, nothing to break, data already in place\n- The same tasks, data and helpers, on the shared screen and in your own tab\n- Your spare if your installation misbehaves at any point\n:::\n:::\n::::\n\n::: {.urlbox .fragment}\n[github.com/CodeMoreh/replication-lab](https://github.com/CodeMoreh/replication-lab) [– download zip → unzip → open in your IDE]{.fs-80}\n:::\n\n::: notes\nSo, concretely, today. The workspace is the folder you downloaded, open in your IDE – Positron on my screen, RStudio or VS Code on yours if that is what you use – Quarto renders your report, fixest fits your models, and there is no git and no cloning because it is just a folder of files. That is what I will be driving on the shared screen, so you can follow keystroke for keystroke. The browser lab is one web page with R compiled to run inside the browser itself. Nothing installed, nothing to break, and the data are already there. The two are at full parity – every task exists in both – so you can switch mid-day if your machine misbehaves, and several people usually do. The address for the workspace zip is at the bottom, and it is on the setup page in the chat.\n:::\n\n## What the tools cannot do {.smaller}\n\n:::: {.none}\n::: {.fragment}\nA perfectly reproducible pipeline can be a perfectly reproducible answer to **a question you never stated**.\n:::\n\n::: {.fragment}\nNone of this software will tell you what your estimand is, whether your controls belong in the model, or whether the association you found means what you think it means.\n:::\n\n::: {.fragment}\nTooling is the **cheap** half of the problem. We have now done it. **The rest of the day is the expensive half.**\n:::\n::::\n\n::: notes\nAnd I want to end this segment by undercutting it slightly. Everything I have just shown you is genuinely worth having – but a perfectly reproducible pipeline can be a perfectly reproducible answer to a question you never stated. None of this software will tell you what your estimand is. None of it will tell you whether the variables you put in the model belong there. None of it will tell you whether the association you found means what you think it means. Tooling is the cheap half of the problem, in the sense that it is solvable by learning things – which is what we have just done. The rest of the day is the expensive half, and it starts after the break with the most useful question in quantitative research, which is: what exactly are you trying to estimate?\n:::\n\n## Hands-on 1: get yourself running {.smaller}\n\n::: {.small}\n**Task 1 – the setup check.** Get to the point where a line of R runs and the data are in front of you.\n\n- **Workspace:** your IDE opens the workspace folder · the packages install · `working_script.R` runs its first block · the report skeleton renders\n- **Browser lab:** the page has finished loading · the first chunk runs · `euframes` has 270 rows\n:::\n\n::: {.fragment .small}\nTake the rest of this part **and the break** for it. Type a green circle in chat when you are through; type **STUCK** and I will come to you.\n:::\n\n::: {.fragment .small}\nIf your installation will not cooperate, do not fight it – open the browser lab and carry on. Nothing today depends on it.\n:::\n\n::: notes\nRight – your turn, and this first one is deliberately not intellectual. The job is to get to the point where a line of R runs and the data are in front of you. The workspace: open the workspace folder in your IDE, let the packages install, run the first block of the working script, and render the report skeleton once so you know it works. The browser lab: wait for the lab page to finish loading, run the first chunk, and check that the panel has two hundred and seventy rows. Take the rest of this part and the whole break over it – there is no prize for finishing early, and getting this right now saves an hour of misery later. Green circle in chat when you are through, STUCK if you need me. And if the workspace will not cooperate, do not fight it. Switch to the browser lab and carry on – nothing today depends on which one you use.\n:::\n\n## Break {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\n30 minutes – the exact return time is in the chat · keep setting up if you need to\n:::\n\n::: notes\nBreak – thirty minutes, and the return time is in the chat. If your setup is not finished, use the break for it and flag me; I will stay on the call. When we come back we stop talking about infrastructure and start on the paper.\n:::\n\n# PART 2 – The claim and its estimand {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\nPart 2 · 90 minutes\n:::\n\n::: notes\nPart two is the conceptual centre of the day: the paper in full, the argument that analysts who look as though they disagree are answering different questions, Lundberg's three steps from a theoretical quantity to an empirical one, and the causal-graph crash course in full – confounders, mediators, colliders, paths, and what fixed effects buy you. Then our own claim, your estimand in one sentence, and the half-built graph.\n:::\n\n## The paper we spend the day inside\n\n::: {.small}\n- 16 Eurobarometer waves, **2004–2013**; about **390,000** respondents in **27 countries**\n\n::: {.claimcard}\n\"The results show, first, that *poor economic performances* **increase negative** and **decrease positive** *dimensions of EU framing*.\"\n:::\n\n- \"What does the EU mean to you personally?\"\n  - COSMOPOLITAN: positive non-materialist form of EU framing ('Peace'; 'Democracy'; 'Freedom to travel, study and work anywhere in the EU'; 'Cultural diversity'; 'Stronger say in the world')\n  - UTILITARIAN: positive materialist form of EU framing (economic prosperity and social protection)\n  - COMMUNITARIAN: negative non-materialist form of EU framing ('Loss of our cultural identity'; 'More crime'; 'Not enough control at external borders'; 'Unemployment')\n  - LIBERTARIAN: negative materialist form of EU framing ('Bureaucracy'; 'Waste of money')\n:::\n::: {.src}\n@Teney2016DoesEUEconomic.\n:::\n::: notes\nBack to OA's paper, and this time properly. Sixteen Eurobarometer waves, 2004 to 2013 – the crisis decade – about three hundred and ninety thousand respondents across twenty-seven member states. The outcome comes from one rather good survey item: what does the EU mean to you personally? Thirteen response options, which OA organises into four framing scales, and read those slowly because the whole afternoon depends on them. Cosmopolitan is the positive non-materialist one: peace, democracy, freedom to travel and study and work anywhere, cultural diversity, a stronger voice in the world. Utilitarian is positive and materialist: prosperity and social protection. Communitarian and libertarian are the negative pair. That sorting into four scales is itself a substantive theoretical claim about what the EU means to people, and it is one you could argue with – which, this afternoon, several of you will.\n:::\n\n## The claim card, as analysts received it\n\n::: {.claimcard}\n\"… poor economic performances … decrease positive dimensions of EU framing\"\n\n<span class=\"src\">Teney (2016: 619)</span>\n:::\n\n::: {.small}\n- Published coefficient – unemployment → cosmopolitan framing, Table 3 Model 1:\n- **b = −0.00340 · [t = −4.03]{.highlight bg-colour=\"#ffe3b3\"} · p < .001**\n:::\n\n::: notes\nThis is, word for word, the claim every Multi100 analyst was handed: \"poor economic performances decrease positive dimensions of EU framing\". And this is the published number behind it, from Table 3, Model 1 – the unemployment coefficient on cosmopolitan framing: minus point zero zero three four, t of minus four. Keep one wrinkle in mind for later. In the paper's own Model 2, with more controls in, that same coefficient drops by more than half and loses significance. The robustness question is already alive inside the original paper.\n:::\n\n\n## What OA actually fitted {.smaller}\n\n::: {.small}\n- The unit is a **person**, not a country-year: roughly 390,000 respondents\n- Thirteen response options collapse into **four framing scales** – cosmopolitan, utilitarian, communitarian, libertarian\n- A **three-level** model: respondents inside country-waves inside countries\n- Individual covariates: sex · age · education band · occupational status · urbanisation · left–right placement\n- Macro predictors: **unemployment rate** and **GDP growth**, entering at the country-wave level\n- Plus **cross-level interactions** – does the macro effect differ by education?\n:::\n\n::: {.fragment .small}\nPublished coefficient, Table 3 Model 1 – unemployment on cosmopolitan framing: **b = −0.00340 · t = −4.03 · p < .001**\n:::\n\n::: {.src}\n@Teney2016DoesEUEconomic.\n:::\n\n::: notes\nSo what is under the bonnet? The unit of analysis is a person – around three hundred and ninety thousand of them – not a country-year. The outcome comes from a single survey item with thirteen response options, which OA collapses into four framing scales: cosmopolitan, utilitarian, communitarian, libertarian. The model is three-level: respondents inside country-waves inside countries. At the individual level there are the usual controls – sex, age, education band, occupational status, urbanisation, left-right placement. The two macro predictors, unemployment and GDP growth, enter at the country-wave level. And there are cross-level interactions, asking whether the macro effect differs by education. The published number for our claim, from Table 3 Model 1, is the unemployment coefficient on cosmopolitan framing: minus point zero zero three four, t of minus four.\n:::\n\n## The robustness question is already in the paper {.smaller}\n\n::: {.small}\n- **Model 1**: unemployment → cosmopolitan framing · b = −0.00340 · t = −4.03 · p < .001\n- **Model 2**: the same coefficient, with further controls added – drops by more than half and **loses significance**\n:::\n\n::: {.fragment .small}\nTwo models, one paper, and support for the claim depends on which one you read. The paper reports both, which is more than many do.\n:::\n\n::: {.fragment .small}\nFor today, that matters because the sixth analyst's problem – *which defensible specification do I report?* – was **already live inside the original study**, before any of us arrived.\n:::\n\n::: notes\nThis next point is easy to miss, and it reframes the whole exercise. Look at what happens inside OA's own paper. Model one gives the published coefficient: minus point zero zero three four, t of minus four, comfortably significant. Model two, which adds further controls, takes that same coefficient, more than halves it, and loses significance. Two models, one paper, and whether the claim is supported depends on which of them you read. To be fair to OA, the paper reports both – which is more than a great many papers do. But notice what it means for us. The problem you will face this afternoon, as the sixth analyst – which of several defensible specifications do I report, and on what grounds? – was already live inside the original study, before any re-analyst was anywhere near it.\n:::\n\n## What we work on instead {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.small}\n**OA's data**\n\n- ~390,000 respondents\n- 16 waves, 27 countries\n- GESIS-licensed: I may not redistribute it\n- Models take minutes\n:::\n:::\n::: {.column width=\"50%\"}\n::: {.small}\n**Today's panel** – `EUframes_cy.csv`\n\n- **270 country-years**, one row each\n- The framing scales, averaged within each country-year\n- Freely shareable, ships with the workspace and the browser lab\n- Models take milliseconds\n:::\n:::\n::::\n\n::: {.fragment .small}\nThe aggregate answers the **contextual** question directly: does a country's framing move when its unemployment moves? What it cannot answer is the **compositional** one – whether it is the same people framing differently, or a different mix of people. There is a companion module that takes that up on simulated individual data.\n:::\n\n::: notes\nNow, a practical matter with a conceptual point behind it. OA's data is Eurobarometer microdata under GESIS licence, which I am not permitted to redistribute – and, as you will see in a moment, that constraint is exactly what wrecked the first reproduction attempt on this paper. So what you get today is an aggregate I built from it and am allowed to share: two hundred and seventy country-years, one row each, with the framing scales averaged within each cell. It ships with the workspace and the browser lab, and it fits in milliseconds. The conceptual point is on the fragment. The aggregate answers the contextual question directly – does a country's framing move when its unemployment moves. What it cannot answer is the compositional one: whether the same people are framing differently, or the mix of people has changed. If that interests you, there is a companion module on the site that takes it up on simulated individual data.\n:::\n## Reproducibility: two attempts, two failures\n\n::: {.small}\n- Data: openly available but not freely redistributable\n\n::: {.claimcard .fragment}\n\"The required data to replicate my analyses can be downloaded on  the Gesis repository website. I am not allowed to forward the Eurobarometer data. Enclosed you´ll find the code to combine the different Eurobarometer data waves and the code for the analysis of the ESR piece\"\n:::\n\n- Code: push-button reproduction failed\n\n::: {.claimcard .fragment}\n\"The reproduction attempt failed because the authors used file names that did not correspond with the names of the files available for download. Additionally 16 datasets are listed on the website as being used but the code references 18 files\"\n:::\n\n- **Source-data reproduction** (rebuild from raw) – **\"not reproduced\"**: could neither extract nor re-calculate the original effect size\n:::\n\n::: notes\nSo what happened when SCORE tried to reproduce this paper? Two attempts, two different failures. And let me be fair to OA here: there was no public archive with the paper, but OA did supply their two Stata do-files when asked – what OA could not share was the data, because GESIS terms do not allow it. Even with OA's code in hand, the push-button reproduction failed, and the wording of the report is instructive – the file names in the code did not correspond to the files you could actually download; sixteen datasets listed, eighteen referenced. The second attempt rebuilt the data from source, and could not recover the published effect size at all. So this claim entered the robustness study already carrying two failed reproductions, of two different kinds.\n:::\n\n## Replication: the coefficient flips sign\n\n::: {.small}\n- Analysis One – the focal test on which SCORE evaluates the claim\n\n  - 352,114 person-year observations in the analytic sample\n  - b = 0.002, p = 0.046, se = 0.0008, t = 2.004\n\n- Analysis Two – the 'still studying' and 'no full-time education' categories in the variable 'age when finished full-time education' were **not** converted to missing values\n\n  - 379,396 person-year observations in the analytic sample\n  - b = 0.002, p = 0.017, se = 0.0007, t = 2.394\n\n- Both give a **positive coefficient** for unemployment on cosmopolitan framing, **significant** at p-values of 0.05 or less, after controlling for selected predictors and for wave and country-level effects\n- By the criteria used by SCORE, Analysis Two did not replicate the claim\n:::\n\n::: {.src}\n[osf.io/zt5y2/files/7efsw](https://osf.io/zt5y2/files/7efsw)\n:::\n\n## One paper, all three Rs\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/score-scoreboard-1.png){width=1008}\n:::\n:::\n\n\n::: {.src}\n[osf.io/h7432](https://osf.io/h7432)\n:::\n\n::: notes\nPut the whole dossier together – every artefact here is public, the link is on the slide. Reproduction: failed, twice, in two different ways. Robustness: mixed – five analysts, one sign, sizes spanning two orders of magnitude. And replication: a preregistered study took the same question to new Eurobarometer data, three hundred and fifty-two thousand observations – and the coefficient flipped sign. Positive, just significant, the wrong way round. So: one paper, three Rs, three different verdicts. That is the uncorrelated-indicators result from part one, embodied in a single case. Asking \"is this paper reliable?\" gets you nowhere; asking \"reliable in which sense?\" gets you all of this. Now – of the three, the middle one is where five careful people disagreed with each other, and it is the only one of the three we can do anything about today. So the rest of this part is about what they were disagreeing over.\n:::\n\n## Same verdict, five different questions {.smaller}\n\n::: {.small}\n| Analyst | Free-phase predictor | Free-phase outcome | Estimator |\n|---|---|---|---|\n| 018OL | GDP per capita (level) | positive framing, 7-item mean | crossed random intercepts |\n| KEVF1 | GDP growth | positive framing, 7-item sum | random intercepts |\n| PRL47 | log GDP + growth + crisis dummy | three positive-framing shares | three-level mixed |\n| KQXUE | GDP growth **and** unemployment | cosmopolitan + utilitarian shares | country FE |\n| **C6HJR** | **GDP growth and unemployment** | **positive framing, 7-item share** | **two-way FE** |\n:::\n\n::: {.fragment .small}\n- Five free analyses, **five different questions** – three of us never touched unemployment at all – and **one shared recorded verdict**: 'evidence for the claim'\n- The constrained phase then *manufactured* a common question; its five comparable answers span **−0.006 to −0.45**\n- Conclusions can agree while estimates cannot even be compared – the two robustness questions that Multi100 was built to separate [@AczelEtAl2026InvestigatingAnalyticalRobustness]\n:::\n\n::: {.src}\nFree-phase records: the public Multi100 dataset (osf.io/q5h2c) – categorical verdicts and free-text reports only; the models themselves read from the analysts' public code.\n:::\n\n::: notes\nThis is the layer underneath, and it is the sharpest illustration I have of this morning's point. Multi100 ran in two phases, and this table is the first one – months before the constrained task, complete freedom. Look at what freedom produced. GDP per capita for one analyst, GDP growth for another, a whole battery of GDP measures at three levels for a third – and three of the five of us never touched the unemployment rate at all. Different outcomes too: a mean, a sum, a share, three separate shares. Five different questions, in other words. And every single one of us recorded the same verdict: evidence for the claim. Then the constrained task arrived, manufactured one common question, and the five comparable answers ran from minus point zero zero six to minus point four five. Conclusions agreed in words while the numbers disagreed by two orders of magnitude. Now, that is five people on one paper. What happens when it is twenty-nine teams?\n:::\n\n## Two studies to set beside our five {.smaller}\n\n::: {.small}\nOur own case has just shown us the pattern in miniature. It was described first, and at far greater scale, in the two studies that the rest of this part rests on.\n:::\n\n:::: {.fragment}\n::: {.small}\n**Silberzahn and colleagues (2018)** – the red-card study from this morning. Twenty-nine teams, one dataset, one question. Twenty of the twenty-nine intervals excluded 1; nine did not.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/silberzahn-strip-1.png){width=864}\n:::\n:::\n\n::::\n\n::: {.fragment .small}\n**Auspurg and Brüderl (2021)** went back through all twenty-nine of those analyses and asked a question that the original had not: what was each team actually trying to measure?\n:::\n\n::: {.fragment .small}\nThe first establishes that careful people disagree. The second explains **why** – and that explanation is what the whole of Part 2 is built on.\n:::\n\n::: {.src}\n@SilberzahnEtAl2018ManyAnalystsOne; @AuspurgBruderl2021HasCredibilitySocial\n:::\n\n::: notes\nBefore we go further into our own case, I want to put two studies beside it – and one of them you have already met. Silberzahn and colleagues, the red-card study from this morning: twenty-nine teams, one dataset, one question, twenty intervals excluding one and nine not. There are all twenty-nine again, flattened onto a single line so you can see the shape rather than read the table. That is the study that establishes careful people disagree. The second one is new, and the rest of this part depends on it. Auspurg and Brüderl, twenty twenty-one, went back through all twenty-nine of those pipelines and asked something that the original had not thought to ask: what was each team actually trying to measure? So one study shows the disagreement, and the other explains it. Let me take the second one properly.\n:::\n\n## They were not answering the same question\n\n:::: {.none}\n<br>\nAuspurg & Brüderl re-read the 29 analyses and found **four** different estimands:\n\n::: {.fragment .fadeInUp}\ndescriptive association · discrimination *net of mediators* · variance-maximising · exploratory\n:::\n\n::: {.fragment .fadeInUp}\nThe dispersion was largely a **question**-multiverse, not an analysis-multiverse.\n:::\n::::\n\n::: {.src}\n@AuspurgBruderl2021HasCredibilitySocial\n:::\n\n::: notes\nAnd what they found is that the teams were not answering one question. They found four. Some estimated the plain descriptive association. Some went after discrimination proper – the effect net of everything that legitimately explains red cards. Some built models tuned to explain variance. And some were frankly exploring. Of course the answers differed – they were answers to different questions. That reframes the crisis quite a bit: much of what looks like analytical instability is unstated disagreement about *what is being estimated*.\n:::\n\n\n## Fix the estimand, and the spread collapses\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/redcard-contrast-1.png){width=864}\n:::\n:::\n\n\n::: {.small}\n- Fix the question → derive the model space from a DAG → run **all 486** justifiable models → **SD 0.45 → 0.06**\n- The spread in the top row is **two analyses wide**: a tight cluster plus the two outliers, which are what carry that 0.45\n:::\n\n::: {.src}\n@AuspurgBruderl2021HasCredibilitySocial. Top row: the 29 published estimates. Bottom row: drawn to their reported median (1.28) and SD (0.06) – the 486 values are not published.\n:::\n\n::: notes\nThis is the optimistic half of the red-card story. Auspurg and Brüderl fixed one estimand – discrimination, properly defined – used a causal graph to derive every model specification consistent with it, four hundred and eighty-six of them, and ran the lot. Look what happens to the spread: standard deviation point four five in the crowd, point zero six with the question fixed. The top row there is the twenty-nine published estimates themselves, and only the bottom row is drawn to the reported median and standard deviation, because those four hundred and eighty-six values were never published. The recipe we take from them is the recipe of this course: a precise question, assumptions drawn out explicitly, then a whole multiverse rather than one path, then sensitivity analysis. And notice where the spread in the top row actually comes from – a tight cluster and two outliers, which is why the standard deviation is four times what the cluster alone would give you. Fix the question and even those go. [advance]\n:::\n\n\n## Has credibility been credibly destroyed? {#the-crisis-has-a-crisis-of-its-own .smaller}\n\n:::: {.none}\nAuspurg and Brüderl's title asks it directly: *has the credibility of the social sciences been credibly destroyed?*\n\n::: {.fragment .fadeInUp}\nIf the twenty-nine teams answered **four different questions**, their disagreement is not evidence that analysis is unreliable.\n:::\n\n::: {.fragment .fadeInUp}\nIt is evidence that **the question was under-specified** – an ordinary, fixable defect.\n:::\n\n::: {.fragment .fadeInUp}\nSo this literature reads as a **diagnosis of vague research questions** rather than a verdict on social science.\n:::\n\n::: {.fragment .fadeInUp}\nMore optimistic – and more demanding, because it hands the problem to whoever writes the question.\n:::\n::::\n\n::: {.src}\n@AuspurgBruderl2021HasCredibilitySocial\n:::\n\n::: notes\nNow, this diagnosis has a consequence that goes well beyond the red-card study, and Auspurg and Brüderl put it in their title: has the credibility of the social sciences been credibly destroyed? Follow the logic. If the twenty-nine teams were in fact answering four different questions, then their disagreement is not evidence that data analysis is unreliable. It is evidence that the question they were handed was under-specified – and that is an ordinary, fixable defect of research design, not a crisis of method. Read that way, the whole many-analyst literature stops being a verdict on the field and becomes a diagnosis of vague research questions. I find that a considerably more optimistic reading. It is also a more demanding one, because it takes the problem away from statistics, where you could hope a better estimator would save you, and puts it back on whoever writes the question. Today that is you.\n:::\n\n## What is your estimand?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/lundberg-pipeline-1.png){width=864}\n:::\n:::\n\n\n::: {.none}\n- The theoretical estimand is stated **outside** any model – before R opens\n:::\n\n::: {.src}\n@LundbergEtAl2021WhatYourEstimand.\n:::\n\n::: notes\nWhich brings us to the most useful question in quantitative research: what is your estimand? Lundberg and colleagues split the answer into three steps. First, the theoretical estimand: a unit-specific quantity and a target population, stated in plain words, before any model exists. Second, the empirical estimand: what in the observable data corresponds to that quantity – and making that link forces your identification assumptions into the open, which is exactly where the causal graph lives. Only third comes estimation, where R finally opens. When they audited a full year of papers in a top sociology journal, the unit quantity was clearly stated in five out of thirty-two. Their demand is the one to remember: every quantitative study must be able to answer the question – what is your estimand?\n:::\n\n## DAG crash course: three roles {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/mini-dags-1.png){width=912}\n:::\n:::\n\n\n::: {.src}\nX = predictor, Y = outcome. **Green** = the causal effect you want; **coloured** = the path you must reason about.\n:::\n\n::: notes\nAll the graph theory you need today, in three small pictures. In every panel the green arrow is the same thing – the effect you are actually after, X on Y. What changes is the coloured structure around it. A confounder is a common cause of your predictor and your outcome – that red fork is a back-door path, and if you leave it open you are biased, so you adjust to close it. A mediator sits on the causal path between them – the amber path is real, it is part of the total effect, so if the total effect is what you want you do not adjust for it, or you remove part of the very thing you are measuring. And a collider is caused by both sides – those edges are harmless until you condition on the collider, which opens a spurious path that was not there before. So the rulebook is short: adjust confounders, leave mediators alone for total effects, and never condition on a collider. That is the entire toolkit – the next four slides just give it a bit more depth before you use it.\n:::\n\n## One number, many stories {.smaller}\n\n:::: {.columns}\n::: {.column width=\"54%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/many-stories-1.png){width=499.2}\n:::\n:::\n\n\n:::\n::: {.column width=\"46%\"}\n::: {.small}\nThe same slope fits four different stories:\n\n::: {.fragment}\n- X really causes Y – the slope *is* the effect\n:::\n::: {.fragment}\n- a common cause inflates it – **confounding**\n:::\n::: {.fragment}\n- we are seeing a selected sample – **collider / selection**\n:::\n::: {.fragment}\n- Y causes X (**reverse causation**), or it is **chance**\n:::\n::: {.fragment}\nThe data look identical in all four. Only an assumption about *how the data arose* tells them apart – that is what a DAG writes down.\n:::\n:::\n:::\n::::\n\n::: {.src}\n@DAgostinoMcGowanEtAl2024CausalInferenceNot; @KeeleEtAl2020CausalInterpretationEstimated. Scatter simulated for illustration.\n:::\n\n::: notes\nHere is a strong correlation – r of about nought point six. Before you reach for a model, consider that this single number is consistent with at least four different stories. Maybe X really does cause Y, and the slope is the effect. Maybe a common cause is inflating it. Maybe we are quietly looking at a selected sample, and the association is an artefact of who got in. Maybe Y causes X, or it is simply chance. The data cannot choose between these – the scatter looks identical in every case. Only a claim about how the data were generated can. That claim is what a DAG writes down, and it is why we draw one before we fit anything.\n:::\n\n## Reading a DAG: open and closed paths {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/backdoor-paths-1.png){width=912}\n:::\n:::\n\n\n::: {.small}\nAssociation flows along **every open path**, not only along the causal arrow. A fork or a chain is open until you adjust the variable sitting on it. A collider is the reverse: shut by default, and opened by the very act of adjusting for it.\n\n- **Back-door criterion**: close every path that enters X from behind, keep the causal X → Y path open\n- That adjustment set – and only that set – earns a causal reading\n:::\n\n::: {.src}\n@HernanRobins2020CausalInferenceWhat; @Huntington-Klein2021EffectIntroductionResearch.\n:::\n\n::: notes\nA DAG is read through its paths. Association does not only travel down the causal arrow – it flows along every open path between X and Y. So the job is to work out which paths are open and shut the ones you do not want. Two rules do all the work. A path through a fork or a chain is open, and you close it by adjusting the variable in the middle – that is the red back-door fork on the left. A path through a collider is the opposite: shut by default, and you open it by adjusting. The back-door criterion just packages this: close every path that sneaks into X from behind, leave the causal X-to-Y path alone. The set that does that – and only that set – is what you are allowed to read as causal.\n:::\n\n## Total effect or direct effect {#which-effect-do-you-even-want .smaller}\n\n:::: {.columns}\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/total-direct-1.png){width=537.6}\n:::\n:::\n\n\n:::\n::: {.column width=\"45%\"}\n::: {.small}\n- **Total** = direct (green) + indirect (amber)\n- Adjust for the mediator M → you estimate the **direct** effect only – a *different* estimand\n- 'Control for everything' silently answers a question you never asked\n- **Table 2 fallacy**: the other coefficients in your model are *not* all causal effects\n:::\n:::\n::::\n\n::: {.src}\n@KeeleEtAl2020CausalInterpretationEstimated; @DAgostinoMcGowanEtAl2024CausalInferenceNot.\n:::\n\n::: notes\nNow the question that the estimand discussion was circling. Suppose M sits between your predictor and outcome. The total effect is the green arrow plus the amber route through M. The direct effect is just the green arrow. These are different numbers and different questions – and which one you get depends entirely on whether you put M in the model. Drop a mediator in as just another 'control' and you have silently switched to the direct effect without telling anyone, including yourself. This is why 'control for everything' is bad advice. And it has a famous corollary – the Table 2 fallacy: when you print a regression table, usually only one coefficient has a clean causal reading. The coefficients on the control variables are not little causal effects of their own.\n:::\n\n## Selection and feedback {#spurious-by-design-selection-feedback .smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/selection-panel-1.png){width=960}\n:::\n:::\n\n\n::: {.small}\n- **Selection / collider bias** – conditioning, or merely *sampling*, on a common effect manufactures an association that was never there (much of the early COVID risk-factor literature)\n- **Reverse causation & feedback** – in a panel, today's outcome can move tomorrow's predictor; two-way fixed effects absorb stable country traits and common-year shocks, **not** time-varying feedback (U = unemployment, F = framing)\n:::\n\n::: {.src}\n@GriffithEtAl2020ColliderBiasUndermines; @ColeEtAl2010IllustratingBiasDue; @LeszczenskyWolbring2022HowDealReverse.\n:::\n\n::: notes\nTwo last ways a relationship can be spurious, and both of them apply to our case. The first is selection, or collider bias. If you condition on – or merely sample on – something that both your variables cause, you manufacture a correlation out of nothing. A lot of the early COVID risk-factor findings were exactly this: conclusions drawn from people who had been tested, which is a selected group. The second is reverse causation and feedback. Our data are a panel, and in a panel today's outcome can feed tomorrow's predictor. Two-way fixed effects – which is the model we are about to draw – soak up stable differences between countries and shocks common to a year. They do not, on their own, fix a time-varying confounder or a feedback loop. Keep that in mind when we build the graph for our own paper.\n:::\n\n## *Revenons à nos moutons*\n\n::: {.claimcard}\n\"The expected change in [unit quantity] among [target population] for a 1-percentage-point difference in unemployment, holding [assumptions] fixed.\"\n:::\n\n::: {.small}\n- Unit quantity – a *person's* cosmopolitan framing, or a *country-year* mean?\n- Target population – which countries, which years?\n:::\n\n::: {.fragment}\n**In chat, now:** your one-sentence estimand for the claim. Type it, hold it, send on \"go\".\n:::\n\n::: notes\nNow apply it to our paper – and this one is a chat exercise. Write the statement on the slide with the brackets filled in: your one-sentence estimand for the claim. Type it, hold it, send when I say go. [go; read three or four aloud.] Look at the spread in the chat – some of you wrote about a person's framing, some about a country-year average, some named different years. None of those are wrong; they are different questions, with different confounding stories, and the coefficient means something different in each. That spread, in a room that just watched the same slides, is the red-card diagnosis happening live. Keep your sentence – it goes into your preregistration this afternoon, and this afternoon you will also see what the unit choice did to the five published analysts.\n:::\n\n## We cannot identify a causal effect here {.smaller}\n\n::: {.small}\nObservational panel · 27 countries · no assignment mechanism · feedback between the variables · a decade of shared shocks.\n\nNothing in this design licenses \"unemployment **causes** a shift in EU framing\".\n:::\n\n::: {.fragment .small}\nSo why spend half an hour on causal graphs?\n:::\n\n::: {.fragment .small}\nBecause the graph does three jobs that survive the loss of identification:\n\n- It says **which association** you are after – the total effect, not whatever the software returns\n- It tells you **which variables belong in the model**, and, just as usefully, which do not\n- It makes your assumptions **legible and arguable** – a reader can disagree with an arrow, and that is a productive disagreement\n:::\n\n::: notes\nLet me be blunt about where we stand. This is an observational panel of twenty-seven countries. Nobody assigned unemployment to anyone. The variables plausibly feed back into each other over time, and the whole decade is shot through with shocks that hit everybody at once. Nothing in that design licenses the sentence \"unemployment causes a shift in EU framing\". So why are we about to spend half an hour on causal graphs? Because the graph does three jobs that survive perfectly well without identification. It says which association you are actually after – the total effect, say, rather than whatever the software happens to return. It tells you which variables belong in your model, and just as usefully which do not. And it puts your assumptions on paper where a reader can disagree with a specific arrow. The third job is the one that pays: an argument about an arrow is productive in a way that an argument about a coefficient usually is not.\n:::\n\n## Publishing the estimand and the graph {#say-it-in-public-or-it-does-not-count .smaller}\n\n::: {.small}\nThe graph and the estimand are only worth anything if they are **written down where someone else can read them**:\n\n- in the paper, not in your head\n- **before** the model runs, not reconstructed afterwards\n- with the **limitations named by you**, not discovered by a reviewer\n:::\n\n::: {.fragment .small}\nIn Part 4 you write exactly that down – the estimand, the graph-based justification, the one specification, and the rule for what would count as support – and you do it **before** you see a result.\n:::\n\n::: {.fragment .small}\nThe technical name for that is preregistration, and what it does is stop the result from choosing the question.\n:::\n\n::: notes\nAnd one more step, which is where the day is heading. A graph you drew and did not publish is worth almost nothing. It has to be written down where someone else can read it – in the paper, not in your head. It has to be written before the model runs, not reconstructed afterwards once you know which way the coefficient went, because a graph drawn after the fact will very reliably justify the result you already have. And the limitations have to be named by you, not discovered by a reviewer. That requirement runs through the rest of today. In part four you will write exactly that down: your estimand, your graph-based justification, the one specification you commit to, and your rule for what would count as support – and you will do it before you see a result. The technical name for it is preregistration; part four is where you do it for real.\n:::\n## The EU-frames DAG, half built\n\n:::: {.columns}\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/teney-dag-1.png){width=1008}\n:::\n:::\n\n\n::: {.dagcode}\nThe same graph in R. Every arrow is a formula, read outcome-first – so a `#` takes an arrow out and the code still runs:\n:::\n\n```r\ndagify(\n  framing ~ unemployment,\n  framing ~ country + year,\n  unemployment ~ country + year,\n  # framing ~ growth,        # uncomment the\n  # unemployment ~ growth,   # arrows you believe\n  exposure = \"unemployment\", outcome = \"framing\"\n) |> adjustmentSets()\n```\n:::\n\n::: {.column width=\"40%\"}\n::: {.small}\n- Drawn: the path + two confounder pairs (**country, year → two-way FE**)\n- Floating, unwired: growth (confounder?) · bailout (mediator?) · politicisation (mediator?)\n- You add the edges you believe, then run `adjustmentSets()`\n:::\n:::\n::::\n\n::: notes\nAnd this is the graph you will finish yourselves. The solid part is what we are committing to: unemployment to framing is the path of interest, and country and year are the two confounder pairs – stable national traits on one side, EU-wide shocks in a given year on the other. Run `adjustmentSets()` on this graph and it answers: country and year. Which is precisely what a two-way fixed-effects model absorbs – the graph and the baseline model are the same claim, written in two languages. The three pale nodes are yours to wire up, and they are genuine decisions. Is GDP growth a time-varying confounder that fixed effects cannot reach – a slump that raises unemployment and sours sentiment in the same year? Is the bailout a mediator, in which case you leave it alone if you want the total effect? Multi100 told us to disregard politicisation – was that defensible? The code beside the picture is the same graph written as R formulas, one arrow to a line, so wiring a node up is uncommenting the line you believe and running it again to see what the adjustment set has become. Whatever you decide here becomes your model in the next task.\n:::\n\n\n<!-- DEEP DIVE START: R tutorial (10 slides). Optional depth – press d during\n     the talk, or load the deck with ?depth=0, and slides/nav-tools.html lifts\n     the whole run out of the DOM. The switch acts on the .deepdive class that\n     every slide in the run carries, so that class is the load-bearing part;\n     these markers are here for the reader. -->\n\n## R, in one slide {.smaller .deepdive run=\"r\"}\n\n::: {.skiplink}\n[10 optional slides · skip to Hands-on 2 →](#hands-on-2-meet-the-panel-draw-the-graph)\n:::\n\n```{.r code-line-numbers=\"|1|3|5|7\"}\nx <- 42                          # <- assigns. \"x gets 42\"\n\nmean(c(2, 4, 6))                 # a function: name, then arguments in ()\n\neuframes$unemp                   # $ picks one column out of a data frame\n\neuframes |> nrow()               # |> the pipe: send the left into the right\n```\n\n::: {.small}\nFour things and you can read most R: **assign** with `<-` · **call** a function with `name(...)` · **reach into** an object with `$` · **chain** with the pipe `|>`.\n:::\n\n::: notes\nIf you have never written a line of R, this slide is most of what you need to read the rest. Four things. First, the arrow assigns: x gets forty-two. You will see the equals sign used the same way and both work, but the arrow is the convention and it reads better out loud. Second, a function is a name followed by round brackets containing its arguments – mean of two, four and six. Third, the dollar sign reaches inside an object to pull out one column. And fourth, the pipe, which is the one that changes how the code reads: it takes whatever is on its left and feeds it in as the first argument of whatever is on its right. So euframes pipe nrow means \"take euframes, and count its rows\". Once you see the pipe as the word 'then', long chains become readable sentences.\n:::\n\n## Getting data in {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1|3|5\"}\nlibrary(readr)                                # load a package\n\neuframes <- read_csv(\"data/EUframes_cy.csv\")  # read it, name it\n\neuframes                                      # print it\n```\n\n::: {.small}\nWhat comes back is a **data frame**: a rectangle, one row per observation, one column per variable, each column of a single type. Almost everything in R takes a data frame and gives you one back.\n\n`library()` makes the functions in a package available. It does **not** install it – that is `install.packages()`, and it happens once, not every time.\n:::\n\n::: notes\nGetting data in. The library line makes the functions in a package available for this session – and note that it does not install anything; installing is a separate thing you do once. Then read underscore csv reads the file and the arrow gives the result a name, so from here on euframes is our panel. Typing the name on its own prints it. What you get back is a data frame, which is the central object in R: a rectangle with one row per observation, one column per variable, and each column holding a single type. Nearly every function you will meet takes a data frame and hands you a data frame back, which is why the pipe works so well – the output of one step is the right shape to be the input of the next.\n:::\n\n## Look before you model {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1|2|3|5-6\"}\nglimpse(euframes)      # every column, its type, the first few values\nnrow(euframes)         # 270\nsummary(euframes$unemp)  # min, quartiles, mean, max\n\neuframes |>\n  count(cntry)         # how many rows per country?\n```\n\n::: {.fragment .small}\nThis is not a warm-up you skip. Every serious error I have made in twenty years of this was visible in the data before it reached a model – a duplicated year, a missing value coded as `-9`, a scale running 1–10 where I assumed 0–1.\n:::\n\n::: notes\nLook before you model. Glimpse shows every column with its type and first few values. nrow counts the rows. Summary on a single column gives the minimum, the quartiles, the mean and the maximum. And count, piped, tells you how many rows there are per country – which for a balanced panel should be the same number every time. Now, the fragment there is not a rhetorical flourish. Every serious error I have made in twenty years of doing this was visible in the data before it ever reached a model: a year that appeared twice, a missing value coded as minus nine and quietly averaged in, a scale running one to ten when I had assumed nought to one. Ten minutes of looking is the highest-return ten minutes in the whole workflow, and it is the part that people skip because it does not feel like analysis.\n:::\n\n## Five verbs do most of the work {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1|2|3|4|5\"}\neuframes |>\n  filter(year >= 2008) |>                       # keep some rows\n  select(cntry, year, mcosmo, unemp) |>         # keep some columns\n  mutate(unemp_c = unemp - mean(unemp)) |>      # make a new column\n  arrange(desc(unemp))                          # sort\n```\n\n::: {.small}\nRead it downwards as a sentence: *take the panel, then keep 2008 onwards, then keep four columns, then add a centred unemployment column, then sort by unemployment, highest first.*\n:::\n\n::: {.fragment .small}\nThe sixth verb is `summarise()`, usually with `group_by()`: collapse many rows into one per group. That is precisely how the panel you are working on was built from 390,000 respondents.\n:::\n\n::: notes\nFive verbs get you a very long way, and they all work the same way: first argument a data frame, result a data frame. Filter keeps rows. Select keeps columns. Mutate makes a new column. Arrange sorts. And the pipe strings them together so you read the whole thing downwards as a sentence: take the panel, then keep 2008 onwards, then keep these four columns, then add a centred unemployment column, then sort by unemployment with the highest first. The sixth verb, on the fragment, is summarise, usually paired with group-by: collapse many rows into one row per group. That is worth naming because it is exactly the operation that produced the panel you will be working on – three hundred and ninety thousand respondents collapsed into two hundred and seventy country-year means.\n:::\n\n## A model is a formula plus data {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1|3|5\"}\nmcosmo ~ unemp                    # \"mcosmo explained by unemp\"\n\nm <- lm(mcosmo ~ unemp, data = euframes)\n\nsummary(m)\n```\n\n::: {.small}\nThe tilde `~` reads **outcome on the left, predictors on the right**. Add predictors with `+`. The formula is an object in its own right – it does not know or care which function will eventually use it.\n:::\n\n::: {.fragment .small}\nAlmost every modelling function in R takes this same shape: `something(formula, data = ...)`. Learn the pattern once and `lm`, `glm`, `lmer`, `feols` and `betareg` all become variations.\n:::\n\n::: notes\nNow models. The tilde is the heart of it: outcome on the left, predictors on the right, and you add more predictors with a plus. The thing that surprises people coming from other software is that the formula is an object in its own right – you can store it in a variable, print it, pass it around – and it has no idea which function will eventually use it. Then lm fits a linear model given that formula and a data frame, the arrow names the result, and summary prints the coefficient table. The genuinely useful pattern is on the fragment: almost every modelling function in R has this same shape, something bracket formula comma data. Learn it once and lm, glm, lmer for multilevel models, feols for fixed effects and betareg for bounded outcomes all become variations on one thing you already know.\n:::\n\n## Fixed effects, the fast way {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1|3|3\"}\nlibrary(fixest)\n\nm1 <- feols(mcosmo ~ unemp_c | cntry + year, data = euframes)\n```\n\n::: {.small}\nThe bar `|` separates the regression from the **fixed effects**. Everything after it is absorbed: `cntry` gives every country its own intercept, `year` gives every year its own.\n\nThe equivalent with dummies would be `mcosmo ~ unemp_c + factor(cntry) + factor(year)` – same estimate, 36 extra rows of output you do not want to read.\n:::\n\n::: {.fragment .small}\nThis is the model you reproduce in Part 3. **`t = −3.804`.**\n:::\n\n::: notes\nThis one you will type yourself in a couple of hours, so it is worth a slow look. Feols comes from the fixest package and fits linear models with fixed effects very fast. The bar is the key piece of syntax: everything to the left of it is the regression, everything to the right is absorbed as fixed effects. Country gives every country its own intercept, so we are comparing each country with itself over time rather than comparing countries with each other. Year gives every year its own intercept, so anything that hit all of Europe in a given year is soaked up. You could write the same model with dummy variables – the estimate would be identical – but you would get thirty-six extra rows of output that nobody wants to read. And this exact line is the model you reproduce in part three, landing on minus three point eight zero four.\n:::\n\n## Reading what comes back {.smaller .deepdive run=\"r\"}\n\n```{.r}\nbroom::tidy(m1)\n#> term      estimate    std.error   statistic   p.value\n#> unemp_c   -0.00347    0.00091     -3.80       0.00019\n```\n\n::: {.small}\n- **estimate** – a one-point rise in unemployment goes with a fall of 0.00347 on a 0–1 framing scale\n- **std.error** – how much that estimate would wobble across repeated samples\n- **statistic** – the *t*: the estimate divided by its standard error. Roughly, how many standard errors from zero\n- **p.value** – how often you would see a *t* this large if the true value were zero\n:::\n\n::: {.fragment .small}\n`broom::tidy()` returns the table as a **data frame**, so you can filter it, join it, plot it. That is how 840 model fits become one chart this afternoon.\n:::\n\n::: notes\nAnd what comes back. The tidy function from broom turns the model into a small table. The estimate says a one-point rise in the unemployment rate goes with a fall of about three thousandths on a nought-to-one framing scale – small, but the scale is small too, which is why we will standardise later. The standard error says how much that estimate would move across repeated samples. The statistic is the t: the estimate divided by its standard error, which you can read as how many standard errors the estimate sits from zero. And the p-value says how often you would see a t that large if the true value were zero. Now the fragment, which matters more than it looks: tidy hands the table back as a data frame. That means you can filter it, join it, stack hundreds of them and plot the lot – and that is precisely how eight hundred and forty model fits become one chart this afternoon.\n:::\n\n## One line of ggplot {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1|2|3|4\"}\nggplot(euframes, aes(x = year, y = mcosmo)) +   # data, and what maps to what\n  geom_line(colour = \"grey55\") +                # draw lines\n  geom_point(size = 0.7) +                      # and points\n  facet_wrap(~ cntry)                           # one small panel per country\n```\n\n::: {.small}\nThree parts, always: the **data**, the **mapping** (`aes`) from variables to visual properties, and one or more **geoms** that draw something. Layers stack with `+`.\n:::\n\n::: {.fragment .small}\n`facet_wrap` is the one worth stealing today: it repeats the whole plot once per group. Twenty-seven small country panels, one line of code, and you can *see* which countries move.\n:::\n\n::: notes\nPlotting, briefly, because you will use it in the next task. Ggplot always has three parts. The data. The mapping – that is what aes does – saying which variable becomes which visual property, here year on the horizontal and cosmopolitan framing on the vertical. And then one or more geoms that actually draw something, stacked with plus signs: lines, then points on top. The one worth stealing today is on the fragment: facet-wrap repeats the entire plot once per group, so that single line gives you twenty-seven small country panels side by side. That is the plot you will make in the next task, and I want you to actually look at it rather than skip past it, because you can see with your eyes which countries move sharply around 2009 – and that is the variation that the fixed-effects model is using.\n:::\n\n## A causal graph is a set of formulas {.smaller .deepdive run=\"r\"}\n\n```{.r code-line-numbers=\"|1-4|2|3|6|7\"}\ndag <- dagify(\n  framing ~ unemployment,          # unemployment -> framing\n  framing ~ country + year,        # country and year -> framing\n  unemployment ~ country + year,   # ... and -> unemployment\n  exposure = \"unemployment\",\n  outcome  = \"framing\")\n\nadjustmentSets(dag)                # what must I control for?\n```\n\n::: {.small}\nEach line is **one arrow, read outcome-first** – exactly the same convention as a model formula. Which means you can comment an arrow out with a `#` and the code still runs.\n:::\n\n::: {.fragment .small}\n`adjustmentSets()` reads the graph and tells you which variables close every back-door path. Change an arrow, rerun, and watch the answer change.\n:::\n\n::: notes\nAnd the last piece, which is the one you use in this next task. A causal graph in R is just a set of formulas, and they follow exactly the same convention you already learned for models: outcome on the left, cause on the right. So the first line says unemployment points at framing. The second says country and year both point at framing. The third says they also both point at unemployment – which makes them common causes, which makes them confounders. Then you declare which node is the exposure and which is the outcome. The lovely part is on the fragment. Because each arrow is its own line, you can put a hash in front of one and the code still runs, so wiring your beliefs into the graph is literally a matter of commenting lines in and out. And adjustmentSets reads the finished graph and tells you which variables you must control for. Change an arrow, rerun it, watch the answer change.\n:::\n\n## When it breaks {.smaller .deepdive run=\"r\"}\n\n::: {.small}\n| What you see | What it usually means |\n|---|---|\n| `could not find function \"feols\"` | The package is not loaded – add `library(fixest)` above |\n| `object 'euframes' not found` | You ran this chunk before the one that creates it – go back up and run in order |\n| `object 'unemp_c' not found` | The column does not exist yet – you skipped the `mutate()` that makes it |\n| `+` on the console, nothing happens | An unclosed bracket or quote. Press **Esc** and look for the missing `)` |\n:::\n\n::: {.fragment .small}\nRead the error. R's messages are terse but almost always literally true – it is telling you the name of the thing it could not find.\n:::\n\n::: notes\nFour errors, which between them will be about ninety per cent of what you hit today. \"Could not find function\" means the package is not loaded – add the library line above it. \"Object euframes not found\" means you ran a chunk before the one that creates the object, so go back up and run them in order, and this is the notebook trap I mentioned this morning. \"Object unemp underscore c not found\" means you skipped the mutate line that makes the column. And if the console is showing you a plus sign and nothing is happening, R thinks you have not finished the command – there is an unclosed bracket or quote somewhere. Press Escape and go looking for it. The general advice is on the fragment and it is the single most useful habit: read the error. R's messages are terse and unfriendly, but they are almost always literally true – it is telling you the exact name of the thing it could not find.\n:::\n\n<!-- DEEP DIVE END -->\n\n## Hands-on 2: meet the panel, draw the graph {.smaller}\n\n::: {.small}\n**Task 2**, in either route – three pieces:\n\n1. **Look at the data.** 270 rows, 27 countries, 10 years. Run the country panel plot and find the ones that move\n2. **Write the estimand in words.** The template gives you the unit quantity, the target population, the aggregation – fill in each for *this* claim\n3. **Wire up the DAG.** Take the `#` off the arrows you are willing to defend, rerun `adjustmentSets()`, and see what it now demands\n:::\n\n::: {.fragment .small}\nTwo sentences for your notes: **what do two-way fixed effects adjust for, and what can they not fix?**\n:::\n\n::: {.fragment .small}\nWhatever you decide here becomes the model you defend in Part 3, and the justification you preregister in Part 4.\n:::\n\n::: notes\nYour turn, and this is the piece that people tell me afterwards changed how they work. Three things, in either route. First, look at the data – twenty-seven small panels, and find the countries that move sharply, because that is the variation that your model will use. Second, write the estimand in words using the template on the page: the unit-specific quantity, the population you want it over, and how you are averaging. Write it for this claim specifically – the whole value is in being forced to be precise. Third, the graph. Take the hash off the arrows you actually believe, rerun, and watch what adjustmentSets gives back. If you add growth as a confounder it will demand something the two-way model cannot deliver, and that is a real finding about the design, not a bug in your code. Then those two sentences for your notes. Twenty minutes. Shout in chat if you get stuck.\n:::\n\n## Lunch {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\nAn hour – the return time is in the chat · lunchtime browsing, if you like: the specification menu\n:::\n\n::: notes\nLunch – a full hour, and the return time is in the chat. If you want a head start on the afternoon, the specification menu page is worth five minutes with a sandwich: it is the list of choices you will pick from when you become the sixth analyst for real. See you back here.\n:::\n\n# PART 3 – Reproduce, then take the model apart {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\nPart 3 · 90 minutes\n:::\n\n::: notes\nPart three. First the reproduction, to the third decimal. Then the menu, and today we walk every axis of it: what the outcome scale and the outcome family do, why claim alignment is needed to compare them, what the predictor form changes and what it cannot, the four estimators and what fixed effects actually buy, the copredictor, the sample and the weights. Then you work the menu yourself.\n:::\n\n## Task 2, in the analysts' own words {.smaller}\n\n::: {.claimcard}\n\"Focus on the **'Cosmopolitan' dimension** for EU framing and on the **unemployment rate** as the independent variable; **disregard contextual variables**.\"\n:::\n\n::: {.small}\nThree instructions. Everything else – estimator, sample, weighting, functional form, how you build the scale – was left to us.\n:::\n\n::: {.fragment .small}\nThat is the design working as intended. Fix just enough to make the numbers comparable; leave the rest free, so that what remains is a measurement of **analytical variability itself**.\n:::\n\n::: notes\nHere, word for word, is what task two told us to do. Focus on the cosmopolitan dimension as the outcome, use the unemployment rate as the independent variable, and disregard the contextual variables. Three instructions – that is the whole brief. Everything else was left open: which estimator, which sample, whether to weight, what functional form, and even how to build the cosmopolitan scale out of the underlying items. And that is the design working exactly as intended. Multi100 fixed just enough to make five numbers comparable, and deliberately left the rest free, so that what remained would be a measurement of analytical variability itself rather than of anything about the paper. It follows that everything they left open is a place where five competent people could legitimately part company. And they did.\n:::\n\n## What those three instructions assume {.smaller}\n\n::: {.small}\n- **'The cosmopolitan dimension'** assumes the five items form one scale, and that a mean of them is the right summary. A sum, a share, or a factor score would all be defensible\n- **'The unemployment rate'** assumes the claim is carried by unemployment. The paper's own abstract says \"poor economic performances\" – which also names GDP growth\n- **'Disregard contextual variables'** removes the country-level controls. That buys comparability and gives up any defence against a time-varying confounder\n:::\n\n::: {.fragment .small}\nNone of these is wrong. Each one is a **decision**, made for you, that a different study could reasonably have made differently.\n:::\n\n::: notes\nNow take those three instructions apart, because each carries an assumption. 'The cosmopolitan dimension' takes for granted that the five items – peace, democracy, freedom of movement, cultural diversity, a stronger voice in the world – form one scale, and that averaging them is the right summary. A sum would be defensible. So would a share, or a factor score. 'The unemployment rate' assumes the claim is carried by unemployment, but the paper's own abstract says \"poor economic performances\", which just as clearly names GDP growth – and in Task 1, three of the five of us used a GDP measure rather than unemployment. And 'disregard contextual variables' strips out the country-level controls, which buys you comparability across analysts and gives up any defence against a confounder that varies over time. None of these is wrong. Each is a decision, made for you, that another study could reasonably have made differently.\n:::\n\n## The panel you will work on {.smaller}\n\n::: {.small}\n`EUframes_cy.csv` – **270 rows**, one per country-year · 27 countries · 2004–2013\n\n| Column | What it is |\n|---|---|\n| `cntry`, `year` | the cell |\n| `mcosmo` | mean cosmopolitan framing in that country-year, 0–1 |\n| `mutil`, `mcomm`, `mlib` | the other three framing scales |\n| `mpos`, `mneg` | the two composites – all positive items, all negative items |\n| `unemp`, `growth` | national unemployment rate and GDP growth |\n| `n_cy` | how many survey respondents are behind the cell |\n| `bailout` | 1 if an EU/IMF assistance programme was running |\n:::\n\n::: {.fragment .small}\n`n_cy` is the interesting one: cells are built from very different numbers of people, which is why **weighting** is a live choice on the menu.\n:::\n\n::: notes\nAnd here is the file itself, which everything from now on works from. Two hundred and seventy rows, one per country-year, twenty-seven countries over ten years. Country and year identify the cell. Mcosmo is the mean cosmopolitan framing in that cell, on a nought-to-one scale, and the other framing scales sit beside it. Unemployment and growth are the national macro indicators. And then n underscore cy, which counts how many survey respondents are behind each cell – and that is the interesting column, because those counts differ a great deal between cells. A country-year built from two thousand respondents and one built from five hundred are not equally precise, which is exactly why whether to weight by n is a live choice on the menu you are about to meet. That is the only file you will need all afternoon.\n:::\n## You are Analyst no. 6\n\n::: {.big}\n- Aim 1: **reproduce** analyst **C6HJR**'s constrained result\n:::\n\n  - **What Multi100 asked:** focus on the 'cosmopolitan' dimension and on the unemployment rate; disregard the contextual variables\n\n  - **What I submitted:** a two-way fixed-effects model, `mcosmo ~ unemp_c | cntry + year`\n\n  - **What is on record:** t ≈ −3.80 (df = 233, N = 270, partial *r* ≈ −0.242)\n\n::: notes\nSo here is your first job as the sixth analyst, and it is the same job I had. Multi100 asked for the cosmopolitan dimension, the unemployment rate, and no contextual variables. What I submitted was a two-way fixed-effects model – cosmopolitan framing on centred unemployment, with country and year absorbed – and what is on record for me is a t of minus three point eight zero, on two hundred and thirty-three degrees of freedom, which standardises to a partial correlation of minus point two four. Now, you have my code. You have my data. The whole of reproducibility is the question of whether that is enough for you to get my number back. Let us find out.\n:::\n\n## Hands-on 3: reproduce the recorded result {.smaller}\n\n::: {.small}\n- **Task 3** in your workspace or in the browser lab – the constrained specification: outcome `mcosmo`, unemployment centred, country and year fixed effects\n- One dataset, one object: `EUframes_cy.csv`, loaded as `euframes`\n- The cell has gaps to fill; there are two hints and a full solution if you want them\n:::\n\n::: {.fragment}\nTarget: **t = −3.804** – the value on record for analyst C6HJR. When you have it, type your t in chat and hold it until I say \"go\".\n:::\n\n::: notes\nNow you work. Open the working script in your workspace and go to Task three, or the browser lab, same task number. It is a fill-the-gaps cell rather than a blank page: centre the unemployment rate on its grand mean, then fit the two-way fixed-effects model with fixest. There are two hints if you want them and a fully worked solution underneath, and using either is not cheating – the point of this task is the number at the end, not the typing. You should land on t equals minus three point eight zero four, which is what Multi100 has on record for me. When you have it, type the t into chat but do not send – when I say \"go\", everyone sends at once. Twenty minutes. [Wait for the wall of identical numbers.]\n:::\n\n## One number, thirty people\n\n:::: {.none}\n::: {.fragment}\nThirty of you just landed on **t = −3.804**, to the third decimal. That is reproducibility, and it is the easy R.\n:::\n\n::: {.fragment}\nYou all ran the *same code*. The five Multi100 analysts each wrote their own – and came back with five different answers.\n:::\n\n::: {.fragment}\nNone of them was careless. So what were they doing differently? **The menu, next.**\n:::\n::::\n\n::: notes\nLook at what just happened. Thirty people, thirty machines, one number, agreeing to the third decimal. That is reproducibility, and I want you to notice how cheap it was: you all ran the same code on the same file, so of course you got the same number. Reproducibility is the easy R, and it is the one that this paper failed. [pause] Now hold that against the chart from this morning – five analysts of this same claim, five different answers, one of them not even significant. Not one of those five was careless. I have read all four of the others' code, line by line, and they are competent, well-organised pipelines written by people who knew exactly what they were doing. So the spread is not a quality problem. It is a choices problem, and the next thing I am going to show you is the full list of choices that were available to us.\n:::\n\n## The specification menu {.smaller}\n\n::: {.small}\n| Axis | Options |\n|---|---|\n| **Outcome** | `mcosmo` · `mutil` · `mcomm` · `mlib` · `mpos` · `mneg` |\n| **Outcome family** | gaussian · beta (logit link, for a bounded 0–1 scale) |\n| **Predictor** | unemployment · GDP growth · both |\n| **Predictor form** | raw · log (unemployment only – growth goes negative) |\n| **Copredictor** | none · the other macro measure |\n| **Estimator** | two-way FE · country FE · random effects · pooled with clustered SE |\n| **Sample** | all · 2004–2008 · 2009–2013 · no bailout countries · no Greece and Spain |\n| **Weights** | none · `n_cy` |\n:::\n\n::: {.small}\nEight axes. Copy-paste code for every option is on the specification menu page.\n:::\n\n::: {.fragment .small}\nTwo were on the board in the red-card study already: its 29 teams split across **four response distributions** (outcome family) and **four ways of handling non-independence** (estimator).\n:::\n\n::: notes\nHere is the menu, and everything left in the day runs off it. Eight axes, and every option on it is a choice a competent analyst could defend in print. Which framing scale is your outcome. Whether you model a bounded nought-to-one scale with a linear model or with something built for proportions. Whether the claim is carried by unemployment or by GDP growth, or both. Whether you take the rate raw or logged. Whether the other macro measure goes in beside it. Which of four ways you handle the fact that observations are grouped in countries and in years. Which countries and which years you keep. And whether you weight by how many people are behind each cell. The menu page has copy-paste code for every one of these, so nobody is writing R from a blank line.\n:::\n\n## What Task 2 left open {.smaller}\n\n::: {.small}\nThe three instructions fixed the **outcome dimension**, the **predictor** and the **contextual controls**. Everything else stayed open – including one thing nobody thinks of as a choice:\n:::\n\n::: {.fragment .small}\n**The unit of analysis.** Two of the five fitted models on **individual respondents**; three worked on **aggregates**. Task 2 never said which, and the wording did not imply one.\n:::\n\n::: {.fragment .small}\nTheir five answers, all obeying all three instructions, still ran from *r* = −0.006 to *r* = −0.45. The remaining freedom was more than enough.\n:::\n\n::: {.fragment .small}\nKeep that in mind this afternoon: **the choices that move an estimate most are usually the ones made before the model is fitted at all.**\n:::\n\n::: notes\nSo what did those three instructions actually pin down? The outcome dimension, the predictor, and the contextual controls. Everything else stayed open – including one thing that almost nobody thinks of as a methodological choice at all, which is the unit of analysis. Two of the five of us fitted models on individual respondents, hundreds of thousands of them. Three worked on aggregates. Task two never said which, and the wording did not imply one either way. And the consequence is on the next fragment: five answers, all obeying all three instructions, still running from minus point zero zero six to minus point four five. The freedom that remained after the constraints was more than enough to produce the whole spread. Hold that thought all afternoon, because it generalises: the choices that move an estimate most are usually the ones made before a model is fitted at all.\n:::\n\n## One deviation, and a reason for it {.smaller}\n\n::: {.small}\nFor the rest of today the rule is: **change one axis, hold the other seven at baseline.**\n\nBaseline = the specification you just reproduced: `mcosmo` · gaussian · unemployment · raw · no copredictor · two-way FE · all years · unweighted.\n:::\n\n::: {.fragment .small}\nWhy one at a time? Because it makes the class chart **readable**. Every dot in the room differs from a common baseline in exactly one declared way, so when a dot moves you can say what moved it.\n:::\n\n::: {.fragment .small}\nAnd one convention binds everyone: **claim-alignment**. The negative framings are reverse-coded, 1 − y, so that 'supports the claim' reads as a negative sign whatever your outcome. Without it the class chart would straddle zero by construction and look like noise.\n:::\n\n::: notes\nTwo ground rules before you touch the menu. First, one deviation: change one axis and hold the other seven at the baseline, which is the specification you have just reproduced – cosmopolitan outcome, gaussian, unemployment raw, no copredictor, two-way fixed effects, all years, unweighted. That sounds restrictive, and it is deliberate, because it is what makes the class chart readable. Every dot in the room will differ from one common baseline in exactly one declared way, so when a dot sits somewhere surprising we can say what put it there. Second, a convention that binds everybody: claim-alignment. If your outcome is one of the negative framings, it gets reverse-coded – one minus the scale – so that supporting the claim reads as a negative sign for every outcome in the room. Without that, half the class would be above zero by construction and the chart would look like noise.\n:::\n\n<!-- DEEP DIVE START: methodological tutorial (12 slides). Optional depth, on\n     the .deepdive class – see the note at the R tutorial in Part 2. -->\n\n## Six ways to say 'EU framing' {.smaller .deepdive run=\"methods\"}\n\n::: {.skiplink}\n[12 optional slides · skip to Hands-on 4 →](#hands-on-4-work-the-menu)\n:::\n\n::: {.small}\n| Scale | Items | Claim predicts |\n|---|---|---|\n| `mcosmo` | peace · democracy · free movement · diversity · voice | negative |\n| `mutil` | prosperity · social protection | negative |\n| `mcomm` | unemployment · identity · crime · borders | **positive** |\n| `mlib` | bureaucracy · waste of money | **positive** |\n| `mpos` | all seven positive items | negative |\n| `mneg` | all six negative items | **positive** |\n:::\n\n::: {.fragment .small}\nThe claim says \"decrease positive dimensions\" – `mpos` is the more literal reading, `mcosmo` is what was instructed. That one disagreement is worth roughly **half** the variance in the grid.\n:::\n\n::: notes\nStart with the outcome, because it turns out to matter more than everything else combined. One survey question – what does the EU mean to you personally – with thirteen response options, which the paper sorts into four scales. Cosmopolitan: peace, democracy, free movement, diversity, a stronger voice in the world. Utilitarian: prosperity and social protection. Communitarian: unemployment, loss of identity, crime, border control. Libertarian: bureaucracy and waste of money. And then two composites, all the positive items and all the negative ones. Notice the third column, because it trips people up: for the negative framings the claim predicts a positive coefficient, not a negative one. And notice the fragment. The claim's own words are \"decrease positive dimensions\", which points at the composite rather than at cosmopolitan alone. That one disagreement is worth about half the variance in the entire grid.\n:::\n\n## Building a scale: mean, sum or share? {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\nFive binary items per respondent. Three defensible summaries:\n\n- **Mean** of the five – a proportion between 0 and 1. Everyone contributes equally\n- **Sum** – a count from 0 to 5. Same information, different scale, different coefficient size\n- **Share** of all mentions – depends on how many options the respondent picked overall\n:::\n\n::: {.fragment .small}\nThese are not cosmetic. A **share** is relative to the respondent's own total, so somebody who ticked eight boxes contributes differently from somebody who ticked two. Mean and sum are not.\n:::\n\n::: {.fragment .small}\nAmong the five Multi100 analysts: one used a **mean**, one a **sum**, one a **share**, one three separate shares. All defensible; none the same quantity.\n:::\n\n::: notes\nAnd how do you turn five binary items into one number? Three summaries, all defensible. The mean of the five, which gives you a proportion between nought and one and lets every item count equally – that is what our panel uses. The sum, which is a count from nought to five: the same information on a different scale, so the coefficient will be five times bigger and mean the same thing. Or a share of all the respondent's mentions, which is the interesting one, because it is relative to how many boxes that person ticked overall. Somebody who ticked eight options contributes differently from somebody who ticked two. The mean and the sum do not work that way. And look at the fragment: among the five of us, one used a mean, one a sum, one a share, one three separate shares. All defensible, and not one of them the same quantity as the others.\n:::\n\n## Claim alignment, and why the room needs it {.smaller .deepdive run=\"methods\"}\n\n```{.r code-line-numbers=\"|1|3\"}\nd$mcomm_ca <- 1 - d$mcomm      # reverse-code a negative framing\n\n# now: negative coefficient = supports the claim, whatever the outcome\n```\n\n::: {.small}\nReverse-coding a bounded scale **flips the sign** of *b*, *t* and *r*, and leaves the magnitude, the standard error, the |t| and the p-value untouched. Exactly so for the beta family too, since logit(1 − μ) = −logit(μ).\n:::\n\n::: {.fragment .small}\nNothing about your evidence changes. Only the direction convention it is reported in.\n:::\n\n::: {.fragment .small}\nIt is still a real analytic decision, which is why it rides on an explicit `claim_align` switch in your preregistration rather than sitting silently inside the fitting code.\n:::\n\n::: notes\nNow the convention that makes the class chart work. If your outcome is one of the negative framings, you reverse-code it before fitting: one minus the scale. What that does is flip the sign of the coefficient, the t and the partial r, and leave everything else exactly where it was – the magnitude, the standard error, the absolute t, the p-value. And it holds exactly for the beta family too, because the logit of one minus mu is just minus the logit of mu. So nothing about your evidence changes; only the direction convention it is reported in. But – and this is why we do it explicitly – it is still a real analytic decision, and a reader deserves to see it. That is why it rides on a visible claim-align switch in your preregistration block rather than being buried three lines inside the fitting code where nobody would find it.\n:::\n\n## A bounded scale in a linear model {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\nOur outcome is a proportion: it lives strictly between 0 and 1, and its variance is smallest near the ends. A linear model assumes neither of those things.\n\n- **Gaussian** – fit it as if it were unbounded. Simple, familiar, and can in principle predict outside 0–1\n- **Beta** – a logit-link beta regression, built for exactly this shape. Reports a **z**, not a *t*\n:::\n\n::: {.fragment .small}\nOn this claim, the two agree: the beta twin of the baseline gives **b(logit) = −0.01399, z = −4.075, r = −0.258**, against the gaussian **r = −0.242**. Same direction, still significant, marginally stronger.\n:::\n\n::: {.fragment .small}\nThe seminar argument about distributional assumptions is real, and on this claim it moves almost nothing.\n:::\n\n::: notes\nHere is a proper methodological question. Our outcome is a proportion – it lives strictly between nought and one, and its variance is necessarily smallest near the two ends, because a mean near zero cannot vary much. A linear model assumes neither of those things. So you have a choice. Gaussian treats it as if it were unbounded: simple, familiar, and in principle capable of predicting a framing score of one point two. Or beta regression with a logit link, which is built for exactly this shape and reports a z rather than a t. Now the part I like. On this claim the two agree: the beta twin of our baseline gives a logit coefficient of minus point zero one four, z of minus four point zero eight, partial r of minus point two six, against the gaussian's minus point two four. Same direction, still significant, marginally stronger. The distributional argument is a real one, and here it moves almost nothing.\n:::\n\n## Which variable carries the claim? {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\nThe abstract says \"poor economic performances\". That names at least two things:\n\n- **Unemployment rate** – what Task 2 instructed. Higher is worse\n- **GDP growth** – what three of the five analysts chose in their free phase. Higher is *better*, so the claim predicts a **positive** coefficient on positive framings\n:::\n\n::: {.fragment .small}\nFitted on our panel, the growth mirror of the baseline gives **b = +0.00167, t = 1.59** – the right direction, not significant.\n:::\n\n::: {.fragment .small}\nAcross the whole growth half of the grid: **70.5%** in the direction predicted by the claim, but only **46.9%** significant. Direction without significance – a different kind of support from the unemployment story.\n:::\n\n::: notes\nWhich variable actually carries the claim? The abstract says \"poor economic performances\", and that phrase names at least two different things. The unemployment rate, which is what task two instructed and where higher means worse. Or GDP growth, which is what three of the five of us reached for when we were free to choose, and where higher means better – so the claim predicts a positive coefficient on the positive framings, not a negative one. Fit the growth mirror of our baseline on this panel and you get plus point zero zero one seven with a t of one point six: right direction, not significant. And across the whole growth half of the grid, seventy per cent in the direction predicted by the claim but only forty-seven per cent significant. That is direction without significance, which is a materially different kind of support from what the unemployment story offers, and a reader deserves to be told which one they are getting.\n:::\n\n## Predictor form, and a warning {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\n- **Raw** `unemp` – a one-point rise in the rate\n- **log(unemp)** – a proportional rise. Says the step from 4% to 5% matters more than 20% to 21%\n:::\n\n::: {.fragment .small}\nThose two are genuinely different models and can give different answers.\n:::\n\n::: {.fragment .small}\nBut **centring and standardising are not**. Subtracting a mean, or dividing by a standard deviation, is an *affine* change of scale: it moves the coefficient and its standard error by the same factor and leaves **t, r and p exactly unchanged**.\n:::\n\n::: {.fragment .small}\nWhich is why the grid holds no separate centred rows. If a robustness check varies only the centring, it is not a robustness check – it is the same analysis, restated.\n:::\n\n::: notes\nPredictor form. Raw unemployment asks what a one-point rise in the rate does. Logged unemployment asks what a proportional rise does, which is a substantively different claim: it says the step from four per cent to five matters more than the step from twenty to twenty-one, and for something like unemployment that is quite plausible. Those two are genuinely different models and they can give different answers. But now the warning, which is the part of this slide worth remembering. Centring and standardising are not. Subtracting a mean, or dividing by a standard deviation, is an affine change of scale: it moves the coefficient and its standard error by exactly the same factor, so the t, the partial r and the p-value are untouched. That is why our grid contains no separate centred rows at all. If you see a robustness check that varies only the centring, it is not a robustness check – it is the same analysis written differently.\n:::\n\n## Four ways to handle countries and years {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\n| Estimator | What it compares | What it assumes |\n|---|---|---|\n| **Pooled, clustered SE** | countries with each other *and* over time | no unobserved country differences |\n| **Country FE** | each country with itself over time | country differences are stable |\n| **Two-way FE** | the same, net of EU-wide year shocks | shocks hit everyone alike |\n| **Random effects** | a weighted blend of both comparisons | country effects uncorrelated with the predictor |\n:::\n\n::: {.fragment .small}\nThese do not answer the same question. Pooled asks whether *high-unemployment countries* frame the EU differently; fixed effects ask whether *a country frames it differently when its own rate rises*.\n:::\n\n::: {.fragment .small}\nAnd it shows: of the 41 wrong-sign specifications in the cosmopolitan universe, **33 are pooled**.\n:::\n\n::: notes\nFour estimators, and the thing to hold on to is that they do not answer the same question. Pooled with clustered standard errors compares countries with each other and with themselves at once, and assumes there is nothing systematically different about countries that you have not measured – which for twenty-seven European states is a strong assumption. Country fixed effects compare each country only with itself over time, which means every stable national difference drops out. Two-way fixed effects do the same and additionally soak up anything that hit all of Europe in a given year. Random effects blend the two comparisons, weighting by precision, and assume the country effects are uncorrelated with your predictor. Read the fragment carefully, because this is the substantive point: pooled asks whether high-unemployment countries frame the EU differently, and fixed effects ask whether a country frames it differently when its own rate rises. Different questions. And it shows – thirty-three of the forty-one wrong-sign specifications are pooled.\n:::\n\n## What fixed effects actually buy you {.smaller .deepdive run=\"methods\"}\n\n:::: {.columns}\n::: {.column width=\"52%\"}\n::: {.small}\n**They do absorb**\n\n- Anything stable about a country over the decade – institutions, history, size, prior EU sentiment\n- Anything common to a year across all countries – the crisis itself, a treaty, a media cycle\n:::\n:::\n::: {.column width=\"48%\"}\n::: {.small}\n**They do not touch**\n\n- A confounder that **varies within a country over time** – a national bailout, a change of government\n- **Reverse causation**: today's framing moving tomorrow's unemployment\n- Measurement error, selection into the sample\n:::\n:::\n::::\n\n::: {.fragment .small}\nThis is the same statement as the DAG you drew before lunch. `adjustmentSets()` on the committed graph returns country and year – exactly what two-way fixed effects absorb. **The graph and the baseline model make the same claim.**\n:::\n\n::: notes\nWorth being precise about what fixed effects buy, because they are often treated as a general-purpose cure. They absorb anything stable about a country across the decade – institutions, history, size, whatever the country already thought about the EU in 2004. And they absorb anything common to a year across all countries: the crisis itself, a treaty, a Europe-wide media cycle. What they do not touch is anything that varies within a country over time, which is precisely where the interesting confounders are – a national bailout programme, a change of government, a domestic scandal. They do nothing about reverse causation, where today's framing moves tomorrow's unemployment. And nothing about measurement error or selection. Then the fragment: run adjustmentSets on the graph you built before lunch and it returns country and year. The graph and the baseline model are making the same claim.\n:::\n\n## Copredictor: control, or second exposure? {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\nPut GDP growth in beside unemployment and you have made a choice you should be able to name:\n\n- **As a confounder** – a slump raises unemployment *and* sours sentiment in the same year. Adjusting closes a back-door that your fixed effects cannot reach\n- **As a rival exposure** – growth is a second measure of the same \"poor economic performance\". Now you are asking which one carries the claim\n- **As a mediator** – if unemployment works *through* growth, adjusting removes part of the effect you wanted\n:::\n\n::: {.fragment .small}\nSame line of code, three different estimands. And remember the **Table 2 fallacy**: the growth coefficient in that model is not automatically the causal effect of growth.\n:::\n\n::: notes\nThe copredictor axis looks like the most innocuous choice on the menu, and it is the one that most often goes wrong. If you put GDP growth into the model beside unemployment, you have made a choice, and you should be able to say which one. You might mean it as a confounder: a slump raises unemployment and sours sentiment in the same year, so adjusting for growth closes a back-door path that your fixed effects cannot reach, because it varies within country over time. Or you might mean it as a rival exposure – growth is another measure of the same poor economic performance, and you are now asking which of them carries the claim. Or, if unemployment works partly through growth, growth is a mediator and adjusting for it removes part of the very effect you set out to measure. Same line of code, three different estimands. And do not forget the Table 2 fallacy: the growth coefficient in that model is not automatically the causal effect of growth.\n:::\n\n## Sample: which countries, which years {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\n- **All** – 2004–2013, 27 countries, 270 cells\n- **2004–2008** vs **2009–2013** – before and during. Halves your data and asks whether the relationship is a crisis phenomenon\n- **No bailout countries** – drop the cells where an EU/IMF programme was running\n- **No Greece and Spain** – drop the two extreme unemployment trajectories\n:::\n\n::: {.fragment .small}\nThe last two exclusions test whether the association is carried by a handful of extreme cases. If it is, removing them should worry you – and it does something visible here: **24 of the 41 wrong-sign specifications** sit in bailout-excluding samples.\n:::\n\n::: {.fragment .small}\nAn exclusion is a claim about **who the finding is meant to be about**. That is an estimand question, not a housekeeping one.\n:::\n\n::: notes\nSample. All years is the baseline. Splitting into 2004 to 2008 and 2009 to 2013 halves your data and asks a real question: is this a crisis phenomenon or a standing relationship? Then two exclusions. Drop the countries while an EU or IMF programme was running. Or drop Greece and Spain, whose unemployment trajectories are so extreme they could plausibly drive the whole thing on their own. Those last two are the interesting ones, because if an association is carried by a handful of extreme cases, taking them out should worry you – and it does something visible here: twenty-four of the forty-one wrong-sign specifications sit in bailout-excluding samples. Take the crisis countries out and the association goes. And notice what an exclusion really is. It is a claim about who your finding is meant to be about. That makes it an estimand question, not housekeeping.\n:::\n\n## Weights: whose country-year counts more? {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\nEach cell is a mean of very different numbers of respondents. Weighting by `n_cy` says a cell built from 2,000 people should count more than one built from 500.\n\n- **Unweighted** – every country-year is one observation. You are studying *countries*\n- **Weighted by `n_cy`** – cells count in proportion to the people behind them. You are closer to studying *people*\n:::\n\n::: {.fragment .small}\nThat is a shift of estimand, not a technical refinement. Which is why the day's convention is to declare it.\n:::\n\n::: {.fragment .small}\nPractical note: random effects are never fitted with weights in the grid – the combination is not well defined for this design, so those rows do not exist.\n:::\n\n::: notes\nWeights. Each cell in the panel is a mean over a very different number of respondents, so weighting by that count says a country-year built from two thousand people should carry more than one built from five hundred. And that sounds like a purely technical refinement, but it is not. Unweighted, every country-year is one observation and you are studying countries – Malta counts as much as Germany. Weighted, cells count in proportion to the people behind them, and you have moved a long way towards studying people. That is a change of estimand, not a change of estimator, which is exactly why the day's convention is that you declare it rather than let it sit in an argument to the fitting function. One practical note: random effects are never fitted with weights in our grid, because the combination is not well defined for this design, so those rows simply do not exist.\n:::\n\n## Making the axes comparable {.smaller .deepdive run=\"methods\"}\n\n::: {.small}\nA coefficient from a beta model on a share and one from a weighted pooled model on a sum are not on the same scale. The answer from Multi100, and ours:\n\n- Take the test statistic and its degrees of freedom\n- Convert to a **partial correlation** *r* – the association between predictor and outcome, net of everything else in the model, on a fixed −1 to +1 scale\n- Apply **claim alignment**, so the sign means the same thing everywhere\n:::\n\n::: {.fragment .small}\nNow every specification in the room, and all 840 in the grid, sit on one axis. `report_result()` does the conversion for you.\n:::\n\n::: {.fragment .small}\nThe cost is worth naming: standardising makes numbers **comparable**, not **equivalent**. It cannot rescue two analyses that estimate different quantities – it can only put them side by side.\n:::\n\n::: {.fragment .small}\nSilberzahn's teams hit the same wall: four of the twenty-nine reported a correlation or a standardised difference rather than an odds ratio. The authors converted everything to one scale and reported the **median**. That is a different answer to the same problem – a median is one number, a curve is a distribution – and which you want depends on what you mean to say next.\n:::\n\n::: notes\nLast one, and it is what makes the afternoon possible. A coefficient from a beta model on a share and a coefficient from a weighted pooled model on a sum are simply not on the same scale – you cannot put them on one axis and read anything off it. The answer from Multi100, and ours, is to take the test statistic and its degrees of freedom, convert to a partial correlation, and then apply claim alignment so the sign means the same thing everywhere. A partial r is the association between predictor and outcome net of everything else in the model, on a fixed scale from minus one to plus one. Report underscore result does that conversion for you. And the cost deserves naming: standardising makes numbers comparable, not equivalent. It cannot rescue two analyses that are estimating different quantities. All it can do is put them next to each other – which is exactly what Part 2 warned you about.\n:::\n\n<!-- DEEP DIVE END -->\n\n## Hands-on 4: work the menu {.smaller}\n\n::: {.small}\n**Task 4 is exploration, and it is meant to be.** Try several specifications, look at what each one does, and get a feel for which axes move the estimate.\n\n1. Start from the baseline you reproduced\n2. Change **one axis**, refit, and note what happened to *b*, *t* and the partial *r*\n3. Do it again with a different axis. Three or four is plenty\n4. Then pick the one you can argue for best, and **submit it**\n:::\n\n::: {.fragment .small}\nYour dot lands on the live **Multiverse** page within seconds. We read the room's dots at the start of Part 4.\n:::\n\n::: {.fragment .small}\nThis is **not** your preregistered analysis. You are allowed to look, change your mind, and try again – that is the whole point of naming this phase separately.\n:::\n\n::: notes\nRight. This is the part of the day where you get your hands properly dirty, and I want to be explicit about what kind of activity it is, because it is different from what comes after the break. Task four is exploration and it is meant to be. Start from the baseline you reproduced. Change one axis, refit, and write down what happened to the coefficient, the t and the partial r. Then do it again with a different axis – three or four goes is plenty. Then pick whichever one you can argue for best and submit it, and your dot lands on the live multiverse page within seconds. We open Part 4 by reading what the room built. And the fragment matters: this is not your preregistered analysis. Here you are allowed to look, change your mind and try again. Naming that phase out loud, as its own thing, is exactly what most published work fails to do.\n:::\n\n## How long will anything take? {.smaller visibility=\"hidden\"}\n\n::: {.small}\nMeasured on the 270-row panel, on an ordinary laptop:\n\n| What | Time |\n|---|---|\n| `feols` two-way FE · pooled OLS with clustered SE | under 0.01 s |\n| `plm` within / random effects | ~0.02 s |\n| `betareg` with country and year dummies | ~0.05 s |\n| `glmmTMB` beta random effects | ~0.3 s |\n:::\n\n::: {.small}\n**Nothing here is slow.** If a participant is waiting, it is not the model – it is a package **download**:\n\n- browser lab, `ggdag` for the Task 2 picture: **≈ 23 MB**, one slow moment on poor wifi. The `adjustmentSets()` answer itself needs none of it\n- browser lab, `glmmTMB` for beta random effects: a heavy wasm download, installed on demand\n- the workspace, first run: the whole package set installs once\n:::\n\n::: notes\n[Facilitator slide, hidden in the deck – for answering \"how long should this take?\" without guessing.] Every fit on this panel is effectively instantaneous, including the beta models. Nobody is waiting for a model. What people do wait for is a package download: ggdag in the browser lab is about twenty-three megabytes, which is one slow moment on a bad connection, and glmmTMB is a heavy wasm download if somebody picks beta random effects. The first run in the workspace installs the whole set once. So if someone reports that it is stuck, ask what it is stuck on before assuming the model is the problem.\n:::\n\n## Break {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\n30 minutes – then we read what the room built · leave the Multiverse page open\n:::\n\n::: notes\nBreak – thirty minutes, and leave the multiverse page open in a tab, because when we come back the first thing we do is read it. If your submission has not landed, flag it in chat and we will sort it out over the break; everybody gets a dot.\n:::\n\n# PART 4 – The multiverse and the one path you declare {.darkslide background-color=\"rgba(0,0,0,0)\"}\n\n::: {.partlabel}\nPart 4 · 90 minutes\n:::\n\n::: notes\nPart four reads what the room built. Where the multiverse idea came from and what it is for, walked in full today; the class chart against the five analysts; which fork carries the variation; and then the part people most often get wrong – why hundreds of estimates on one dataset are not hundreds of tests, and what a curve-level test would have to do. We end on the critics, on what preregistration settles, and on the one analysis you declare before it runs.\n:::\n\n## You just built a small multiverse {.smaller}\n\n:::: {.none}\n::: {.fragment}\nYou ran three or four specifications, all defensible, and watched the estimate move.\n:::\n\n::: {.fragment}\nNothing about that is unusual. **Every analysis you have ever published sat inside a space like that** – you simply reported one point from it.\n:::\n\n::: {.fragment}\nThe multiverse idea is not a new estimator. It is the proposal that the **space** is the finding, and that showing one point without it is a form of incomplete reporting.\n:::\n::::\n\n::: notes\nLook at what you just did. You ran three or four specifications, every one of them defensible, and you watched the estimate move around. Now – nothing about that is unusual or improper. I want to say that clearly, because there is a slightly accusatory tone in some of this literature that I do not think is deserved. Every analysis any of us has ever published sat inside a space exactly like the one you were just wandering around in. The difference is that we reported one point from it and did not mention the rest, mostly because it did not occur to us that the rest was reportable. So the multiverse idea is not a new estimator and not an accusation. It is the proposal that the space itself is a finding, and that showing one point from it without the space around it is a form of incomplete reporting.\n:::\n\n<!-- DEEP DIVE START: multiverse tutorial (8 slides). Optional depth, on the\n     .deepdive class – see the note at the R tutorial in Part 2. -->\n\n## Where the idea comes from {.smaller .deepdive run=\"multiverse\"}\n\n::: {.skiplink}\n[8 optional slides · skip to the class chart →](#the-class-multiverse)\n:::\n\n::: {.small}\n- **Multiverse analysis** [@SteegenEtAl2016IncreasingTransparencyMultiverse] – born from *data-processing* choices: how you code, exclude and combine. Report the whole set of datasets that your choices could have produced\n- **Specification curve analysis** [@SimonsohnEtAl2020SpecificationCurveAnalysis] – the same move for *model* choices, plus a visual grammar: estimates on top, the choices that produced each one underneath\n- **The vibration of effects** – the same idea, arrived at independently in epidemiology\n- **The book-length treatment** [@YoungCumberworth2025MultiverseAnalysisComputational] – computational recipes at scale\n:::\n\n::: {.fragment .small}\nDifferent names, one move: **stop treating your analytical choices as invisible, and enumerate them.**\n:::\n\n::: notes\nBrief history, because the vocabulary is a mess and knowing which word came from where helps. Multiverse analysis is Steegen and colleagues in 2016, and it grew out of data-processing choices specifically – how you code a variable, which cases you exclude, how you combine items – with the proposal that you report the whole set of datasets that your choices could have produced. Specification curve analysis is Simonsohn, Simmons and Nelson, making the same move for model choices, and adding the visual grammar you are about to see: estimates plotted on top, and underneath them a panel showing which choices produced each one. The vibration of effects is the same idea arrived at independently in epidemiology, which tells you it is a natural response to the problem rather than a fashion. And there is now a book-length treatment with computational recipes. Different names, one move: stop treating your analytical choices as invisible and enumerate them.\n:::\n\n## The garden, drawn {.smaller .deepdive run=\"multiverse\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/forking-paths-1.png){width=864}\n:::\n:::\n\n\n::: {.small}\nFour binary choices give sixteen analyses. **Eight axes with several options each give hundreds.** The published paper reports one red line and no tree.\n:::\n\n::: notes\nHere is the structure of the problem, drawn. Four choices, two options each, and you already have sixteen distinct analyses. Our menu has fourteen axes and most of them have more than two options, which is how you get from hundreds to hundreds of thousands. And the point of the picture is the red line: what a published paper reports is one route through this tree, with no indication that the tree exists. The reader sees a coefficient and a standard error, and the standard error describes uncertainty from sampling – it says nothing whatever about the fifteen other branches. Gelman and Loken's phrase for this is the garden of forking paths, and their sharp observation, which we met this morning, is that you do not have to walk every path for this to be a problem. Walking one path that you chose after seeing the data is enough.\n:::\n\n## Justifiable, not merely possible {.smaller .deepdive run=\"multiverse\"}\n\n::: {.small}\nA multiverse is **not** every analysis you could run. Two filters have to be applied before anything goes in:\n\n- **Justifiability** – could you defend this specification to a reviewer, in writing, before seeing its result?\n- **The same estimand** – does it estimate the quantity you said you were after?\n:::\n\n::: {.fragment .small}\nDrop the first filter and you get a cloud of nonsense that makes any finding look fragile. Drop the second and you are averaging over answers to different questions – which is the red-card mistake, at scale.\n:::\n\n::: {.fragment .small}\nToday's grid is a **curated 840**, chosen against both filters. That curation is itself an analytical decision, and it is the one that a critic should attack first.\n:::\n\n::: notes\nThis is where multiverse analysis is most often done badly, so it is worth slowing down. A multiverse is not every analysis you could run. Two filters have to be applied before a specification is allowed in. The first is justifiability: could you defend this specification to a reviewer, in writing, before seeing what it gives? The second is that it has to estimate the same quantity you said you were after. Drop the first filter and you generate a cloud of nonsense, and since nonsense specifications produce scattered answers, any finding on earth looks fragile. Drop the second and you are averaging over answers to different questions, which is the red-card mistake reproduced at scale. Today's grid is a curated eight hundred and forty, chosen against both filters. And notice that the curation is itself an analytical decision – it is the first thing that a critic should attack.\n:::\n\n## Enumerate, or curate? {.smaller .deepdive run=\"multiverse\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.small}\n**Enumerate**\n\nCross every option on every axis. Complete, mechanical, reproducible.\n\nRisk: the set fills up with specifications nobody would defend, and the spread stops meaning anything.\n:::\n:::\n::: {.column width=\"50%\"}\n::: {.small}\n**Curate**\n\nInclude only the specifications you would actually defend.\n\nRisk: you are choosing the set, so a sceptic can ask whether you chose it to get the picture you wanted.\n:::\n:::\n::::\n\n::: {.fragment .small}\nThere is no way out of this. Either way, **the set is a claim**, and it belongs in the paper alongside the curve – ideally declared before the curve is drawn.\n:::\n\n::: notes\nSo how do you build the set? Two strategies, and both have a real cost. Enumerate: cross every option on every axis mechanically. It is complete, it is reproducible, and nobody can accuse you of hand-picking. The risk is that the set fills up with specifications nobody would defend, and once it does, the spread stops meaning anything – of course the answer varies, you included analyses that are wrong. Or curate: include only the specifications you would actually defend in print. That fixes the first problem and creates a second, because now you are choosing the set, and a sceptic can reasonably ask whether you chose it to produce the picture you wanted. There is no way out of this dilemma, and I do not think you should pretend there is. Either way the set is a claim, it belongs in the paper next to the curve, and ideally it is declared before the curve is drawn.\n:::\n\n## Multiplying the menu out {#the-arithmetic-gets-away-from-you .smaller .deepdive run=\"multiverse\"}\n\n::: {.small}\nOur menu, multiplied out:\n\n- 6 outcomes × 2 predictor forms × 3 copredictors × 4 estimators × 5 samples × 2 weightings, minus the combinations that are not defined → **840** distinct analyses\n- Add the **outcome family** axis → **1,680**\n- Add **GDP growth** as the claim carrier → **2,520**, the canonical universe on the results page\n- Open the four regression weights and the five **measurement** decisions – how the outcome is built, what happens to no-opinion respondents, which items, design-weighted cells or not, which published series – and the standard-error convention → **449,280** linear fits, **457,080** rows once the beta twins and two imputation engines are in\n- Open the **unit of analysis** as well – person level or aggregate – and the arithmetic doubles again\n:::\n\n::: {.fragment .small}\nTwo consequences. **Compute stops being free**, so somebody must decide what is worth running. And **you cannot look at 450,000 numbers** – you need a picture, and a way to ask which axis is doing the work.\n:::\n\n::: notes\nNow multiply the menu out. Six outcomes, two predictor forms, three copredictor settings, four estimators, five samples, two weightings – minus the combinations that are not defined, like random effects with weights – and you land on eight hundred and forty distinct analyses. Add the outcome family axis and it doubles to one thousand six hundred and eighty. Add GDP growth as an alternative claim carrier and it is two and a half thousand. And if you also opened the unit of analysis, person level or aggregate, the menu arithmetic runs past five thousand. Two consequences follow. First, compute stops being free, so somebody has to decide what is worth running, and that decision is not neutral. Second, and more practically, you cannot look at two and a half thousand numbers. You need a picture, and you need a way of asking which axis is actually doing the work.\n:::\n\n## What is a multiverse *for*? {.smaller .deepdive run=\"multiverse\"}\n\n::: {.small}\nRohrer, Hullman and Gelman's question, and it has three different answers that want three differently built universes:\n\n- **Reflection** – to understand your own analysis. Which choices matter, where the argument has to happen. Build it broad, and read it yourself\n- **Persuasion** – to convince a reader that the finding is not an artefact of one path. Build it from specifications that *your critic* would accept\n- **Inference** – to make a probabilistic statement about the curve as a whole. Build it to a fixed, declared rule, and bring a null distribution\n:::\n\n::: {.fragment .small}\nToday's grid was built for **reflection**. Reading it as inference is the mistake we take apart later in this part.\n:::\n\n::: {.src}\n@RohrerEtAl2026WhatsMultiverseGood\n:::\n\n::: notes\nAnd then the question that organises the whole debate, which is Rohrer, Hullman and Gelman's: what is a multiverse actually for? Because there are three answers and they want three differently built universes. If it is for reflection – understanding your own analysis, finding out which choices matter and where the argument has to happen – build it broad and read it yourself; it does not even have to go in the paper. If it is for persuasion – convincing a reader that your finding is not an artefact of one path – then build it out of specifications that your critic would accept, not ones you like. And if it is for inference, making a probabilistic statement about the curve as a whole, then you need a fixed declared rule and a null distribution, and that is a much heavier undertaking. Today's grid was built for reflection. Reading it as inference is exactly the mistake we take apart later in this part.\n:::\n\n## Which fork matters? {.smaller .deepdive run=\"multiverse\"}\n\n::: {.small}\nOnce you have hundreds of estimates and the choices that produced each one, you can ask a question that no single analysis can answer: **how much of the variation does each axis account for?**\n\n- Treat the specification grid as data: one row per analysis, the axes as factors, the estimate as the outcome\n- Decompose the variance across axes\n:::\n\n::: {.fragment .small}\nThe answer is the most useful thing a multiverse produces, because it tells you **where to spend your argument**. An axis that moves nothing does not need defending. An axis that moves everything needs a paragraph.\n:::\n\n::: {.fragment .small}\nOn this claim, the answer surprises almost everybody – which is why you are going to bet on it in a minute before I show you.\n:::\n\n::: notes\nThis analysis only becomes possible once you have hundreds of estimates and a record of which choices produced each one. You can turn the grid itself into a dataset – one row per analysis, the eight axes as factors, the estimate as the outcome – and decompose the variance across axes. How much of the spread does each fork account for? I think that is the most useful thing a multiverse produces, and it is much more useful than the curve itself, because it tells you where to spend your argument. An axis that moves nothing does not need defending in your paper; you can say so in a sentence and move on. An axis that moves everything needs a paragraph of justification, and probably a sensitivity analysis. On this claim the answer surprises nearly everybody, which is why in a moment I am going to make you bet on it before I show you.\n:::\n\n## Reading a specification curve {.smaller .deepdive run=\"multiverse\"}\n\n::: {.small}\nFive questions to ask any curve you meet, in any paper:\n\n1. **What is on the vertical axis** – a raw coefficient, or something standardised? Are the signs aligned so that up and down mean the same thing throughout?\n2. **How was the set built** – enumerated or curated, and by whom?\n3. **Where does the published estimate sit** – at the median, or out at an end?\n4. **Is the spread patterned** – does one axis produce the extremes, or is it scattered?\n5. **What null is the significance shading against** – and are the specifications independent? (They almost never are.)\n:::\n\n::: {.fragment .small}\nYou are about to answer all five for your own curve. That is a publishable robustness section.\n:::\n\n::: notes\nAnd to close the tutorial, five questions to ask of any specification curve you ever meet, in anybody's paper. One: what is on the vertical axis – a raw coefficient, which is not comparable across outcomes, or something standardised; and are the signs aligned so that up and down mean the same thing all the way across. Two: how was the set built, enumerated or curated, and by whom. Three: where does the published estimate sit – comfortably at the median, or out at one end, because those are very different situations for the author. Four: is the spread patterned – does one axis produce all the extremes, or is it genuinely scattered. And five, the one nobody asks: what null is that significance shading against, and are the specifications independent of each other? They almost never are, and we will spend some time on why that matters. You are about to answer all five for your own curve, and that is a publishable robustness section.\n:::\n\n<!-- DEEP DIVE END -->\n\n## The class multiverse\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/spec-curve-1.png){width=912}\n:::\n:::\n\n\n::: {.small}\n- The canonical universe of **2,520** specifications: the canonical **840** (blue unemployment triangles) plus the outcome-family and predictor axes, all at the canonical measurement settings\n- The canonical 840: **68.7%** claim-consistent direction · **63.9%** significant · claim-aligned partial r from **−0.70 to +0.24**\n:::\n\n::: {.src}\nPre-computed over the specification menu (data/spec_grid_full.csv), claim-aligned – negative framings reverse-coded and growth predictors sign-flipped, as recorded in your Task 5 preregistration (claim_align = TRUE).\n:::\n\n::: notes\nThis is the space your results live in – the same chart that the Multiverse page has been drawing your dots onto. The whole menu, run: two and a half thousand models, each one a point, ranked by partial correlation within its family. Blue is the gaussian family – the canonical eight hundred and forty are its unemployment triangles; green is the beta twin of each; squares carry GDP growth as the claim predictor. Everything is claim-aligned, the same convention you applied in your own code: negative framings reverse-coded, growth sign-flipped, so below zero means supports the claim, whichever outcome and whichever predictor. Faded points miss significance. On the canonical half, about two thirds sit below the line and about two thirds are significant; the orange triangle is the baseline we all reproduced. And notice the shape: support reaches minus point seven, while nothing climbs past plus point four – and the strongest wrong-sign results are growth squares, not unemployment triangles. Right. Where did the room land? Did anyone end up above the line? Lose significance? Which choice moved your estimate most?\n:::\n\n## Where your result lands\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/spec-overlay-1.png){width=912}\n:::\n:::\n\n\n::: {.resultline}\nYour orange dot lands here → live on the **Multiverse** page as the room submits\n:::\n\n::: {.src}\n`report_result()` gives you a one-click submission link; results stream onto the [Multiverse]({{< var live-results-url >}}) page.\n:::\n\n::: notes\nSame chart – nothing moved – with the five Multi100 analysts dropped onto the curve where each recorded result falls, me in orange. And one more tag, in red: the original author's own published result, converted to this axis the same way. A person-level t of minus four, read against a third of a million respondents, lands just beside PRL47's near-zero triangle – the degrees-of-freedom lesson from the statistical methods module, drawn as one marker. What I like about this picture: the five published reanalyses are themselves just draws from this same space. Nobody was wrong; we were standing in different places in the garden. Your own dots have been landing on the live Multiverse page since before the break – keep it open next to this chart and find yourself. The conversion that report_result did for you – turning your b and t into the partial correlation, computed exactly the way that Multi100 computed it – is what lets a Stata pooled model, an R fixed-effects model, and your submission all sit on the same axis.\n:::\n\n## Place your bet\n\n::: {.big}\nSix axes: outcome · predictor form · estimator · copredictor · sample · weights\n:::\n\n::: {.none}\n**Which axis moves the estimates most across all 840 specifications?**\n\nType your guess – hold it – send on \"go\".\n:::\n\n::: notes\nBefore I show you the answer, commit to a guess – you have just spent a day making these choices, so you have instincts now. Of the six menu axes, which one moves the estimates most across the whole grid? Estimator is the popular pick – fixed versus random effects is the methods seminar's favourite fight. Copredictors is another – everyone worries about growth. Type your answer, hold it, and send on go. [go; scan the chat.] Interesting spread. Most rooms bet on estimator or copredictors. Let's see.\n:::\n\n## The outcome fork carries half the variance {#the-outcome-fork-carries-half-of-everything}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/fork-importance-1.png){width=864}\n:::\n:::\n\n\n::: {.small}\n- **Outcome operationalisation: 49.7%** of specification variance · estimator + predictor form + copredictor + weights together: **under 2%**\n- Computed on the grid **as estimated** – part of the outcome share *is* the polarity split between positive and negative framings, the split the claim-aligned chart removes from display\n:::\n\n::: {.src}\nComputed over the committed data/spec_grid.csv; imported as data/fork_importance.csv.\n:::\n\n::: notes\nThe outcome fork carries essentially half of all the variation in the grid – forty-nine point seven per cent. And now look at the bottom of the chart: estimator, predictor form, copredictor and weights – the axes we argue about in seminars – together account for under two per cent. The residual block is interactions, combinations that matter beyond any single axis. One caveat, stated plainly: this decomposition is computed on the grid as estimated, before claim-alignment, so part of the share carried by the outcome fork is the polarity split itself – positive framings falling, negative framings rising. That split is real variation in what the specifications estimate; the aligned chart removes it from the display, not from the decomposition. So the day's empirical lesson stands: *what you measure* dwarfs *how you model it*. The fixed-versus-random-effects debate, the to-weight-or-not debate – on this claim, they barely move the estimate. Deciding what 'EU framing' means moves it half the distance all by itself. Whoever guessed \"outcome\" in the chat: take the point.\n:::\n\n## The unit of analysis does the work\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/analyst-placement-1.png){width=864}\n:::\n:::\n\n\n::: {.small}\n- The two **person-level** analysts sit at the two extremes of the recorded range – the unit of analysis and the metric dominate, not the software or the estimator\n:::\n\n::: notes\nNow put the five published analysts inside the same grid – for each one, the share of all eight hundred and forty claim-aligned specifications that come out more negative than their value. And look who sits at the ends. KEVF1, the most strongly claim-supporting of the five at around the sixteenth percentile, and PRL47, the closest to the null at around the sixty-eighth – those two, at the opposite extremes, are the two analysts who worked at *person level*, on the third of a million respondents, rather than on aggregates. The three aggregate pipelines sit between them; my own constrained baseline lands almost exactly at the median of the grid. It is not Stata versus R, and it is not the estimator: it is the unit of analysis and the outcome metric, decided before any model is fitted, that scatter five competent people across half the curve. Which is the fork-importance chart again, this time with names attached.\n:::\n\n## Where the sign flips concentrate {#the-sign-flips-are-patterned-not-random}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](one-day-methods_files/figure-revealjs/sign-flips-1.png){width=960}\n:::\n:::\n\n\n::: {.small}\n- In the cosmopolitan-only universe, the wrong-sign estimates concentrate in the **pooled cluster-robust estimator** and the **bailout-excluding samples**\n:::\n\n::: notes\nOne more way to read the grid: where do the sign flips live? Take only the cosmopolitan-outcome specifications – the claim predicts a negative coefficient, so a positive estimate is a flip – and cross-tab the flips by axis. They are not scattered randomly. The estimator that absorbs no between-country differences at all – the pooled model with clustered errors – hosts thirty-three of the forty-one, and the flips also lean heavily towards the samples that exclude the bailout countries. In other words, when this claim flips sign, it flips for identifiable, diagnosable reasons: remove the between-country comparison, or remove the crisis countries, and the association goes. A specification curve is more than a spread to gawp at. Take it apart and you can name the choices that produce the extremes.\n:::\n\n## Find your own percentile {.smaller}\n\n::: {.small}\n- Open the **'your percentile'** cell in the browser lab – everyone uses it for this one; it runs in any browser tab, no install\n- Enter the result you submitted before the break – it computes the share of the 840 specifications more negative than yours, on the claim-aligned scale\n- The same statistic that placed the five analysts, computed for **you**\n:::\n\n::: {.fragment}\nPaste your percentile in chat – hold – send on \"go\".\n:::\n\n::: notes\nYour turn to be placed. Open the percentile chunk in the browser lab – Workspace people too, this one lives in the lab and it is just a browser tab, no install – and give it your submitted result. It computes for you exactly the statistic I computed for the five analysts: the share of the whole grid that is more negative than your value. Two or three minutes. Then paste your percentile in chat, hold it, send on go. [go] Look at the range in the chat – the room spans a good stretch of the curve, and every one of you can now say precisely where you stand relative to eight hundred and forty defensible alternatives. That sentence – \"my estimate sits at the Nth percentile of the specification space\" – is a genuinely publishable way to report a robustness check. You have just done it.\n:::\n\n## What the curve leaves out {.smaller}\n\n::: {.small}\n- **The specifications nobody ran.** Person-level models, a different scale construction, a lagged predictor. The curve is silent about everything outside the menu, and looks just as complete either way\n- **The dependence.** All 840 use the same 270 country-years, so they share their noise. The width of the cloud is not 840 independent opinions\n- **Estimand drift.** Some of these specifications answer subtly different questions. The chart puts them on one axis; that does not make them commensurable\n- **The data-building choices.** Everything upstream of the panel – how the scales were coded, which waves were pooled – is fixed for everyone here\n:::\n\n::: {.fragment .small}\nA curve is a **map of the menu you wrote**. It cannot tell you the menu was the right one.\n:::\n\n::: notes\nBefore we go on, four things that this picture does not contain, because a chart this satisfying invites you to think it is complete. First, the specifications nobody ran: person-level models, a different scale construction, a lagged predictor. The curve is silent about everything outside the menu, and – this is the treacherous part – it looks exactly as complete either way. Second, the dependence: all eight hundred and forty of these use the same two hundred and seventy country-years, so they share their noise, and the width of that cloud is not eight hundred and forty independent opinions. Third, estimand drift: some of these answer subtly different questions, and putting them on one axis does not make them commensurable. And fourth, everything upstream of the panel – how the scales were coded, which waves were pooled – is fixed for everyone in this room. A curve is a map of the menu you wrote, and it cannot tell you the menu was right.\n:::\n\n## Two jobs, one curve\n\n::: {.none}\n**Description** – map how the estimate moves across every defensible choice. *(What we have been doing all day.)*\n\n::: {.fragment}\n**Inference** – ask whether the curve *as a whole* is surprising if there were no effect at all. *(A different, harder job.)*\n:::\n\n::: {.fragment}\nThe two are detachable, and most published curves stop at description.\n:::\n:::\n\n::: {.src}\n@SteegenEtAl2016IncreasingTransparencyMultiverse; @SimonsohnEtAl2020SpecificationCurveAnalysis\n:::\n\n::: notes\nLast conceptual move of the day, and it is the one that separates careful readers of specification curves from impressed ones. A curve like ours does two different jobs. The first is description: showing how the estimate moves as the choices move – that is what we built, and it is genuinely valuable on its own. The second is inference: asking whether the curve, taken as a whole, is more extreme than you would expect if there were no effect at all. Those are different questions with different machinery, and they detach cleanly – Multi100 did the description without the inference, and so, so far, have we. The next three slides are about what the second job takes.\n:::\n\n## 840 estimates are not 840 tests\n\n:::: {.none}\n::: {.fragment .fadeInUp}\nEvery specification re-uses the **same 270 country-years**. The estimates are deeply dependent.\n:::\n\n::: {.fragment .fadeInUp}\n'63.9% significant' **describes** the curve. It is not a p-value for the claim.\n:::\n\n::: {.fragment .fadeInUp}\nVote-counting across dependent specifications has no null distribution. You cannot tally the stars.\n:::\n::::\n\n::: notes\nThe percentages set a trap. Sixty-three point nine per cent of our specifications are significant. It is very tempting to read that as evidence strength: \"most tests pass, so the claim holds\". But all eight hundred and forty specifications interrogate the same two hundred and seventy country-years. They share the data, so they share the noise: if sampling luck pushed a handful of country-years the claim's way, it pushed hundreds of specifications the same way at once. The percentage significant is a description of the curve, not a test of the claim. To test the claim at curve level you need to know what the whole curve would look like if there were nothing to find, and that null has to be constructed.\n:::\n\n## The permutation design {#building-the-nothing-the-permutation-design}\n\n::: {.small}\n- Break the one link that the claim needs: **shuffle each country's unemployment series in time** (jointly with growth), keeping everything else intact\n- Refit **all 840 specifications** on each shuffled dataset · repeat **B = 500** times\n- Compare the observed curve to the 500 null curves: is ours more extreme than chance produces?\n:::\n\n::: {.src}\nThe design is worked through in your inference reading; permutation inference after @PhipsonSmyth2010PermutationPValues.\n:::\n\n::: notes\nThe null is built like this. The claim says a country's unemployment moves its EU framing over time. So take each country and shuffle its unemployment series in time – together with growth, so the macro side stays internally coherent – while leaving the framing data untouched. In a shuffled world the alignment between unemployment and framing is broken by construction: whatever curve you get is what pure chance produces on these exact data with these exact 840 specifications. Do that five hundred times, refit the entire grid each time, and you have five hundred ghost curves to stand ours against. If our curve sits in the far tail of those ghosts, the curve as a whole is evidence. If it sits comfortably among them – the description stands, but the inference does not.\n:::\n\n## How to read a curve-level test {.smaller}\n\n::: {.small}\n- With B = 500, the smallest reportable p is **2/(B+1) ≈ 0.004** – a floor, not a zero\n- Near p = .05 the Monte-Carlo wobble is about **±0.01**, so treat p = .04 and p = .06 as the same finding\n- [A DESIGN · NOT YET RUN]{.highlight bg-colour=\"#ffe3b3\"} – a curve-level test has to be fixed in advance, and this one has not been run; today we read the design, not a result\n:::\n\n::: {.fragment}\n**Discussion (2 minutes, then chat):** the constrained cosmopolitan-only universe has 140 specs: **70.7% negative, 57.1% negative *and* significant.** Strong evidence? *Against what null?*\n:::\n\n::: notes\nTwo literacy points and then you argue. First: with five hundred draws, the smallest p-value the test can report is two over five hundred and one – about point zero zero four. That is a resolution floor, not a zero; more draws buy sharper floors at real compute cost. Second: near the point-oh-five boundary the Monte-Carlo wobble is around plus or minus point zero one, so a permutation p of point zero four and point zero six are the same finding twice. And the badge matters: this test is designed, not run – you are reading a plan today, which is itself the preregistration lesson again. Now the discussion beat. The constrained universe – cosmopolitan outcome only, 140 specifications – is 70.7 per cent negative, 57.1 per cent negative and significant. Two minutes: is that strong evidence? Against what null? Type your answer. [harvest: the sharp ones will say – we don't know until we know what chance produces on these dependent data; that is exactly the point.]\n:::\n\n## What stands without the test\n\n:::: {.none}\n::: {.fragment .fadeInUp}\nEverything descriptive survives: the **49.7%** outcome fork, the analysts' placement, the sign-flip pattern, **your dot**.\n:::\n\n::: {.fragment .fadeInUp}\nWhat waits for the permutation is one sentence: \"the curve as a whole is unlikely under no effect\".\n:::\n\n::: {.fragment .fadeInUp}\nCareful reporting says which of the two layers a claim lives in.\n:::\n::::\n\n::: notes\nSo that nothing feels deflated: notice how much of today needs no permutation at all. That the outcome fork carries half the variance – description, stands. That the two person-level analysts bracket the range – stands. That the sign flips concentrate in the pooled estimator and the non-bailout samples – stands. Your preregistered dot, the whole structure of the curve – all of it stands. The single sentence that has to wait is \"this curve as a whole is unlikely if there is no effect\". Keeping those two layers apart in your own writing – saying which one your claim belongs to – is what inference literacy means in practice, and it puts you ahead of most published specification curves.\n:::\n\n## The multiverse has its critics {.smaller}\n\n::: {.small}\n- \"Robustness is better assessed with a **few thoughtful models** than with billions of regressions\" [@Auspurg2025RobustnessBetterAssessed; answering @GanslmeierVlandas2025EstimatingExtentSources] – only *justified* models targeting the *same estimand* belong in one curve. Today's grid is a **curated 840**, not billions, and the fork chart does the job that every critic endorses: it locates where the argument must happen\n- \"**There is only one correct analysis**\" once the question is fully specified [@LakensEtAl2026ThereOnlyOne] – your declared specification answers *cherry-picking*, and their deeper point is that declaring in advance does not yet make a choice *justified*, which is what the estimand and DAG work were for\n- \"What's a multiverse **good for** anyway?\" – reflection, persuasion, or inference, and each purpose wants a *differently built* universe [@RohrerEtAl2026WhatsMultiverseGood]. Today's was built for **reflection**, and how much more to read into it is the open debate\n:::\n\n::: {.src}\nThe book-length how-to: @YoungCumberworth2025MultiverseAnalysisComputational; the estimand diagnosis behind Part 2: @AuspurgBruderl2021HasCredibilitySocial.\n:::\n\n::: notes\nOne last literacy layer: the method you practised is under live debate, and you can now read it. Katrin Auspurg – Part 2's estimand diagnosis – answered a 3.6-billion-estimate study with the line at the top of this slide: only thoughtful, justified models belong in a curve. Today mostly agreed with her: our grid is a curated eight hundred and forty, not an enumeration, and the fork chart does the one job that every critic endorses – it tells you where the argument has to happen. Lakens and colleagues say that once the question is fixed, only one analysis implements it correctly. Your preregistration answered cherry-picking; their deeper point – that declaring early does not make a choice justified – is exactly why we built the DAG before declaring. And Rohrer, Hullman and Gelman ask what a multiverse is for: reflection, persuasion, or inference – each wanting a differently built set. Ours was built for reflection. How much more to read into it is the debate you have now joined. [advance]\n:::\n\n## \"There is only one correct analysis\" {.smaller}\n\n::: {.small}\nLakens and colleagues push back hard, and the argument deserves to be taken seriously:\n\n- A research question, **fully specified**, implies a quantity to be estimated\n- That quantity, together with the design and the assumptions you are willing to make, implies **one analysis** that estimates it\n- So a spread of results is not evidence of legitimate diversity. It is evidence that **most of those specifications are wrong** – they estimate something else\n- On this reading, showing a wide curve is closer to an admission than to a robustness check\n:::\n\n::: {.fragment .small}\nTake it back to the red cards. Twenty-nine teams modelled one count of red cards as **linear, logistic or Poisson**. Those are claims about how the outcome was generated, and they cannot all be right – so on this argument the spread is not diversity, it is mostly error.\n:::\n\n::: {.src}\n@LakensEtAl2026ThereOnlyOne\n:::\n\n::: notes\nAnd now the strongest objection to everything I have just taught you, and I want to give it its full force rather than a straw version. Lakens and colleagues argue that a research question, once fully specified, implies a quantity to be estimated. That quantity, together with your design and the assumptions you are prepared to make, implies one analysis that estimates it. Not a family, one. From which it follows that a spread of results is not evidence of legitimate analytical diversity at all. It is evidence that most of those specifications are simply wrong – they estimate something other than what you said you wanted. And on that reading, publishing a wide specification curve is closer to an admission that you never specified your question than to a robustness check. That is an uncomfortable argument and I think it is largely right.\n:::\n\n## Which analysis, and how you would know {#how-would-you-know .smaller}\n\n:::: {.none}\n::: {.fragment}\nGrant the argument. **One correct analysis exists.** Now: which one is it?\n:::\n\n::: {.fragment}\nGetting there needs the estimand *and* the identification assumptions *and* agreement about the measurement – and on this claim, reasonable people disagree about all three.\n:::\n\n::: {.fragment}\nSo the curve is not a rival to the one-correct-analysis view. It is a **map of the remaining disagreement**, drawn because we cannot yet settle it.\n:::\n\n::: {.fragment}\nAnd it points at what to argue about: on this claim, at the **outcome**, not at the estimator.\n:::\n::::\n\n::: notes\nSo let us grant the argument. Suppose one correct analysis does exist. The immediately following question is: which one is it, and how would you know? To get there you need the estimand, and the identification assumptions, and agreement about how the construct is measured – and on this claim reasonable people disagree about all three, as you saw for yourselves this afternoon. So I do not think the curve is a rival to the one-correct-analysis view at all. I think it is a map of the disagreement that remains, drawn precisely because we cannot yet settle it. And read that way it is genuinely useful, because it tells you where the disagreement lives. On this claim it lives at the outcome – what 'EU framing' means – and not at the estimator, which is where the seminar argument would have been.\n:::\n\n## What preregistration settles {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.small}\n**It does settle**\n\n- That your specification was not chosen *because of* the result\n- That your rule for what counts as support was written before you had one\n- That a reader can see what you intended, and what you changed\n:::\n:::\n::: {.column width=\"50%\"}\n::: {.small}\n**It does not settle**\n\n- Whether the specification was **any good**\n- Whether it estimates the quantity that your question implies\n- Whether the assumptions behind it hold\n\nA badly-reasoned analysis declared in advance is still badly reasoned – now with a timestamp\n:::\n:::\n::::\n\n::: {.fragment .small}\nWhich is why the estimand and the DAG came **first** today. Preregistration protects a choice; it is the causal reasoning that makes the choice worth protecting.\n:::\n\n::: notes\nSo where does preregistration fit? It settles a specific and limited set of things, and the two columns matter equally. On the left: it settles that your specification was not chosen because of the result it gave, that your rule for what counts as support was written before you had a result to bend it around, and that a reader can see both what you intended and what you subsequently changed. Those are real guarantees and no other mechanism provides them. On the right, what it emphatically does not settle: whether the specification was any good, whether it estimates the quantity that your question implies, or whether its assumptions hold. A badly reasoned analysis declared in advance is still badly reasoned – it just has a timestamp on it now. Which is exactly why we did the estimand and the graph first this morning. Preregistration protects a choice. Causal reasoning is what makes the choice worth protecting.\n:::\n## You are Analyst no. 6 – for real this time {.smaller}\n\n::: {.big}\n- Aim 2: assess the **robustness** of the constrained result\n:::\n\n::: {.small}\n  - **Before the break** you explored: several specifications, tried in order to find out what they do. That was the right way to learn them\n\n  - **Now** you commit: **one** specification, declared in writing *before* it runs, with a reason that your DAG can carry\n\n  - **The difference is not the code.** It is that one of these can be chosen because of its result and the other cannot\n:::\n\n::: notes\nThis afternoon you reproduced my constrained result, and then you explored – several specifications, tried in whatever order took your interest, in order to find out what they do. That was exactly the right way to learn them, and I want to be clear that there was nothing improper about it. Now comes the other half. You commit to one specification, declared in writing before it runs, with a reason that your causal graph can carry. And notice what the difference between the two activities is, because it is not the code – the code is identical. The difference is that one of them can be chosen because of the result it gave, and the other one cannot. That is the whole distinction, and almost no published paper tells you which of the two it is reporting.\n:::\n\n## THE PREREGISTRATION MOMENT\n\n::: {.none}\n1. Open the preregistration block in your report\n2. Complete fields 1–5 – claim · data-in-hand · your one specification · DAG sentence · support/undermine rule\n3. **Render**, or on the browser lab page save the completed block into your script\n4. Type **\"declared\"** in chat – then wait for the room\n:::\n\n::: {.fragment}\nNobody runs a model until the room is declared.\n:::\n\n::: notes\nThis is the moment that the day is named after, and we do it synchronously, because a thing that the whole room does at once sticks in a way that an instruction does not. Open Task 5. Fill in the five fields: the claim, the data-in-hand statement, your one specification across the eight axes, the one-sentence justification that your graph gives you, and the rule – written now, before any result – for what would support the claim and what would undermine it. Render the report; the rendered file with its timestamp is your record, exactly like the frozen snapshot of a real registration. On the browser lab page, save the completed block into your script. Then type \"declared\" in chat, and wait. [count them in aloud: \"eight declared… twelve…\"] Nobody runs anything until the room is in. And if you now want to declare the same specification you already explored before the break – that is allowed, and you should say so in the block. Declaring something you have already seen is not preregistration, and being able to tell the difference is the point.\n:::\n\n## Run it – then watch the chart {.smaller}\n\n::: {.small}\n- **Task 5** – run your declared specification, and only that one\n- `report_result()` prints a one-click link with your numbers already in it – click, submit\n- Your dot joins the **Multiverse** page as a *declared* result, beside the exploratory ones from before the break\n:::\n\n::: {.fragment .small}\nWatch what the two waves look like together. If the declared cloud sits systematically to one side of the exploratory cloud, that is worth a conversation.\n:::\n\n::: {.fragment .small}\nStuck? Chat \"STUCK\" · reload and rerun · second browser · follow my screen · last resort: the grid lookup on the menu page gives you your numbers by hand\n:::\n\n::: notes\nGo. Run the specification you declared, just that one, and when the numbers are in front of you call report underscore result: it prints a link with your values already filled in, one click and you have submitted. Your dot joins the chart as a declared result, and it lands beside the exploratory dots that the room put up before the break. Watch the two waves together, because there is something worth seeing. If the declared cloud sits systematically to one side of the exploratory cloud, that tells you something about what people chose to commit to once they had seen the alternatives, and it is worth a conversation. If anything misbehaves: type STUCK in chat and work down the ladder on the cheatsheet. And if your machine is truly finished for the day, the menu page shows you how to read the numbers for your specification straight off the published grid. Everybody lands a dot, no exceptions.\n:::\n\n## Two sentences worth keeping\n\n::: {.claimcard}\n\"the common single-path analyses in social and behavioural research should not be simply assumed to be robust to alternative analyses\" [@AczelEtAl2026InvestigatingAnalyticalRobustness]\n:::\n\n::: {.claimcard}\nA blueprint: precise question → causal reasoning (DAG) → multiverse → sensitivity analysis [@AuspurgBruderl2021HasCredibilitySocial]\n:::\n\n::: {.small}\n- Same-conclusion robustness and same-*number* robustness are different bars\n- Justifiability is the criterion – choose with reasons, show the spread\n:::\n\n::: notes\nTwo sentences to take away. From the Multi100 paper: single-path analyses should not simply be assumed robust. And notice what preregistration did and did not do for you today – it protected your choice from being opportunistic, but it gave your declared dot no special status inside the curve. You lived both halves: the declaration made your one path defensible, and the grid showed it was still just one path among 840. Declare your path, then show the space it sits in – the two moves go together. From Auspurg and Brüderl, the constructive recipe we followed: precise question, explicit assumptions, multiverse, sensitivity. And keep the two robustness standards apart in your own writing: same *conclusion* – seventy-four per cent in Multi100 – and same *number* – thirty-four. When you claim robustness, say which one you mean.\n:::\n\n## A single analytical path is a choice\n\n:::: {.none .fs-120}\n::: {.fragment .fadeInUp}\nThere is no privileged single analytical path – only justifiable ones, explored openly.\n:::\n\n::: {.fragment .fadeInUp}\nYou made one justifiable choice today – transparently, with a reason, inside a multiverse.\n:::\n\n::: {.fragment .fadeInUp}\nAnd that was the workshop.\n:::\n::::\n\n::: fragment\n::: {.urlbox}\ncodemoreh.github.io/applied-replication\n:::\n::: {.none}\nFork anything. Everything is open.\n:::\n:::\n\n::: notes\nIf the day had one sentence, it is this one. There is no privileged single analytical path – only justifiable ones, explored openly. And notice that you have already done the right thing once: you made one defensible choice, you wrote down your reason before running it, and you placed your answer inside the space of alternatives rather than pretending it was the only one. That is the transferable habit. Everything else today – the tooling, the estimand, the graph, the curve – was in its service.\n:::\n\n## What you take with you {.smaller}\n\n::: {.small}\n- **Yours now**: a preregistered, rendered report · an estimand and a causal graph you wrote yourself · two dots on the class curve, one explored and one declared\n- **Read**: the three *Nature* 2026 papers [@MiskeEtAl2026InvestigatingReproducibilitySocial; @AczelEtAl2026InvestigatingAnalyticalRobustness; @TynerEtAl2026InvestigatingReplicabilitySocial] · the glossary [@NosekEtAl2025BriefGlossaryTerms] · @AuspurgBruderl2021HasCredibilitySocial · @LundbergEtAl2021WhatYourEstimand · @LakensEtAl2026ThereOnlyOne · @Teney2016DoesEUEconomic\n- **Explore**: the ten companion modules (intro to R · Quarto documents · the statistics behind today · causal graphs · the multiverse debate · simulation · one claim at two levels · repositories & preregistration · git & GitHub) · the Multi100 data · `fixest` & `ggdag` docs\n- **Keep going locally**: the research-software and open-research teams at your university · a ReproducibiliTea journal club near you\n- Everything is on the course site, and everything is open – fork any of it\n:::\n\n::: notes\nHere is what goes home with you. A rendered report with a preregistration block in it, an estimand and a causal graph that you wrote for a real published claim, and a dot on the class curve. The website on screen holds everything else – the readings, the data, the companion modules, the specification-curve reading, and the full SCORE dossier on the paper if you want to dig further. Two pointers for keeping the habit alive wherever you work: most universities have a research-software engineering team and an open-research or library data service that run training exactly like today's, and ReproducibiliTea journal clubs meet in dozens of cities – if there is not one near you, they will help you start it.\n:::\n\n## References {.scrollable .smaller visibility=\"uncounted\"}\n\n::: {#refs}\n:::\n\n\n## Thank you – and your feedback\n\n::: {.pollbox}\nFeedback form<br>\n<span style=\"font-size:0.7em\">(link in the chat · two minutes, while the chart is still on screen)</span>\n:::\n\n::: notes\nThat is the day. Before you go: the feedback form link is in the chat – two minutes, and it genuinely shapes the next delivery of this workshop. I will leave the class multiverse on screen while you fill it in; find your dot one last time. Thank you for the work you put in today – you reproduced a published result to the third decimal, wrote an estimand and a causal graph for a real published claim, explored a specification space and then committed to one path in writing before you ran it, and read a specification curve like a reviewer rather than like an audience. That is a genuinely full day's work.\n:::\n\n",
    "supporting": [
      "one-day-methods_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}