{
  "hash": "6bcb01b83b8a60ea871fa0a36ddbdd9b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simulation as a method\"\nsubtitle: \"Fake data, planted coefficients, and what they teach about real analyses\"\nbibliography: [../references.bib, ../references-new.bib]\n---\n\n\n\nThis is the simulation module of the [companion curriculum](index.qmd), and it is optional. Every other quantitative page on this site analyses data that came from the world. This module works the other way round. It analyses data that came from a recipe we wrote ourselves, so that for once the answer is known before any model runs. That inversion – fake-data simulation – is one of the core habits of modern applied statistics. *Regression and Other Stories* uses it constantly, on the argument that fitting models to data whose coefficients you planted yourself is how you learn what your models can and cannot recover [@GelmanEtAl2020RegressionOtherStories]; the same habit anchors classroom practice [@GelmanVehtari2024ActiveStatisticsStories] and the workflow literature, where experimentation on simulated data is a named pillar of serious model-building [@GelmanEtAl2026BayesianWorkflow].\n\nThe module teaches from a dataset built for the purpose. `EUframes_person_sim.csv` is a simulated person-level companion to the EU-frames case – 41,660 synthetic respondents across the real 270 country-year cells, with the real macro variables attached. It carries the original analysis rather than a cut-down version of it: all four framing dimensions and both composites, each with its own response to unemployment and to growth, plus the individual controls the original author (OA) used. Its [codebook](../data/EUframes_person_sim_codebook.md) states the construction in full, and two facts about it govern everything below.\n\nFirst, **no Eurobarometer respondent appears in it**. The raw microdata behind the case are GESIS-licensed and cannot be redistributed in any form, including as samples or extracts – [the repositories module](repositories.qmd#sec-gesis) explains that regime – so a person-level dataset this site can legitimately ship has to be synthetic. What the licensed file supplied, read once and locally, is a set of summaries: the demographic marginals, how a respondent's own age, sex and education move their framing, and how much individuals differ within a country-year. Those are aggregate statistics of the kind published appendices carry, and they are committed as `_model-outputs/sim_calibration*.csv`.\n\nSecond – and this is the pedagogical point rather than a limitation – **the recipe is known**. A data-generating process is the explicit rule by which every value was produced. Real data never comes with its rule attached; simulated data is nothing but the rule, which is what makes it a laboratory.\n\n## 1. The recipe, stated in full {#sec-dgp}\n\nThe generator is `_model-outputs/simulate_person_twin.R`, a committed script worth reading – it is the data-generating process made executable. Its central move is to simulate the *instrument* rather than the four scores. In the real survey a respondent hears a list of thirteen things the EU might mean and names those that apply. Their dimension scores are the shares of their mentions falling to each dimension. The simulation does the same: decide whether the respondent mentions anything, then divide their mentions.\n\nThe expected composition for person $i$ in country $c$ and year $t$ has two layers. The cell layer comes from the public panel, fitted under the anchor specification with GDP growth added as a co-predictor, one step along the day's co-predictor fork:\n\n$$\na_j + b_j\\,\\text{unemp}_{ct} + c_j\\,\\text{growth}_{ct} + \\text{year}_{jt} + u_{jc} + u_{jct},\n$$\n\nand to it are added the shifts a respondent's own age, sex and education produce, calibrated from the real respondents and centred on the population marginals.\n\nLook at what the subscript $j$ is doing there. **Every dimension has its own coefficients.** Nothing is derived from a privileged dimension with the others absorbing the remainder – which would impose the false claim that utilitarian, communitarian and libertarian framings have no independent relationship with the economy. The four shares still sum to one, but that comes free: because they sum to one in the data, coefficients estimated the same way on all four sum to zero automatically. Nothing has to be held passive for the constraint to hold.\n\nTwo further construction details are worth knowing. Mentioning anything at all is modelled on the logit scale, because the linear alternative does not fit under the ceiling. About 94 per cent of respondents mention something, and the calibrated education contrast is worth about 6.4 percentage points at that rate, which carries graduates past a probability of one in 61 per cent of the 270 cells. That share is what the public panel shows; computed on the licensed respondent file, where the contrast is not flattened into a single average rate, it is higher still. Read from the other end, the same arithmetic drives the 6 per cent probability of mentioning nothing below zero – the classic linear-probability failure, met here in a setting where you can watch it.\n\nThe country and cell deviations are drawn fresh, then residualised against the full design including year, because growth is dominated by common shocks: 2009 collapsed everywhere at once, so a draw made orthogonal to raw growth can still correlate with it once year is absorbed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim |>\n  slice_sample(n = 6) |>\n  select(cntry, year, w1, age, female, edu4, cosmo, util, comm, lib, unemp) |>\n  arrange(cntry, year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 11\n  cntry  year    w1   age female edu4     cosmo  util  comm   lib unemp\n  <chr> <dbl> <dbl> <dbl>  <dbl> <fct>    <dbl> <dbl> <dbl> <dbl> <dbl>\n1 DE     2012 0.952    45      1 e16_19   0     0     1         0  5.38\n2 DK     2006 0.793    33      1 le15     1     0     0         0  3.90\n3 HU     2005 1.27     62      0 studying 1     0     0         0  7.19\n4 MT     2005 0.953    44      1 le15     0.333 0.333 0.333     0  6.92\n5 MT     2010 0.863    34      0 e16_19   0     0.5   0.5       0  6.85\n6 NL     2008 0.713    24      1 e20plus  1     0     0         0  3.65\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The share columns are stored rounded to six decimals, so four of them can\n# drift from their sum: the identities need a tolerance, not ==.\nidentities <- sim |>\n  filter(cosmo + util + comm + lib > 0) |>\n  summarise(\n    `dimensions sum to 1` = all(abs(cosmo + util + comm + lib - 1) < 5e-6),\n    `pos + neg = 1`       = all(abs(pos + neg - 1) < 5e-6),\n    `share exactly 0`     = mean(cosmo == 0),\n    `share exactly 1`     = mean(cosmo == 1))\nidentities\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  `dimensions sum to 1` `pos + neg = 1` `share exactly 0` `share exactly 1`\n  <lgl>                 <lgl>                       <dbl>             <dbl>\n1 TRUE                  TRUE                        0.172             0.248\n```\n\n\n:::\n:::\n\n\nAmong respondents who mention anything, 17% score exactly zero on cosmopolitan framing and 25% score exactly one – the latter because someone who mentions one item and finds it cosmopolitan, or two and finds both, scores 1 by construction. This is faithful to the real instrument, and it is the concrete reason beta regression, which needs the outcome strictly inside the unit interval, cannot be used at person level while it can be used on country-year means. The [statistical methods module](stats-methods.qmd#sec-glm) states that constraint; here you can verify it.\n\n## 2. Simulate, fit, recover {#sec-recover}\n\nThe first thing to do with data whose recipe you know is to ask a model to find what the recipe planted. Each dimension's planted coefficient is the one the **real panel** yields under the same specification, so a model fitted to the twin should land where the same model fitted to the real data lands.\n\nEach macro slope plants exactly one number, and `sim_planted.csv` records it. That is a design decision worth stating, because it was not always so. An earlier version of the twin gave respondents an authored `unemployed` indicator and set its prevalence to a fixed multiple of the country's unemployment rate, which opened a second route from the macro rate to the cell mean and split every planted unemployment coefficient into two – one for a model that held the indicator fixed, one for a model that did not. The indicator is gone. A national unemployment rate is a property of a labour market and being out of work is a property of a person; wiring the second to the first smuggles in a mechanism the case never claimed, and no such variable was ever calibrated from the real respondents. [Section 4](#sec-composition) works through what that decision costs and what it buys.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_cells <- sim |>\n  summarise(across(c(all_of(DIMS), pos, neg), mean),\n            unemp = first(unemp), growth = first(growth),\n            .by = c(cntry, year))\n\nmap(planted$outcome, \\(v) {\n  cf <- coef(lm(anchor(v), data = sim_cells))\n  tibble(outcome = v, sim_unemp = cf[[\"unemp\"]], sim_growth = cf[[\"growth\"]])\n}) |>\n  list_rbind() |>\n  left_join(planted, by = \"outcome\") |>\n  select(outcome, planted_unemp, sim_unemp, planted_growth, sim_growth) |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  outcome planted_unemp sim_unemp planted_growth sim_growth\n  <chr>           <dbl>     <dbl>          <dbl>      <dbl>\n1 cosmo       -0.00356  -0.00316     -0.000242    0.000238 \n2 util        -0.000678 -0.000417     0.00191     0.00211  \n3 comm         0.00524   0.00513     -0.00163    -0.00192  \n4 lib          0.000105 -0.000235     0.00000514 -0.0000258\n5 pos         -0.00424  -0.00358      0.00167     0.00235  \n6 neg          0.00534   0.00489     -0.00162    -0.00195  \n```\n\n\n:::\n:::\n\n\nRead the substance first, before the arithmetic. Rising unemployment pushes framing away from **both** cosmopolitan and utilitarian terms and towards communitarian ones, while libertarian framing barely moves. Growth works differently again, lifting utilitarian framing most of all – which makes sense, since the utilitarian dimension is built from the economic-prosperity and social-protection items. That pattern is not an artefact of the simulation. It is what the real panel says, carried into the twin so that a participant analysing simulated respondents meets the same structure a participant analysing the real ones would.\n\nNow the arithmetic. The simulated coefficients sit near the planted values but not on them, and the reason is worth dwelling on: each of the twin's cell means is an average over a tenth of the real respondents, so it is noisier than the panel's own. A cell-level slope here carries a standard error near a third of the anchor's size. That is a property of the design, not a defect, and it is the sort of thing single-dataset analysis can never show you. Repeated draws can.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sweep, aes(sim_unemp, outcome)) +\n  geom_point(alpha = 0.45, colour = \"#00205b\", size = 1.6) +\n  geom_point(data = planted, aes(planted_unemp, outcome),\n             colour = \"#c8102e\", shape = 124, size = 8) +\n  labs(x = \"estimated unemployment slope\", y = NULL) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Twenty independent draws from the same recipe, each refitted with the anchor specification. Red marks show the planted coefficient.](simulation_files/figure-html/fig-sweep-1.png){#fig-sweep width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Both slopes for all six outcomes: twelve quantities, each read against its\n# own planted value.\nplanted_long <- planted |>\n  select(outcome, sim_unemp = planted_unemp, sim_growth = planted_growth) |>\n  pivot_longer(-outcome, names_to = \"slope\", values_to = \"planted\")\n\nsweep_summary <- sweep |>\n  pivot_longer(c(sim_unemp, sim_growth), names_to = \"slope\",\n               values_to = \"estimate\") |>\n  summarise(draws = n(), mean_estimate = mean(estimate),\n            sd_estimate = sd(estimate), .by = c(outcome, slope)) |>\n  left_join(planted_long, by = c(\"outcome\", \"slope\")) |>\n  mutate(gap_in_ses = (mean_estimate - planted) / (sd_estimate / sqrt(draws)))\n\n# A single draw's nominal standard error, for comparison with the spread of\n# the twenty.\nSE_ONE   <- sqrt(diag(vcov(lm(anchor(\"cosmo\"), data = sim_cells))))[[\"unemp\"]]\nSD_SWEEP <- sd(sweep$sim_unemp[sweep$outcome == \"cosmo\"])\n\nsweep_summary |>\n  arrange(slope, outcome) |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 7\n   outcome slope      draws mean_estimate sd_estimate     planted gap_in_ses\n   <chr>   <chr>      <dbl>         <dbl>       <dbl>       <dbl>      <dbl>\n 1 comm    sim_growth    20    -0.00165      0.000773 -0.00163       -0.0946\n 2 cosmo   sim_growth    20     0.0000839    0.000799 -0.000242       1.83  \n 3 lib     sim_growth    20    -0.000216     0.000572  0.00000514    -1.73  \n 4 neg     sim_growth    20    -0.00186      0.000842 -0.00162       -1.26  \n 5 pos     sim_growth    20     0.00195      0.000829  0.00167        1.51  \n 6 util    sim_growth    20     0.00187      0.00044   0.00191       -0.462 \n 7 comm    sim_unemp     20     0.00528      0.000844  0.00524        0.233 \n 8 cosmo   sim_unemp     20    -0.00349      0.000939 -0.00356        0.327 \n 9 lib     sim_unemp     20     0.000102     0.000625  0.000105      -0.0163\n10 neg     sim_unemp     20     0.00538      0.000895  0.00534        0.209 \n11 pos     sim_unemp     20    -0.00419      0.000883 -0.00424        0.251 \n12 util    sim_unemp     20    -0.000698     0.000557 -0.000678      -0.153 \n```\n\n\n:::\n:::\n\n\nAcross draws the estimates centre on the planted values. The last column is the test: it expresses each remaining gap as a multiple of the standard error of the twenty-draw mean. All 12 fall inside two standard errors, and the largest is 1.8. Twenty draws are not enough to rule out a bias smaller than the noise – nothing here shows the recipe is exactly unbiased, only that it is unbiased to the precision twenty draws can see – but there is no residual to explain, which is the state a generator should be in.\n\nGetting there took a design change worth recording, because it is the kind of mistake fake data is uniquely good at exposing. The earlier `unemployed` indicator put a systematic offset into every unemployment slope, and the sweep found it: the largest deviation then ran to 2.8 standard errors, which is more than twenty draws should produce by chance. The tempting response is to record the offset as a second estimand and let readers pick a column. The better response, and the one taken here, is to notice that the offset came from an authored mechanism nobody had asked for and remove the mechanism. A simulation study is a laboratory for the recipe as much as for the models fitted to it.\n\nTwo things about the sweep are worth noticing before leaving it. The spread of the twenty estimates is narrower than the standard error any one of them reports – 0.00094 against 0.00120 on the cosmopolitan dimension – because the generator residualises every country and cell deviation against the full design, so those components contribute nothing to the fitted slope while still inflating the residual variance an ordinary standard error is built from. And any *one* draw can still sit a good distance off. The committed file is one such draw, and it was kept rather than reseeded: rerolling until the estimate looked good would be the simulation-study version of the very practice this workshop is about, and that temptation has a literature of its own [@PawelEtAl2024PitfallsPotentialsSimulation].\n\n::: {.callout-tip}\n## Try it\n\nOpen the generator and change `SIM_FRACTION` from `0.10` to `0.40`. That is the only lever on how many respondents each cell gets, and it is the cleanest one-parameter experiment in the file: nothing about the recipe's coefficients changes, only how precisely a cell mean can be measured.\n\nDo not judge the result on one rerun. A single draw shows you one estimate, and one estimate cannot tell you whether the spread has narrowed. Sweep instead: ten seeds at `0.10` and ten at `0.40`, with `$SIM_SEED` naming the draw and `$SIM_SWEEP` collecting the estimates into two separate files. Then compare the standard deviation of each set of ten. Quadrupling the cell sizes should roughly halve it, which is the square-root law meeting you as an experimental result rather than a formula. That is a designed simulation study in miniature – one parameter moved, everything else held – and it is exactly how a power analysis is built.\n\nTwo practical warnings. Point `$SIM_OUT` at a scratch directory unless you mean to overwrite the committed twin, and note that at `0.40` the file is four times the size. The generator also writes `companion/_model-outputs/sim_planted.csv` to that hard-coded path on every run whatever `$SIM_OUT` says – its contents do not depend on the seed or on `SIM_FRACTION`, so an experiment run in place leaves it unchanged in substance, but check `git status` before committing.\n:::\n\n## 3. Six outcomes, one instrument {#sec-outcomes}\n\nOn the grid as estimated, the choice of outcome – which framing scale you treat as 'EU framing' – moves results more than any other analytical decision. The twin lets you see part of why, because the dimensions are shares of one instrument and cannot move independently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplanted |>\n  select(outcome, unemp = planted_unemp, growth = planted_growth) |>\n  mutate(ratio_to_cosmo = unemp / unemp[outcome == \"cosmo\"],\n         across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  outcome     unemp      growth ratio_to_cosmo\n  <chr>       <dbl>       <dbl>          <dbl>\n1 cosmo   -0.00356  -0.000242           1     \n2 util    -0.000678  0.00191            0.191 \n3 comm     0.00524  -0.00163           -1.47  \n4 lib      0.000105  0.00000514        -0.0293\n5 pos     -0.00424   0.00167            1.19  \n6 neg      0.00534  -0.00162           -1.5   \n```\n\n\n:::\n:::\n\n\nTwo things sit in that table. On unemployment the signs fall exactly along the line the day's claim-alignment convention describes, both positive framings declining as unemployment rises and both negative ones gaining. Growth is what breaks the convention. There the cosmopolitan dimension moves with the communitarian one and utilitarian framing with the libertarian, so the split runs between whichever dimension is gaining and whichever are giving way, and which is which depends on the predictor. Libertarian framing is the weak case in that reading, since its growth coefficient is under one per cent of the communitarian one in size and what the two share is a sign rather than a magnitude. What claim alignment actually rests on is narrower and does hold exactly here: `pos` and `neg` partition the mentions, so `neg` = 1 − `pos` for every mentioner and reverse-coding the negative composite is exact arithmetic.\n\nThe magnitudes also span a wide range, so an analyst choosing `util` and one choosing `comm` are estimating genuinely different quantities from one instrument. That is the panel's own structure rather than a simulation artefact, and it is a substantial part of why the outcome fork carries so much specification variance. [The multiverse module](multiverse.qmd#sec-auspurg) takes that argument further, because it is precisely where Auspurg's measurement-nonequivalence objection bites.\n\n## 4. Composition or context? {#sec-composition}\n\nA country-year's unemployment rate could move EU framing in two different ways. It might be that unemployed *people* frame the EU differently, so a high-unemployment cell simply contains more of them and its mean shifts with the mix – a **compositional** effect. Or it might be that living through high unemployment changes how everyone in the country frames the EU, whatever their own situation – a **contextual** effect. The distinction matters because the two carry different implications and often different policies, and it is one of the oldest problems in multilevel analysis.\n\nThe country-year panel cannot separate them at all, because it contains no individuals: 270 means, and no way to ask who is inside each one. That is the limitation a person-level dataset is supposed to lift. So it is worth being exact about what this twin can and cannot do here, because the answer is instructive.\n\n**This twin plants context only.** Its respondents' characteristics are drawn from fixed population marginals, so a high-unemployment cell contains the same mix of ages, sexes and education levels as a low-unemployment one. There is no compositional path to find, and a model that goes looking for one will correctly find nothing.\n\nThat was a deliberate choice, and an earlier version of the twin chose otherwise. It gave every respondent an authored `unemployed` indicator whose prevalence was set to a fixed multiple of their country's unemployment rate, precisely so that this section would have a compositional path to display. Two things were wrong with it. The first is that no such variable was ever calibrated: the licensed file supplied age, sex and education effects, and nothing about employment status, so the indicator's prevalence and its effect were both invented. The second is deeper. A country's unemployment rate and a person's employment status are different constructs measured at different levels, and the case's claim is about the first. Tying the second to the first by a made-up constant does not model a compositional path so much as assert one, and it then leaks into every macro coefficient the twin plants – which is exactly what the recovery sweep in [section 2](#sec-recover) detected.\n\nWhat survives, and is worth more than the exhibit that was removed, is the arithmetic. Suppose being unemployed did lower a person's cosmopolitan score by 0.04 – about ten times the cell-level coefficient per unit, so a large individual effect by the standards of this instrument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What a compositional path would be worth, given an individual effect and a\n# prevalence gradient. Neither number is in the twin; both are the kind of\n# figure a reader can look up for a real dataset, which is the point.\nb_individual <- -0.04    # effect on a person's own cosmopolitan share\nd_prevalence <- 0.006    # extra unemployed respondents per point of unemployment\n\ntibble(\n  quantity = c(\"individual effect of being unemployed\",\n               \"extra unemployed share per point of unemployment\",\n               \"implied compositional contribution to the cell slope\",\n               \"planted cell slope, cosmopolitan (all of it contextual)\",\n               \"compositional share of the total\"),\n  value = c(b_individual, d_prevalence, b_individual * d_prevalence, B_COSMO,\n            b_individual * d_prevalence / (B_COSMO + b_individual * d_prevalence))\n) |>\n  mutate(value = signif(value, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  quantity                                                   value\n  <chr>                                                      <dbl>\n1 individual effect of being unemployed                   -0.04   \n2 extra unemployed share per point of unemployment         0.006  \n3 implied compositional contribution to the cell slope    -0.00024\n4 planted cell slope, cosmopolitan (all of it contextual) -0.00356\n5 compositional share of the total                         0.0631 \n```\n\n\n:::\n:::\n\n\nA one-point rise in a country's unemployment rate adds well under one percentage point to the share of respondents who are themselves unemployed. Multiply a large individual effect by that small a gradient and the compositional contribution comes to a few per cent of the cell-level slope. Context dominates composition not because anyone decided it should, but because of the arithmetic: an individual-level mechanism has to move a *lot* of people to shift an aggregate mean. That is the calculation a reader needs whenever a paper explains an aggregate association with 'it must be the people', and it is usually not done.\n\nDoing it properly on real data means measuring the prevalence gradient rather than assuming it, and it is a good use of a licensed microdata file. What a simulated twin is for is checking that your estimator recovers the answer once you have it – not supplying the answer.\n\n## 5. The demographics are not decoration {#sec-individual}\n\nAge, sex and education carry into the twin the effects they have in the real respondents, which is what lets it support OA's own model rather than a simplified one. Education is the largest effect in the file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The calibrated coefficients are effects on the composition among people who\n# mention something, so the fit has to be restricted to them. Run on all rows\n# the education contrast comes back about a quarter larger, because education\n# drives whether a respondent mentions anything as well.\nm_ind <- lm(cosmo ~ age10 + female + edu4 + factor(cntry) + factor(year),\n            data = filter(sim, cosmo + util + comm + lib > 0))\nind <- parameters::model_parameters(m_ind, keep = \"^(age10|female|edu4)\")\n\nrecovery <- pcoef |>\n  filter(outcome == \"cosmo\") |>\n  select(term, calibrated = value) |>\n  left_join(ind |> as_tibble() |> select(term = Parameter, recovered = Coefficient,\n                                         se = SE),\n            by = \"term\") |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 4)))\n\n# Three significant figures round the smaller contrasts to a point where a\n# fraction-of-a-standard-error agreement reads as a mismatch.\nold_sigfig <- options(pillar.sigfig = 4)\nprint(recovery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  term         calibrated recovered       se\n  <chr>             <dbl>     <dbl>    <dbl>\n1 age10         -0.009211 -0.007669 0.001083\n2 female         0.009179  0.003691 0.003472\n3 edu4e16_19     0.04992   0.03894  0.004687\n4 edu4e20plus    0.1236    0.1123   0.005022\n5 edu4studying   0.1619    0.141    0.007207\n```\n\n\n:::\n\n```{.r .cell-code}\noptions(old_sigfig)\n```\n:::\n\n\nGraduates sit about 0.12 higher on cosmopolitan framing than those who left school by 15, and the twin returns that. Notice how much more precisely these individual-level coefficients are recovered than the macro ones two sections ago: there are forty thousand respondents carrying information about education and only 270 cells carrying information about unemployment. The same dataset is richly informative about one question and thin on the other, which is the design lesson [section 9](#sec-design) makes explicit.\n\n::: {.callout-tip}\n## Try it\n\nBuild your own placebo. Take any *person-level* variable in the file, shuffle it within country-year, and refit the model above with the shuffled version in place of the real one. Its coefficient should land near zero with an interval covering it, and if you repeat that twenty times about one run in twenty will not, which is the five-per-cent rule doing exactly what it advertises. Meeting a false positive somewhere you are certain there is nothing to find is worth more than reading about one.\n\nThe italics on *person-level* are doing real work. `unemp`, `growth` and `bailout` hold one value for a whole country-year, so shuffling them inside a cell puts every value back where it was and hands you the real coefficient with the real *p*-value, looking for all the world like a placebo that failed. That is not a quirk of the shuffle: a variable that does not vary within the unit you are permuting cannot be permuted there at all, which is the same aliasing that makes a null impossible to build at the level a macro predictor lives at.\n:::\n\n## 6. The degrees-of-freedom story, run live {#sec-df}\n\nThe statistical methods module tells a story it can only display, because it rests on the licensed file: a naive analysis that ignores clustering reports an enormous *t* on hundreds of thousands of degrees of freedom, while the multilevel model reports a modest one on a couple of hundred – because the predictor varies only at the country-year level. On the twin you can run the contrast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3     <- lmer(cosmo ~ unemp + (1 | cntry) + (1 | cntry:year), data = sim)\nnaive  <- lm(cosmo ~ unemp, data = sim)\nm3_par <- parameters::model_parameters(m3, ci_method = \"satterthwaite\")\n\ndf_tbl <- tibble(\n  model = c(\"naive OLS, clustering ignored\", \"three-level random intercepts\"),\n  estimate = c(coef(naive)[[\"unemp\"]], fixef(m3)[[\"unemp\"]]),\n  se = c(sqrt(diag(vcov(naive)))[[\"unemp\"]],\n         m3_par$SE[m3_par$Parameter == \"unemp\"]),\n  t = estimate / se,\n  df = c(df.residual(naive), m3_par$df_error[m3_par$Parameter == \"unemp\"]))\n\n# The two rows differ in the estimate as well as in the standard error, so it is\n# worth having the within-country slope to hand: it is the one the multilevel\n# fit leans towards, while the naive fit blends it with the between-country one.\ncells_w <- sim_cells |>\n  left_join(count(sim, cntry, year), by = c(\"cntry\", \"year\"))\nB_WITHIN <- coef(lm(cosmo ~ unemp + factor(cntry), data = cells_w,\n                    weights = n))[[\"unemp\"]]\n\ndf_tbl |> mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  model                         estimate      se      t    df\n  <chr>                            <dbl>   <dbl>  <dbl> <dbl>\n1 naive OLS, clustering ignored -0.00461 0.00044 -10.5  41700\n2 three-level random intercepts -0.00538 0.00092  -5.84   247\n```\n\n\n:::\n:::\n\n\nThe naive row claims forty thousand independent witnesses; the multilevel row counts the few hundred effective ones, because respondents inside a country-year share one unemployment value and largely echo their cell. Person-level sample sizes advertise precision the design does not possess whenever the predictor lives at a higher level. The model that respects the structure pays for that respect in degrees of freedom, and here in the estimate too: the naive fit is a different weighted average of between-country and within-country variation, landing at -0.00461 against the multilevel -0.00538, which sits near the within-country slope of -0.00544. Neither of the two is the planted coefficient, because both leave out the year effects the anchor carries. This is also why, in Block 1 of the workshop, two Multi100 analysts fitting person-level models to the same claim could reach such different strengths of evidence.\n\n## 7. Weights that matter {#sec-weights}\n\nSurvey weights are usually taught as a procedure. The interesting question is when they change anything, and simulated data can answer it because the distortion the weight corrects can be built in deliberately. The sample here was drawn with a fieldwork distortion – younger respondents over-selected – and `w1` is the exact reciprocal of that selection factor, normalised to mean 1 within each country-year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cell sizes are drawn in proportion to each cell's real n_cy, so a person-level\n# mean of the twin's respondents estimates the panel's respondent-weighted\n# value. The average of the 270 cell means is a different quantity and would\n# make the weight look like it was doing harm.\nPOP_COSMO <- weighted.mean(panel$mcosmo, panel$n_cy)\nERR_UNW   <- mean(sim$cosmo) - POP_COSMO\nERR_WTD   <- weighted.mean(sim$cosmo, sim$w1) - POP_COSMO\n\ntibble(\n  quantity = c(\"mean age\", \"mean cosmopolitan share\"),\n  unweighted = c(mean(sim$age), mean(sim$cosmo)),\n  weighted = c(weighted.mean(sim$age, sim$w1),\n               weighted.mean(sim$cosmo, sim$w1)),\n  population = c(AGE_REF, POP_COSMO)\n) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  quantity                unweighted weighted population\n  <chr>                        <dbl>    <dbl>      <dbl>\n1 mean age                    45.4     49.4         49.3\n2 mean cosmopolitan share      0.509    0.505        0.5\n```\n\n\n:::\n:::\n\n\nThe achieved sample is about four years too young, and weighting recovers the population age almost exactly. Because age genuinely affects framing in the recipe, that composition error propagates into the outcome: unweighted, the cosmopolitan share sits 0.009 above the population value, and weighting removes about 47 per cent of that. It re-balances who is counted, and it matters exactly to the extent that the mis-counted people differ on the thing being measured. That is the whole of what a weight does to a mean.\n\nThe population column repays a second look. A person-level mean of the twin's respondents is aiming at the panel's respondent-weighted value, not at the average of its 270 cell means, because cells enter the twin in proportion to how many real respondents they held. The two differ by 0.007, which is larger than the whole effect of the weight, so a table benchmarked against the wrong one would show weighting making the estimate worse. Choosing the estimand – the quantity a statistic is actually estimating – is not a technicality here. It decides which direction the lesson runs in.\n\nThe distortion here is constant across cells, so it shifts levels without touching the relationship of interest – the common case, and the reason analysts often find weighting changes their descriptive statistics more than their coefficients. It stops being the common case the moment the distortion varies with the predictor.\n\n::: {.callout-tip}\n## Try it\n\nIn the generator, set `SIM_DISTORT_SLOPE` to 0.01. The youth over-selection then grows with a cell's unemployment rate, from about two and a half years of achieved age shift in the calmest labour markets to eight and a half in the most stressed, and because age moves framing in the recipe the distortion now bends the macro slope itself rather than only the levels.\n\nOne rerun will not show you that. Across draws the unweighted estimate carries the larger bias, but the separation within any single draw is small next to that draw's own sampling variation, so one comparison is an unreliable demonstration and can as easily show the weighted estimate sitting further away. Run eight or ten seeds, keep each `$SIM_OUT` file, and fit the anchor to every one of them weighted and unweighted. `$SIM_SWEEP` will not do this job for you, because it records the unweighted estimates only.\n\nTwo things to expect. The weighted estimate does not land exactly on the planted value either, since `w1` inverts the selection factor exactly only for an untruncated age distribution, and ages are truncated at 15 and 98, which delivers about three quarters of the intended shift at the top of the range. And much above 0.03 the tilt turns negative in low-unemployment countries, over-selecting the old there instead, which muddies the lesson.\n:::\n\n## 8. Building the nothing {#sec-null}\n\nThe [inference reading](../exercise/reading-inference.qmd) argues that to test a specification curve you must know what the curve would look like if there were nothing to find, and the test designed there builds that nothing by permutation. Simulation offers a more direct route: write the recipe with the effect removed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One null world: the twin's cell structure with the slope written out of the\n# recipe, and a small menu of estimators fitted to it. Every estimate below is\n# of a quantity that is exactly zero.\nsimulate_null <- function(seed) {\n  set.seed(seed)\n  cells <- panel |>\n    select(cntry, year, n_cy, unemp) |>\n    mutate(n_sim = pmax(1L, as.integer(round(n_cy * 0.10))),\n           u_cy = rnorm(n(), 0, SD_CY))\n  cells |>\n    left_join(cells |> distinct(cntry) |>\n                mutate(u_c = rnorm(n(), 0, SD_CNTRY)), by = \"cntry\") |>\n    uncount(n_sim) |>\n    mutate(cosmo = pmin(pmax(MEAN_COSMO + 0 * unemp + u_c + u_cy +\n                               rnorm(n(), 0, SD_PERSON), 0), 1))\n}\n\nd_null <- simulate_null(2026)\nnull_fits <- list(\n  pooled      = \\(d) lm(cosmo ~ unemp, data = d),\n  country_re  = \\(d) lmer(cosmo ~ unemp + (1 | cntry), data = d),\n  three_level = \\(d) lmer(cosmo ~ unemp + (1 | cntry) + (1 | cntry:year), data = d),\n  cell_means  = \\(d) lm(mcosmo ~ unemp,\n                        data = summarise(d, mcosmo = mean(cosmo),\n                                         unemp = first(unemp),\n                                         .by = c(cntry, year)))\n) |>\n  imap(\\(f, nm) {\n    p <- parameters::model_parameters(f(d_null))\n    tibble(estimator = nm, estimate = p$Coefficient[p$Parameter == \"unemp\"],\n           p_value = p$p[p$Parameter == \"unemp\"])\n  }) |>\n  list_rbind()\n\nnull_fits |> mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  estimator   estimate  p_value\n  <chr>          <dbl>    <dbl>\n1 pooled      -0.00132 0.000411\n2 country_re   0.00129 0.0108  \n3 three_level  0.00102 0.195   \n4 cell_means  -0.001   0.242   \n```\n\n\n:::\n:::\n\n\nEvery row estimates a quantity known to be zero, and on this seed 2 of the four reject it at the five per cent level. Rerun with a different seed (the function takes one for exactly that reason) and the two extremes hold. Over thirty draws the pooled row, which treats forty thousand echoing respondents as independent, rejects in about six draws in ten. The three-level row, which counts the units that actually carry information about unemployment, rejects rarely – blocks of thirty draws put it anywhere from none to one in ten – and is the closest of the four to the five per cent a valid test should deliver. The two rows in between land between those extremes and move about from one block of seeds to the next, which is worth seeing for itself.\n\nA miniature multiverse fitted to a null world shows what a full-scale permutation test constructs: the distribution of whole curves under nothing. It also disciplines how the real curve's percentages should be read, a point [the multiverse module](multiverse.qmd#sec-reading) develops – some share of any universe will look supportive under a true zero, so a share alone, with no null to stand it against, is a description rather than a verdict.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreal_panel <- sample(1:9, 1)\nmap(1:9, \\(i) {\n  d <- if (i == real_panel) sim_cells else\n    sim_cells |> mutate(unemp = sample(unemp), .by = cntry)\n  d |> mutate(panel = i)\n}) |>\n  list_rbind() |>\n  ggplot(aes(unemp, cosmo)) +\n  geom_point(alpha = 0.4, size = 0.8, colour = \"#00205b\") +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 0.6, colour = \"#c8102e\") +\n  facet_wrap(~panel) +\n  labs(x = \"unemployment (%)\", y = \"cell mean, simulated cosmopolitan share\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![A lineup: nine cell-level scatters of mean simulated cosmopolitan framing against unemployment. Eight permute the unemployment series within country; one is the twin's real structure. Pick the panel that looks like an effect before reading on.](simulation_files/figure-html/fig-lineup-1.png){#fig-lineup width=768}\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Which panel is real?\nPanel 8. If you picked it, you have informally rejected the null by eye – the logic of a permutation test, run on your visual system. If you could not, that is itself evidence about how strong a level-2 relationship of this size looks at this sample size.\n:::\n\n## 9. Test the design before you run it {#sec-design}\n\nPower analysis for multilevel designs rarely has clean formulas, and the standard advice is to simulate: generate data from the design you are contemplating and see how precisely it estimates the quantity you care about [@GelmanEtAl2020RegressionOtherStories; @DeBruineBarr2021UnderstandingMixedeffectsModels]. Precision on a level-2 slope is bought mainly with countries and years rather than with respondents, so it is worth asking what four times as many of each would buy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulate_design <- function(k, seed, per_cell = 1) {\n  set.seed(seed)\n  cells <- panel |>\n    select(cntry, year, n_cy, unemp) |>\n    crossing(clone = seq_len(k)) |>\n    mutate(cntry = paste0(cntry, \"_\", clone),\n           n_sim = pmax(1L, as.integer(round(n_cy * 0.10 * per_cell))),\n           u_cy = rnorm(n(), 0, SD_CY))\n  cells |>\n    left_join(cells |> distinct(cntry) |>\n                mutate(u_c = rnorm(n(), 0, SD_CNTRY)), by = \"cntry\") |>\n    uncount(n_sim) |>\n    mutate(cosmo = pmin(pmax(MEAN_COSMO + B_COSMO * unemp + u_c + u_cy +\n                               rnorm(n(), 0, SD_PERSON), 0), 1))\n}\n\nlist(c(k = 1, per_cell = 1), c(k = 1, per_cell = 4), c(k = 4, per_cell = 1)) |>\n  map(\\(d) {\n    m <- lmer(cosmo ~ unemp + (1 | cntry) + (1 | cntry:year),\n              data = simulate_design(d[[\"k\"]], seed = 20260727 + d[[\"k\"]],\n                                     per_cell = d[[\"per_cell\"]]))\n    p <- parameters::model_parameters(m, ci_method = \"satterthwaite\")\n    tibble(countries = 27 * d[[\"k\"]], respondents = nobs(m),\n           se = p$SE[p$Parameter == \"unemp\"],\n           df = p$df_error[p$Parameter == \"unemp\"])\n  }) |>\n  list_rbind() |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  countries respondents       se    df\n      <dbl>       <dbl>    <dbl> <dbl>\n1        27       41700 0.000899   256\n2        27      167000 0.000759   253\n3       108      167000 0.000411  1060\n```\n\n\n:::\n:::\n\n\nRead the three rows against each other. Quadrupling the respondents inside the existing country-year map does buy precision (people are not worthless), but it buys much less than quadrupling the countries, and it buys almost no degrees of freedom, because the number of units carrying independent information about unemployment has not changed. No feasible amount of extra survey data inside the existing 27 countries would do what 81 more countries would, and no choice on the specification menu can manufacture level-2 information the design does not contain. That is why this literature argues within wide uncertainty bands, and simulation measures a design's ceiling before anyone commits to it. A methodological literature exists on doing this properly – declaring aims, data-generating mechanisms, estimands, methods and performance measures rather than tinkering [@MorrisEtAl2019UsingSimulationStudies] – and it is the natural next reading.\n\n## Where this leads {#sec-further}\n\nFour routes onward. For the habit itself, *Regression and Other Stories* is the anchor text, its fake-data simulations short, constant and cumulative [@GelmanEtAl2020RegressionOtherStories], with *Active Statistics* packaging the same moves as classroom activities [@GelmanVehtari2024ActiveStatisticsStories]. For multilevel structures specifically, DeBruine and Barr's tutorial is sections 2 and 6 of this module done properly: it builds a mixed-effects simulation from nothing and recovers its parameters, on the argument that constructing the data is how you come to understand the model [@DeBruineBarr2021UnderstandingMixedeffectsModels]. For simulation inside a modelling workflow – prior and posterior predictive checking, calibration, experimentation on synthetic data before touching the real thing – the Bayesian workflow book is the current statement [@GelmanEtAl2026BayesianWorkflow], and its habits transfer well beyond Bayesian settings. And for simulation as a research method in its own right, the design framework of @MorrisEtAl2019UsingSimulationStudies supplies the vocabulary, the book-length treatment written for social scientists is @CarseyHarden2014MonteCarloSimulation, and an applied Monte Carlo study this site already cites, on cross-lagged panel models, shows the genre working on a question adjacent to this case's own estimator fork [@LeszczenskyWolbring2022HowDealReverse].\n\nOne closing thought ties the module back to the rest of the site. Simulation studies are analyses too, and they have researcher degrees of freedom of their own – conditions, performance measures, which results get reported – so a comparative study can be tuned until any method looks superior [@PawelEtAl2024PitfallsPotentialsSimulation]. The disciplines this course keeps returning to, declared designs and justified choices, apply in the laboratory exactly as they apply in the field. The generator, the calibration script, the codebook and this page's chunks are all committed, so the fastest route of all is the one from the first Try-it: change what the recipe plants, rerun, and watch what your tools do when you already know the answer.\n",
    "supporting": [
      "simulation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}