<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exercise Overview – Applied Replication for Data Skills</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-abc8d05d46af1384937a7dca9ae4bb04.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/more-fragments-0.1.0/more-fragments.js"></script>
<link href="../site_libs/quarto-contrib/more-fragments-0.1.0/animate.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/more-fragments-0.1.0/magic.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/more-fragments-0.1.0/more-fragments.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/logo.png" alt="CM logo" class="navbar-logo light-content">
    <img src="../assets/logo.png" alt="CM logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Applied Replication for Data Skills</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-setup" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Setup</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-setup">    
        <li>
    <a class="dropdown-item" href="../setup.html">
 <span class="dropdown-text">Install and check</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../help.html">
 <span class="dropdown-text">Setup help</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/ide.html">
 <span class="dropdown-text">Positron, RStudio and VS Code</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tracks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tracks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tracks">    
        <li>
    <a class="dropdown-item" href="../tracks/one-day-replication/index.html">
 <span class="dropdown-text">One day – open science and replication</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tracks/one-day-tools/index.html">
 <span class="dropdown-text">One day – social data science tools</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tracks/one-day-methods/index.html">
 <span class="dropdown-text">One day – the statistical methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tracks/three-days/index.html">
 <span class="dropdown-text">Three days</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tracks/semester/index.html">
 <span class="dropdown-text">Semester</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tracks/self-study/index.html">
 <span class="dropdown-text">Self-study</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-exercise">    
        <li>
    <a class="dropdown-item" href="../exercise/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercise/browser-lab.html">
 <span class="dropdown-text">Browser lab</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercise/spec-menu.html">
 <span class="dropdown-text">Specification menu</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercise/estimand-dial.html">
 <span class="dropdown-text">Estimand choices</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercise/cheatsheet.html">
 <span class="dropdown-text">Cheatsheet</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../results.html"> 
<span class="menu-text">Multiverse</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-companion" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Companion</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-companion">    
        <li>
    <a class="dropdown-item" href="../companion/index.html">
 <span class="dropdown-text">Curriculum overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Computational tools</li>
        <li>
    <a class="dropdown-item" href="../companion/intro-r.html">
 <span class="dropdown-text">Getting started with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/ide.html">
 <span class="dropdown-text">Positron, RStudio and VS Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/quarto.html">
 <span class="dropdown-text">Quarto and reproducible documents</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Reproducibility and collaboration</li>
        <li>
    <a class="dropdown-item" href="../companion/repositories.html">
 <span class="dropdown-text">Repositories &amp; preregistration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/git-github.html">
 <span class="dropdown-text">Git &amp; GitHub</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Statistical methods</li>
        <li>
    <a class="dropdown-item" href="../companion/stats-methods.html">
 <span class="dropdown-text">The statistical methods behind the course</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/dags.html">
 <span class="dropdown-text">Causal graphs &amp; adjustment sets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/multiverse.html">
 <span class="dropdown-text">The multiverse and its critics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/weighting.html">
 <span class="dropdown-text">Weights</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/missingness.html">
 <span class="dropdown-text">Missing answers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/measurement.html">
 <span class="dropdown-text">The items behind the scales</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/simulation.html">
 <span class="dropdown-text">Simulation as a method</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../companion/individual-level.html">
 <span class="dropdown-text">The individual level</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-claim-you-are-working-on" id="toc-the-claim-you-are-working-on" class="nav-link active" data-scroll-target="#the-claim-you-are-working-on">The claim you are working on</a></li>
  <li><a href="#the-five-published-analysts" id="toc-the-five-published-analysts" class="nav-link" data-scroll-target="#the-five-published-analysts">The five Multi100 analysts</a></li>
  <li><a href="#the-tasks" id="toc-the-tasks" class="nav-link" data-scroll-target="#the-tasks">The tasks</a>
  <ul class="collapse">
  <li><a href="#part-1-credibility-and-tools" id="toc-part-1-credibility-and-tools" class="nav-link" data-scroll-target="#part-1-credibility-and-tools">Part 1 – Credibility and tools</a></li>
  <li><a href="#part-2-the-claim-and-its-estimand" id="toc-part-2-the-claim-and-its-estimand" class="nav-link" data-scroll-target="#part-2-the-claim-and-its-estimand">Part 2 – The claim and its estimand</a></li>
  <li><a href="#part-3-reproduction-and-exploration" id="toc-part-3-reproduction-and-exploration" class="nav-link" data-scroll-target="#part-3-reproduction-and-exploration">Part 3 – Reproduction and exploration</a></li>
  <li><a href="#part-4-multiverse-and-preregistration" id="toc-part-4-multiverse-and-preregistration" class="nav-link" data-scroll-target="#part-4-multiverse-and-preregistration">Part 4 – Multiverse and preregistration</a></li>
  </ul></li>
  <li><a href="#what-makes-a-result-valid" id="toc-what-makes-a-result-valid" class="nav-link" data-scroll-target="#what-makes-a-result-valid">What counts as a result</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/CodeMoreh/applied-replication/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercise Overview</h1>
<p class="subtitle lead">You are analyst no. 6</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This page sets out the whole exercise. Your work happens in the workspace you downloaded and opened in your IDE; the <a href="../exercise/browser-lab.html">Browser lab</a> holds the same exercise in a browser tab, for following a demonstration, for trying it without an installation, and as a fallback. Come back here whenever you want the overview again.</p>
<hr>
<section id="the-claim-you-are-working-on" class="level2">
<h2 class="anchored" data-anchor-id="the-claim-you-are-working-on">The claim you are working on</h2>
<p>Five independent analysts reanalysed a claim made by the original author (OA) as part of the Multi100 project. The claim, as presented to all analysts, was:</p>
<blockquote class="blockquote">
<p>“…poor economic performances … decrease positive dimensions of EU framing” (Teney 2016, p.&nbsp;619)</p>
</blockquote>
<p>The published coefficient – the specific number that the Task 2 constraints pointed to – is:</p>
<blockquote class="blockquote">
<p><strong>Unemployment → cosmopolitan EU framing: b = −0.0034, t = −4.03, p &lt; .001</strong> (Table 3, Model 1)</p>
</blockquote>
<p>This comes from a three-level random-intercept model using pooled Eurobarometer data (16 waves, 2004–2013, 27 EU countries). Your first job is to get as close to this result as possible using a transparent, reproducible pipeline. Your second job is to deviate from it – deliberately, with a written justification – and see what that does to the estimate.</p>
<hr>
</section>
<section id="the-five-published-analysts" class="level2">
<h2 class="anchored" data-anchor-id="the-five-published-analysts">The five Multi100 analysts</h2>
<p>Before you begin, here is what the five Multi100 analysts found when they reanalysed the same claim:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Analyst</th>
<th>Tool</th>
<th>Statistic</th>
<th>N</th>
<th>Partial r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>018OL</td>
<td>R</td>
<td>t = −1.21</td>
<td>420</td>
<td>−0.060</td>
</tr>
<tr class="even">
<td><strong>C6HJR</strong></td>
<td><strong>R</strong></td>
<td><strong>t = −3.80</strong></td>
<td><strong>270</strong></td>
<td><strong>−0.242</strong></td>
</tr>
<tr class="odd">
<td>KEVF1</td>
<td>R</td>
<td>t = −5.90</td>
<td>209,826</td>
<td>−0.452</td>
</tr>
<tr class="even">
<td>KQXUE</td>
<td>Stata</td>
<td>t = −7.17</td>
<td>270</td>
<td>−0.419</td>
</tr>
<tr class="odd">
<td>PRL47</td>
<td>Stata</td>
<td>z = −3.59</td>
<td>394,575</td>
<td>−0.006</td>
</tr>
</tbody>
</table>
<p>All five reported a negative effect (same direction as the original). The partial r ranges from −0.006 to −0.452, a factor of 75, so five competent analysts working on one claim arrived at widely different estimates. The multiverse debrief in Part 4 explains most of that gap; for now it is enough to know that the gap is there.</p>
<hr>
</section>
<section id="the-tasks" class="level2">
<h2 class="anchored" data-anchor-id="the-tasks">The tasks</h2>
<p>The exercise runs as five numbered tasks across four 90-minute parts. Each task says what to do in the workspace and, where it differs, on the browser lab page, which reaches the same numbers.</p>
<section id="part-1-credibility-and-tools" class="level3">
<h3 class="anchored" data-anchor-id="part-1-credibility-and-tools">Part 1 – Credibility and tools</h3>
<p><strong>Task 1 – Get yourself running (~8 minutes, and the break if you need it).</strong> The only aim is to reach the point where a line of R runs and the data are in front of you. There is no prize for finishing early, and getting this right now saves an hour of misery later. <em>Workspace:</em> open the workspace folder in your IDE, let the packages install, and render the report skeleton once – if it renders, everything works; if it does not, <code>source("R/check_setup.R")</code> names what is missing. <em>Browser lab:</em> wait for the engine to finish downloading, then run the setup-check cell and confirm the panel has 270 rows. The vocabulary warm-up on the same page – three R’s and one impostor – is there to fill the waiting.</p>
<p>If your installation will not cooperate, do not fight it. Open the browser lab and carry on there; nothing in the day depends on it.</p>
<hr>
</section>
<section id="part-2-the-claim-and-its-estimand" class="level3">
<h3 class="anchored" data-anchor-id="part-2-the-claim-and-its-estimand">Part 2 – The claim and its estimand</h3>
<p><strong>Task 2 – Meet the panel, name the estimand, draw the graph (~18 minutes).</strong> Three pieces, in order. First, look at the data: the <strong>EU-frames dataset</strong> (<code>EUframes_cy.csv</code>) is the country-year panel behind the whole exercise – 270 country-years, unemployment and GDP growth alongside several EU-framing measures, published in the analyst’s OSF fork (<code>osf.io/6zqct</code>, main folder; the official Multi100 archival record is at <code>osf.io/8rtwe</code>). Run the small-multiples figure and find the countries that move sharply around 2009, because that within-country variation is exactly what the model will use.</p>
<p>Second, write the <strong>estimand</strong> in words: the unit-specific quantity, the target population, the aggregation. The template gives you the shape; the value is in being forced to be precise about this claim in particular.</p>
<p>Third, complete the <strong>causal graph</strong>. Take the <code>#</code> off the arrows you are willing to defend, re-run <code>adjustmentSets()</code>, and watch what the graph now demands. Then two sentences for your notes: what do two-way fixed effects adjust for, and what can they not fix? <em>Workspace:</em> edit <code>R/dag_starter.R</code>, where every arrow is an ordinary R formula and adopting one means deleting a <code>#</code>. <em>Browser lab:</em> the same graph with <code>dagify()</code> in the browser lab. The <a href="../companion/dags.html">causal-graphs companion module</a> works the material through slowly if you want it.</p>
<hr>
</section>
<section id="part-3-reproduction-and-exploration" class="level3">
<h3 class="anchored" data-anchor-id="part-3-reproduction-and-exploration">Part 3 – Reproduction and exploration</h3>
<p><strong>Task 3 – Reproduce the recorded result (~22 minutes).</strong> Fit the constrained two-way fixed-effects model – <code>mcosmo ~ unemp_c</code>, with country and year fixed effects – and confirm you get <strong>t = −3.804</strong> (df = 233, N = 270). This is the reproduction step, and −3.804 is the value on record for analyst C6HJR: the same data and the same code give the same number. <em>Workspace:</em> run the model in your working script. <em>Browser lab:</em> fill the gaps in the exercise cell; there are two hints and a full solution, and using them is not cheating.</p>
<p>Your reproduction is one check among several, and the paper fares differently on the others. It was put through all three Rs in the SCORE dossier (<a href="https://osf.io/h7432/">osf.io/h7432</a>): the push-button reproduction failed, the source-data reproduction was recorded as “not reproduced”, and a preregistered replication on fresh data (N = 352,114) flipped sign, with b = +0.002 and p = .046.</p>
<p><strong>Task 4 – Work the menu (~20 minutes).</strong> This task is <strong>exploration, and it is meant to be</strong>. Try several specifications from the <a href="../exercise/spec-menu.html">specification menu</a>, see what each one does, and get a feel for which choices move the estimate and which barely touch it. <code>try_spec()</code> takes one argument per axis and every argument already carries the baseline you just reproduced, so changing one thing means changing one argument. <code>my_experiments()</code> prints everything you have tried, side by side – the small multiverse you have just built. Then pick the one you would defend if you had to, and <code>submit_exploration()</code> puts it on the live <a href="../results.html">Multiverse</a> chart as an <strong>exploratory</strong> result, drawn as an open circle.</p>
<p>Nothing here commits you to anything. You are allowed to look, change your mind and try again – which is why the label matters.</p>
<hr>
</section>
<section id="part-4-multiverse-and-preregistration" class="level3">
<h3 class="anchored" data-anchor-id="part-4-multiverse-and-preregistration">Part 4 – Multiverse and preregistration</h3>
<p>The part opens by reading what the room built: the class chart laid over the full 840-specification curve and the five published analysts, which analytical choice moves estimates most, where the sign flips come from, and <strong>your own percentile</strong> – the share of the 840 specifications more negative than the estimate you submitted. It then turns to what a curve can and cannot establish, and to the argument that once a question is fully specified there is only one correct analysis. The <a href="../exercise/reading-inference.html">reading on the specification curve</a> is the companion for this part.</p>
<p><strong>Task 5 – Declare one specification, run it, report it (~20 minutes).</strong> Now you commit. Pick ONE analysis from the menu, one choice on each of the fourteen axes, and complete the preregistration block <strong>before you run anything</strong>. It is a shortened but real preregistration template: what you are testing, what you already know about the data, your one specification, why those controls (grounded in your Task 2 graph), and the rule you will judge the result by. <code>claim_align &lt;- TRUE</code> is the day’s convention and is applied for you: negative framings are reverse-coded and the claim-expected sign of GDP growth is flipped, so ‘supports the claim’ reads as a negative sign for everyone.</p>
<p>Render that block, or on the browser lab page copy it into your notes, so it is written down before you see the result. Then translate the declaration into model syntax yourself – <code>build_model()</code> accepts only code that matches what you declared – run it, and <code>report_result()</code> prints a one-click, pre-filled form link. Your dot joins the chart as a <strong>declared</strong> result, drawn as a filled circle beside the open exploratory ones.</p>
<p>Task 4 and Task 5 run identical code. What separates them is that an exploratory specification can have been chosen because of its result and a declared one cannot, and seeing the two clouds side by side is why you submit twice.</p>
<hr>
</section>
</section>
<section id="what-makes-a-result-valid" class="level2">
<h2 class="anchored" data-anchor-id="what-makes-a-result-valid">What counts as a result</h2>
<p>Your result is valid for the multiverse chart if it:</p>
<ul>
<li>reports the claim-carrying coefficient (unemployment or GDP growth, or its transformation) from a model on <code>EUframes_cy.csv</code>,</li>
<li>is submitted to the class-results form via the <code>report_result()</code> link (so it lands on the live <a href="../results.html">Multiverse</a> chart), and</li>
<li>has a written justification for the choice you made (2 sentences is enough).</li>
</ul>
<p>The justification is what the whole exercise depends on. Auspurg &amp; Brüderl (2021) argue that a multiverse of unjustified specifications shows dispersion and nothing more; the stated reasons are what let it count as evidence.</p>
<hr>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li><a href="../exercise/browser-lab.html">Browser lab</a> – the whole exercise and its data in a browser tab, for demonstrations and for trying it without an installation.</li>
<li><a href="../exercise/spec-menu.html">Specification menu</a> – the fourteen axes you choose one option from, grouped into the three levels of decision they belong to, with a worked example.</li>
<li><a href="../exercise/estimand-dial.html">Estimand choices</a> – set the seven Level 1 choices, read the question they ask, and watch how far the answer moves when only its measurement changes.</li>
<li><a href="../exercise/reading-inference.html">Reading a specification curve</a> – the companion reading for Part 4: what a large set of results can and cannot establish.</li>
<li><a href="../exercise/cheatsheet.html">Cheatsheet</a> – the one-page card to keep open on the day, with the in-room links and what to do if something stalls.</li>
</ul>
<p>Two of the nine <a href="../companion/index.html">companion modules</a> pick up the skills that the day sets aside and take them further, at your own pace:</p>
<ul>
<li><a href="../companion/git-github.html">Git and GitHub for reproducible research</a> – version control and publishing your report, the part lifted out of the core day.</li>
<li><a href="../companion/repositories.html">Reproducibility repositories</a> – archives, OSF, and preregistration templates in more depth.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/codemoreh\.github\.io\/applied-replication\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content licensed <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> · <a href="https://github.com/CodeMoreh/applied-replication">GitHub repo</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/CodeMoreh/applied-replication/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>