{
  "hash": "3aeb9cad367ac8e351d5d4493f741895",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The statistical methods behind the workshop\"\nsubtitle: \"Foundation to advanced – the methods at work in the case\"\nbibliography: [../references.bib, ../references-new.bib]\n---\n\n\n\nThis is the second module of the [companion curriculum](index.qmd). It works through the statistical methods the EU-frames case draws on, from the simplest linear model to Bayesian and generalised extensions, using the workshop's own data throughout: the country-year panel you fit models on, the raw respondent-level records behind it, the specification grid behind the class chart, and the five Multi100 analysts whose results you meet on the day. It follows on naturally from [getting started with R](intro-r.qmd) and assumes only what that module covers – reading a CSV, a dplyr chain, and the idea of a model formula.\n\nUnlike a textbook chapter, every model on this page is genuinely fitted and every output shown is real. The outputs come in two kinds, and the difference is worth knowing from the start. Models on the **committed workshop data** – the 270-row country-year panel and the small analyst and grid files – execute when this page is built, so what you see is what the code produces, and you can reproduce every one of them yourself from the shipped files. (The one exception is the Bayesian model of section 8: its data ship with the workshop too, but Stan compiles and samples for a minute or two, so its saved output is displayed instead – with the exact call that made it.) Models on the **respondent-level microdata** cannot ship: the raw Eurobarometer records are GESIS-licensed and may not be redistributed. Those models were fitted once, on the facilitator's machine, by the script `companion/_model-outputs/fit_models.R` in the site's source repository, and their printed summaries are displayed here exactly as R returned them. The code above each such output is the code that produced it.\n\n## 1. From respondents to country-years: what aggregation does {#sec-aggregation}\n\nThe original author (OA) modelled individual survey respondents directly, in the original study. Sixteen Eurobarometer waves pool to 416,698 people interviewed across 27 EU member states between 2004 and 2013, each asked what the European Union means to them. The workshop's core exercise does not work with those individuals. It works with `EUframes_cy.csv`, which collapses them to **270 country-year rows** – 27 countries observed in each of 10 years – with every framing scale averaged within the cell. For country $c$ in year $t$, the cell value is the mean of its respondents' scores:\n\n$$ \\bar{y}_{ct} = \\frac{1}{n_{ct}} \\sum_{i \\,\\in\\, (c,t)} y_{ict} $$\n\nwhere $y_{ict}$ is respondent $i$'s framing scale and $n_{ct}$ the number of respondents in that country-year. Unemployment and GDP growth, which are national figures to begin with, attach directly to each cell.\n\nThe data therefore live at three levels – respondents, country-years, and countries – and this module climbs through all three. Two things are gained by working at the middle level. The first is practical and it is the reason the workshop can exist at all: the raw microdata are GESIS-licensed and cannot be redistributed, whereas the derived country-year averages can be released under an open licence and shipped with the materials. The second is that the country-year is the level at which the predictor genuinely varies. Every respondent interviewed in Germany in 2010 shares one German 2010 unemployment rate, so all the information the data hold about the alignment of unemployment with EU framing is carried by 270 country-level pairings, not by the hundreds of thousands of individuals. Aggregating to that level discards almost no identifying variation about the relationship of interest.\n\nWhat is lost is equally worth naming. Averaging within a cell removes all the between-individual variation inside it, so nothing about how framing differs across people of different ages, educations or outlooks survives in the panel. The standard errors no longer reflect 416,698 respondents but 270 cells, which is why the fitted models below carry residual degrees of freedom in the low hundreds rather than the hundreds of thousands. And a relationship among country-year averages need not hold among individuals: reading an aggregate association as if it described people is the ecological inference problem, and the country-year panel cannot speak to the individual-level question at all. Whether that matters is not a technicality but a question about what you are trying to measure, which is the theme [section 6](#sec-multilevel) returns to.\n\n::: {.callout-tip}\n## Try it\n\nRead `data/EUframes_cy.csv` and sum its `n_cy` column (`sum(euframes$n_cy)`); you should recover the 416,698 respondents that stand behind the 270 rows. Then run `nrow(euframes)` to confirm the 270. Holding those two numbers side by side – the people who were interviewed and the rows you actually analyse – is the whole of what aggregation does, made concrete.\n:::\n\n## 2. Ordinary least squares: one simple model, read line by line {#sec-ols}\n\nEvery model in this module is a variation on one idea, so it pays to meet the idea in its plainest form. A **linear model** proposes that the outcome is a straight-line function of a predictor plus noise. For row $i$ of the panel:\n\n$$ y_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i $$\n\nEach symbol has a plain meaning. $y_i$ is the outcome, here a country-year's mean cosmopolitan framing score. $x_i$ is the predictor, its unemployment rate. $\\beta_0$, the **intercept**, is the expected outcome when the predictor is zero. $\\beta_1$, the **slope**, is the expected change in the outcome for a one-unit rise in the predictor, and it is the number every research question in this case turns on. $\\varepsilon_i$ is the **error**: everything else that moves the outcome, assumed to average out to zero. **Ordinary least squares** (OLS) estimates the two $\\beta$s by choosing the line that minimises the sum of squared errors,\n\n$$ (\\hat\\beta_0, \\hat\\beta_1) = \\underset{\\beta_0,\\,\\beta_1}{\\arg\\min} \\sum_i \\left( y_i - \\beta_0 - \\beta_1 x_i \\right)^2 $$\n\nwhich is what `lm()` (for 'linear model') computes. The name is literal, and a picture makes it so:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The geometry of 'least squares' on the workshop panel. Each red square's side is one country-year's error – the vertical gap between the point and the line – so its area is that error squared. OLS chooses the line that makes the summed area of all 270 such squares (six of them drawn here) as small as possible. Both axes are standardised so the squares draw true.](stats-methods_files/figure-html/fig-ols-squares-1.png){#fig-ols-squares width=672}\n:::\n:::\n\n\nNothing in that geometry is tied to a single predictor. Give the model two,\n\n$$ y_i = \\beta_0 + \\beta_1 x_{1i} + \\beta_2 x_{2i} + \\varepsilon_i $$\n\nand the fitted object is no longer a line but a **plane** floating over the two predictors' grid. The errors are still the vertical gaps between each point and the fitted surface, OLS still minimises their summed squares, and each slope acquires the reading it keeps for the rest of this module: $\\beta_1$ is the expected change in the outcome for a one-unit rise in $x_1$ *with* $x_2$ *held fixed* – movement along the plane parallel to one axis. That is all 'controlling for' means, made literal. The figure below fits exactly this on the panel, with GDP growth as the second predictor – the very variable the specification menu can add as a co-predictor – and it is a live three-dimensional object: **drag it to rotate, scroll to zoom**, and watch the red residual drops stay vertical from every angle.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nnull \n   1 \n```\n\n\n:::\n\n::: {#fig-ols-plane .cell-output-display}\n\n```{=html}\n<div id=\"rgl72179\" style=\"width:100%;height:487px;\" class=\"rglWebGL html-widget\" role=\"img\" aria-labelledby=\"rgl72179-aria\"></div>\n<script type=\"application/json\" data-for=\"rgl72179\">{\"x\":{\"material\":{\"color\":\"#000000\",\"alpha\":1,\"lit\":true,\"ambient\":\"#000000\",\"specular\":\"#FFFFFF\",\"emission\":\"#000000\",\"shininess\":50,\"smooth\":true,\"front\":\"filled\",\"back\":\"filled\",\"size\":3,\"lwd\":1,\"fog\":true,\"point_antialias\":false,\"line_antialias\":false,\"texture\":null,\"textype\":\"rgb\",\"texmode\":\"modulate\",\"texmipmap\":false,\"texminfilter\":\"linear\",\"texmagfilter\":\"linear\",\"texenvmap\":false,\"depth_mask\":true,\"depth_test\":\"less\",\"isTransparent\":false,\"polygon_offset\":[0,0],\"margin\":\"\",\"floating\":false,\"tag\":\"\",\"blend\":[\"src_alpha\",\"one_minus_src_alpha\"]},\"rootSubscene\":1,\"objects\":{\"8\":{\"id\":8,\"type\":\"points\",\"material\":{\"lit\":false,\"size\":4},\"vertices\":\"0\",\"colors\":\"1\",\"centers\":\"2\",\"ignoreExtent\":false,\"flags\":34816},\"10\":{\"id\":10,\"type\":\"text\",\"material\":{\"lit\":false,\"margin\":0,\"floating\":true,\"edge\":[0,1,1]},\"vertices\":\"3\",\"colors\":\"4\",\"texts\":[[\"unemployment\"]],\"cex\":[[1]],\"adj\":[[0.5,0.5,0.5]],\"centers\":\"5\",\"family\":[[\"sans\"]],\"font\":[[1]],\"ignoreExtent\":true,\"flags\":33808},\"11\":{\"id\":11,\"type\":\"text\",\"material\":{\"lit\":false,\"margin\":1,\"floating\":true,\"edge\":[1,1,1]},\"vertices\":\"6\",\"colors\":\"7\",\"texts\":[[\"growth\"]],\"cex\":[[1]],\"adj\":[[0.5,0.5,0.5]],\"centers\":\"8\",\"family\":[[\"sans\"]],\"font\":[[1]],\"ignoreExtent\":true,\"flags\":33808},\"12\":{\"id\":12,\"type\":\"text\",\"material\":{\"lit\":false,\"margin\":2,\"floating\":true,\"edge\":[1,1,1]},\"vertices\":\"9\",\"colors\":\"10\",\"texts\":[[\"mcosmo\"]],\"cex\":[[1]],\"adj\":[[0.5,0.5,0.5]],\"centers\":\"11\",\"family\":[[\"sans\"]],\"font\":[[1]],\"ignoreExtent\":true,\"flags\":33808},\"13\":{\"id\":13,\"type\":\"surface\",\"material\":{\"alpha\":0.3490196168422699,\"lit\":false,\"isTransparent\":true},\"vertices\":\"12\",\"colors\":\"13\",\"dim\":[[24,24]],\"centers\":\"14\",\"ignoreExtent\":false,\"flipped\":true,\"flags\":32810},\"14\":{\"id\":14,\"type\":\"lines\",\"material\":{\"lit\":false,\"lwd\":2},\"vertices\":\"15\",\"colors\":\"16\",\"centers\":\"17\",\"ignoreExtent\":false,\"flags\":41024},\"15\":{\"id\":15,\"type\":\"points\",\"material\":{\"lit\":false,\"size\":6},\"vertices\":\"18\",\"colors\":\"19\",\"centers\":\"20\",\"ignoreExtent\":false,\"flags\":34816},\"5\":{\"id\":5,\"type\":\"light\",\"vertices\":[[0,0,1]],\"colors\":[[1,1,1,1],[1,1,1,1],[1,1,1,1]],\"viewpoint\":true,\"finite\":false},\"7\":{\"id\":7,\"type\":\"background\",\"material\":{\"lit\":false,\"back\":\"lines\"},\"colors\":\"21\",\"centers\":\"22\",\"sphere\":false,\"fogtype\":\"none\",\"fogscale\":1,\"flags\":32768},\"9\":{\"id\":9,\"type\":\"bboxdeco\",\"material\":{\"front\":\"lines\",\"back\":\"lines\"},\"vertices\":\"23\",\"colors\":\"24\",\"axes\":{\"mode\":[\"pretty\",\"pretty\",\"pretty\"],\"step\":[5,5,0.1000000014901161],\"nticks\":[5,5,5],\"marklen\":[15,15,15],\"expand\":[1.029999971389771,1.029999971389771,1.029999971389771]},\"draw_front\":true,\"flags\":32769},\"1\":{\"id\":1,\"type\":\"subscene\",\"par3d\":{\"antialias\":8,\"FOV\":60,\"ignoreExtent\":false,\"listeners\":1,\"mouseMode\":{\"none\":\"none\",\"left\":\"trackball\",\"right\":\"zoom\",\"middle\":\"fov\",\"wheel\":\"pull\"},\"observer\":[0,0,41.38243865966797],\"modelMatrix\":[[0.7119948267936707,0,23.1657772064209,-22.18253707885742],[-0.1036531552672386,0.7555476427078247,6.878583431243896,-0.5987255573272705],[-0.4876497387886047,-0.1605966091156006,32.36119079589844,-49.53681182861328],[0,0,0,1]],\"projMatrix\":[[2.037706851959229,0,0,0],[0,2.037706851959229,0,0],[0,0,-2,-62.07365798950195],[0,0,-1,0]],\"skipRedraw\":false,\"userMatrix\":[[0.8191520571708679,0,0.5735764503479004,0],[-0.1192532554268837,0.9781476259231567,0.17031130194664,0],[-0.5610424280166626,-0.2079117000102997,0.8012516498565674,0],[0,0,0,1]],\"userProjection\":[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],\"scale\":[0.8691851496696472,0.7724270224571228,40.38829803466797],\"viewport\":{\"x\":0,\"y\":0,\"width\":1,\"height\":1},\"zoom\":0.8500000238418579,\"bbox\":[3.650000095367432,27.46999931335449,-14.83860874176025,11.9652042388916,0.2999051213264465,0.6587415337562561],\"windowRect\":[0,0,256,256],\"family\":\"sans\",\"font\":1,\"cex\":1,\"useFreeType\":false,\"fontname\":\"NULL\",\"maxClipPlanes\":2147483647,\"glVersion\":\"NA\",\"activeSubscene\":0},\"embeddings\":{\"viewport\":\"replace\",\"projection\":\"replace\",\"model\":\"replace\",\"mouse\":\"replace\"},\"objects\":[7,9,8,10,11,12,13,14,15,5],\"subscenes\":[],\"flags\":44411}},\"crosstalk\":{\"key\":[],\"group\":[],\"id\":[],\"options\":[]},\"width\":720,\"height\":540,\"buffer\":{\"accessors\":[{\"bufferView\":0,\"componentType\":5126,\"count\":270,\"type\":\"VEC3\"},{\"bufferView\":1,\"componentType\":5126,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":2,\"componentType\":5126,\"count\":270,\"type\":\"VEC3\"},{\"bufferView\":3,\"componentType\":5126,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":4,\"componentType\":5121,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":5,\"componentType\":5126,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":6,\"componentType\":5126,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":7,\"componentType\":5121,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":8,\"componentType\":5126,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":9,\"componentType\":5126,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":10,\"componentType\":5121,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":11,\"componentType\":5126,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":12,\"componentType\":5126,\"count\":576,\"type\":\"VEC3\"},{\"bufferView\":13,\"componentType\":5126,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":14,\"componentType\":5126,\"count\":529,\"type\":\"VEC3\"},{\"bufferView\":15,\"componentType\":5126,\"count\":16,\"type\":\"VEC3\"},{\"bufferView\":16,\"componentType\":5126,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":17,\"componentType\":5126,\"count\":8,\"type\":\"VEC3\"},{\"bufferView\":18,\"componentType\":5126,\"count\":8,\"type\":\"VEC3\"},{\"bufferView\":19,\"componentType\":5126,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":20,\"componentType\":5126,\"count\":8,\"type\":\"VEC3\"},{\"bufferView\":21,\"componentType\":5121,\"count\":1,\"type\":\"VEC4\"},{\"bufferView\":22,\"componentType\":5121,\"count\":1,\"type\":\"VEC3\"},{\"bufferView\":23,\"componentType\":5126,\"count\":14,\"type\":\"VEC3\"},{\"bufferView\":24,\"componentType\":5121,\"count\":1,\"type\":\"VEC4\"}],\"bufferViews\":[{\"buffer\":0,\"byteLength\":3240,\"byteOffset\":0},{\"buffer\":0,\"byteLength\":16,\"byteOffset\":3240},{\"buffer\":0,\"byteLength\":3240,\"byteOffset\":3256},{\"buffer\":0,\"byteLength\":12,\"byteOffset\":6496},{\"buffer\":0,\"byteLength\":4,\"byteOffset\":6508},{\"buffer\":0,\"byteLength\":12,\"byteOffset\":6512},{\"buffer\":0,\"byteLength\":12,\"byteOffset\":6524},{\"buffer\":0,\"byteLength\":4,\"byteOffset\":6536},{\"buffer\":0,\"byteLength\":12,\"byteOffset\":6540},{\"buffer\":0,\"byteLength\":12,\"byteOffset\":6552},{\"buffer\":0,\"byteLength\":4,\"byteOffset\":6564},{\"buffer\":0,\"byteLength\":12,\"byteOffset\":6568},{\"buffer\":0,\"byteLength\":6912,\"byteOffset\":6580},{\"buffer\":0,\"byteLength\":16,\"byteOffset\":13492},{\"buffer\":0,\"byteLength\":6348,\"byteOffset\":13508},{\"buffer\":0,\"byteLength\":192,\"byteOffset\":19856},{\"buffer\":0,\"byteLength\":16,\"byteOffset\":20048},{\"buffer\":0,\"byteLength\":96,\"byteOffset\":20064},{\"buffer\":0,\"byteLength\":96,\"byteOffset\":20160},{\"buffer\":0,\"byteLength\":16,\"byteOffset\":20256},{\"buffer\":0,\"byteLength\":96,\"byteOffset\":20272},{\"buffer\":0,\"byteLength\":4,\"byteOffset\":20368},{\"buffer\":0,\"byteLength\":3,\"byteOffset\":20372},{\"buffer\":0,\"byteLength\":168,\"byteOffset\":20376},{\"buffer\":0,\"byteLength\":4,\"byteOffset\":20544}],\"buffers\":[{\"byteLength\":20548,\"bytes\":\"XI+6QDYML0DHlbo+9ii0QMSeD0BAbrw+FK6nQAUPXUAAALg+H4WbQPmNbkA7Scc+9iiEQCrv\\nuj94HsM+mpmpQNnucMCGQcc+cT2aQOMl6z/WYbM+heuRQBwPO0B0wLc+CtebQK4xLj8117U+\\nSOGqQELv0Dx2s8U+H4XrQJ2OZEAEdvg+PQoHQVeXFEBfWgM/AAAEQbRZI0CqAwU/UrjuQAVS\\na0DSDQY/KVzfQNjT5D5UfAk/uB79QNtTAcDQqPQ+16MEQZJQN0DA5fE+4XrkQNXl2D+OqfI+\\nrkfxQFg9PT+1rts+SOEGQcsh6z4ut9w+16NAQWpV0EA+bf0+rkchQZnN4UDMNwE/MzMPQdCu\\n2UDlB/8+9ijcQJjs0kCSTx0/H4WzQGu2w0An4xg/cT3aQA9mUcDzqhs/4XokQcBZxT+cbBk/\\n9ig0QSh6BkBW2h4/7FFEQR5DQT9V9h4/PQpPQYh8D78IpB8/XI+KQM/XoECTwBY/mpmpQM9L\\nm0BcWRM/rkeRQK/XlkBjNhg/SOF6QGAjo0DvegY/mplpQF5laUA1XBE/H4WrQA/6AMDOjQI/\\n7FHIQMbwAECvWPA+H4X7QEaJzT6vtus+zcw8QbyYXMAhd78+het9QdGy0cCW9bw+KVwDQW0O\\nmkB5Y/w+j8L9QHNA00CYJgA/zczkQLaK2ECQKAU/cT2qQDdAskBrNQg/4XqMQCzuK0BJBQQ/\\nuB7VQNsIlcBC+wI/w/XoQHDVG0D8ffA+UrjWQHdT4T/cSdw+KVzfQAv2SL/Jo90+ZmbeQH4F\\nPL0qYuc+FK4rQUpplj8NAek+UrgyQSlROz9PKvs+AAAkQZZAdEC0UQE/XI8KQT5+PkClXwI/\\n16PwQKS6dT9SZvg+FK73QOgztsDzaAQ/PQrfQJnBhUC+COg+cT26QFs2e0BdN+Q+9iisQFFF\\n1j5P4uk+KVynQPgL4D4/OuE+ZmamQBvEKkCMKfA+XI+aQIiLFUCCS/0+mpl5QLluekAlDAE/\\nMzNzQOLDaD8I4ws/H4VrQIgTA7+Cawc/uB7NQHACncCLo/U+AAD4QKN87z+b0v4+16P4QIkb\\nqz+wSQQ/mpn5QJDvZz5Z9gU/9ijsQG/vbj/qKAQ/AAAkQW+62UCPK98+4XoAQT9sGEHLCNg+\\nuB69QNQ/HEEcjNw+SOGSQFKI8kBTSx0/ZmauQFo5pMDNDxo/zcxYQZwQasHikhs/FK6FQddu\\nHEBmehU/rkdFQTBr6EByRAk/7FEgQdaaTkBbrA4/exQKQcqtuj8uegs/pHAxQeHbR0Dpxg4/\\nZmYSQee6aUBhwQM/MzMHQYpJg0Bd4v0+FK4DQTWzZkCypwE/AAA0QfIbYz80bgA/SOGOQcvY\\ncMBKSho/SOGeQSfsJj4se+w+uB6rQcd6UL++aug+7FHGQXxnPcBFpdY+UrjQQQC7t79kMcg+\\nj8IlQWx+f0BWFvY+exQGQRLpMUBVl+8+PQr3QIrggEBUhug+MzPbQCqUqUBwpvs+CtfLQOaz\\nSD9lDfc+AAAEQfAwAcHzxPk+cT0GQb/mS0Dmp+8+w/X4QPEMI0DoxPc+exT2QMfisr9RruU+\\nPQoDQZLVZr8mJO0+XI8OQawaNUDnbww/CtcHQWTk1D9hfA0/MzMHQbjBHEDlxhA/uB71QOEu\\nG0BBZRE/hevhQEeIgj4h9xQ/CtcLQWDkN8DM/g0/hesNQSyH+T9HvAs/w/UMQTVVDEA3hQA/\\nZmYWQTNToD54yQY/UrgeQSWKEz+RM/w+SOGSQKPCFkCijcI+AACYQE34JUDpE7k+MzOrQPlh\\nJUCwN8A+7FGoQEY/EUA5/b4+CtezQLBjdb5xeKo+rkfxQFjqh8D4l7U+rkf5QHxpCEApSaU+\\n16MAQXCRuj9/Q5o+9ij8QEYlvD8qjZk+16PwQB/s8T9BOqs+w/UkQafzoUAY4g0/CtcfQV1h\\nGT+LUQ0/9igQQb3gtEBzng8/ZmYGQRKFUUChCBc/7FH4QL2bq75kWws/hesZQZyficDkSg0/\\nKVxLQepQr8BPhO4+SOGOQZhjIsGl29s+H4XDQTjG4sDdz9M+j8LbQRkGIcDg/8g+XI+6QKwD\\noECNBwU/exTmQOxyiUCRbAQ/FK7vQEKofEBajAo/uB7tQGzQjT5FsQo/cT36QNbTgD+rQgk/\\n4XogQSAO08AHgvs+UrgyQaKjij/6jAk/4XowQZAZ7j9LE/c+AAAwQfD9oL+Sf/U+SOEiQe82\\n5z+3kwU/FK6PQN8l2UAfUPQ+SOGKQAuPt0CIG/4+uB6NQEZgn0BnfQk/KVyfQGbGqUB6MgQ/\\n16PYQDmSj8CajwI/j8JJQQ83o8A6ZQM/4XpoQXym4D+7QPY+mpl1QXvFiD9VN+w+MzN3Qflx\\nVr04td0+FK5bQYktoj/6ytk+Ctf7QFU4tj/xPhk/KVz3QI1eUT8DSBA/w/XYQK4z5T823xQ/\\nXI/CQGhYvj9XGxE/PQrXQHlGdr+2uP8+AAD4QHD9qMCPJhA/j8IFQUdN2z8Dsgk/j8IFQcwT\\nNT/caPE+ZmYqQSnHPsDCydw+ZmZCQQio678A4+k+SOEqQUM50kBTdAU/uB4FQY5v90CUYAQ/\\nw/W4QHtA7UBdPQs/AACIQD24MUFqLBo/XI+6QLVSJ0BFkRk/16NcQfFqbcExtxI/4XqOQdtb\\n0z+7HxY/cT12QY4/wUBplhA/j8JVQeEBdkDkJRQ/7FE8QWU0Y0BgAhg/H4WjQKdrh0A/nwQ/\\nFK6PQGvnHkDD2Qk/KVyXQO6IwECVhQE/cT2CQCSUAUGb1Aw/heuhQLKwmb7xKAw/CtejQAZL\\nT8BJoyg/H4WLQJ6qcEBkoxc/zcycQJSrhT9JjRs/4XqkQP0v0z9Vjxc/MzO7QJ7+SkABhAQ/\\nKVw7QfWCBEH4IMk+4XogQZNxK0EOBu4+w/XgQHpxP0G5IA8/mpnBQIkWH0HcCBQ/FK73QAmK\\nT8AT5/k+exSMQfj4Y8GnIQk/CtebQfURj8CKKw4/FK6BQYIfJEAsZwo/zcxwQbQx4UCYQBE/\\nhes9QQuwAEA0Vg0/cT3qQHOiDz5RXxE/pHDdQMyMWEC8gAk/mpnZQCymIEAKEQU/PQrPQGPK\\nmEAjjhY/KVy/QBPjdEAMfhM/4XrcQMQikb9c6gk/MzPbQH5lsUDJfgw/9ijMQEoh7z5klwc/\\nZmbGQELEg0DMMw0/H4XDQLslr0CZuAk/zcyUQLMS/j8wQfg+Cte7QI5BA0DDzAE/AACgQNiA\\nXUAN2gE/zcyEQEB2cUCrCwE/mplpQJrmCkBR0Qk/MzOLQDquasDXowk/FK6fQOLeqz92bQY/\\nKVyfQF+Nxj/7kPs+cT26QKTig799QAQ/FK7nQKxMBb5Fz+k+XI+YQU9zn0DSFRg/AACOQTpw\\nYED3DRc/pHBdQUgyxEB/CCM/mpkZQSr44UDNLyg/CtfjQCVmhkAIVyI/UrgCQWhCNUDcehU/\\ncT0aQbNkb0DCiRc/exQaQY0+mECMKw8/pHAhQTSWqT/U8ws/rkclQQQZkD95xRA/cT3KQEr1\\n5D+fAuY+XI/yQDQnSD8b1/U+zcz0QB8B0D/ul8w+PQr/QM1rIECW/gA/mpnxQHd0oz7BHug+\\nSOEWQSbQR8ABpO0+7FEsQYNq3j8uNs8+SOFKQe0b2b/pSb0+4Xp4QVnVgcDAJLU+H4WBQXEy\\nbL/VW7Y+PQr3QI3ZJkFFmhw/pHDlQHhhlUBAXBI/16PoQAN2AEHRxxE/uB7NQFp750Bitxo/\\nrke5QGPrFEH1NRU/H4XbQH+OsMAighE/UrjeQNutecBe9hE/j8LlQAf68z+CnBA/rkfZQEKa\\nAkDRXhI/MzPjQHJXcUAtUBI/exTWQIfHikCkTfQ+FK7vQKL2NkCU0/0+cT3iQHE1lUCqvwk/\\nuB7FQDYcXEC8Awk/KVzHQLSv5r6hWQ8/mpkFQZDfisCmhRQ/j8IJQal3vkB4TAw/mpn5QFeA\\nTEBb/g8/KVz/QCGbFr82+gY/zcwAQQkJmD91OgQ/7FHAQIJ+i0A0qQk/7FHQQPwRc0DKBgI/\\nZma+QHzit0DzGQU/cT2aQHpd30CJ7wc/CteLQD6hYEDX8wE/H4W7QM2M8cD33AE/FK7nQPP/\\nqz8BF/g+UrgCQfl/XD+FCfg+pHANQZHsKMD7uPI+mpkhQYq/g79GE+U+zcyUQZXsqEApkAI/\\nexSCQWfz00CmwQI/hetVQQ3kB0FQQQ0/cT0yQf5PLUHHoBI/9igYQXplskCNGAo/4XpAQbuT\\nrsBg0w8/exRmQZliyUCLaAg/hetZQSPLKEDGjvw+KVxfQWDarT9iTPQ+H4VjQbOeJz9Nq/U+\\n5+bmPufm5j7n5uY+AACAP1yPukA2DC9Ax5W6PvYotEDEng9AQG68PhSup0AFD11AAAC4Ph+F\\nm0D5jW5AO0nHPvYohEAq77o/eB7DPpqZqUDZ7nDAhkHHPnE9mkDjJes/1mGzPoXrkUAcDztA\\ndMC3PgrXm0CuMS4/Nde1PkjhqkBC79A8drPFPh+F60CdjmRABHb4Pj0KB0FXlxRAX1oDPwAA\\nBEG0WSNAqgMFP1K47kAFUmtA0g0GPylc30DY0+Q+VHwJP7ge/UDbUwHA0Kj0PtejBEGSUDdA\\nwOXxPuF65EDV5dg/jqnyPq5H8UBYPT0/ta7bPkjhBkHLIes+LrfcPtejQEFqVdBAPm39Pq5H\\nIUGZzeFAzDcBPzMzD0HQrtlA5Qf/PvYo3ECY7NJAkk8dPx+Fs0BrtsNAJ+MYP3E92kAPZlHA\\n86obP+F6JEHAWcU/nGwZP/YoNEEoegZAVtoeP+xRREEeQ0E/VfYePz0KT0GIfA+/CKQfP1yP\\nikDP16BAk8AWP5qZqUDPS5tAXFkTP65HkUCv15ZAYzYYP0jhekBgI6NA73oGP5qZaUBeZWlA\\nNVwRPx+Fq0AP+gDAzo0CP+xRyEDG8ABAr1jwPh+F+0BGic0+r7brPs3MPEG8mFzAIXe/PoXr\\nfUHRstHAlvW8PilcA0FtDppAeWP8Po/C/UBzQNNAmCYAP83M5EC2ithAkCgFP3E9qkA3QLJA\\nazUIP+F6jEAs7itASQUEP7ge1UDbCJXAQvsCP8P16EBw1RtA/H3wPlK41kB3U+E/3EncPilc\\n30AL9ki/yaPdPmZm3kB+BTy9KmLnPhSuK0FKaZY/DQHpPlK4MkEpUTs/Tyr7PgAAJEGWQHRA\\ntFEBP1yPCkE+fj5ApV8CP9ej8ECkunU/Umb4PhSu90DoM7bA82gEPz0K30CZwYVAvgjoPnE9\\nukBbNntAXTfkPvYorEBRRdY+T+LpPilcp0D4C+A+PzrhPmZmpkAbxCpAjCnwPlyPmkCIixVA\\ngkv9PpqZeUC5bnpAJQwBPzMzc0Diw2g/COMLPx+Fa0CIEwO/gmsHP7gezUBwAp3Ai6P1PgAA\\n+ECjfO8/m9L+Ptej+ECJG6s/sEkEP5qZ+UCQ72c+WfYFP/Yo7EBv724/6igEPwAAJEFvutlA\\njyvfPuF6AEE/bBhBywjYPrgevUDUPxxBHIzcPkjhkkBSiPJAU0sdP2ZmrkBaOaTAzQ8aP83M\\nWEGcEGrB4pIbPxSuhUHXbhxAZnoVP65HRUEwa+hAckQJP+xRIEHWmk5AW6wOP3sUCkHKrbo/\\nLnoLP6RwMUHh20dA6cYOP2ZmEkHnumlAYcEDPzMzB0GKSYNAXeL9PhSuA0E1s2ZAsqcBPwAA\\nNEHyG2M/NG4AP0jhjkHL2HDASkoaP0jhnkEn7CY+LHvsPrgeq0HHelC/vmroPuxRxkF8Zz3A\\nRaXWPlK40EEAu7e/ZDHIPo/CJUFsfn9AVhb2PnsUBkES6TFAVZfvPj0K90CK4IBAVIboPjMz\\n20AqlKlAcKb7PgrXy0Dms0g/ZQ33PgAABEHwMAHB88T5PnE9BkG/5ktA5qfvPsP1+EDxDCNA\\n6MT3PnsU9kDH4rK/Ua7lPj0KA0GS1Wa/JiTtPlyPDkGsGjVA528MPwrXB0Fk5NQ/YXwNPzMz\\nB0G4wRxA5cYQP7ge9UDhLhtAQWURP4Xr4UBHiII+IfcUPwrXC0Fg5DfAzP4NP4XrDUEsh/k/\\nR7wLP8P1DEE1VQxAN4UAP2ZmFkEzU6A+eMkGP1K4HkElihM/kTP8PkjhkkCjwhZAoo3CPgAA\\nmEBN+CVA6RO5PjMzq0D5YSVAsDfAPuxRqEBGPxFAOf2+PgrXs0CwY3W+cXiqPq5H8UBY6ofA\\n+Je1Pq5H+UB8aQhAKUmlPtejAEFwkbo/f0OaPvYo/EBGJbw/Ko2ZPtej8EAf7PE/QTqrPsP1\\nJEGn86FAGOINPwrXH0FdYRk/i1ENP/YoEEG94LRAc54PP2ZmBkEShVFAoQgXP+xR+EC9m6u+\\nZFsLP4XrGUGcn4nA5EoNPylcS0HqUK/AT4TuPkjhjkGYYyLBpdvbPh+Fw0E4xuLA3c/TPo/C\\n20EZBiHA4P/IPlyPukCsA6BAjQcFP3sU5kDscolAkWwEPxSu70BCqHxAWowKP7ge7UBs0I0+\\nRbEKP3E9+kDW04A/q0IJP+F6IEEgDtPAB4L7PlK4MkGio4o/+owJP+F6MEGQGe4/SxP3PgAA\\nMEHw/aC/kn/1PkjhIkHvNuc/t5MFPxSuj0DfJdlAH1D0PkjhikALj7dAiBv+PrgejUBGYJ9A\\nZ30JPylcn0BmxqlAejIEP9ej2EA5ko/Amo8CP4/CSUEPN6PAOmUDP+F6aEF8puA/u0D2PpqZ\\ndUF7xYg/VTfsPjMzd0H5cVa9OLXdPhSuW0GJLaI/+srZPgrX+0BVOLY/8T4ZPylc90CNXlE/\\nA0gQP8P12ECuM+U/Nt8UP1yPwkBoWL4/VxsRPz0K10B5Rna/trj/PgAA+EBw/ajAjyYQP4/C\\nBUFHTds/A7IJP4/CBUHMEzU/3GjxPmZmKkEpxz7AwsncPmZmQkEIqOu/AOPpPkjhKkFDOdJA\\nU3QFP7geBUGOb/dAlGAEP8P1uEB7QO1AXT0LPwAAiEA9uDFBaiwaP1yPukC1UidARZEZP9ej\\nXEHxam3BMbcSP+F6jkHbW9M/ux8WP3E9dkGOP8FAaZYQP4/CVUHhAXZA5CUUP+xRPEFlNGNA\\nYAIYPx+Fo0Cna4dAP58EPxSuj0Br5x5Aw9kJPylcl0DuiMBAlYUBP3E9gkAklAFBm9QMP4Xr\\noUCysJm+8SgMPwrXo0AGS0/ASaMoPx+Fi0CeqnBAZKMXP83MnECUq4U/SY0bP+F6pED9L9M/\\nVY8XPzMzu0Ce/kpAAYQEPylcO0H1ggRB+CDJPuF6IEGTcStBDgbuPsP14EB6cT9BuSAPP5qZ\\nwUCJFh9B3AgUPxSu90AJik/AE+f5PnsUjEH4+GPBpyEJPwrXm0H1EY/AiisOPxSugUGCHyRA\\nLGcKP83McEG0MeFAmEARP4XrPUELsABANFYNP3E96kBzog8+UV8RP6Rw3UDMjFhAvIAJP5qZ\\n2UAspiBAChEFPz0Kz0BjyphAI44WPylcv0AT43RADH4TP+F63EDEIpG/XOoJPzMz20B+ZbFA\\nyX4MP/YozEBKIe8+ZJcHP2ZmxkBCxINAzDMNPx+Fw0C7Ja9AmbgJP83MlECzEv4/MEH4PgrX\\nu0COQQNAw8wBPwAAoEDYgF1ADdoBP83MhEBAdnFAqwsBP5qZaUCa5gpAUdEJPzMzi0A6rmrA\\n16MJPxSun0Di3qs/dm0GPylcn0BfjcY/+5D7PnE9ukCk4oO/fUAEPxSu50CsTAW+Rc/pPlyP\\nmEFPc59A0hUYPwAAjkE6cGBA9w0XP6RwXUFIMsRAfwgjP5qZGUEq+OFAzS8oPwrX40AlZoZA\\nCFciP1K4AkFoQjVA3HoVP3E9GkGzZG9AwokXP3sUGkGNPphAjCsPP6RwIUE0lqk/1PMLP65H\\nJUEEGZA/ecUQP3E9ykBK9eQ/nwLmPlyP8kA0J0g/G9f1Ps3M9EAfAdA/7pfMPj0K/0DNayBA\\nlv4AP5qZ8UB3dKM+wR7oPkjhFkEm0EfAAaTtPuxRLEGDat4/LjbPPkjhSkHtG9m/6Um9PuF6\\neEFZ1YHAwCS1Ph+FgUFxMmy/1Vu2Pj0K90CN2SZBRZocP6Rw5UB4YZVAQFwSP9ej6EADdgBB\\n0ccRP7gezUBae+dAYrcaP65HuUBj6xRB9TUVPx+F20B/jrDAIoIRP1K43kDbrXnAXvYRP4/C\\n5UAH+vM/gpwQP65H2UBCmgJA0V4SPzMz40ByV3FALVASP3sU1kCHx4pApE30PhSu70Ci9jZA\\nlNP9PnE94kBxNZVAqr8JP7gexUA2HFxAvAMJPylcx0C0r+a+oVkPP5qZBUGQ34rApoUUP4/C\\nCUGpd75AeEwMP5qZ+UBXgExAW/4PPylc/0Ahmxa/NvoGP83MAEEJCZg/dToEP+xRwECCfotA\\nNKkJP+xR0ED8EXNAygYCP2ZmvkB84rdA8xkFP3E9mkB6Xd9Aie8HPwrXi0A+oWBA1/MBPx+F\\nu0DNjPHA99wBPxSu50Dz/6s/ARf4PlK4AkH5f1w/hQn4PqRwDUGR7CjA+7jyPpqZIUGKv4O/\\nRhPlPs3MlEGV7KhAKZACP3sUgkFn89NApsECP4XrVUEN5AdBUEENP3E9MkH+Ty1Bx6ASP/Yo\\nGEF6ZbJAjRgKP+F6QEG7k67AYNMPP3sUZkGZYslAi2gIP4XrWUEjyyhAxo78PilcX0Fg2q0/\\nYkz0Ph+FY0Gznic/Tav1PgAAwH8AAIBAAACAPwAAAAEAAMB/AACAQAAAgD8AAMB/AACAQAAA\\ngD8AAAABAADAfwAAgEAAAIA/AADAfwAAgEAAAIA/AAAAAQAAwH8AAIBAAACAP5qZaUDxam3B\\nAvfsPt3wlUDxam3BMMTsPu0Ut0Dxam3BX5HsPv042EDxam3BjV7sPg1d+UDxam3BvCvsPo5A\\nDUHxam3B6vjrPpbSHUHxam3BGMbrPp5kLkHxam3BR5PrPqb2PkHxam3BdWDrPq6IT0Hxam3B\\npC3rPrYaYEHxam3B0vrqPr6scEHxam3BAMjqPmOfgEHxam3BL5XqPmfoiEHxam3BXWLqPmsx\\nkUHxam3BjC/qPm96mUHxam3BuvzpPnPDoUHxam3B6cnpPncMqkHxam3BF5fpPntVskHxam3B\\nRWTpPn+eukHxam3BdDHpPoPnwkHxam3Bov7oPocwy0Hxam3B0cvoPot500Hxam3B/5joPo/C\\n20Hxam3BLWboPpqZaUCIxVrBOp7uPt3wlUCIxVrBaGvuPu0Ut0CIxVrBlzjuPv042ECIxVrB\\nxQXuPg1d+UCIxVrB9NLtPo5ADUGIxVrBIqDtPpbSHUGIxVrBUG3tPp5kLkGIxVrBfzrtPqb2\\nPkGIxVrBrQftPq6IT0GIxVrB3NTsPrYaYEGIxVrBCqLsPr6scEGIxVrBOW/sPmOfgEGIxVrB\\nZzzsPmfoiEGIxVrBlQnsPmsxkUGIxVrBxNbrPm96mUGIxVrB8qPrPnPDoUGIxVrBIXHrPncM\\nqkGIxVrBTz7rPntVskGIxVrBfQvrPn+eukGIxVrBrNjqPoPnwkGIxVrB2qXqPocwy0GIxVrB\\nCXPqPot500GIxVrBN0DqPo/C20GIxVrBZg3qPpqZaUAfIEjBckXwPt3wlUAfIEjBoBLwPu0U\\nt0AfIEjBz9/vPv042EAfIEjB/azvPg1d+UAfIEjBLHrvPo5ADUEfIEjBWkfvPpbSHUEfIEjB\\niBTvPp5kLkEfIEjBt+HuPqb2PkEfIEjB5a7uPq6IT0EfIEjBFHzuPrYaYEEfIEjBQknuPr6s\\ncEEfIEjBcRbuPmOfgEEfIEjBn+PtPmfoiEEfIEjBzbDtPmsxkUEfIEjB/H3tPm96mUEfIEjB\\nKkvtPnPDoUEfIEjBWRjtPncMqkEfIEjBh+XsPntVskEfIEjBtbLsPn+eukEfIEjB5H/sPoPn\\nwkEfIEjBEk3sPocwy0EfIEjBQRrsPot500EfIEjBb+frPo/C20EfIEjBnrTrPpqZaUC2ejXB\\nquzxPt3wlUC2ejXB2LnxPu0Ut0C2ejXBB4fxPv042EC2ejXBNVTxPg1d+UC2ejXBZCHxPo5A\\nDUG2ejXBku7wPpbSHUG2ejXBwbvwPp5kLkG2ejXB74jwPqb2PkG2ejXBHVbwPq6IT0G2ejXB\\nTCPwPrYaYEG2ejXBevDvPr6scEG2ejXBqb3vPmOfgEG2ejXB14rvPmfoiEG2ejXBBVjvPmsx\\nkUG2ejXBNCXvPm96mUG2ejXBYvLuPnPDoUG2ejXBkb/uPncMqkG2ejXBv4zuPntVskG2ejXB\\n7lnuPn+eukG2ejXBHCfuPoPnwkG2ejXBSvTtPocwy0G2ejXBecHtPot500G2ejXBp47tPo/C\\n20G2ejXB1lvtPpqZaUBN1SLB4pPzPt3wlUBN1SLBEGHzPu0Ut0BN1SLBPy7zPv042EBN1SLB\\nbfvyPg1d+UBN1SLBnMjyPo5ADUFN1SLBypXyPpbSHUFN1SLB+WLyPp5kLkFN1SLBJzDyPqb2\\nPkFN1SLBVf3xPq6IT0FN1SLBhMrxPrYaYEFN1SLBspfxPr6scEFN1SLB4WTxPmOfgEFN1SLB\\nDzLxPmfoiEFN1SLBPv/wPmsxkUFN1SLBbMzwPm96mUFN1SLBmpnwPnPDoUFN1SLByWbwPncM\\nqkFN1SLB9zPwPntVskFN1SLBJgHwPn+eukFN1SLBVM7vPoPnwkFN1SLBgpvvPocwy0FN1SLB\\nsWjvPot500FN1SLB3zXvPo/C20FN1SLBDgPvPpqZaUDlLxDBGjv1Pt3wlUDlLxDBSQj1Pu0U\\nt0DlLxDBd9X0Pv042EDlLxDBpaL0Pg1d+UDlLxDB1G/0Po5ADUHlLxDBAj30PpbSHUHlLxDB\\nMQr0Pp5kLkHlLxDBX9fzPqb2PkHlLxDBjaTzPq6IT0HlLxDBvHHzPrYaYEHlLxDB6j7zPr6s\\ncEHlLxDBGQzzPmOfgEHlLxDBR9nyPmfoiEHlLxDBdqbyPmsxkUHlLxDBpHPyPm96mUHlLxDB\\n0kDyPnPDoUHlLxDBAQ7yPncMqkHlLxDBL9vxPntVskHlLxDBXqjxPn+eukHlLxDBjHXxPoPn\\nwkHlLxDBu0LxPocwy0HlLxDB6Q/xPot500HlLxDBF93wPo/C20HlLxDBRqrwPpqZaUD4FPvA\\nUuL2Pt3wlUD4FPvAga/2Pu0Ut0D4FPvAr3z2Pv042ED4FPvA3Un2Pg1d+UD4FPvADBf2Po5A\\nDUH4FPvAOuT1PpbSHUH4FPvAabH1Pp5kLkH4FPvAl371Pqb2PkH4FPvAxkv1Pq6IT0H4FPvA\\n9Bj1PrYaYEH4FPvAIub0Pr6scEH4FPvAUbP0PmOfgEH4FPvAf4D0PmfoiEH4FPvArk30Pmsx\\nkUH4FPvA3Br0Pm96mUH4FPvACujzPnPDoUH4FPvAObXzPncMqkH4FPvAZ4LzPntVskH4FPvA\\nlk/zPn+eukH4FPvAxBzzPoPnwkH4FPvA8+nyPocwy0H4FPvAIbfyPot500H4FPvAT4TyPo/C\\n20H4FPvAflHyPpqZaUAmytXAion4Pt3wlUAmytXAuVb4Pu0Ut0AmytXA5yP4Pv042EAmytXA\\nFfH3Pg1d+UAmytXARL73Po5ADUEmytXAcov3PpbSHUEmytXAoVj3Pp5kLkEmytXAzyX3Pqb2\\nPkEmytXA/vL2Pq6IT0EmytXALMD2PrYaYEEmytXAWo32Pr6scEEmytXAiVr2PmOfgEEmytXA\\ntyf2PmfoiEEmytXA5vT1PmsxkUEmytXAFML1Pm96mUEmytXAQ4/1PnPDoUEmytXAcVz1PncM\\nqkEmytXAnyn1PntVskEmytXAzvb0Pn+eukEmytXA/MP0PoPnwkEmytXAK5H0Pocwy0EmytXA\\nWV70Pot500EmytXAhyv0Po/C20EmytXAtvjzPpqZaUBUf7DAwjD6Pt3wlUBUf7DA8f35Pu0U\\nt0BUf7DAH8v5Pv042EBUf7DATpj5Pg1d+UBUf7DAfGX5Po5ADUFUf7DAqjL5PpbSHUFUf7DA\\n2f/4Pp5kLkFUf7DAB834Pqb2PkFUf7DANpr4Pq6IT0FUf7DAZGf4PrYaYEFUf7DAkjT4Pr6s\\ncEFUf7DAwQH4PmOfgEFUf7DA7873PmfoiEFUf7DAHpz3PmsxkUFUf7DATGn3Pm96mUFUf7DA\\nezb3PnPDoUFUf7DAqQP3PncMqkFUf7DA19D2PntVskFUf7DABp72Pn+eukFUf7DANGv2PoPn\\nwkFUf7DAYzj2Pocwy0FUf7DAkQX2Pot500FUf7DAwNL1Po/C20FUf7DA7p/1PpqZaUCDNIvA\\n+tf7Pt3wlUCDNIvAKaX7Pu0Ut0CDNIvAV3L7Pv042ECDNIvAhj/7Pg1d+UCDNIvAtAz7Po5A\\nDUGDNIvA4tn6PpbSHUGDNIvAEaf6Pp5kLkGDNIvAP3T6Pqb2PkGDNIvAbkH6Pq6IT0GDNIvA\\nnA76PrYaYEGDNIvAy9v5Pr6scEGDNIvA+aj5PmOfgEGDNIvAJ3b5PmfoiEGDNIvAVkP5Pmsx\\nkUGDNIvAhBD5Pm96mUGDNIvAs934PnPDoUGDNIvA4ar4PncMqkGDNIvAD3j4PntVskGDNIvA\\nPkX4Pn+eukGDNIvAbBL4PoPnwkGDNIvAm9/3Pocwy0GDNIvAyaz3Pot500GDNIvA+Hn3Po/C\\n20GDNIvAJkf3PpqZaUBj00vAMn/9Pt3wlUBj00vAYUz9Pu0Ut0Bj00vAjxn9Pv042EBj00vA\\nvub8Pg1d+UBj00vA7LP8Po5ADUFj00vAGoH8PpbSHUFj00vASU78Pp5kLkFj00vAdxv8Pqb2\\nPkFj00vApuj7Pq6IT0Fj00vA1LX7PrYaYEFj00vAA4P7Pr6scEFj00vAMVD7PmOfgEFj00vA\\nXx37PmfoiEFj00vAjur6PmsxkUFj00vAvLf6Pm96mUFj00vA64T6PnPDoUFj00vAGVL6PncM\\nqkFj00vASB/6PntVskFj00vAduz5Pn+eukFj00vApLn5PoPnwkFj00vA04b5Pocwy0Fj00vA\\nAVT5Pot500Fj00vAMCH5Po/C20Fj00vAXu74PpqZaUC/PQHAaib/Pt3wlUC/PQHAmfP+Pu0U\\nt0C/PQHAx8D+Pv042EC/PQHA9o3+Pg1d+UC/PQHAJFv+Po5ADUG/PQHAUyj+PpbSHUG/PQHA\\ngfX9Pp5kLkG/PQHAr8L9Pqb2PkG/PQHA3o/9Pq6IT0G/PQHADF39PrYaYEG/PQHAOyr9Pr6s\\ncEG/PQHAaff8PmOfgEG/PQHAl8T8PmfoiEG/PQHAxpH8PmsxkUG/PQHA9F78Pm96mUG/PQHA\\nIyz8PnPDoUG/PQHAUfn7PncMqkG/PQHAgMb7PntVskG/PQHArpP7Pn+eukG/PQHA3GD7PoPn\\nwkG/PQHACy77Pocwy0G/PQHAOfv6Pot500G/PQHAaMj6Po/C20G/PQHAlpX6PpqZaUBxoFq/\\n0WYAP93wlUBxoFq/aE0AP+0Ut0BxoFq/ADQAP/042EBxoFq/lxoAPw1d+UBxoFq/LgEAP45A\\nDUFxoFq/i8//PpbSHUFxoFq/uZz/Pp5kLkFxoFq/52n/Pqb2PkFxoFq/Fjf/Pq6IT0FxoFq/\\nRAT/PrYaYEFxoFq/c9H+Pr6scEFxoFq/oZ7+PmOfgEFxoFq/0Gv+PmfoiEFxoFq//jj+Pmsx\\nkUFxoFq/LAb+Pm96mUFxoFq/W9P9PnPDoUFxoFq/iaD9PncMqkFxoFq/uG39PntVskFxoFq/\\n5jr9Pn+eukFxoFq/FAj9PoPnwkFxoFq/Q9X8Pocwy0FxoFq/caL8Pot500FxoFq/oG/8Po/C\\n20FxoFq/zjz8PpqZaUA4bJ8+bToBP93wlUA4bJ8+BCEBP+0Ut0A4bJ8+nAcBP/042EA4bJ8+\\nM+4APw1d+UA4bJ8+ytQAP45ADUE4bJ8+YbsAP5bSHUE4bJ8++aEAP55kLkE4bJ8+kIgAP6b2\\nPkE4bJ8+J28AP66IT0E4bJ8+vlUAP7YaYEE4bJ8+VTwAP76scEE4bJ8+7SIAP2OfgEE4bJ8+\\nhAkAP2foiEE4bJ8+NuD/PmsxkUE4bJ8+ZK3/Pm96mUE4bJ8+k3r/PnPDoUE4bJ8+wUf/PncM\\nqkE4bJ8+8BT/PntVskE4bJ8+HuL+Pn+eukE4bJ8+Ta/+PoPnwkE4bJ8+e3z+Pocwy0E4bJ8+\\nqUn+Pot500E4bJ8+2Bb+Po/C20E4bJ8+BuT9PpqZaUBUBr0/CQ4CP93wlUBUBr0/ofQBP+0U\\nt0BUBr0/ONsBP/042EBUBr0/z8EBPw1d+UBUBr0/ZqgBP45ADUFUBr0//Y4BP5bSHUFUBr0/\\nlXUBP55kLkFUBr0/LFwBP6b2PkFUBr0/w0IBP66IT0FUBr0/WikBP7YaYEFUBr0/8Q8BP76s\\ncEFUBr0/ifYAP2OfgEFUBr0/IN0AP2foiEFUBr0/t8MAP2sxkUFUBr0/TqoAP296mUFUBr0/\\n5ZAAP3PDoUFUBr0/fXcAP3cMqkFUBr0/FF4AP3tVskFUBr0/q0QAP3+eukFUBr0/QisAP4Pn\\nwkFUBr0/2REAP4cwy0FUBr0/4fD/Pot500FUBr0/EL7/Po/C20FUBr0/Pov/PpqZaUDNGClA\\npeECP93wlUDNGClAPcgCP+0Ut0DNGClA1K4CP/042EDNGClAa5UCPw1d+UDNGClAAnwCP45A\\nDUHNGClAmWICP5bSHUHNGClAMUkCP55kLkHNGClAyC8CP6b2PkHNGClAXxYCP66IT0HNGClA\\n9vwBP7YaYEHNGClAjeMBP76scEHNGClAJcoBP2OfgEHNGClAvLABP2foiEHNGClAU5cBP2sx\\nkUHNGClA6n0BP296mUHNGClAgWQBP3PDoUHNGClAGUsBP3cMqkHNGClAsDEBP3tVskHNGClA\\nRxgBP3+eukHNGClA3v4AP4PnwkHNGClAduUAP4cwy0HNGClADcwAP4t500HNGClApLIAP4/C\\n20HNGClAO5kAP5qZaUBxrnNAQbUDP93wlUBxrnNA2ZsDP+0Ut0BxrnNAcIIDP/042EBxrnNA\\nB2kDPw1d+UBxrnNAnk8DP45ADUFxrnNANTYDP5bSHUFxrnNAzRwDP55kLkFxrnNAZAMDP6b2\\nPkFxrnNA++kCP66IT0FxrnNAktACP7YaYEFxrnNAKbcCP76scEFxrnNAwZ0CP2OfgEFxrnNA\\nWIQCP2foiEFxrnNA72oCP2sxkUFxrnNAhlECP296mUFxrnNAHTgCP3PDoUFxrnNAtR4CP3cM\\nqkFxrnNATAUCP3tVskFxrnNA4+sBP3+eukFxrnNAetIBP4PnwkFxrnNAErkBP4cwy0FxrnNA\\nqZ8BP4t500FxrnNAQIYBP4/C20FxrnNA12wBP5qZaUAKIp9A3YgEP93wlUAKIp9AdW8EP+0U\\nt0AKIp9ADFYEP/042EAKIp9AozwEPw1d+UAKIp9AOiMEP45ADUEKIp9A0QkEP5bSHUEKIp9A\\nafADP55kLkEKIp9AANcDP6b2PkEKIp9Al70DP66IT0EKIp9ALqQDP7YaYEEKIp9AxYoDP76s\\ncEEKIp9AXXEDP2OfgEEKIp9A9FcDP2foiEEKIp9Aiz4DP2sxkUEKIp9AIiUDP296mUEKIp9A\\nugsDP3PDoUEKIp9AUfICP3cMqkEKIp9A6NgCP3tVskEKIp9Af78CP3+eukEKIp9AFqYCP4Pn\\nwkEKIp9ArowCP4cwy0EKIp9ARXMCP4t500EKIp9A3FkCP4/C20EKIp9Ac0ACP5qZaUDbbMRA\\neVwFP93wlUDbbMRAEUMFP+0Ut0DbbMRAqCkFP/042EDbbMRAPxAFPw1d+UDbbMRA1vYEP45A\\nDUHbbMRAbd0EP5bSHUHbbMRABcQEP55kLkHbbMRAnKoEP6b2PkHbbMRAM5EEP66IT0HbbMRA\\nyncEP7YaYEHbbMRAYl4EP76scEHbbMRA+UQEP2OfgEHbbMRAkCsEP2foiEHbbMRAJxIEP2sx\\nkUHbbMRAvvgDP296mUHbbMRAVt8DP3PDoUHbbMRA7cUDP3cMqkHbbMRAhKwDP3tVskHbbMRA\\nG5MDP3+eukHbbMRAsnkDP4PnwkHbbMRASmADP4cwy0HbbMRA4UYDP4t500HbbMRAeC0DP4/C\\n20HbbMRADxQDP5qZaUCtt+lAFTAGP93wlUCtt+lArRYGP+0Ut0Ctt+lARP0FP/042ECtt+lA\\n2+MFPw1d+UCtt+lAcsoFP45ADUGtt+lACbEFP5bSHUGtt+lAoZcFP55kLkGtt+lAOH4FP6b2\\nPkGtt+lAz2QFP66IT0Gtt+lAZksFP7YaYEGtt+lA/jEFP76scEGtt+lAlRgFP2OfgEGtt+lA\\nLP8EP2foiEGtt+lAw+UEP2sxkUGtt+lAWswEP296mUGtt+lA8rIEP3PDoUGtt+lAiZkEP3cM\\nqkGtt+lAIIAEP3tVskGtt+lAt2YEP3+eukGtt+lATk0EP4PnwkGtt+lA5jMEP4cwy0Gtt+lA\\nfRoEP4t500Gtt+lAFAEEP4/C20Gtt+lAq+cDP5qZaUA/gQdBsQMHP93wlUA/gQdBSeoGP+0U\\nt0A/gQdB4NAGP/042EA/gQdBd7cGPw1d+UA/gQdBDp4GP45ADUE/gQdBpoQGP5bSHUE/gQdB\\nPWsGP55kLkE/gQdB1FEGP6b2PkE/gQdBazgGP66IT0E/gQdBAh8GP7YaYEE/gQdBmgUGP76s\\ncEE/gQdBMewFP2OfgEE/gQdByNIFP2foiEE/gQdBX7kFP2sxkUE/gQdB9p8FP296mUE/gQdB\\njoYFP3PDoUE/gQdBJW0FP3cMqkE/gQdBvFMFP3tVskE/gQdBUzoFP3+eukE/gQdB6iAFP4Pn\\nwkE/gQdBggcFP4cwy0E/gQdBGe4EP4t500E/gQdBsNQEP4/C20E/gQdBR7sEP5qZaUCoJhpB\\nTdcHP93wlUCoJhpB5b0HP+0Ut0CoJhpBfKQHP/042ECoJhpBE4sHPw1d+UCoJhpBqnEHP45A\\nDUGoJhpBQlgHP5bSHUGoJhpB2T4HP55kLkGoJhpBcCUHP6b2PkGoJhpBBwwHP66IT0GoJhpB\\nnvIGP7YaYEGoJhpBNtkGP76scEGoJhpBzb8GP2OfgEGoJhpBZKYGP2foiEGoJhpB+4wGP2sx\\nkUGoJhpBknMGP296mUGoJhpBKloGP3PDoUGoJhpBwUAGP3cMqkGoJhpBWCcGP3tVskGoJhpB\\n7w0GP3+eukGoJhpBhvQFP4PnwkGoJhpBHtsFP4cwy0GoJhpBtcEFP4t500GoJhpBTKgFP4/C\\n20GoJhpB444FP5qZaUARzCxB6qoIP93wlUARzCxBgZEIP+0Ut0ARzCxBGHgIP/042EARzCxB\\nr14IPw1d+UARzCxBRkUIP45ADUERzCxB3isIP5bSHUERzCxBdRIIP55kLkERzCxBDPkHP6b2\\nPkERzCxBo98HP66IT0ERzCxBOsYHP7YaYEERzCxB0qwHP76scEERzCxBaZMHP2OfgEERzCxB\\nAHoHP2foiEERzCxBl2AHP2sxkUERzCxBLkcHP296mUERzCxBxi0HP3PDoUERzCxBXRQHP3cM\\nqkERzCxB9PoGP3tVskERzCxBi+EGP3+eukERzCxBI8gGP4PnwkERzCxBuq4GP4cwy0ERzCxB\\nUZUGP4t500ERzCxB6HsGP4/C20ERzCxBf2IGP5qZaUB6cT9Bhn4JP93wlUB6cT9BHWUJP+0U\\nt0B6cT9BtEsJP/042EB6cT9BSzIJPw1d+UB6cT9B4hgJP45ADUF6cT9Bev8IP5bSHUF6cT9B\\nEeYIP55kLkF6cT9BqMwIP6b2PkF6cT9BP7MIP66IT0F6cT9B1pkIP7YaYEF6cT9BboAIP76s\\ncEF6cT9BBWcIP2OfgEF6cT9BnE0IP2foiEF6cT9BMzQIP2sxkUF6cT9ByhoIP296mUF6cT9B\\nYgEIP3PDoUF6cT9B+ecHP3cMqkF6cT9BkM4HP3tVskF6cT9BJ7UHP3+eukF6cT9Bv5sHP4Pn\\nwkF6cT9BVoIHP4cwy0F6cT9B7WgHP4t500F6cT9BhE8HP4/C20F6cT9BGzYHP+HgYD3t7Gw+\\n1dTUPrOysj7VXoVAPBhkwTWx7T7lgqZAPBhkwWR+7T71psdAPBhkwZJL7T4Fy+hAPBhkwcAY\\n7T6K9wRBPBhkwe7l7D6SiRVBPBhkwR2z7D6aGyZBPBhkwUyA7D6irTZBPBhkwXpN7D6qP0dB\\nPBhkwaga7D6y0VdBPBhkwdbn6z66Y2hBPBhkwQW16z7C9XhBPBhkwTSC6z7lw4RBPBhkwWJP\\n6z7pDI1BPBhkwZAc6z7tVZVBPBhkwb7p6j7xnp1BPBhkwe626j7156VBPBhkwRyE6j75MK5B\\nPBhkwUpR6j79ebZBPBhkwXge6j4Bw75BPBhkwabr6T4FDMdBPBhkwda46T4JVc9BPBhkwQSG\\n6T4NntdBPBhkwTJT6T7VXoVA1HJRwW1Y7z7lgqZA1HJRwZwl7z71psdA1HJRwcry7j4Fy+hA\\n1HJRwfi/7j6K9wRB1HJRwSaN7j6SiRVB1HJRwVVa7j6aGyZB1HJRwYQn7j6irTZB1HJRwbL0\\n7T6qP0dB1HJRweDB7T6y0VdB1HJRwQ6P7T66Y2hB1HJRwT5c7T7C9XhB1HJRwWwp7T7lw4RB\\n1HJRwZr27D7pDI1B1HJRwcjD7D7tVZVB1HJRwfaQ7D7xnp1B1HJRwSZe7D7156VB1HJRwVQr\\n7D75MK5B1HJRwYL46z79ebZB1HJRwbDF6z4Bw75B1HJRwd6S6z4FDMdB1HJRwQ5g6z4JVc9B\\n1HJRwTwt6z4NntdB1HJRwWr66j7VXoVAas0+waX/8D7lgqZAas0+wdTM8D71psdAas0+wQKa\\n8D4Fy+hAas0+wTBn8D6K9wRBas0+wV408D6SiRVBas0+wY0B8D6aGyZBas0+wbzO7z6irTZB\\nas0+weqb7z6qP0dBas0+wRhp7z6y0VdBas0+wUY27z66Y2hBas0+wXYD7z7C9XhBas0+waTQ\\n7j7lw4RBas0+wdKd7j7pDI1Bas0+wQBr7j7tVZVBas0+wS447j7xnp1Bas0+wV4F7j7156VB\\nas0+wYzS7T75MK5Bas0+wbqf7T79ebZBas0+wels7T4Bw75Bas0+wRY67T4FDMdBas0+wUYH\\n7T4JVc9Bas0+wXTU7D4NntdBas0+waKh7D7VXoVAASgswd2m8j7lgqZAASgswQx08j71psdA\\nASgswTpB8j4Fy+hAASgswWgO8j6K9wRBASgswZbb8T6SiRVBASgswcao8T6aGyZBASgswfR1\\n8T6irTZBASgswSJD8T6qP0dBASgswVAQ8T6y0VdBASgswX7d8D66Y2hBASgswa6q8D7C9XhB\\nASgswdx38D7lw4RBASgswQpF8D7pDI1BASgswTkS8D7tVZVBASgswWbf7z7xnp1BASgswZas\\n7z7156VBASgswcR57z75MK5BASgswfJG7z79ebZBASgswSEU7z4Bw75BASgswU7h7j4FDMdB\\nASgswX6u7j4JVc9BASgswax77j4NntdBASgswdpI7j7VXoVAmYIZwRVO9D7lgqZAmYIZwUQb\\n9D71psdAmYIZwXLo8z4Fy+hAmYIZwaC18z6K9wRBmYIZwc6C8z6SiRVBmYIZwf5P8z6aGyZB\\nmYIZwSwd8z6irTZBmYIZwVrq8j6qP0dBmYIZwYi38j6y0VdBmYIZwbaE8j66Y2hBmYIZweZR\\n8j7C9XhBmYIZwRQf8j7lw4RBmYIZwULs8T7pDI1BmYIZwXG58T7tVZVBmYIZwZ6G8T7xnp1B\\nmYIZwc5T8T7156VBmYIZwfwg8T75MK5BmYIZwSru8D79ebZBmYIZwVm78D4Bw75BmYIZwYeI\\n8D4FDMdBmYIZwbZV8D4JVc9BmYIZweQi8D4NntdBmYIZwRLw7z7VXoVAMN0GwU719T7lgqZA\\nMN0GwXzC9T71psdAMN0GwaqP9T4Fy+hAMN0Gwdhc9T6K9wRBMN0GwQYq9T6SiRVBMN0GwTb3\\n9D6aGyZBMN0GwWTE9D6irTZBMN0GwZKR9D6qP0dBMN0GwcFe9D6y0VdBMN0Gwe4r9D66Y2hB\\nMN0GwR758z7C9XhBMN0GwUzG8z7lw4RBMN0GwXqT8z7pDI1BMN0Gwalg8z7tVZVBMN0GwdYt\\n8z7xnp1BMN0GwQb78j7156VBMN0GwTTI8j75MK5BMN0GwWKV8j79ebZBMN0GwZFi8j4Bw75B\\nMN0GwcAv8j4FDMdBMN0Gwe788T4JVc9BMN0GwRzK8T4NntdBMN0GwUqX8T7VXoVAkG/owIac\\n9z7lgqZAkG/owLRp9z71psdAkG/owOI29z4Fy+hAkG/owBAE9z6K9wRBkG/owD7R9j6SiRVB\\nkG/owG6e9j6aGyZBkG/owJxr9j6irTZBkG/owMo49j6qP0dBkG/owPkF9j6y0VdBkG/owCbT\\n9T66Y2hBkG/owFag9T7C9XhBkG/owIRt9T7lw4RBkG/owLI69T7pDI1BkG/owOEH9T7tVZVB\\nkG/owA/V9D7xnp1BkG/owD6i9D7156VBkG/owGxv9D75MK5BkG/owJo89D79ebZBkG/owMkJ\\n9D4Bw75BkG/owPjW8z4FDMdBkG/owCak8z4JVc9BkG/owFRx8z4NntdBkG/owII+8z7VXoVA\\nvSTDwL5D+T7lgqZAvSTDwOwQ+T71psdAvSTDwBre+D4Fy+hAvSTDwEmr+D6K9wRBvSTDwHZ4\\n+D6SiRVBvSTDwKZF+D6aGyZBvSTDwNQS+D6irTZBvSTDwALg9z6qP0dBvSTDwDGt9z6y0VdB\\nvSTDwF569z66Y2hBvSTDwI5H9z7C9XhBvSTDwLwU9z7lw4RBvSTDwOrh9j7pDI1BvSTDwBmv\\n9j7tVZVBvSTDwEh89j7xnp1BvSTDwHZJ9j7156VBvSTDwKQW9j75MK5BvSTDwNLj9T79ebZB\\nvSTDwAGx9T4Bw75BvSTDwDB+9T4FDMdBvSTDwF5L9T4JVc9BvSTDwIwY9T4NntdBvSTDwLrl\\n9D7VXoVA7NmdwPbq+j7lgqZA7NmdwCS4+j71psdA7NmdwFKF+j4Fy+hA7NmdwIFS+j6K9wRB\\n7NmdwK4f+j6SiRVB7NmdwN7s+T6aGyZB7NmdwAy6+T6irTZB7NmdwDqH+T6qP0dB7NmdwGlU\\n+T6y0VdB7NmdwJch+T66Y2hB7NmdwMbu+D7C9XhB7NmdwPS7+D7lw4RB7NmdwCKJ+D7pDI1B\\n7NmdwFFW+D7tVZVB7NmdwIAj+D7xnp1B7NmdwK7w9z7156VB7NmdwNy99z75MK5B7NmdwAqL\\n9z79ebZB7NmdwDlY9z4Bw75B7NmdwGgl9z4FDMdB7NmdwJby9j4JVc9B7NmdwMS/9j4NntdB\\n7NmdwPSM9j7VXoVANR5xwC6S/D7lgqZANR5xwFxf/D71psdANR5xwIos/D4Fy+hANR5xwLn5\\n+z6K9wRBNR5xwObG+z6SiRVBNR5xwBaU+z6aGyZBNR5xwERh+z6irTZBNR5xwHIu+z6qP0dB\\nNR5xwKH7+j6y0VdBNR5xwNDI+j66Y2hBNR5xwP6V+j7C9XhBNR5xwCxj+j7lw4RBNR5xwFow\\n+j7pDI1BNR5xwIn9+T7tVZVBNR5xwLjK+T7xnp1BNR5xwOaX+T7156VBNR5xwBRl+T75MK5B\\nNR5xwEIy+T79ebZBNR5xwHH/+D4Bw75BNR5xwKDM+D4FDMdBNR5xwM6Z+D4JVc9BNR5xwPxm\\n+D4NntdBNR5xwCw0+D7VXoVAkYgmwGY5/j7lgqZAkYgmwJQG/j71psdAkYgmwMLT/T4Fy+hA\\nkYgmwPGg/T6K9wRBkYgmwB9u/T6SiRVBkYgmwE47/T6aGyZBkYgmwHwI/T6irTZBkYgmwKrV\\n/D6qP0dBkYgmwNmi/D6y0VdBkYgmwAhw/D66Y2hBkYgmwDY9/D7C9XhBkYgmwGQK/D7lw4RB\\nkYgmwJLX+z7pDI1BkYgmwMGk+z7tVZVBkYgmwPBx+z7xnp1BkYgmwB4/+z7156VBkYgmwEwM\\n+z75MK5BkYgmwHzZ+j79ebZBkYgmwKmm+j4Bw75BkYgmwNhz+j4FDMdBkYgmwAZB+j4JVc9B\\nkYgmwDQO+j4NntdBkYgmwGTb+T7VXoVA2+W3v57g/z7lgqZA2+W3v8yt/z71psdA2+W3v/p6\\n/z4Fy+hA2+W3vylI/z6K9wRB2+W3v1gV/z6SiRVB2+W3v4bi/j6aGyZB2+W3v7Sv/j6irTZB\\n2+W3v+J8/j6qP0dB2+W3vxFK/j6y0VdB2+W3v0AX/j66Y2hB2+W3v27k/T7C9XhB2+W3v5yx\\n/T7lw4RB2+W3v8p+/T7pDI1B2+W3v/lL/T7tVZVB2+W3vygZ/T7xnp1B2+W3v1bm/D7156VB\\n2+W3v4Sz/D75MK5B2+W3v7SA/D79ebZB2+W3v+FN/D4Bw75B2+W3vxAb/D4FDMdB2+W3vz7o\\n+z4JVc9B2+W3v2y1+z4NntdB2+W3v5yC+z7VXoVAVeqKvurDAD/lgqZAVeqKvoKqAD/1psdA\\nVeqKvhqRAD8Fy+hAVeqKvrB3AD+K9wRBVeqKvkheAD+SiRVBVeqKvt9EAD+aGyZBVeqKvnYr\\nAD+irTZBVeqKvg0SAD+qP0dBVeqKvknx/z6y0VdBVeqKvni+/z66Y2hBVeqKvqaL/z7C9XhB\\nVeqKvtRY/z7lw4RBVeqKvgQm/z7pDI1BVeqKvjHz/j7tVZVBVeqKvmDA/j7xnp1BVeqKvo6N\\n/j7156VBVeqKvrxa/j75MK5BVeqKvuwn/j79ebZBVeqKvhn1/T4Bw75BVeqKvkjC/T4FDMdB\\nVeqKvnaP/T4JVc9BVeqKvqRc/T4NntdBVeqKvtQp/T7VXoVAYuFkP4aXAT/lgqZAYuFkPx5+\\nAT/1psdAYuFkP7ZkAT8Fy+hAYuFkP0xLAT+K9wRBYuFkP+QxAT+SiRVBYuFkP3sYAT+aGyZB\\nYuFkPxL/AD+irTZBYuFkP6rlAD+qP0dBYuFkP0DMAD+y0VdBYuFkP9iyAD+6Y2hBYuFkP2+Z\\nAD/C9XhBYuFkPwaAAD/lw4RBYuFkP55mAD/pDI1BYuFkPzRNAD/tVZVBYuFkP8wzAD/xnp1B\\nYuFkP2MaAD/156VBYuFkP/oAAD/5MK5BYuFkPyTP/z79ebZBYuFkP1Gc/z4Bw75BYuFkP4Bp\\n/z4FDMdBYuFkP642/z4JVc9BYuFkP9wD/z4NntdBYuFkPwzR/j7VXoVA+80DQCNrAj/lgqZA\\n+80DQLpRAj/1psdA+80DQFI4Aj8Fy+hA+80DQOgeAj+K9wRB+80DQIAFAj+SiRVB+80DQBfs\\nAT+aGyZB+80DQK7SAT+irTZB+80DQEa5AT+qP0dB+80DQNyfAT+y0VdB+80DQHSGAT+6Y2hB\\n+80DQAttAT/C9XhB+80DQKJTAT/lw4RB+80DQDo6AT/pDI1B+80DQNAgAT/tVZVB+80DQGgH\\nAT/xnp1B+80DQP/tAD/156VB+80DQJbUAD/5MK5B+80DQC67AD/9ebZB+80DQMShAD8Bw75B\\n+80DQFyIAD8FDMdB+80DQPNuAD8JVc9B+80DQIpVAD8NntdB+80DQCI8AD/VXoVAn2NOQL8+\\nAz/lgqZAn2NOQFYlAz/1psdAn2NOQO4LAz8Fy+hAn2NOQITyAj+K9wRBn2NOQBzZAj+SiRVB\\nn2NOQLO/Aj+aGyZBn2NOQEqmAj+irTZBn2NOQOKMAj+qP0dBn2NOQHhzAj+y0VdBn2NOQBBa\\nAj+6Y2hBn2NOQKdAAj/C9XhBn2NOQD4nAj/lw4RBn2NOQNYNAj/pDI1Bn2NOQGz0AT/tVZVB\\nn2NOQATbAT/xnp1Bn2NOQJvBAT/156VBn2NOQDKoAT/5MK5Bn2NOQMqOAT/9ebZBn2NOQGB1\\nAT8Bw75Bn2NOQPhbAT8FDMdBn2NOQJBCAT8JVc9Bn2NOQCYpAT8NntdBn2NOQL4PAT/VXoVA\\nonyMQFsSBD/lgqZAonyMQPL4Az/1psdAonyMQIrfAz8Fy+hAonyMQCDGAz+K9wRBonyMQLis\\nAz+SiRVBonyMQE+TAz+aGyZBonyMQOZ5Az+irTZBonyMQH5gAz+qP0dBonyMQBRHAz+y0VdB\\nonyMQKwtAz+6Y2hBonyMQEMUAz/C9XhBonyMQNr6Aj/lw4RBonyMQHLhAj/pDI1BonyMQAjI\\nAj/tVZVBonyMQKCuAj/xnp1BonyMQDeVAj/156VBonyMQM57Aj/5MK5BonyMQGZiAj/9ebZB\\nonyMQPxIAj8Bw75BonyMQJQvAj8FDMdBonyMQCwWAj8JVc9BonyMQML8AT8NntdBonyMQFrj\\nAT/VXoVAc8exQPflBD/lgqZAc8exQI7MBD/1psdAc8exQCazBD8Fy+hAc8exQLyZBD+K9wRB\\nc8exQFSABD+SiRVBc8exQOtmBD+aGyZBc8exQIJNBD+irTZBc8exQBo0BD+qP0dBc8exQLAa\\nBD+y0VdBc8exQEgBBD+6Y2hBc8exQN/nAz/C9XhBc8exQHbOAz/lw4RBc8exQA61Az/pDI1B\\nc8exQKSbAz/tVZVBc8exQDyCAz/xnp1Bc8exQNRoAz/156VBc8exQGpPAz/5MK5Bc8exQAI2\\nAz/9ebZBc8exQJgcAz8Bw75Bc8exQDADAz8FDMdBc8exQMjpAj8JVc9Bc8exQF7QAj8NntdB\\nc8exQPa2Aj/VXoVARBLXQJO5BT/lgqZARBLXQCqgBT/1psdARBLXQMKGBT8Fy+hARBLXQFht\\nBT+K9wRBRBLXQPBTBT+SiRVBRBLXQIc6BT+aGyZBRBLXQB4hBT+irTZBRBLXQLYHBT+qP0dB\\nRBLXQEzuBD+y0VdBRBLXQOTUBD+6Y2hBRBLXQHy7BD/C9XhBRBLXQBKiBD/lw4RBRBLXQKqI\\nBD/pDI1BRBLXQEBvBD/tVZVBRBLXQNhVBD/xnp1BRBLXQHA8BD/156VBRBLXQAYjBD/5MK5B\\nRBLXQJ4JBD/9ebZBRBLXQDTwAz8Bw75BRBLXQMzWAz8FDMdBRBLXQGS9Az8JVc9BRBLXQPqj\\nAz8NntdBRBLXQJKKAz/VXoVAFl38QC+NBj/lgqZAFl38QMZzBj/1psdAFl38QF5aBj8Fy+hA\\nFl38QPRABj+K9wRBFl38QIwnBj+SiRVBFl38QCMOBj+aGyZBFl38QLr0BT+irTZBFl38QFLb\\nBT+qP0dBFl38QOjBBT+y0VdBFl38QICoBT+6Y2hBFl38QBiPBT/C9XhBFl38QK51BT/lw4RB\\nFl38QEZcBT/pDI1BFl38QNxCBT/tVZVBFl38QHQpBT/xnp1BFl38QAwQBT/156VBFl38QKL2\\nBD/5MK5BFl38QDrdBD/9ebZBFl38QNDDBD8Bw75BFl38QGiqBD8FDMdBFl38QACRBD8JVc9B\\nFl38QJZ3BD8NntdBFl38QC5eBD/VXoVA9NMQQctgBz/lgqZA9NMQQWJHBz/1psdA9NMQQfot\\nBz8Fy+hA9NMQQZAUBz+K9wRB9NMQQSj7Bj+SiRVB9NMQQcDhBj+aGyZB9NMQQVbIBj+irTZB\\n9NMQQe6uBj+qP0dB9NMQQYSVBj+y0VdB9NMQQRx8Bj+6Y2hB9NMQQbRiBj/C9XhB9NMQQUpJ\\nBj/lw4RB9NMQQeIvBj/pDI1B9NMQQXgWBj/tVZVB9NMQQRD9BT/xnp1B9NMQQajjBT/156VB\\n9NMQQT7KBT/5MK5B9NMQQdawBT/9ebZB9NMQQWyXBT8Bw75B9NMQQQR+BT8FDMdB9NMQQZxk\\nBT8JVc9B9NMQQTJLBT8NntdB9NMQQcoxBT/VXoVAXHkjQWc0CD/lgqZAXHkjQf4aCD/1psdA\\nXHkjQZYBCD8Fy+hAXHkjQSzoBz+K9wRBXHkjQcTOBz+SiRVBXHkjQVy1Bz+aGyZBXHkjQfKb\\nBz+irTZBXHkjQYqCBz+qP0dBXHkjQSBpBz+y0VdBXHkjQbhPBz+6Y2hBXHkjQVA2Bz/C9XhB\\nXHkjQeYcBz/lw4RBXHkjQX4DBz/pDI1BXHkjQRTqBj/tVZVBXHkjQazQBj/xnp1BXHkjQUS3\\nBj/156VBXHkjQdqdBj/5MK5BXHkjQXKEBj/9ebZBXHkjQQlrBj8Bw75BXHkjQaBRBj8FDMdB\\nXHkjQTg4Bj8JVc9BXHkjQc4eBj8NntdBXHkjQWYFBj/VXoVAxh42QQQICT/lgqZAxh42QZru\\nCD/1psdAxh42QTLVCD8Fy+hAxh42Qci7CD+K9wRBxh42QWCiCD+SiRVBxh42QfiICD+aGyZB\\nxh42QY5vCD+irTZBxh42QSZWCD+qP0dBxh42Qbw8CD+y0VdBxh42QVQjCD+6Y2hBxh42QewJ\\nCD/C9XhBxh42QYLwBz/lw4RBxh42QRrXBz/pDI1Bxh42QbC9Bz/tVZVBxh42QUikBz/xnp1B\\nxh42QeCKBz/156VBxh42QXZxBz/5MK5Bxh42QQ5YBz/9ebZBxh42QaU+Bz8Bw75Bxh42QTwl\\nBz8FDMdBxh42QdQLBz8JVc9Bxh42QWryBj8NntdBxh42QQLZBj/2KPxARiW8PwKlAT/2KPxA\\nRiW8PyqNmT4K16NABktPwGQj/T4K16NABktPwEmjKD8AAJhATfglQMm9Aj8AAJhATfglQOkT\\nuT7sUahARj8RQHt2Aj/sUahARj8RQDn9vj4pXDtB9YIEQfkbBj8pXDtB9YIEQfggyT4fhZtA\\n+Y1uQAaJAz8fhZtA+Y1uQDtJxz5I4apAQu/QPA7dAD9I4apAQu/QPHazxT5mZq5AWjmkwLlj\\n+j5mZq5AWjmkwM0PGj+ioSE/AAAAAAAAAAAAAIA/9ij8QEYlvD+Xa84+CtejQAZLT8B+mhM/\\nAACYQE34JUC+R98+7FGoQEY/EUAY9eE+KVw7QfWCBEF1rOo+H4WbQPmNbkCkLec+SOGqQELv\\n0DzJtuM+ZmauQFo5pMDVoAs/9ij8QEYlvD8qjZk+CtejQAZLT8BJoyg/AACYQE34JUDpE7k+\\n7FGoQEY/EUA5/b4+KVw7QfWCBEH4IMk+H4WbQPmNbkA7Scc+SOGqQELv0Dx2s8U+ZmauQFo5\\npMDNDxo/oqEhPwAAAAAAAAAAAACAP/Yo/EBGJbw/Ko2ZPgrXo0AGS0/ASaMoPwAAmEBN+CVA\\n6RO5PuxRqEBGPxFAOf2+PilcO0H1ggRB+CDJPh+Fm0D5jW5AO0nHPkjhqkBC79A8drPFPmZm\\nrkBaOaTAzQ8aPwEBAQEAAAAAAACgQAAAwH8AAMB/AAAgQQAAwH8AAMB/AABwQQAAwH8AAMB/\\nAACgQQAAwH8AAMB/AADIQQAAwH8AAMB/AADAfwAAIMEAAMB/AADAfwAAoMAAAMB/AADAfwAA\\nAAAAAMB/AADAfwAAoEAAAMB/AADAfwAAIEEAAMB/AADAfwAAwH+amZk+AADAfwAAwH/NzMw+\\nAADAfwAAwH8AAAA/AADAfwAAwH+amRk/AAAAAQ==\"}]},\"context\":{\"shiny\":false,\"rmarkdown\":null},\"vertexShader\":\"#line 2 1\\n// File 1 is the vertex shader\\n#ifdef GL_ES\\n#ifdef GL_FRAGMENT_PRECISION_HIGH\\nprecision highp float;\\n#else\\nprecision mediump float;\\n#endif\\n#endif\\n\\nattribute vec3 aPos;\\nattribute vec4 aCol;\\nuniform mat4 mvMatrix;\\nuniform mat4 prMatrix;\\nvarying vec4 vCol;\\nvarying vec4 vPosition;\\n\\n#ifdef NEEDS_VNORMAL\\nattribute vec3 aNorm;\\nuniform mat4 normMatrix;\\nvarying vec4 vNormal;\\n#endif\\n\\n#if defined(HAS_TEXTURE) || defined (IS_TEXT)\\nattribute vec2 aTexcoord;\\nvarying vec2 vTexcoord;\\n#endif\\n\\n#ifdef FIXED_SIZE\\nuniform vec3 textScale;\\n#endif\\n\\n#ifdef FIXED_QUADS\\nattribute vec3 aOfs;\\n#endif\\n\\n#ifdef IS_TWOSIDED\\n#ifdef HAS_NORMALS\\nvarying float normz;\\nuniform mat4 invPrMatrix;\\n#else\\nattribute vec3 aPos1;\\nattribute vec3 aPos2;\\nvarying float normz;\\n#endif\\n#endif // IS_TWOSIDED\\n\\n#ifdef FAT_LINES\\nattribute vec3 aNext;\\nattribute vec2 aPoint;\\nvarying vec2 vPoint;\\nvarying float vLength;\\nuniform float uAspect;\\nuniform float uLwd;\\n#endif\\n\\n#ifdef USE_ENVMAP\\nvarying vec3 vReflection;\\n#endif\\n\\nvoid main(void) {\\n  \\n#ifndef IS_BRUSH\\n#if defined(NCLIPPLANES) || !defined(FIXED_QUADS) || defined(HAS_FOG) || defined(USE_ENVMAP)\\n  vPosition = mvMatrix * vec4(aPos, 1.);\\n#endif\\n  \\n#ifndef FIXED_QUADS\\n  gl_Position = prMatrix * vPosition;\\n#endif\\n#endif // !IS_BRUSH\\n  \\n#ifdef IS_POINTS\\n  gl_PointSize = POINTSIZE;\\n#endif\\n  \\n  vCol = aCol;\\n  \\n// USE_ENVMAP implies NEEDS_VNORMAL\\n\\n#ifdef NEEDS_VNORMAL\\n  vNormal = normMatrix * vec4(-aNorm, dot(aNorm, aPos));\\n#endif\\n\\n#ifdef USE_ENVMAP\\n  vReflection = normalize(reflect(vPosition.xyz/vPosition.w, \\n                        normalize(vNormal.xyz/vNormal.w)));\\n#endif\\n  \\n#ifdef IS_TWOSIDED\\n#ifdef HAS_NORMALS\\n  /* normz should be calculated *after* projection */\\n  normz = (invPrMatrix*vNormal).z;\\n#else\\n  vec4 pos1 = prMatrix*(mvMatrix*vec4(aPos1, 1.));\\n  pos1 = pos1/pos1.w - gl_Position/gl_Position.w;\\n  vec4 pos2 = prMatrix*(mvMatrix*vec4(aPos2, 1.));\\n  pos2 = pos2/pos2.w - gl_Position/gl_Position.w;\\n  normz = pos1.x*pos2.y - pos1.y*pos2.x;\\n#endif\\n#endif // IS_TWOSIDED\\n  \\n#ifdef NEEDS_VNORMAL\\n  vNormal = vec4(normalize(vNormal.xyz), 1);\\n#endif\\n  \\n#if defined(HAS_TEXTURE) || defined(IS_TEXT)\\n  vTexcoord = aTexcoord;\\n#endif\\n  \\n#if defined(FIXED_SIZE) && !defined(ROTATING)\\n  vec4 pos = prMatrix * mvMatrix * vec4(aPos, 1.);\\n  pos = pos/pos.w;\\n  gl_Position = pos + vec4(aOfs*textScale, 0.);\\n#endif\\n  \\n#if defined(IS_SPRITES) && !defined(FIXED_SIZE)\\n  vec4 pos = mvMatrix * vec4(aPos, 1.);\\n  pos = pos/pos.w + vec4(aOfs,  0.);\\n  gl_Position = prMatrix*pos;\\n#endif\\n  \\n#ifdef FAT_LINES\\n  /* This code was inspired by Matt Deslauriers' code in \\n   https://mattdesl.svbtle.com/drawing-lines-is-hard */\\n  vec2 aspectVec = vec2(uAspect, 1.0);\\n  mat4 projViewModel = prMatrix * mvMatrix;\\n  vec4 currentProjected = projViewModel * vec4(aPos, 1.0);\\n  currentProjected = currentProjected/currentProjected.w;\\n  vec4 nextProjected = projViewModel * vec4(aNext, 1.0);\\n  vec2 currentScreen = currentProjected.xy * aspectVec;\\n  vec2 nextScreen = (nextProjected.xy / nextProjected.w) * aspectVec;\\n  float len = uLwd;\\n  vec2 dir = vec2(1.0, 0.0);\\n  vPoint = aPoint;\\n  vLength = length(nextScreen - currentScreen)/2.0;\\n  vLength = vLength/(vLength + len);\\n  if (vLength > 0.0) {\\n    dir = normalize(nextScreen - currentScreen);\\n  }\\n  vec2 normal = vec2(-dir.y, dir.x);\\n  dir.x /= uAspect;\\n  normal.x /= uAspect;\\n  vec4 offset = vec4(len*(normal*aPoint.x*aPoint.y - dir), 0.0, 0.0);\\n  gl_Position = currentProjected + offset;\\n#endif\\n  \\n#ifdef IS_BRUSH\\n  gl_Position = vec4(aPos, 1.);\\n#endif\\n}\",\"fragmentShader\":\"#line 2 2\\n// File 2 is the fragment shader\\n#ifdef GL_ES\\n#ifdef GL_FRAGMENT_PRECISION_HIGH\\nprecision highp float;\\n#else\\nprecision mediump float;\\n#endif\\n#endif\\nvarying vec4 vCol; // carries alpha\\nvarying vec4 vPosition;\\n#if defined(HAS_TEXTURE) || defined (IS_TEXT)\\nvarying vec2 vTexcoord;\\nuniform sampler2D uSampler;\\n#endif\\n\\n#ifdef HAS_FOG\\nuniform int uFogMode;\\nuniform vec3 uFogColor;\\nuniform vec4 uFogParms;\\n#endif\\n\\n#if defined(IS_LIT) && !defined(FIXED_QUADS)\\nvarying vec4 vNormal;\\n#endif\\n\\n#if NCLIPPLANES > 0\\nuniform vec4 vClipplane[NCLIPPLANES];\\n#endif\\n\\n#if NLIGHTS > 0\\nuniform mat4 mvMatrix;\\n#endif\\n\\n#ifdef IS_LIT\\nuniform vec3 emission;\\nuniform float shininess;\\n#if NLIGHTS > 0\\nuniform vec3 ambient[NLIGHTS];\\nuniform vec3 specular[NLIGHTS]; // light*material\\nuniform vec3 diffuse[NLIGHTS];\\nuniform vec3 lightDir[NLIGHTS];\\nuniform bool viewpoint[NLIGHTS];\\nuniform bool finite[NLIGHTS];\\n#endif\\n#endif // IS_LIT\\n\\n#ifdef IS_TWOSIDED\\nuniform bool front;\\nvarying float normz;\\n#endif\\n\\n#ifdef FAT_LINES\\nvarying vec2 vPoint;\\nvarying float vLength;\\n#endif\\n\\n#ifdef USE_ENVMAP\\nvarying vec3 vReflection;\\n#endif\\n\\nvoid main(void) {\\n  vec4 fragColor;\\n#ifdef FAT_LINES\\n  vec2 point = vPoint;\\n  bool neg = point.y < 0.0;\\n  point.y = neg ? (point.y + vLength)/(1.0 - vLength) :\\n                 -(point.y - vLength)/(1.0 - vLength);\\n#if defined(IS_TRANSPARENT) && defined(IS_LINESTRIP)\\n  if (neg && length(point) <= 1.0) discard;\\n#endif\\n  point.y = min(point.y, 0.0);\\n  if (length(point) > 1.0) discard;\\n#endif // FAT_LINES\\n  \\n#ifdef ROUND_POINTS\\n  vec2 coord = gl_PointCoord - vec2(0.5);\\n  if (length(coord) > 0.5) discard;\\n#endif\\n  \\n#if NCLIPPLANES > 0\\n  for (int i = 0; i < NCLIPPLANES; i++)\\n    if (dot(vPosition, vClipplane[i]) < 0.0) discard;\\n#endif\\n    \\n#ifdef FIXED_QUADS\\n    vec3 n = vec3(0., 0., 1.);\\n#elif defined(IS_LIT)\\n    vec3 n = normalize(vNormal.xyz);\\n#endif\\n    \\n#ifdef IS_TWOSIDED\\n    if ((normz <= 0.) != front) discard;\\n#endif\\n\\n#ifdef IS_LIT\\n    vec3 eye = normalize(-vPosition.xyz/vPosition.w);\\n    vec3 lightdir;\\n    vec4 colDiff;\\n    vec3 halfVec;\\n    vec4 lighteffect = vec4(emission, 0.);\\n    vec3 col;\\n    float nDotL;\\n#ifdef FIXED_QUADS\\n    n = -faceforward(n, n, eye);\\n#endif\\n    \\n#if NLIGHTS > 0\\n    // Simulate two-sided lighting\\n    if (n.z < 0.0)\\n      n = -n;\\n    for (int i=0;i<NLIGHTS;i++) {\\n      colDiff = vec4(vCol.rgb * diffuse[i], vCol.a);\\n      lightdir = lightDir[i];\\n      if (!viewpoint[i]) {\\n        if (finite[i]) {\\n          lightdir = (mvMatrix * vec4(lightdir, 1.)).xyz;\\n        } else {\\n          lightdir = (mvMatrix * vec4(lightdir, 0.)).xyz;\\n        }\\n      }\\n      if (!finite[i]) {\\n        halfVec = normalize(lightdir + eye);\\n      } else {\\n        lightdir = normalize(lightdir - vPosition.xyz/vPosition.w);\\n        halfVec = normalize(lightdir + eye);\\n      }\\n      col = ambient[i];\\n      nDotL = dot(n, lightdir);\\n      col = col + max(nDotL, 0.) * colDiff.rgb;\\n      col = col + pow(max(dot(halfVec, n), 0.), shininess) * specular[i];\\n      lighteffect = lighteffect + vec4(col, colDiff.a);\\n    }\\n#else\\n    lighteffect.a = 1.;\\n#endif\\n    \\n#else // not IS_LIT\\n    vec4 colDiff = vCol;\\n    vec4 lighteffect = colDiff;\\n#endif\\n    \\n#ifdef IS_TEXT\\n    vec4 textureColor = lighteffect*texture2D(uSampler, vTexcoord);\\n#endif\\n    \\n#ifdef HAS_TEXTURE\\n\\n// These calculations use the definitions from \\n// https://docs.gl/gl3/glTexEnv\\n\\n#ifdef USE_ENVMAP\\n    float m = 2.0 * sqrt(dot(vReflection, vReflection) + 2.0*vReflection.z + 1.0);\\n    vec4 textureColor = texture2D(uSampler, vReflection.xy / m + vec2(0.5, 0.5));\\n#else\\n    vec4 textureColor = texture2D(uSampler, vTexcoord);\\n#endif\\n\\n#ifdef TEXTURE_rgb\\n\\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\\n    textureColor = vec4(textureColor.rgb, lighteffect.a);\\n#endif \\n\\n#ifdef TEXMODE_modulate\\n    textureColor = lighteffect*vec4(textureColor.rgb, 1.);\\n#endif\\n\\n#ifdef TEXMODE_blend\\n    textureColor = vec4((1. - textureColor.rgb) * lighteffect.rgb, lighteffect.a);\\n#endif\\n\\n#ifdef TEXMODE_add\\n    textureColor = vec4(lighteffect.rgb + textureColor.rgb, lighteffect.a);\\n#endif\\n\\n#endif //TEXTURE_rgb\\n        \\n#ifdef TEXTURE_rgba\\n\\n#ifdef TEXMODE_replace\\n// already done\\n#endif \\n\\n#ifdef TEXMODE_modulate\\n    textureColor = lighteffect*textureColor;\\n#endif\\n\\n#ifdef TEXMODE_decal\\n    textureColor = vec4((1. - textureColor.a)*lighteffect.rgb) +\\n                     textureColor.a*textureColor.rgb, \\n                     lighteffect.a);\\n#endif\\n\\n#ifdef TEXMODE_blend\\n    textureColor = vec4((1. - textureColor.rgb) * lighteffect.rgb,\\n                    lighteffect.a*textureColor.a);\\n#endif\\n\\n#ifdef TEXMODE_add\\n    textureColor = vec4(lighteffect.rgb + textureColor.rgb,\\n                    lighteffect.a*textureColor.a);\\n#endif\\n    \\n#endif //TEXTURE_rgba\\n    \\n#ifdef TEXTURE_alpha\\n    float luminance = dot(vec3(1.,1.,1.),textureColor.rgb)/3.;\\n\\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\\n    textureColor = vec4(lighteffect.rgb, luminance);\\n#endif \\n\\n#if defined(TEXMODE_modulate) || defined(TEXMODE_blend) || defined(TEXMODE_add)\\n    textureColor = vec4(lighteffect.rgb, lighteffect.a*luminance);\\n#endif\\n \\n#endif // TEXTURE_alpha\\n    \\n// The TEXTURE_luminance values are not from that reference    \\n#ifdef TEXTURE_luminance\\n    float luminance = dot(vec3(1.,1.,1.),textureColor.rgb)/3.;\\n\\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\\n    textureColor = vec4(luminance, luminance, luminance, lighteffect.a);\\n#endif \\n\\n#ifdef TEXMODE_modulate\\n    textureColor = vec4(luminance*lighteffect.rgb, lighteffect.a);\\n#endif\\n\\n#ifdef TEXMODE_blend\\n    textureColor = vec4((1. - luminance)*lighteffect.rgb,\\n                        lighteffect.a);\\n#endif\\n\\n#ifdef TEXMODE_add\\n    textureColor = vec4(luminance + lighteffect.rgb, lighteffect.a);\\n#endif\\n\\n#endif // TEXTURE_luminance\\n \\n    \\n#ifdef TEXTURE_luminance_alpha\\n    float luminance = dot(vec3(1.,1.,1.),textureColor.rgb)/3.;\\n\\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\\n    textureColor = vec4(luminance, luminance, luminance, textureColor.a);\\n#endif \\n\\n#ifdef TEXMODE_modulate\\n    textureColor = vec4(luminance*lighteffect.rgb, \\n                        textureColor.a*lighteffect.a);\\n#endif\\n\\n#ifdef TEXMODE_blend\\n    textureColor = vec4((1. - luminance)*lighteffect.rgb,\\n                        textureColor.a*lighteffect.a);\\n#endif\\n\\n#ifdef TEXMODE_add\\n    textureColor = vec4(luminance + lighteffect.rgb, \\n                        textureColor.a*lighteffect.a);\\n\\n#endif\\n\\n#endif // TEXTURE_luminance_alpha\\n    \\n    fragColor = textureColor;\\n\\n#elif defined(IS_TEXT)\\n    if (textureColor.a < 0.1)\\n      discard;\\n    else\\n      fragColor = textureColor;\\n#else\\n    fragColor = lighteffect;\\n#endif // HAS_TEXTURE\\n    \\n#ifdef HAS_FOG\\n    // uFogParms elements: x = near, y = far, z = fogscale, w = (1-sin(FOV/2))/(1+sin(FOV/2))\\n    // In Exp and Exp2: use density = density/far\\n    // fogF will be the proportion of fog\\n    // Initialize it to the linear value\\n    float fogF;\\n    if (uFogMode > 0) {\\n      fogF = (uFogParms.y - vPosition.z/vPosition.w)/(uFogParms.y - uFogParms.x);\\n      if (uFogMode > 1)\\n        fogF = mix(uFogParms.w, 1.0, fogF);\\n      fogF = fogF*uFogParms.z;\\n      if (uFogMode == 2)\\n        fogF = 1.0 - exp(-fogF);\\n      // Docs are wrong: use (density*c)^2, not density*c^2\\n      // https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/mesa/swrast/s_fog.c#L58\\n      else if (uFogMode == 3)\\n        fogF = 1.0 - exp(-fogF*fogF);\\n      fogF = clamp(fogF, 0.0, 1.0);\\n      gl_FragColor = vec4(mix(fragColor.rgb, uFogColor, fogF), fragColor.a);\\n    } else gl_FragColor = fragColor;\\n#else\\n    gl_FragColor = fragColor;\\n#endif // HAS_FOG\\n    \\n}\",\"players\":[],\"webGLoptions\":{\"preserveDrawingBuffer\":true},\"fastTransparency\":true},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nThe same geometry, one predictor up: mean cosmopolitan framing against unemployment and GDP growth, with the OLS plane fitted to all 270 country-years. Red segments are residuals for eight of the larger gaps – vertical distances from point to plane, whose squared sum the fit minimises. Drag to rotate and scroll to zoom. Axes in raw units.\n:::\n:::\n\n\nWith a third predictor the plane becomes a hyperplane no picture can hold, but the algebra in the arg-min never changes, and neither does the reading of a coefficient: each slope is a comparison with everything else in the model held level. The sections that follow stay with the single-slope version until the menu's co-predictor choice brings growth back in.\n\n`lm()`'s first argument is a **formula**, written `outcome ~ predictor` and read \"outcome as explained by predictor\". The panel was read into `euframes` at the top of the page, this way:\n\n```r\nlibrary(readr)\neuframes <- read_csv(\"../data/EUframes_cy.csv\")   # ../ because this page lives in companion/\n```\n\nFitting the model and reading it back takes two lines:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_model <- lm(mcosmo ~ unemp, data = euframes)\nsummary(first_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mcosmo ~ unemp, data = euframes)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.208129 -0.036661  0.008259  0.051255  0.150833 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.516683   0.010133  50.989   <2e-16 ***\nunemp       -0.001098   0.001055  -1.041    0.299    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.07042 on 268 degrees of freedom\nMultiple R-squared:  0.004025,\tAdjusted R-squared:  0.0003084 \nF-statistic: 1.083 on 1 and 268 DF,  p-value: 0.299\n```\n\n\n:::\n:::\n\n\nThis output format recurs, with variations, in every model this module fits, so it is worth reading slowly once. The `Call` restates the model. The `Residuals` block summarises the estimated errors $\\hat\\varepsilon_i = y_i - \\hat y_i$, the gaps between each observed value and the fitted line. The `Coefficients` table is the heart, one row per $\\beta$, four columns each:\n\n- **Estimate** is $\\hat\\beta$ itself. The `unemp` row says a one-point rise in the unemployment rate goes with a fall of about 0.0011 in the cosmopolitan-framing score; the `(Intercept)` row says a hypothetical country-year with zero unemployment would be expected to score about 0.52.\n- **Std. Error** is the standard deviation of the estimate across imagined repeated samples: how precisely the data pin the coefficient down. It is the denominator of everything that follows.\n- **t value** is Estimate divided by Std. Error – how many standard errors the estimate sits from zero. It is unit-free, which is why the workshop can put every submitted result on one chart: whatever the scale of the model, its `t` means the same thing.\n- **Pr(>|t|)** is the p-value: the probability of a `t` at least this large in magnitude if the true coefficient were zero. Small values are conventionally read as evidence the association is not just noise.\n\nBelow the table, the **residual standard error** (0.070 here) estimates the spread of $\\varepsilon$, on **268 degrees of freedom** – the 270 observations minus the two $\\beta$s estimated. Degrees of freedom measure how many independent pieces of information remain for estimating uncertainty, and they become a central character later in this module. **Multiple R-squared** is the share of the outcome's variance the line explains – 0.4% here, essentially nothing – and the **F-statistic** tests all the predictors at once.\n\nSo read as a whole: this first model finds no relationship worth reporting. The slope is small, its `t` of −1.04 is well inside the range chance produces, and the p-value of 0.30 confirms it. Yet the workshop's anchor result, on exactly these 270 rows, is a clearly negative and conventionally significant t = −3.80. Nothing about the data changes between here and there – only the model's structure does, and the rest of this module is the story of that structure.\n\nThe reason to distrust this simple fit is precise, and it names the module's agenda. OLS's standard errors assume the 270 errors $\\varepsilon_i$ are **independent and identically distributed**, and the estimate itself is only unbiased if the error is uncorrelated with the predictor. Both assumptions are strained here. The 270 rows are not 270 unrelated observations; they are 27 countries observed ten times each, and Denmark's ten rows share everything durable about Denmark. Those shared national features sit in $\\varepsilon$, they are correlated within country, and – since unemployment levels also differ durably between countries – they are correlated with $x$ too. The next three sections deal with each consequence in turn: first the standard errors, then the estimate itself.\n\n## 3. Pooled OLS, like-for-like results, and cluster-robust errors {#sec-pooled}\n\nApplied to a panel, the simple regression of section 2 has a proper name: **pooled OLS**, because it pools all country-years into one undifferentiated cloud. Writing the same equation with the panel's two-index notation makes the pooling visible – one line for all $c$ and $t$, with nothing in the model that knows rows share a country:\n\n$$ \\bar{y}_{ct} = \\beta_0 + \\beta_1 x_{ct} + \\varepsilon_{ct} $$\n\nR offers several routes to this fit, and the workshop's materials use three of them: base R's `lm()`, `feols()` from the fixest package [@BergeEtAl2026FastUserfriendlyEconometrics], and `plm()` from the plm package [@CroissantMillo2023PanelDataEconometrics], the panel-econometrics toolkit the published Multi100 analysis used. A habit this module recommends before any new setting is introduced: **make different functions agree on the model you already understand**. If two functions give the same numbers under settings you can name, you know exactly what each is doing; when their defaults later diverge, you will know which setting moved.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fixest)\nlibrary(plm)\n\nm_lm  <- lm(mcosmo ~ unemp, data = euframes)\nm_fx  <- feols(mcosmo ~ unemp, data = euframes, vcov = \"iid\")\nm_plm <- plm(mcosmo ~ unemp, data = euframes,\n             index = c(\"cntry\", \"year\"), model = \"pooling\")\n\ntibble(\n  fitted_with = c(\"lm()\", \"feols()\", \"plm()\"),\n  estimate  = c(coef(m_lm)[\"unemp\"], coef(m_fx)[\"unemp\"], coef(m_plm)[\"unemp\"]),\n  std_error = c(sqrt(vcov(m_lm)[\"unemp\", \"unemp\"]),\n                sqrt(vcov(m_fx)[\"unemp\", \"unemp\"]),\n                sqrt(vcov(m_plm)[\"unemp\", \"unemp\"]))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  fitted_with estimate std_error\n  <chr>          <dbl>     <dbl>\n1 lm()        -0.00110   0.00105\n2 feols()     -0.00110   0.00105\n3 plm()       -0.00110   0.00105\n```\n\n\n:::\n:::\n\n\nIdentical to every digit, because it is one estimator under three names: `vcov = \"iid\"` asks fixest for the classical standard errors that `lm()` and `plm(model = \"pooling\")` report by default. That is the like-for-like baseline. Now change one thing only.\n\nThe first repair for the correlated-errors problem keeps the estimate and fixes the uncertainty. **Cluster-robust standard errors** replace the classical variance formula with one that permits the errors inside each cluster – here, each country – to be correlated however they like:\n\n$$ \\widehat{\\operatorname{Var}}(\\hat\\beta) \\;=\\; (X'X)^{-1} \\Big( \\textstyle\\sum_{g=1}^{G} X_g' \\hat\\varepsilon_g^{\\vphantom{\\prime}} \\hat\\varepsilon_g' X_g^{\\vphantom{\\prime}} \\Big) (X'X)^{-1} $$\n\nThe notation is less fearsome than it looks. $X$ is the matrix of predictor values and $G$ the number of clusters (27 countries). The formula is a sandwich: the outer 'bread' terms are the ordinary OLS ingredients, and the middle 'meat' sums each country's residuals in a way that keeps every within-country correlation intact rather than assuming it away. Only the standard error changes; $\\hat\\beta$ is untouched.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sandwich)\nlibrary(lmtest)\n\n# fixest: one argument\nm_cl <- feols(mcosmo ~ unemp, data = euframes, cluster = ~cntry)\ncoeftable(m_cl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate  Std. Error    t value     Pr(>|t|)\n(Intercept)  0.516683404 0.025017527 20.6528565 1.183841e-17\nunemp       -0.001097567 0.002195328 -0.4999559 6.213113e-01\nattr(,\"vcov_type\")\n[1] \"Clustered (cntry)\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# the same repair applied to the lm() fit via the sandwich package\ncoeftest(m_lm, vcov = vcovCL(m_lm, cluster = ~cntry, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.5166834  0.0250175  20.653   <2e-16 ***\nunemp       -0.0010976  0.0021953  -0.500   0.6175    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe two routes agree once the settings are matched: fixest's default small-sample adjustment corresponds to sandwich's `type = \"HC1\"` (and to plm's `vcovHC(..., type = \"sss\")`); with `type = \"HC0\"` the numbers would drift apart in the trailing digits, which is exactly the kind of discrepancy the like-for-like habit exists to explain. Substantively, clustering doubles the standard error, and the `t` falls from −1.04 to −0.50. The 270 rows were never 270 independent pieces of evidence, and the clustered errors say so.\n\nWhat clustering cannot do is rescue the estimate, and here the pooled estimate itself is the problem. Because the model absorbs no between-country differences, its slope blends two different comparisons: how framing moves when a single country's unemployment rises over time, and how framing differs between high-unemployment and low-unemployment countries in the cross-section. In these data the two point in opposite directions – [section 5](#sec-re) puts numbers on them: about −0.0056 within countries and +0.0041 between – and the pooled slope of −0.0011 is their blend, close to zero and, in many nearby specifications, on the wrong side of it.\n\nThat is exactly the pattern participants see on the class chart. Of the 140 specifications in the cosmopolitan universe (outcome = `mcosmo`), 41 come out with the 'wrong' sign, a positive coefficient running against the claim's negative direction. Almost all of them sit in one estimator:\n\n| Estimator | Wrong-sign specifications (cosmopolitan universe) |\n|---|---|\n| Pooled OLS (cluster-robust) | 33 |\n| Two-way fixed effects | 8 |\n| Country fixed effects only | 0 |\n| Random effects | 0 |\n| **Total** | **41** |\n\nThirty-three of the 41 wrong-sign results are pooled models. The sign flip is overwhelmingly a property of throwing away the panel structure, not of any other choice on the menu. Clustering is the right way to report uncertainty once you have committed to the pooled estimator; it does nothing to the sign, because the sign is a property of the estimate, not of its standard error.\n\n::: {.callout-tip}\n## Try it\n\nRead `data/spec_grid.csv`, keep the cosmopolitan universe (`filter(outcome == \"mcosmo\")`), and count the wrong-sign specifications by estimator (`filter(!supports_claim) |> count(estimator)`). You should recover the 33-and-8 split in the table above. Seeing it fall straight out of the committed grid, rather than taking it on trust, is the point.\n:::\n\n## 4. Two-way fixed effects: the workshop's anchor model {#sec-fe}\n\nThe second repair goes after the estimate itself. The workshop's anchor model, the one you reproduce in Task 3, is deliberately constrained: cosmopolitan framing regressed on the unemployment rate, with **country and year fixed effects** and nothing else.\n\n$$ \\bar{y}_{ct} = \\beta\\, x_{ct} + \\alpha_c + \\gamma_t + \\varepsilon_{ct} $$\n\nHere $\\alpha_c$ is a separate intercept for each country and $\\gamma_t$ a separate intercept for each year. The value of the fixed effects is in what they absorb. The country effects $\\alpha_c$ soak up everything time-constant about a country – its language, institutions, size, and its enduring baseline level of EU enthusiasm – so the unemployment slope is identified only from how a country changes against itself over time, never from the fact that, say, Denmark and Greece differ. The year effects $\\gamma_t$ soak up everything common to all countries in a given year, the EU-wide shocks and the shared arc of the crisis among them. Two-way fixed effects, in one line, compare a country to itself over time, net of whatever moved all of Europe together that year.\n\nMechanically there are two equivalent ways to fit this, and seeing them agree teaches how the estimator works. The literal way estimates every intercept: 26 country dummies and 9 year dummies alongside the slope, the 'least squares dummy variable' route. The efficient way never estimates them at all: the **within transformation** subtracts each country's mean and each year's mean from both sides,\n\n$$ \\left( \\bar{y}_{ct} - \\bar{y}_{c\\cdot} - \\bar{y}_{\\cdot t} + \\bar{y} \\right) \\;=\\; \\beta \\left( x_{ct} - \\bar{x}_{c\\cdot} - \\bar{x}_{\\cdot t} + \\bar{x} \\right) + \\tilde\\varepsilon_{ct} $$\n\nwhere a dot in place of an index means \"averaged over it\". The demeaning wipes the $\\alpha_c$ and $\\gamma_t$ out of the equation, and OLS on the transformed data recovers exactly the same $\\beta$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_lsdv   <- lm(mcosmo ~ unemp + factor(cntry) + factor(year), data = euframes)\nm_within <- plm(mcosmo ~ unemp, data = euframes, index = c(\"cntry\", \"year\"),\n                effect = \"twoways\", model = \"within\")\nm_twfe   <- feols(mcosmo ~ unemp | cntry + year, data = euframes, vcov = \"iid\")\n\nc(lsdv = coef(m_lsdv)[\"unemp\"], plm = coef(m_within)[\"unemp\"],\n  feols = coef(m_twfe)[\"unemp\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lsdv.unemp    plm.unemp  feols.unemp \n-0.003472985 -0.003472985 -0.003472985 \n```\n\n\n:::\n:::\n\n\nThree functions, one estimator, one number. The fixest summary is the most informative to read:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m_twfe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: mcosmo\nObservations: 270\nFixed-effects: cntry: 27,  year: 10\nStandard-errors: IID \n       Estimate Std. Error  t value   Pr(>|t|)    \nunemp -0.003473   0.000913 -3.80372 0.00018214 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.034875     Adj. R2: 0.715885\n                 Within R2: 0.058465\n```\n\n\n:::\n:::\n\n\nThe slope is −0.00347: within a country, a one-point rise in unemployment goes with a fall of about 0.0035 in the mean cosmopolitan-framing score, net of common yearly shocks. Its `t` of −3.80 (p = 0.0002) is the workshop's anchor. Two R-squared lines repay attention. The overall adjusted R-squared of 0.72 mostly measures how much the fixed effects themselves explain – country identities are hugely predictive of framing levels – while the **within R-squared** of 0.058 is the slope's own contribution: unemployment movements explain about 6% of the within-country variation. Both are true; only the second is about the research question.\n\nThe same model on the as-submitted Multi100 file gives the day's other anchor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrep_data <- read_csv(\"../data/rep_data.csv\", show_col_types = FALSE)\nfeols(mcosmopolitan ~ unemp | cntry + year, data = rep_data, vcov = \"iid\") |>\n  coeftable()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Estimate   Std. Error   t value     Pr(>|t|)\nunemp -0.003408595 0.0008846405 -3.853085 0.0001508345\nattr(,\"vcov_type\")\n[1] \"IID\"\n```\n\n\n:::\n:::\n\n\nOn the corrected panel the constrained model returns **t = −3.804** (df = 233, N = 270), the value on record for analyst C6HJR; on the as-submitted file the same specification returns **t = −3.853**. The small gap is produced by a data-preparation error whose story Block 2 tells – a wave file read twice in the as-submitted pipeline, caught and corrected during the project; both figures are exact, and the story belongs there rather than in this module.\n\nTwo footnotes to the anchor, both of which recur on the specification menu. First, grand-mean centring the predictor shifts the intercept but leaves the slope and its `t` untouched once fixed effects are present: a centred predictor and its raw form give an identical coefficient, which is exactly why the specification grid keeps only the raw row rather than carrying a redundant centred twin. Second, the standard error above is the classical one, matching the published analysis; ask fixest to cluster by country instead and the same slope's `t` becomes −2.31 (p = 0.029). Still negative, still conventionally significant, but a reminder that even after the estimator is settled, the uncertainty convention is a separate, consequential choice – when you compare outputs across analysts, check which convention each is reporting before comparing the `t`s.\n\nWhat fixed effects cannot do is the other half of the lesson, and it is the reason Block 3 builds a causal graph before choosing a specification. They are silent on **time-varying confounding**: anything that changes within a country over the period and moves both its unemployment and its EU framing – a national political scandal, a country-specific austerity programme, a swing in the governing party's Europe stance – is not absorbed by either set of effects and can bias $\\beta$. They are equally silent on **feedback**: if EU framing itself feeds back onto economic outcomes, or if both respond to some third time-varying driver, the model has no way to know. A fixed-effects design is a strong answer to time-constant confounders and common shocks, and no answer at all to confounders that move.\n\n## 5. Random effects, the Hausman question, and within versus between {#sec-re}\n\nBetween the pooled and fixed-effects extremes sits a third estimator. **Random effects** keeps a country term in the model but, rather than estimating 27 separate intercepts, treats the country departures as draws from a distribution:\n\n$$ \\bar{y}_{ct} = \\beta_0 + \\beta_1 x_{ct} + u_c + \\varepsilon_{ct}, \\qquad u_c \\sim N(0, \\sigma_u^2) $$\n\nInstead of 27 numbers, the model estimates one: $\\sigma_u^2$, the variance of the country effects. Estimation is by generalised least squares, and its mechanics locate the estimator on the pooled-to-fixed spectrum precisely. Where fixed effects subtract each country's *entire* mean, random effects subtract a *fraction* $\\theta$ of it:\n\n$$ \\bar{y}_{ct} - \\theta \\bar{y}_{c\\cdot} = \\beta_0 (1 - \\theta) + \\beta_1 \\left( x_{ct} - \\theta \\bar{x}_{c\\cdot} \\right) + \\text{error}, \\qquad \\theta = 1 - \\sqrt{ \\frac{\\sigma_\\varepsilon^2}{\\sigma_\\varepsilon^2 + T \\sigma_u^2} } $$\n\nwith $T$ the number of years per country. At $\\theta = 0$ this is pooled OLS; at $\\theta = 1$ it is fixed effects; the data place it in between according to how much of the total variance sits between countries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_re <- plm(mcosmo ~ unemp, data = euframes,\n            index = c(\"cntry\", \"year\"), model = \"random\")\nsummary(m_re)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Random Effect Model \n   (Swamy-Arora's transformation)\n\nCall:\nplm(formula = mcosmo ~ unemp, data = euframes, model = \"random\", \n    index = c(\"cntry\", \"year\"))\n\nBalanced Panel: n = 27, T = 10, N = 270\n\nEffects:\n                   var  std.dev share\nidiosyncratic 0.001612 0.040151 0.337\nindividual    0.003170 0.056299 0.663\ntheta: 0.78\n\nResiduals:\n   Min. 1st Qu.  Median 3rd Qu.    Max. \n-0.1258 -0.0287  0.0014  0.0295  0.1275 \n\nCoefficients:\n               Estimate  Std. Error z-value  Pr(>|z|)    \n(Intercept)  0.55283984  0.01324871 41.7278 < 2.2e-16 ***\nunemp       -0.00525044  0.00081212 -6.4651 1.012e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    0.50821\nResidual Sum of Squares: 0.43965\nR-Squared:      0.13492\nAdj. R-Squared: 0.13169\nChisq: 41.7974 on 1 DF, p-value: 1.0124e-10\n```\n\n\n:::\n:::\n\n\nThe `Effects` block is the new output to learn. The **individual** variance (0.0032) is $\\hat\\sigma_u^2$, the between-country component; the **idiosyncratic** variance (0.0016) is $\\hat\\sigma_\\varepsilon^2$, the within noise; the `share` column says 66% of the error variance is between-country. The reported $\\theta$ of 0.78 places this fit 78% of the way from pooled towards fixed effects, and the slope duly lands near the country-fixed-effects answer: −0.0053 (z = −6.5) against the −0.0056 that country fixed effects give on their own. (Note that `plm`'s default random-effects model has country effects only, so its natural comparator is one-way, not two-way, fixed effects.)\n\nRandom effects is more efficient than fixed effects when its central assumption holds: that the country effects $u_c$ are **uncorrelated with the predictor**. Here that assumption is a strong one, because a country's unemployment level is very likely tied up with the same durable national features that shape its baseline EU framing – exactly the correlation fixed effects were designed to sweep away. The **Hausman test** formalises the comparison: if the assumption held, fixed and random effects would estimate the same quantity and differ only by noise, so a large gap between them is evidence against it. Comparing the two one-way (country) estimators:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfe_country <- plm(mcosmo ~ unemp, data = euframes, index = c(\"cntry\", \"year\"),\n                  effect = \"individual\", model = \"within\")\nre_country <- plm(mcosmo ~ unemp, data = euframes, index = c(\"cntry\", \"year\"),\n                  effect = \"individual\", model = \"random\")\nphtest(fe_country, re_country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHausman Test\n\ndata:  mcosmo ~ unemp\nchisq = 9.8431, df = 1, p-value = 0.001705\nalternative hypothesis: one model is inconsistent\n```\n\n\n:::\n:::\n\n\nThe test rejects (p = 0.002): the estimators disagree by more than chance allows, the random-effects assumption is not defensible here, and the fixed-effects estimate is the safer of the two.\n\nThere is, though, a more informative response than picking a winner, and it dissolves the fixed-versus-random dilemma rather than settling it. Split the predictor into its two kinds of variation – each country's *average* unemployment across the decade, and each year's *departure* from that average – and give each its own slope. This is the **within–between** (or Mundlak) formulation:\n\n$$ \\bar{y}_{ct} = \\beta_0 + \\beta_W \\left( x_{ct} - \\bar{x}_{c\\cdot} \\right) + \\beta_B\\, \\bar{x}_{c\\cdot} + u_c + \\varepsilon_{ct} $$\n\n$\\beta_W$ is the within-country slope, $\\beta_B$ the between-country one. The fit below uses `lmer()` from lme4 [@BatesEtAl2015FittingLinearMixedeffects], the mixed-model workhorse that [section 6](#sec-multilevel) introduces properly; the random-intercept term `(1 | cntry)` plays the role of $u_c$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmerTest)   # lme4's lmer(), plus degrees of freedom for its t-tests\n\neuframes_wb <- euframes |>\n  group_by(cntry) |>\n  mutate(unemp_between = mean(unemp),\n         unemp_within  = unemp - unemp_between) |>\n  ungroup()\n\nm_wb <- lmer(mcosmo ~ unemp_within + unemp_between + (1 | cntry), data = euframes_wb)\nsummary(m_wb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']\nFormula: mcosmo ~ unemp_within + unemp_between + (1 | cntry)\n   Data: euframes_wb\n\nREML criterion at convergence: -862.4\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3294 -0.5742  0.0433  0.6396  3.0258 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n cntry    (Intercept) 0.003170 0.05630 \n Residual             0.001612 0.04015 \nNumber of obs: 270, groups:  cntry, 27\n\nFixed effects:\n                Estimate Std. Error         df t value Pr(>|t|)    \n(Intercept)    4.711e-01  3.664e-02  2.500e+01  12.857 1.61e-12 ***\nunemp_within  -5.645e-03  8.218e-04  2.420e+02  -6.869 5.42e-11 ***\nunemp_between  4.143e-03  4.010e-03  2.500e+01   1.033    0.311    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) unmp_w\nunemp_withn  0.000       \nunemp_betwn -0.953  0.000\n```\n\n\n:::\n:::\n\n\nRead the two slopes against everything fitted so far. The within slope, −0.0056, is *exactly* the country-fixed-effects estimate (fit `feols(mcosmo ~ unemp | cntry, ...)` and compare), because separating out the between variation is precisely what fixed effects do. The between slope is +0.0041 – positive, imprecise, and telling its own story: countries with chronically higher unemployment do not frame the EU less cosmopolitanly; if anything, slightly the reverse. Now the pooled puzzle of section 3 has an arithmetic answer: the pooled slope of −0.0011 was a weighted blend of −0.0056 and +0.0041, two real patterns with opposite signs, averaged into meaninglessness. The Hausman rejection above is the same fact in test form – it fires precisely because $\\beta_W \\neq \\beta_B$. And the estimand lesson lands early: 'the effect of unemployment on EU framing' was never one number; there is a within-country number and a between-country number, and a model is a decision about which one you are asking for. (For the fuller argument that this formulation should usually replace the fixed-versus-random contest, see @BellJones2015ExplainingFixedEffects.)\n\nOne practical note completes the estimator tour. The random-effects estimator is also the reason the grid holds 840 specifications rather than the full 960 that the menu's six remaining axes – with the outcome family held at Gaussian and the claim-carrying predictor at unemployment – would otherwise produce: six outcomes, two predictor forms, two co-predictor sets, four estimators, five samples and two weighting choices multiply to 960, but frequency weights do not compose cleanly with the variance-component machinery a random-effects GLS estimates, so the 120 weighted random-effects cells are omitted as not well defined. That arithmetic – and the shares quoted from the grid, 68.7% of specifications in the claim's direction and 63.9% significant – is all computable from the committed `spec_grid.csv`.\n\n## 6. The multilevel framework: modelling respondents directly {#sec-multilevel}\n\nEverything so far has lived at the country-year level. OA's own study did not: its anchor result – **b = −0.0034, t = −4.03, p < .001** (Table 3, Model 1) – comes from a three-level random-intercept model fitted to the individual respondents. This section climbs down to that level and fits the same family of models on the actual microdata: 416,698 respondents, rebuilt from the sixteen GESIS waves exactly as the codebook describes.\n\n::: {.callout-note}\n## How the outputs in this section were produced\n\nThe respondent-level file cannot ship with the workshop (GESIS licence), so every model fitted to it – the multilevel fits below, the weighted fits of [section 7](#sec-weights), and the generalised models of [section 9](#sec-glm) – is displayed rather than executed on the page. Each output was produced by the script `companion/_model-outputs/fit_models.R` in the site's repository, run on the facilitator's machine against the rebuilt person-level data; the text shown is R's output verbatim. (The Bayesian summaries of [section 8](#sec-bayes) come from the same script for a different reason: their model uses the committed panel, but compiling and sampling it takes a minute or two rather than the instant a live chunk needs.) These are single, deliberately simple fits chosen to teach each method's output – nothing beyond them is computed on the microdata anywhere in this workshop. To run them yourself you need the raw waves under your own (free) GESIS registration – the [repositories module](repositories.qmd#sec-gesis) walks that path.\n:::\n\nA **multilevel model** (also called a hierarchical or mixed model) fits the respondents directly while representing the nesting explicitly: respondents sit inside country-years, which sit inside countries. Written at its three levels, with $i$ indexing respondents:\n\n$$ y_{i(ct)} = \\pi_{ct} + \\varepsilon_{ict} \\qquad\\qquad \\text{(respondents around their cell mean)} $$\n$$ \\pi_{ct} = \\alpha_c + \\beta x_{ct} + r_{ct} \\qquad \\text{(cell means moved by unemployment)} $$\n$$ \\alpha_c = \\gamma_0 + v_c \\qquad\\qquad\\quad \\text{(countries around the grand mean)} $$\n\nor, substituted into one line:\n\n$$ y_{ict} = \\gamma_0 + \\beta x_{ct} + v_c + r_{ct} + \\varepsilon_{ict} $$\n\nwith $v_c \\sim N(0, \\sigma_v^2)$, $r_{ct} \\sim N(0, \\sigma_r^2)$ and $\\varepsilon_{ict} \\sim N(0, \\sigma_\\varepsilon^2)$. Three variance components now share the noise: $\\sigma_v^2$ for durable country differences, $\\sigma_r^2$ for country-year departures, and $\\sigma_\\varepsilon^2$ for person-to-person differences inside a cell. The fixed part ($\\gamma_0 + \\beta x_{ct}$) is shared by everyone; the random part is a sum of draws at each level. This is the random-effects idea of section 5 generalised, and `(1 | group)` in `lmer()` notation declares each random intercept. Drawn rather than written, the structure looks like this:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The three levels of the multilevel model, in a simulated miniature: three countries, two survey years each, fourteen respondents per cell. Respondents (grey points) scatter around their country-year cell mean (red bars) – the person-level noise. Cell means scatter around their country's own level (solid blue line) – the country-year component. And country levels scatter around the grand mean (dashed line) – the country component. A multilevel model estimates one variance for each of those three kinds of scatter.](stats-methods_files/figure-html/fig-ml-structure-1.png){#fig-ml-structure width=768}\n:::\n:::\n\n\nStart deliberately wrong, with only the country level declared:\n\n```r\nlibrary(lme4)\nperson <- readRDS(\"person_level.rds\")   # 416,698 respondents; GESIS-licensed rebuild\n\nm_two <- lmer(cosmo ~ unemp + (1 | cntry), data = person)\nsummary(m_two)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']\nFormula: cosmo ~ unemp + (1 | cntry)\n   Data: person\n\nREML criterion at convergence: 353436.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.65509 -0.93396  0.00253  1.03162  1.80580 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n cntry    (Intercept) 0.003941 0.06278 \n Residual             0.136677 0.36970 \nNumber of obs: 416698, groups:  cntry, 27\n\nFixed effects:\n              Estimate Std. Error         df t value Pr(>|t|)    \n(Intercept)  5.474e-01  1.222e-02  2.705e+01   44.80   <2e-16 ***\nunemp       -4.790e-03  1.953e-04  3.912e+05  -24.52   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n      (Intr)\nunemp -0.140\n```\n\n\n:::\n:::\n\n\nThe output's anatomy: the `Random effects` block reports the estimated variance components ($\\hat\\sigma_v^2 = 0.0039$ for countries, $\\hat\\sigma_\\varepsilon^2 = 0.1367$ for respondents), and the `Fixed effects` table reads like an `lm()` coefficient table with one addition – a `df` column, computed by Satterthwaite's approximation, saying how many independent pieces of information stand behind each `t`. And that column exposes the model's flaw. A slope of −0.0048 with t = −24.5 on **391,200 degrees of freedom** looks like overwhelming evidence, but the model has been allowed to treat every respondent as fresh information about unemployment, when every respondent in a country-year shares one unemployment value. The predictor only has 270 distinct values; a model whose df runs to six figures is counting people as if they were countries.\n\nDeclare the country-year level and the same data answer differently:\n\n```r\nm_three <- lmer(cosmo ~ unemp + (1 | cntry) + (1 | cntry:year), data = person)\nsummary(m_three)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']\nFormula: cosmo ~ unemp + (1 | cntry) + (1 | cntry:year)\n   Data: person\n\nREML criterion at convergence: 350414.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.77238 -0.96186  0.01493  0.99635  1.89818 \n\nRandom effects:\n Groups     Name        Variance Std.Dev.\n cntry:year (Intercept) 0.001485 0.03853 \n cntry      (Intercept) 0.003759 0.06131 \n Residual               0.135469 0.36806 \nNumber of obs: 416698, groups:  cntry:year, 270; cntry, 27\n\nFixed effects:\n              Estimate Std. Error         df t value Pr(>|t|)    \n(Intercept)  5.526e-01  1.393e-02  4.441e+01  39.682  < 2e-16 ***\nunemp       -5.237e-03  8.021e-04  2.531e+02  -6.528 3.61e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n      (Intr)\nunemp -0.502\n```\n\n\n:::\n:::\n\n\nThe slope barely moves (−0.0052), but everything around it does. The standard error quadruples, the `t` falls from −24.5 to −6.5, and the Satterthwaite df collapses from 391,200 to **253** – the scale of the 270 cells, not of the 416,698 respondents, because the cells are where the genuine predictor contrasts live. The new variance component ($\\hat\\sigma_r^2 = 0.0015$) is small in absolute terms, yet acknowledging it changes the inference fourfold, because it is the level at which the predictor lives. Compare this fit with section 5's aggregate models: the three-level person model's slope of −0.0052 (t = −6.5) is, to two decimals, the aggregate random-intercept estimate. Once the error structure matches the data's real structure, modelling 416,698 people and modelling their 270 cell means give the same answer about a country-year-level predictor – which is the deep reason the workshop can teach the case from the shipped panel.\n\nThe framework's genuine additions come when you let more than the intercept vary. A **random slope** lets each country have its own unemployment coefficient, drawn from a distribution whose spread is estimated:\n\n$$ y_{ict} = \\gamma_0 + (\\beta + b_c)\\, x_{ct} + v_c + r_{ct} + \\varepsilon_{ict}, \\qquad b_c \\sim N(0, \\sigma_b^2) $$\n\n```r\nm_slopes <- lmer(cosmo ~ unemp + (1 + unemp | cntry) + (1 | cntry:year), data = person)\nsummary(m_slopes)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']\nFormula: cosmo ~ unemp + (1 + unemp | cntry) + (1 | cntry:year)\n   Data: person\n\nREML criterion at convergence: 350388.3\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.76748 -0.95971  0.01417  0.99887  1.89847 \n\nRandom effects:\n Groups     Name        Variance  Std.Dev. Corr  \n cntry:year (Intercept) 1.201e-03 0.034660       \n cntry      (Intercept) 4.133e-03 0.064291       \n            unemp       3.713e-05 0.006093 -0.44 \n Residual               1.355e-01 0.368061       \nNumber of obs: 416698, groups:  cntry:year, 270; cntry, 27\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept)  0.553728   0.015552 20.196050  35.606  < 2e-16 ***\nunemp       -0.005712   0.001684 18.815257  -3.392  0.00309 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n      (Intr)\nunemp -0.658\n```\n\n\n:::\n:::\n\n\nTwo things in this output matter. In the `Random effects` block, the slope's standard deviation is 0.0061 – larger than the mean slope of −0.0057 itself. Countries do not share one unemployment effect: the model estimates that the effect ranges from clearly negative in some countries to positive in others, with the average sitting where the earlier fits put it (the `Corr` of −0.44 adds that higher-intercept countries tend to have more negative slopes). And the fixed slope's df is now about **19** – once each country testifies mainly about its own slope, the effective evidence for the *average* slope is the 27 countries, not the 270 cells. The df column keeps strict count of where the information genuinely comes from, and it will decide the effect-size story in [section 10](#sec-onescale).\n\nTwo of the five Multi100 analysts worked at this level, and they bracket the recorded range. Analyst KEVF1 (in R) reported t = −5.90 with a Satterthwaite-style df of about 136, converting to a partial correlation of −0.452; analyst PRL47 (in Stata) reported z = −3.59 with the respondent count of nearly 395,000 standing in for df, converting to −0.006. Same data, same model family, same negative direction – and a 75-fold gap in converted effect size produced almost entirely by the df convention you have just watched move from 391,200 to 253 to 19 across three model declarations. The unit of analysis, and the error structure declared around it, is therefore an **estimand** choice: a decision about what 'the effect' refers to and which draws of the world would count as replications, not a software preference. The aggregated models answer a question about country-years; the person-level models appear to answer one about people, but with a predictor that varies only by country-year they mostly re-ask the same question with more elaborate error accounting. Reasonable analysts answering \"which question?\" differently get genuinely different numbers, before any estimation begins.\n\nCarry section 5's grid arithmetic down a level, finally, and the framework's consequences for the multiverse become concrete. Moving to the respondents does not just re-estimate the same 840 cells with richer machinery; it widens the menu itself. Person-level covariates that simply do not exist in the aggregates – age, gender, education – become available as a new adjustment fork. The estimator axis changes membership: the multilevel designs of this section stand alongside their fixed-effects and pooled counterparts. The design weights every respondent carries become usable at last ([section 7](#sec-weights)), and with them one block of cells comes back from the dead – the aggregate grid had to drop its 120 weighted random-effects cells because frequency weights do not compose with GLS, but genuine design weights *do* compose with multilevel models through the pseudo-maximum-likelihood route of the next section, so the weighted multilevel cells are well defined at the person level. Multiply the menu out – six outcomes, two predictor forms, two macro co-predictor sets, four estimators, five samples, two weight choices, and the new demographic-adjustment fork – and the person-level menu holds 1,920 Gaussian cells. Add one more binary fork – the outcome-family choice [section 9](#sec-glm) introduces – and the universe doubles to **3,840 person-level specifications**. Pooled with the family universe of 1,680 aggregated cells (the 840 of section 5 plus their family twins of section 9), they make a **5,520**-specification joint universe in which the level of aggregation is itself a further fork, arguably the most consequential one on the whole menu. None of it has been computed; the arithmetic is the lesson – a menu widens geometrically the moment the data allow new forks.\n\n## 7. Survey weights: from design to estimation {#sec-weights}\n\nEvery Eurobarometer respondent arrives with a number attached: a **survey weight**. This section is about what those numbers are, how estimation uses them, and why they interact awkwardly with the multilevel framework – a corner of practice where software choices genuinely change results.\n\nWeights exist because samples are not miniature populations. Some people are harder to reach, some decline, some designs deliberately over-sample small groups; the result is that a 60-year-old rural woman may stand for more people than an urban student who was easier to find. A design weight $w_i$ is, at its cleanest, the inverse of person $i$'s probability of ending up in the sample, $w_i = 1 / \\pi_i$; post-stratification adjustments then align the weighted sample with known population margins. Estimation uses the weights by letting each observation count $w_i$ times. The weighted mean is the simplest case,\n\n$$ \\hat{\\bar{Y}} = \\frac{\\sum_i w_i\\, y_i}{\\sum_i w_i} $$\n\nand weighted least squares generalises it, choosing coefficients to minimise $\\sum_i w_i \\left( y_i - \\beta_0 - \\beta_1 x_i \\right)^2$ so that under-represented kinds of people pull the line with their population share rather than their sample share.\n\nThe Eurobarometer's own weighting scheme, documented in the GESIS Eurobarometer Data Service's weighting overview [@GESISWeightingOverview], is a complete worked example of that logic, and every wave's file labels its weights plainly. The basic one is **W1, \"WEIGHT RESULT FROM TARGET\"** – the `w1` of the rebuilt person file. It is a pure post-stratification (in the Eurobarometer's vocabulary, *redressment*) weight: an iterative marginal-weighting procedure aligns each national sample with its population's known margins on sex, age, region (NUTS 2) and size of locality, reproducing each country's real case count. W1 makes each national sample representative *of its own country*, and it deliberately does nothing to rescale countries against one another. The companion weights divide the remaining labour. W3 (\"WEIGHT GERMANY\") and W4 (\"WEIGHT UNITED KINGDOM\") combine the separately drawn East/West German and Great Britain/Northern Ireland samples into united national totals – the same sample splits that the workshop codebook's DE and GB recodes fold together. The long W5–W30 series (\"WEIGHT EU6\" through \"WEIGHT EU27\", euro zone in and out) add the population-size scaling needed when similarly sized national samples must stand for populations as different as Malta's and Germany's, and **WEX** (\"WEIGHT EXTRA POPULATION 15+\") extrapolates results to the actual population aged fifteen and over. The habit that transfers to any survey: find the weighting documentation, identify which weight answers *your* question's population, and say in the methods which one you used. For a question about the within-country alignment of framing and unemployment, W1 is the natural choice – and it is the natural weights fork for any person-level universe built on this menu.\n\nIn R, design-based estimation is the survey package's job [@Lumley2004AnalysisComplexSurvey]. You declare the design once – weights, and where the data supply them, clusters and strata – and then every estimator respects it:\n\n```r\nlibrary(survey)\n\ndes <- svydesign(ids = ~1, weights = ~w1, data = person)   # weights only; no PSU info here\nm_svy <- svyglm(cosmo ~ unemp, design = des)\nsummary(m_svy)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nsvyglm(formula = cosmo ~ unemp, design = des)\n\nSurvey design:\nsvydesign(ids = ~1, weights = ~w1, data = person)\n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.5055600  0.0014713  343.61   <2e-16 ***\nunemp       0.0001262  0.0001538    0.82    0.412    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for gaussian family taken to be 0.1398685)\n\nNumber of Fisher Scoring iterations: 2\n```\n\n\n:::\n:::\n\n\nTwo readings of this output. As a weighting demonstration: the W1-weighted pooled slope is +0.0001 with t = 0.8 – nothing, and on the wrong side of zero. Weights repair *representation*, and they have done their job; what they cannot repair is a mis-structured model, and this is the pooled estimator of section 3 again, blending within and between variation across 27 countries. A weighted wrong model is a well-weighted wrong model. As an output-reading exercise: note that `svyglm()` reports design-robust (linearised) standard errors as a matter of course – there is no classical-SE option to forget, which is one reason survey statisticians like the package.\n\nThe awkward corner is combining weights with the multilevel framework. The difficulty is conceptual before it is computational: a multilevel model needs to know the selection probability *at each level* – the country's probability of inclusion, then the respondent's probability given the country – but surveys typically publish one all-in weight per person, and there is no unique way to split it. The standard answer is **pseudo-maximum-likelihood**, weighting each level's contribution to the likelihood [@Rabe-HeskethSkrondal2006MultilevelModellingComplex], and it comes with a genuine fork: level-1 weights can be scaled in more than one defensible way, the choice can move variance estimates noticeably, and the literature's recommendation is to report sensitivity across scalings rather than trust any one [@Carle2009FittingMultilevelModels].\n\nBecause implementations differ in those choices, **the same weighted multilevel model can return different numbers in different software**, and knowing which convention you are running is part of reporting the model. Three practical facts anchor the R side. First, `lmer()`'s `weights` argument is *not* a survey-weights argument – it treats weights as precision weights, a different quantity entirely, and silently gives design-inconsistent answers if you feed it `w1`. Second, Stata's `mixed` accepts probability weights (`[pw = ...]`) and implements pseudo-maximum-likelihood with its own scaling options (`pwscale()`); much of the applied literature's weighted multilevel results were produced under its conventions. Third, the R package that speaks Stata's dialect is **WeMix** [@BaileyEtAl2023WeMixWeightedMixed]: it takes one weight column per level and fits by pseudo-maximum-likelihood; in our own comparative survey work it has reproduced Stata's weighted `mixed` fixed-effect estimates to three decimals, which makes it the tool of choice when a published Stata result needs re-implementing in R.\n\nTwo of the five Multi100 analysts worked in Stata, and their public code turns these abstractions into something you can point at. Analyst PRL47 – the person-level multilevel analyst of [section 6](#sec-multilevel) – builds the level-2 cell identifier and fits three-level random intercepts with `mixed`; these lines are from their Multi100 upload:\n\n```stata\negen cquarter=concat(country quarter)    // the country-by-quarter cell id\nmixed cosmo || country: || cquarter:     // three-level random intercepts\n```\n\nTwo absences in that second line repay a close look. The weight is missing: PRL47's script carefully assembles a survey weight for every wave (`gen weight=w3a4a`), then uses it only in descriptive checks (`sum cosmo cosmo2 [w=weight]`) – it never reaches the model, because carrying it there would mean committing to `[pw = ...]` and a defensible `pwscale()` choice, exactly the pseudo-maximum-likelihood fork above. Building a weight is easy; defending its use inside a multilevel model is a decision, and a careful analyst who stops short of it is itself instructive. And no estimation options are missing by accident either: a bare `mixed` estimates by maximum likelihood with model-based standard errors, whereas R's `lmer()` defaults to REML – so a line-for-line port disagrees with the original for no substantive reason unless one side's default is overridden. The correspondence, made explicit for Stata users:\n\n```stata\n* Stata – PRL47's estimator (maximum likelihood by Stata's default)\nmixed cosmo || country: || cquarter:\n* what a design-weighted version would have needed\nmixed cosmo [pw = weight] || country: || cquarter:, pwscale(size)\n```\n\n```r\n# the R twin – lmer() defaults to REML, so match Stata's ML explicitly\nlmer(cosmo ~ 1 + (1 | country) + (1 | cquarter), data = d, REML = FALSE)\n\n# the design-weighted twin – WeMix, pseudo-maximum-likelihood, one weight per level\nmix(cosmo ~ 1 + (1 | country), data = d, weights = c(\"weight\", \"w_country\"))\n```\n\nBack to the case's data. Supplying a constant 1 at the country level reproduces the common \"weights at level 1 only\" scenario:\n\n```r\nlibrary(WeMix)\n\nperson <- person |>\n  mutate(w_lvl2 = 1)   # unit weight at the country level – weighting at level 1 only\nm_wemix <- mix(cosmo ~ unemp + (1 | cntry), data = person,\n               weights = c(\"w1\", \"w_lvl2\"))\nsummary(m_wemix)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmix(formula = cosmo ~ unemp + (1 | cntry), data = person, weights = c(\"w1\", \n    \"w_lvl2\"))\n\nVariance terms:\n Level    Group        Name Variance Std. Error Std.Dev.\n     2    cntry (Intercept) 0.003741   0.001394  0.06116\n     1 Residual             0.136155   0.004246  0.36899\nGroups:\n Level Group n size mean wgt sum wgt\n     2 cntry     27        1      27\n     1   Obs 416677        1  416698\n\nFixed Effects:\n             Estimate Std. Error t value\n(Intercept)  0.555062   0.015043  36.898\nunemp       -0.004915   0.001488  -3.302\n\nlnl= -175909.61 \nIntraclass Correlation= 0.02674 \n```\n\n\n:::\n:::\n\n\nSet this beside the unweighted two-level fit of section 6 and read the comparison carefully, because it contains one more like-for-like trap. The weighted slope, −0.0049, sits next to the unweighted −0.0048: the W1 weights barely move the estimate, which is itself a finding (the framing–unemployment alignment is not an artefact of who is over- or under-represented within national samples). The standard errors, though, are not comparable at a glance – 0.0015 here against 0.0002 there – and most of that gap is not the weights but the *variance estimator*: WeMix reports design-linearised (robust) standard errors while `lmer()` reports model-based ones. Two settings changed between the outputs, and only one of them is the weighting. The habit from section 3 applies at every level of sophistication: before attributing a difference to the interesting setting, equalise the boring ones.\n\nThe workshop's own weighting axis, finally, is a humbler object than any of this. The specification menu offers `n_cy` weighting – each country-year weighted by the number of respondents behind its average, on the reasoning that a cell mean built from 3,000 people is measured more precisely than one built from 300. That is a precision argument about aggregated cells, not a design weight, and the genuine design weights cannot be reconstructed from the shipped aggregates at all; they live with the microdata, as above. The case's second Stata analyst, KQXUE, works at exactly this end of the spectrum, and their pipeline shows the whole weighting question dissolving in two lines:\n\n```stata\ncollapse cosmo util, by(cntry year)    // unweighted country-year means\nxtreg cosmo unemployment, fe           // = the within estimator of section 4\n```\n\nThe `collapse` averages every respondent equally, so the design weights are gone before any model is fitted, and each cell then enters `xtreg` with equal say whether 300 people or 3,000 stand behind it – precisely the axis the menu's `n_cy` option toggles. (The Stata–R correspondence continues here too: `xtreg, fe` after `xtset cntry_num year` is `plm`'s within estimator.) The menu's weighting fork, for the record, moves almost nothing: it contributes less than one per cent of the specification variance in the grid.\n\n## 8. Bayesian estimation with brms {#sec-bayes}\n\nThe multilevel framework has a natural next step. Partial pooling – every random effect shrunk towards the grand mean in proportion to its group's data – is already half the Bayesian idea, and hierarchical models are the setting where the full version pays for itself most clearly. The shift is one of interpretation before machinery. Frequentist estimation asks \"what parameter values make this data likeliest?\" and attaches uncertainty via imagined repeated sampling. **Bayesian** estimation treats the parameters themselves as uncertain quantities, starts from a **prior** distribution $p(\\theta)$ expressing what is plausible before the data, and updates it through the likelihood into a **posterior**:\n\n$$ p(\\theta \\mid y) \\;\\propto\\; p(y \\mid \\theta)\\; p(\\theta) $$\n\nEverything you report – point estimates, intervals, probabilities of direction – is then read directly off the posterior distribution. For hierarchical models this buys three concrete things: group-level variances carry their full uncertainty even with few groups (our ten years are few), every derived quantity inherits that uncertainty rather than a plug-in point estimate, and the assumptions that frequentist multilevel models make implicitly become visible, stated priors you can inspect and vary.\n\nSpelled out, the three ingredients read like a recipe. The **likelihood** $p(y \\mid \\theta)$ is the model itself – exactly the multilevel equations of section 6, read as a statement of how probable the observed data are under candidate parameter values. The **prior** $p(\\theta)$ says what is plausible for each parameter before the data arrive; here, mild commitments like \"the between-country standard deviation is positive and probably not enormous\". Their product, renormalised, is the **posterior** $p(\\theta \\mid y)$: a full probability distribution over all the parameters jointly, of which any coefficient table is only a summary. For real models that distribution has no closed form, so it is explored by sampling – **Markov chain Monte Carlo** draws thousands of parameter values whose long-run frequencies match the posterior, and the modern samplers (Stan's Hamiltonian Monte Carlo, underneath everything below) have made this routine for exactly the hierarchical models this page has been building. Inference then *is* the summarising of draws: a posterior mean, an interval containing 95% of them, the share of them below zero. Two books carry a reader from this page to fluency. Gelman and Hill's classic [-@GelmanHill2007DataAnalysisUsing] is the bridge from single-level regression to multilevel and Bayesian thinking – its statistical chapters have aged well, though its software examples predate Stan and should not be typed in. McElreath's *Statistical Rethinking* [-@McElreath2020StatisticalRethinkingBayesian] is the modern course-style introduction, and its examples exist in a free online translation into brms and tidyverse code [@Kurz2023StatisticalRethinkingBrms] that pairs naturally with everything on this page.\n\nThe **brms** package [@Burkner2017BrmsPackageBayesian] makes the transition almost frictionless: it accepts the same formula syntax as `lmer()`, translates the model to Stan, and estimates it by Markov chain Monte Carlo (MCMC) – four independent 'chains' wandering the posterior, whose agreement is itself the convergence diagnostic. Here is section 5's aggregate random-intercept model, now with a year intercept alongside, in its Bayesian form. This one uses the committed panel, so you can run it yourself; it compiles for about a minute and samples in seconds:\n\n$$ \\bar{y}_{ct} \\sim N\\!\\left( \\gamma_0 + \\beta x_{ct} + v_c + w_t,\\; \\sigma^2 \\right), \\qquad v_c \\sim N(0, \\sigma_v^2), \\quad w_t \\sim N(0, \\sigma_w^2) $$\n\n```r\nlibrary(brms)\n\nm_bayes <- brm(mcosmo ~ unemp + (1 | cntry) + (1 | year), data = euframes,\n               backend = \"cmdstanr\", chains = 4, iter = 4000, seed = 2026)\nsummary(m_bayes)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: mcosmo ~ unemp + (1 | cntry) + (1 | year) \n   Data: euframes (Number of observations: 270)\n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nMultilevel Hyperparameters:\n~cntry (Number of levels: 27) \n              Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nsd(Intercept)   0.0627    0.0098   0.0471   0.0847 1.0028     1254     1945\n\n~year (Number of levels: 10) \n              Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nsd(Intercept)   0.0184    0.0063   0.0094   0.0333 1.0020     1862     3555\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nIntercept   0.5383    0.0157   0.5077   0.5691 1.0011     1019     1805\nunemp      -0.0036    0.0009  -0.0054  -0.0018 0.9998     5858     6558\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nsigma   0.0378    0.0018   0.0345   0.0414 1.0005     4855     5142\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nThe output's vocabulary maps onto what you already know, with meanings upgraded. **Estimate** is now the posterior mean and **Est.Error** the posterior standard deviation – the analogues of coefficient and standard error. The **l-95% / u-95% CI** columns are a **credible interval**, and unlike the confidence interval it means what everyone wants intervals to mean: given model and data, the parameter lies in this range with 95% probability. The genuinely new columns are the diagnostics. **Rhat** compares the four chains' answers; at convergence it is 1.00, and values above about 1.01 mean the sampler has not settled and the numbers should not be used. **Bulk_ESS** and **Tail_ESS** are effective sample sizes – how many independent draws the correlated MCMC samples are worth. And the `Multilevel Hyperparameters` block shows the machinery earning its keep: `sd(Intercept)` for `year` is estimated at 0.018 with an interval running from 0.009 to 0.033, a candid statement of how little ten years can say about a between-year variance, where a frequentist fit would hand you a bare point estimate.\n\nNotice where the slope itself landed: −0.0036, between the country-only random-effects estimate (−0.0053) and the two-way fixed-effects anchor (−0.0035), because the year intercepts absorb the common yearly shocks much as the year fixed effects did. That placement is a property of the model, not of the Bayesian machinery, and the direct check is to fit the same model by REML – its exact frequentist twin, live on the committed panel:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_freq_twin <- lmer(mcosmo ~ unemp + (1 | cntry) + (1 | year), data = euframes)\nsummary(m_freq_twin)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Std. Error        df   t value     Pr(>|t|)\n(Intercept)  0.538805859 0.0147467137  54.01694 36.537351 9.024290e-40\nunemp       -0.003638517 0.0008628051 251.41246 -4.217079 3.455893e-05\n```\n\n\n:::\n:::\n\n\nIdentical to the displayed posterior within Monte Carlo error: −0.0036 with a standard error of 0.0009 against a posterior mean of −0.0036 with an Est.Error of 0.0009. With 270 observations and weak priors, Bayesian and frequentist answers agree, as they should – the data dominate. The traditions come apart, in exactly the direction this section opened with, where data are thin: compare the twins' between-year variance statements, a bare REML point estimate against a full posterior interval.\n\nThe priors this model ran with are inspectable, and inspecting them is the habit to build:\n\n```r\nprior_summary(m_bayes)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                  prior     class      coef group resp dpar nlpar lb ub tag\n                 (flat)         b                                          \n                 (flat)         b     unemp                                \n student_t(3, 0.5, 2.5) Intercept                                          \n   student_t(3, 0, 2.5)        sd                                  0       \n   student_t(3, 0, 2.5)        sd           cntry                  0       \n   student_t(3, 0, 2.5)        sd Intercept cntry                  0       \n   student_t(3, 0, 2.5)        sd            year                  0       \n   student_t(3, 0, 2.5)        sd Intercept  year                  0       \n   student_t(3, 0, 2.5)     sigma                                  0       \n       source\n      default\n (vectorized)\n      default\n      default\n (vectorized)\n (vectorized)\n (vectorized)\n (vectorized)\n      default\n```\n\n\n:::\n:::\n\n\nbrms's defaults are deliberately mild: flat on the slope, a Student-t centred on the data's own median for the intercept, and half-Student-t distributions keeping the variance components positive but otherwise unconstrained. Priors are stated assumptions, which makes them arguable – and re-fitting under different reasonable priors, exactly as the workshop re-fits under different reasonable specifications, is the Bayesian wing of the same robustness discipline. The person-level extension is a one-line change (the section 6 formula, `data = person`, and patience while 416,698 rows sample), and it is the gateway to the generalised models next.\n\n## 9. Beyond the continuous outcome: generalised models {#sec-glm}\n\nOne assumption has ridden along unexamined since section 2: that a Gaussian linear model is the right shape for this outcome. Strictly, it never was. Every framing scale in this case is bounded between 0 and 1; a Gaussian model has unbounded support, so a straight line extended far enough always predicts impossible values, and nothing inside `lm()` knows the walls exist. What changes between the two levels of the data is not whether that assumption is wrong but how much its wrongness costs, and one pair of pictures carries the whole argument:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same outcome at two levels. Left: the person-level cosmopolitan score is bounded, with heavy masses at exactly 0 (26% of respondents) and exactly 1 (25%) – a shape no Gaussian can imitate. Right: averaging within country-years produces 270 cell means huddled in mid-scale, far from either bound, where a Gaussian model is a safe working approximation despite being wrong in principle. The person-level distribution is plotted from committed aggregate counts (companion/_model-outputs/cosmo_dist.csv).](stats-methods_files/figure-html/fig-outcome-scales-1.png){#fig-outcome-scales width=768}\n:::\n:::\n\n\nAt the aggregate level (right panel) the cell means bunch in the middle of the scale, several residual standard deviations clear of either bound. Fitted values from the models of sections 2 to 5 never approach the walls, the probability the Gaussian error places beyond them is negligible, and the approximation is safe *in practice* – safe because of where this particular outcome happens to sit, not because the model respects the bounds. That is a judgement to make consciously, and to re-make whenever an outcome drifts towards its floor or ceiling. At the person level (left panel) the judgement reverses emphatically. A respondent's score is the share of their mentioned items that are cosmopolitan: a quarter of all respondents sit at exactly 0 and another quarter at exactly 1, and a Gaussian model treats those pile-ups as ordinary noise around a middle that describes almost nobody. The **generalised linear model** (GLM) family fixes the shape problem by modelling a *transformed* mean:\n\n$$ g\\!\\left( \\mathbb{E}[y_i] \\right) = \\eta_i = \\beta_0 + \\beta_1 x_i $$\n\nThe **linear predictor** $\\eta_i$ stays a familiar straight line; the **link function** $g$ maps the outcome's constrained mean onto the unconstrained line, and a distribution suited to the outcome's actual support replaces the Gaussian.\n\nThe classic member is **logistic regression**, for binary outcomes, with the log-odds link. Collapsing our outcome to \"mentions at least one cosmopolitan item\":\n\n$$ \\log \\frac{p_i}{1 - p_i} = \\beta_0 + \\beta_1 x_i, \\qquad p_i = \\Pr(y_i = 1) $$\n\n```r\nm_logit <- glm(I(cosmo > 0) ~ unemp, family = binomial(), data = person)\nsummary(m_logit)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = I(cosmo > 0) ~ unemp, family = binomial(), data = person)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.262274   0.008360  151.00   <2e-16 ***\nunemp       -0.026735   0.000837  -31.94   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 481477  on 416697  degrees of freedom\nResidual deviance: 480478  on 416696  degrees of freedom\nAIC: 480482\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nReading a GLM's coefficients takes one extra step, because the estimate lives on the link scale. The slope of −0.027 is a change in *log-odds* per unemployment point; exponentiating gives an odds ratio of $e^{-0.027} \\approx 0.974$, and the quick 'divide by four' rule bounds the probability change at about −0.027 / 4 ≈ −0.7 percentage points per unemployment point at most. The `z value` replaces `t` (the dispersion is fixed, not estimated) and **deviance** replaces R-squared as the fit currency. And one number should now trigger the section 3 alarm: z = −31.9 is the pooled-independence illusion again, 416,698 respondents counted as if each were fresh evidence about 270 unemployment values. The generalised and multilevel machineries are not rivals; they are two orthogonal upgrades, and this outcome needs both at once.\n\nFor a *bounded continuous* outcome the classical tool is **beta regression**, which models a variable on the open interval (0, 1) with a logit-linked mean and a precision parameter $\\phi$. Its defect for our variable is those endpoint masses: the beta distribution has no probability at exactly 0 or 1, and the traditional dodge of nudging the data inward is exactly the kind of silent choice this workshop exists to make visible. **Ordered beta regression** [@Kubinec2023OrderedBetaRegression] repairs it at the root: one model with ordered cutpoints deciding whether an observation is exactly 0, in between, or exactly 1, and a beta distribution for the middle – one coefficient vector governing all three parts, so the slope keeps a single interpretation.\n\nBoth of the day's inferential traditions implement it. The frequentist route is **glmmTMB** [@BrooksEtAl2017GlmmTMBBalancesSpeed], a fast maximum-likelihood engine for GLMs with random effects – here with the full three-level structure of section 6, on all 416,698 respondents:\n\n```r\nlibrary(glmmTMB)\n\nm_ordfreq <- glmmTMB(cosmo ~ unemp + (1 | cntry) + (1 | cntry:year),\n                     family = ordbeta(), data = person)\nsummary(m_ordfreq)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: ordbeta  ( logit )\nFormula:          cosmo ~ unemp + (1 | cntry) + (1 | cntry:year)\nData: person\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n 683220.8  683297.4 -341603.4  683206.8    416691 \n\nRandom effects:\n\nConditional model:\n Groups     Name        Variance Std.Dev.\n cntry      (Intercept) 0.015782 0.1256  \n cntry:year (Intercept) 0.006162 0.0785  \nNumber of obs: 416698, groups:  cntry, 27; cntry:year, 270\n\nDispersion parameter for ordbeta family (): 9.28 \n\nConditional model:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.183815   0.028629   6.421 1.36e-10 ***\nunemp       -0.011789   0.001665  -7.080 1.44e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe output assembles pieces you now recognise: variance components for the two grouping levels (on the latent logit scale, so not directly comparable with section 6's), a dispersion parameter ($\\phi$ = 9.3, the beta precision), and a conditional-model slope of −0.012 on the logit scale with z = −7.1 – the divide-by-four rule translates it to at most −0.3 percentage points of cosmopolitan share per unemployment point, the same order as every Gaussian estimate of it, now from a model whose predictions cannot leave the unit interval. Note the z of −7, not −32: the random effects are doing the clustering work the bare logistic model ignored.\n\nThe Bayesian route is **ordbetareg**, Kubinec's own implementation of the model on top of brms [@Kubinec2023OrderedBetaRegression]. The exhibit below runs on a random subsample of 20,000 respondents – the full-data posterior would sample for hours, and the purpose here is the output's shape, not a production estimate:\n\n```r\nlibrary(ordbetareg)\n\nset.seed(2026)\nperson_sub <- slice_sample(person, n = 20000)\nm_ordbayes <- ordbetareg(cosmo ~ unemp + (1 | cntry), data = person_sub,\n                         true_bounds = c(0, 1), backend = \"cmdstanr\",\n                         chains = 4, iter = 2000, seed = 2026)\nsummary(m_ordbayes)\n```\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: ord_beta_reg \n  Links: mu = identity \nFormula: cosmo ~ unemp + (1 | cntry) \n   Data: data (Number of observations: 20000) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nMultilevel Hyperparameters:\n~cntry (Number of levels: 27) \n              Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nsd(Intercept)   0.1305    0.0209   0.0962   0.1782 1.0051      647     1264\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nIntercept   0.1508    0.0316   0.0894   0.2107 1.0163      464     1126\nunemp      -0.0078    0.0020  -0.0118  -0.0038 0.9998     4370     3540\n\nFurther Distributional Parameters:\n        Estimate Est.Error l-95% CI u-95% CI   Rhat Bulk_ESS Tail_ESS\nphi       9.2926    0.1278   9.0450   9.5445 1.0009     3555     2674\ncutzero  -0.9643    0.0170  -0.9976  -0.9314 1.0000     3123     3302\ncutone    0.7709    0.0085   0.7543   0.7878 1.0002     3138     3064\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nEverything in it combines sections 8 and above, and it rewards the discipline of reading diagnostics first – because doing so catches something. The intercept's Rhat of 1.016 sits above the 1.01 bar, so its chains have not fully settled; in a production analysis the response would be to sample longer before using that parameter. The slope, by contrast, is clean (Rhat at 1.00, effective sample sizes in the thousands), and its posterior – −0.008 on the logit scale, credible interval −0.012 to −0.004 – agrees with the full-data glmmTMB estimate while being less precise on a twentieth of the data. The family's extra distributional parameters close the loop: `cutzero` and `cutone` are the ordered cutpoints governing the exact-0 and exact-1 masses, and `phi`, the beta precision, posts 9.29 where glmmTMB's maximum likelihood put it at 9.28 on all 416,698 respondents. Two estimation traditions, one model family, one answer.\n\nThe reason to know this model family goes back to the workshop's central finding: the fork that moves this case's results is the outcome's operationalisation, and how you model the outcome's *distribution* is part of that fork. Treat the family as one more binary fork, Gaussian versus beta, both defensible for a bounded scale, and every universe it touches doubles. For the aggregated grid the doubling is computed, not hypothetical. The committed `data/spec_grid_family.csv` holds **the family universe of 1,680 specifications** – the canonical 840, imported verbatim, plus a beta twin of each – built by `companion/_model-outputs/build_family_grid.R` from the committed panel and grid alone. The file sits on the [specification menu](../exercise/spec-menu.qmd) as a first-class axis, and one label travels with it everywhere: the family axis is a **workshop extension**, not part of the Multi100 menu.\n\nA second extension works the predictor side of the same lesson. Multi100's Task 2 fixed unemployment as the measure of poor economic performance, but Task 1 shows three of the five analysts, left free, chose GDP measures instead – and OA's own operationalisation used both. The committed `data/spec_grid_full.csv` therefore adds GDP growth as a second, claim-carrying predictor: raw form, alone or beside unemployment as a co-predictor, 840 cells across both outcome families, taking the full universe to 2,520 (the family universe of 1,680 rows plus these 840 growth rows). Only the raw form is fitted, deliberately. Affine transforms – centring, z-standardising – rescale a coefficient without moving its t, p or partial correlation, so on an r-ranked curve they would only ever duplicate a point that is already there. That is exactly why the canonical grid keeps a single raw-and-log pair per specification rather than the four affine variants it once carried, and it is also part of why the predictor-form fork's share of specification variance is essentially zero. The growth universe's own result is the two-indicator construct speaking: the direction agrees with the claim about as often as unemployment's (70.5%), but significance falls below half (46.9%).\n\nThe twins are plain logit-link beta regressions on the cell means, well defined because the 270 means sit strictly inside the unit interval, as the right panel above showed, with none of the endpoint masses that force the ordered-beta repair at the person level. betareg carries the pooled and fixed-effects designs, with the fixed effects as country and year dummies and the pooled errors cluster-robust by country. glmmTMB's `beta_family()` carries the random-effects design, and section 5's weighted random-effects exclusion is mirrored, 120 cells per family. A beta model reports a z statistic rather than a t, and that changes nothing downstream. The [section 10](#sec-onescale) conversion $r = z / \\sqrt{z^{2} + \\mathit{df}}$ reads a z exactly as the record read analyst PRL47's, so every twin lands on the common axis unchanged; the grid also evaluates each twin's significance against the same t reference its Gaussian sibling uses, a deliberate uniformity that matters only in the third decimal place at 100-plus df. Both halves can be checked straight from the committed file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_csv(\"../data/spec_grid_family.csv\", show_col_types = FALSE) |>\n  group_by(family) |>\n  summarise(specifications = n(),\n            claim_direction = mean(supports_claim))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  family   specifications claim_direction\n  <chr>             <int>           <dbl>\n1 beta                840           0.710\n2 gaussian            840           0.687\n```\n\n\n:::\n:::\n\n\nTwo facts in the twins are worth carrying away. The Gaussian half posts the canonical shares, 68.7% of specifications in the claim's direction and 63.9% significant; the beta half posts 71.0% and 63.1%. The beta twin of the workshop's anchor – `mcosmo`, raw predictor, no co-predictor, two-way fixed effects, all years, unweighted – estimates a logit-scale slope of −0.014 with **z = −4.075**, converting to a partial correlation of **−0.258** against the Gaussian anchor's −0.242. Same direction, still significant, slightly stronger. And the wrong-sign anatomy of section 3 reappears line for line. In the cosmopolitan universe each family holds exactly 41 wrong-sign specifications, 33 of them pooled and 8 two-way fixed effects. Run section 3's 'Try it' count on the family grid and the split repeats twice over. The family fork moves the numbers, not the lessons.\n\nThe person-level doubling, unlike the aggregated one, is arithmetic rather than computation. Carrying the family fork down a level meets one substitution the person-level data force: the person-level scales place real mass on exact zeros, so the beta likelihood is unavailable there and a logit-link fractional-response binomial would stand in as each cell's twin (reverse-coding stays exact, since the flip works through the same logit identity). That takes the person-level universe to 3,840 specifications and the joint universe to 5,520, none of it computed. The lesson the arithmetic teaches: universes grow geometrically, one defensible fork at a time, and the discipline is not to run the largest universe you can afford but to state in advance which forks you consider defensible and why. That statement is precisely what a preregistration is for.\n\n## 10. From many results to one axis: meta-analysis and standardised effects {#sec-onescale}\n\nThe five Multi100 analysts fitted different models, in different software, at different levels of analysis, so their raw coefficients are not comparable: a Stata pooled coefficient, an R fixed-effects coefficient and a person-level multilevel coefficient are not the same kind of number. The discipline with a century of practice at exactly this problem is **meta-analysis**, and its machinery is worth meeting properly before seeing what Multi100 borrowed from it – not least because that machinery turns out to be an old friend.\n\nMeta-analysis starts from $K$ estimates $\\hat\\theta_k$, each with a known sampling variance $v_k$ (from its standard error). The **equal-effects** model assumes one true value $\\theta$ behind them all and pools by inverse-variance weighting, so precise studies count for more:\n\n$$ \\hat\\theta_{\\text{EE}} = \\frac{\\sum_k \\hat\\theta_k / v_k}{\\sum_k 1 / v_k} $$\n\nThe **random-effects** model drops the one-true-value assumption and lets the true effects themselves vary between studies:\n\n$$ \\hat\\theta_k = \\mu + u_k + e_k, \\qquad u_k \\sim N(0, \\tau^2), \\quad e_k \\sim N(0, v_k) $$\n\nHere $\\mu$ is the average true effect, $\\tau^2$ the between-study variance, and $e_k$ each study's sampling error. Look at that equation twice and section 6 looks back: a random-effects meta-analysis **is a two-level multilevel model** – studies as level-2 units, random intercepts $u_k$ – with a single twist, that the level-1 variances $v_k$ are not estimated but *known*, imported from each study's standard error. That is the whole difference between the two traditions. Heterogeneity statistics then quantify the between-study spread: $\\tau$ on the effect's own scale, Cochran's $Q$ as a test, and $I^2$ as the share of total variability that is real between-study difference rather than sampling noise.\n\nFor correlations, the conventional pooling scale is **Fisher's z** transformation, $z = \\operatorname{atanh}(r)$, whose sampling variance depends only on sample size, $v = 1/(n - 3)$. The five analysts' recorded partial correlations are in the committed `analysts5.csv`, so the standard tool – the metafor package [@Viechtbauer2010ConductingMetaanalysesMetafor] – can run on them live:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(metafor)\n\nanalysts <- read_csv(\"../data/analysts5.csv\", show_col_types = FALSE) |>\n  mutate(zi = atanh(r), vi = 1 / (n - 3))\n\nma_re <- rma(yi = zi, vi = vi, data = analysts, method = \"REML\", slab = analyst_id)\nma_re\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRandom-Effects Model (k = 5; tau^2 estimator: REML)\n\ntau^2 (estimated amount of total heterogeneity): 0.0472 (SE = 0.0347)\ntau (square root of estimated tau^2 value):      0.2172\nI^2 (total heterogeneity / total variability):   99.97%\nH^2 (total variability / sampling variability):  3250.05\n\nTest for Heterogeneity:\nQ(df = 4) = 31765.7952, p-val < .0001\n\nModel Results:\n\nestimate      se     zval    pval    ci.lb    ci.ub    \n -0.2481  0.0991  -2.5035  0.0123  -0.4423  -0.0539  * \n\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nRun as a demonstration, this output is worth every line; run as an analysis, it would be seriously wrong, and both halves are the lesson. The heterogeneity block first: $I^2$ = 99.97%. In a genuine meta-analysis that number would say the studies barely share a phenomenon; here it says something cleaner, because we *know* all five results come from the same data and claim. Sampling error explains essentially none of the spread between the five analysts – the spread is analytic variation, choices about outcome, estimator, level and df, which is precisely the multiverse's subject read off a meta-analytic dial. The pooled estimate, by contrast, should not be believed even as arithmetic: meta-analysis assumes independent studies, and five reanalyses of one dataset are the textbook violation. The weighting adds its own distortion – the two person-level analysts enter with $v_k$ built from six-figure respondent counts, so the equal-effects pooled value (run `method = \"EE\"` yourself: −0.17) is mostly their voice, inheriting exactly the df problem section 6 dissected. Multi100's design takes the point: it borrowed meta-analysis's *standardisation* step, but deliberately not its *pooling* step, reporting the distribution of results rather than an average pretending to independence.\n\nMeta-analysis's native picture, the **forest plot**, makes the same case at a glance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest(ma_re, atransf = tanh, refline = 0,\n       xlab = \"partial correlation r (back-transformed from Fisher's z)\",\n       header = c(\"Analyst\", \"r [95% CI]\"))\n```\n\n::: {.cell-output-display}\n![The five Multi100 analysts as a forest plot. Each row is one analyst's partial correlation with its 95% interval, back-transformed from Fisher's z; the two person-level analysts' intervals are vanishingly narrow because their sampling variances are computed from six-figure respondent counts – the df problem in visual form. The diamond at the bottom is the random-effects pooled estimate. In a genuine meta-analysis the diamond would be the result; here the plot's real message is the spread, which the pooling assumptions cannot explain.](stats-methods_files/figure-html/fig-forest-1.png){#fig-forest width=720}\n:::\n:::\n\n\n### What the five analysts actually did {#sec-analysts}\n\nThe five reanalyses were not free-for-alls. Multi100's Task 2 fixed both ends of the question – use the positive non-materialist (cosmopolitan) form of EU framing as the outcome, use the unemployment rate as the measure of poor economic performance, and disregard the paper's EU-policy and party-politicisation contextual variables – and left everything between them open. What each analyst did with that freedom, read off their public code:\n\n| Analyst | Data as analysed | Outcome construction | Predictor | Controls | Estimator | SEs and df |\n|---|---|---|---|---|---|---|\n| 018OL | 420 country-by-wave cell means, EU-27 | mean of the 5 items, rescaled 0–1 | unemployment 15–74, raw | none | crossed random intercepts: country, year, EB wave | Satterthwaite, 396.9 |\n| **C6HJR** | **270 country-years** | **cosmopolitan share, corrected panel** | **unemployment, centred** | **none** | **two-way FE: country + year** | **conventional, 233** |\n| KEVF1 | 209,826 respondents | sum of the 5 items (0–7) | unemployment, raw | none | nested random intercepts: year within country | Satterthwaite, 135.6 |\n| KQXUE | 270 country-years | cosmopolitan share | unemployment 20–64, raw | none | one-way country FE | conventional, 242 |\n| PRL47 | 394,575 respondents | cosmopolitan share, no-opinion coded 0 | unemployment 25–64, raw + yearly change | gender, age, education, occupation, rural, crisis dummy, log GDP, growth | three-level: respondent in country-quarter in country | Wald z, no df |\n\nThat brief, though, was the *second* act of Multi100's two-phase design [@AczelEtAl2026InvestigatingAnalyticalRobustness]. Task 1, months earlier, was free: analysts \"could conduct and report as many analyses as they wished, but they had to draw a single conclusion\". What freedom produced belongs beside the standardised table:\n\n| Analyst | Free-phase predictor | Free-phase outcome | Recorded verdict |\n|---|---|---|---|\n| 018OL | GDP per capita (level, Eurostat) | positive framing, 7-item mean | evidence for the claim |\n| KEVF1 | GDP growth (Eurostat) | positive framing, 7-item sum | evidence for the claim |\n| PRL47 | log GDP + quarterly growth + crisis dummy | three positive-framing shares | evidence for the claim |\n| KQXUE | GDP growth and unemployment (Eurostat) | cosmopolitan + utilitarian shares | evidence for the claim |\n| **C6HJR** | **GDP growth and unemployment (World Bank)** | **positive framing, 7-item share** | **evidence for the claim** |\n\nThree of the five never used the unemployment rate until the instructions named it; most were not using the non-materialist outcome the instructions fixed. Yet all five recorded the same categorical Task-1 verdict, because Task 1 asked for a conclusion, not a number – no standardised Task-1 effect sizes exist anywhere in the project's public data. The instructions therefore did not trim covariates from five similar models; they *created* the common question the standardised results answer. Read together, the two phases separate two robustness claims that are easily conflated: the five free analyses agreed in words, and the five standardised estimates, finally comparable, disagreed across a 75-fold range. This workshop runs the arc in reverse – participants start from the standardised baseline and open one axis at a time – so the day's freedom arrives as a menu rather than a blank page.\n\nEvery row of the standardised table is a defensible reading of the same brief, and the table explains the numbers that puzzle first-time readers. The Ns differ because the units differ. KQXUE and C6HJR collapsed respondents to 270 country-year means; 018OL kept the survey wave as its own grouping level, giving 420 country-by-wave cells; KEVF1 and PRL47 modelled respondents directly, and even their two Ns disagree for pipeline reasons – KEVF1 merged an unemployment series with full country coverage only from 2009 (2004–2008 exists only for France), so complete-case fitting halved the stacked file to 209,826, while PRL47's EU-27 filter and respondent-level controls left 394,575. The dfs then differ because each model keeps its own account of where the information about a country-year predictor lives: fixed-effects OLS counts observations minus parameters, the Satterthwaite approximation estimates an effective df (397 on 420 cells, but 136 on 209,826 respondents, because the predictor varies only across country-years and the approximation knows it), and Stata's `mixed` reports an asymptotic z with no residual df at all. The conversion machinery below turns those choices into the numbers on the common axis.\n\nThe standardisation step is this. Every recorded result is converted to a **partial correlation** from just two numbers, the test statistic and its degrees of freedom:\n\n$$ r = \\frac{t}{\\sqrt{t^{2} + \\mathit{df}}} $$\n\nFeed it any model's `t` (or `z`) and df, and it returns a number between −1 and 1 that a Stata pooled model, an R fixed-effects model and every class submission can be read on together. This is the exact conversion the workshop's `report_result()` helper applies before a dot lands on the multiverse chart, and it is why Task 2 asked every analyst for a statistic and its degrees of freedom in the first place. The closely related Cohen's $d$ follows from the same $r$:\n\n$$ d = \\frac{2r}{\\sqrt{1 - r^{2}}} $$\n\nThe same pair of numbers also carries the significance verdict, and the conversion is worth stating alongside the effect-size one because the two run in opposite directions. A t statistic's two-sided p-value is the probability of a result at least as extreme when the true effect is zero – in R, `2 * pt(-abs(t), df)`. A z statistic runs the identical computation on the standard normal, `2 * pnorm(-abs(z))`, which is simply the t-distribution with its df sent to infinity; that is literally where PRL47's missing df entry went. The df matters only at the margins here: with 20 df the 5% threshold is |t| = 2.09, and by a hundred df it has effectively converged on the normal's 1.96. What matters far more is what each conversion does with the volume of data. The p-value asks whether the estimate stands out from zero *given* how much data went in, so at any fixed underlying effect it shrinks as n grows; the partial correlation divides the sample size back out. Feed both conversions the same t and df and they can disagree spectacularly about which results are 'big', which is exactly what the five analysts show:\n\n| Analyst | Tool | Model unit | Statistic | df | p (two-sided) | N | Partial r |\n|---|---|---|---|---|---|---|---|\n| 018OL | R | aggregate | t = −1.21 | 396.9 | .229 | 420 | −0.060 |\n| **C6HJR** | **R** | **country-year (270)** | **t = −3.80** | **233** | **< .001** | **270** | **−0.242** |\n| KEVF1 | R | person-level multilevel | t = −5.90 | 135.6 | < .001 | 209,826 | −0.452 |\n| KQXUE | Stata | country-year (270) | t = −7.17 | 242 | < .001 | 270 | −0.419 |\n| PRL47 | Stata | person-level multilevel | z = −3.59 | – | < .001 | 394,575 | −0.006 |\n\nEvery analyst found a negative effect, agreeing on direction, and four of the five clear the conventional significance bar decisively. Read the last two columns against each other, though, and the verdicts come apart. PRL47's z of −3.59 is unambiguously significant (p < .001) while converting to a partial correlation of −0.006 – significance carried by 394,575 respondents, not by the size of the effect. 018OL, the one non-significant row (p = .23), converts to an r ten times PRL47's. A p-value and a standardised effect are answers to different questions, and neither substitutes for the other. Yet the partial correlations run from −0.006 to −0.452, a factor of about 75, and the two person-level analysts sit at the opposite extremes. You have now seen the whole mechanism from the inside: KEVF1's conversion divides through a group-scale df of about 136, of the kind the three-level and random-slope fits of section 6 produce; PRL47's runs the respondent count through the denominator, of the kind the two-level fit produced. The same negative relationship, converted under two df conventions, becomes either a substantial correlation or a rounding error. The habit the workshop insists on follows: read the degrees of freedom before reading the effect size, because a converted number is only as meaningful as the df behind it.\n\nThe common axis is also what makes the workshop's central result legible. Decomposing the 840-specification grid to ask which analytical fork moves the estimate most gives an unambiguous answer:\n\n| Analytical fork | Share of specification variance |\n|---|---|\n| Outcome (which framing scale) | ≈ 49.7% |\n| Estimator + predictor form + co-predictor + weights (combined) | < 2% |\n\nThe choice of outcome – which of the four framing dimensions, or their positive and negative composites, you treat as 'EU framing' – accounts for roughly half of all the variation across the grid. Everything else the menu lets you vary, the estimator tour of sections 3 to 6 included, together moves the result by under two per cent. Two qualifications keep that number readable. The decomposition is computed on the grid as estimated, before the claim-alignment convention the workshop's charts apply for display. Part of the outcome share is therefore the polarity split between positive and negative framings: real variation in what the specifications estimate, which the aligned chart removes from the picture but not from the decomposition. Recomputed on the claim-aligned scale in the facilitator's extended analysis of the same grid, the ranking inverts, with the estimator fork rising to about 58% and the outcome fork falling to roughly 11–12%; once every outcome points the same way, the pooled-versus-within contrast of section 5 becomes the biggest mover. The outcome-family fork of section 9, meanwhile, barely registers: across the family universe of 1,680 rows the Gaussian-versus-beta choice accounts for under 1% of claim-aligned specification variance, and the two family curves all but coincide.\n\nThe lesson participants leave with survives every recount. Deciding what 'EU framing' means – which scale, and which polarity – sets what a model estimates before the machinery of sections 3 to 6 gets its say, and modelling the outcome's *distribution* matters far less than choosing the outcome itself. For what a specification curve can and cannot conclude once all those results are on one axis, the workshop's [reading on the specification curve](../exercise/reading-inference.qmd) picks up exactly here.\n\n## Sources and provenance {#sec-sources}\n\nThis module is written fresh for the workshop rather than adapted from an existing lesson, and every number in it is computed, not quoted. The models of sections 2 to 5 and the meta-analysis of section 10 execute on this page from the committed files (`EUframes_cy.csv`, `rep_data.csv`, `analysts5.csv`, `spec_grid.csv`); the country-year construction and item definitions are in the [data codebook](../data/EUframes_cy_codebook.md). The person-level and Bayesian outputs of sections 6 to 9 were produced by `companion/_model-outputs/fit_models.R` in the site's source repository, run against the person-level rebuild of the sixteen GESIS waves; the raw microdata are GESIS-licensed and never travel with the workshop – the [repositories module](repositories.qmd#sec-gesis) explains the registration route. The Stata excerpts in section 7 are from analysts PRL47's and KQXUE's public Multi100 materials; the Task-1 free-phase recipes and recorded verdicts in section 10 come from the same analysts' public code and the Multi100 project's public dataset [@AczelEtAl2026InvestigatingAnalyticalRobustness]. The wrong-sign counts, the 840-versus-960 arithmetic, and the claim-direction and significance shares come from `spec_grid.csv`; the fork-importance decompositions (outcome ≈ 49.7% of specification variance as estimated, estimator ≈ 58% on the claim-aligned scale) come from the facilitator's extended analysis of the same grid; the 3,840- and 5,520-specification universes of sections 6 and 9 are menu arithmetic, not computed analyses. The exhibit fits on this page are illustrations of each method; nothing beyond them is computed on the microdata.\n\nThe methods and software cited above are gathered in the reference list below: the panel estimators [@BergeEtAl2026FastUserfriendlyEconometrics; @CroissantMillo2023PanelDataEconometrics], within–between modelling [@BellJones2015ExplainingFixedEffects], the multilevel workhorse [@BatesEtAl2015FittingLinearMixedeffects], survey-weighted estimation [@Lumley2004AnalysisComplexSurvey; @Rabe-HeskethSkrondal2006MultilevelModellingComplex; @Carle2009FittingMultilevelModels; @BaileyEtAl2023WeMixWeightedMixed; @GESISWeightingOverview], Bayesian estimation and its textbooks [@Burkner2017BrmsPackageBayesian; @GelmanHill2007DataAnalysisUsing; @McElreath2020StatisticalRethinkingBayesian; @Kurz2023StatisticalRethinkingBrms], the generalised models [@BrooksEtAl2017GlmmTMBBalancesSpeed; @Kubinec2023OrderedBetaRegression], and meta-analysis [@Viechtbauer2010ConductingMetaanalysesMetafor].\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "stats-methods_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/rglWebGL-binding-1.3.36/rglWebGL.js\"></script>\n<link href=\"../site_libs/rglwidgetClass-1.3.36/rgl.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/rglwidgetClass-1.3.36/rglClass.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/utils.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/buffer.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/subscenes.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/shaders.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/shadersrc.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/textures.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/projection.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/mouse.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/init.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/pieces.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/draw.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/controls.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/selection.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/rglTimer.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/pretty.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/axes.src.js\"></script>\n<script src=\"../site_libs/rglwidgetClass-1.3.36/animation.src.js\"></script>\n<script src=\"../site_libs/CanvasMatrix4-1.3.36/CanvasMatrix.src.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}