{
  "hash": "12fe2f29d7dd714234c38c743f8b8ab4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The individual level\"\nsubtitle: \"The case fitted at the respondent level, on the real respondents and on their synthetic twin, and the second claim of the paper\"\nbibliography: [../references.bib, ../references-new.bib]\n---\n\n\n\nEvery other page on this site works at the country-year level: 270 rows, one per country and year, which is where the course exercise lives. The study underneath it did not. Its central result comes from a model fitted to individual survey respondents, and some things visible there are invisible from above.\n\nThis page fits that model. It is optional, it is not part of the workshop day, and it exists so that the individual-level version of the argument is available rather than merely described. It runs on two datasets, and section 2 says which is which: the real respondents, for anyone who has built the respondent file from their own GESIS downloads, and a synthetic twin of them, which ships with the course and on which every code chunk on this page runs. The closing section takes the same data to the second claim of the paper, the one about the education gap, which is intrinsically a claim about individuals inside countries. The original author is referred to throughout as OA, following the convention of the rest of the site.\n\n## 1. The level of analysis {#sec-why}\n\nThe claim is about countries: when a national economy performs badly, do the people in it frame the EU less positively? That is a statement about country-years, and the course panel answers it directly.\n\nBut the same words license a second reading. Perhaps unemployed *people* frame the EU differently, so a country with more of them shows a lower average without anything having changed for anyone else. The first reading is **contextual** – living through high unemployment changes how everyone frames the EU. The second is **compositional** – the mix of people changed, not the people.\n\nA country-year panel cannot separate them, because it contains no people. Individual data can, and this page does it.\n\n## 2. The two datasets {#sec-twin}\n\nThe Eurobarometer microdata behind the case are GESIS-licensed and cannot be redistributed, so this page cannot ship the real respondents. They are reachable all the same: the sixteen survey files download under a free GESIS account, and the workspace's build script turns them into one respondent file, `data_private/eb_respondents.rds`, whose [codebook](../data/eb_respondents_codebook.md) is published even though the file is not. The [data sources module](data-sources.qmd#sec-gesis) walks through the download and the [data management module](data-management.qmd) through the build. Every number on this page labelled \"real\" was computed on that file by a script in the course repository, and a reader who holds the file can rerun the script; the code chunks shown on the page run on the twin, so that the page renders for everyone, and swapping the twin for the respondent file in the setup chunk is a one-line change.\n\nWhat the course ships is a **synthetic twin**: `EUframes_person_full.csv`, 41,660 simulated respondents across the real 270 country-years, carrying every variable that OA's published regressions use. No real respondent appears in it. [The simulation module](simulation.qmd) explains how it is built; the short version is that a respondent's characteristics come from a correlation structure estimated on the real file, and their answers from a model of the survey instrument conditional on those characteristics.\n\nWhat licenses a number from it is the validation rather than the care in construction: the same model was fitted to the real respondents and to the twin, and the two coefficient vectors were compared.\n\n\n::: {#tbl-validation .cell tbl-cap='Every coefficient of OA\\'s published model, fitted on 416,698 real respondents and on the twin. The last column is the difference over the two-sample standard error.'}\n\n```{.r .cell-code}\nvalid |>\n  summarise(\n    `coefficients compared` = n(),\n    `within 1 standard error` = sum(abs(z) < 1),\n    `within 2 standard errors` = sum(abs(z) < 2),\n    `largest discrepancy` = round(max(abs(z)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  `coefficients compared` `within 1 standard error` `within 2 standard errors`\n                    <int>                     <int>                      <int>\n1                      64                        46                         60\n# ℹ 1 more variable: `largest discrepancy` <dbl>\n```\n\n\n:::\n:::\n\n\n60 of 64 agree within two standard errors, where roughly three would be expected to fall outside by chance alone. The comparison lives in `_model-outputs/twin_validation.csv` and can be read line by line.\n\nTwo cautions belong here rather than in a footnote. The yardstick above is the **two-sample** standard error, which asks whether a difference exceeds the sampling noise of the twin itself – the question that a reader quoting one of its numbers has. Judged instead against the precision that 416,698 respondents afford, only 39 agree; the twin holds a tenth as many people and cannot stand in at full precision. And the model validated is OA's specification with its cross-level interactions removed. The twin reproduces that. It is not validated for the interacted form, and should not be quoted for it.\n\n## 3. The published model {#sec-published-model}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- function(y) {\n  f <- reformulate(c(\"female\", \"mage\", \"edu3\", \"ses\", \"urban\",\n                     \"mgrowth\", \"munemp\", \"(1 | cntry)\", \"(1 | cy)\"),\n                   response = y)\n  lmer(f, data = twin, REML = FALSE)\n}\nm_cosmo <- fit(\"cosmo\")\n\nparameters::model_parameters(m_cosmo, effects = \"fixed\",\n                             ci_method = \"satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter           | Coefficient |       SE |         95% CI |     t\n---------------------------------------------------------------------\n(Intercept)         |        0.42 |     0.01 | [ 0.39,  0.44] | 29.85\nfemale              |    9.32e-03 | 3.59e-03 | [ 0.00,  0.02] |  2.59\nmage                |   -9.73e-04 | 1.45e-04 | [ 0.00,  0.00] | -6.72\nedu3 [mid]          |        0.05 | 4.62e-03 | [ 0.04,  0.06] |  9.99\nedu3 [high]         |        0.10 | 5.16e-03 | [ 0.09,  0.11] | 19.81\nses [self_employed] |        0.02 | 7.32e-03 | [ 0.01,  0.04] |  2.98\nses [manager]       |        0.06 | 6.66e-03 | [ 0.05,  0.07] |  9.00\nses [white_collar]  |        0.02 | 6.16e-03 | [ 0.01,  0.04] |  3.76\nses [house_person]  |        0.01 | 7.13e-03 | [ 0.00,  0.03] |  1.69\nses [unemployed]    |       -0.03 | 6.95e-03 | [-0.04, -0.01] | -4.00\nses [retired]       |        0.01 | 6.64e-03 | [ 0.00,  0.03] |  2.18\nses [student]       |        0.09 | 7.40e-03 | [ 0.07,  0.10] | 11.62\nurban [rural]       |       -0.02 | 4.39e-03 | [-0.03, -0.01] | -4.24\nurban [small_town]  |       -0.01 | 4.33e-03 | [-0.02,  0.00] | -3.03\nmgrowth             |   -5.22e-04 | 9.30e-04 | [ 0.00,  0.00] | -0.56\nmunemp              |   -5.44e-03 | 1.15e-03 | [-0.01,  0.00] | -4.75\n\nParameter           |       df |      p\n---------------------------------------\n(Intercept)         |    38.25 | < .001\nfemale              | 41515.07 | 0.009 \nmage                | 41506.86 | < .001\nedu3 [mid]          | 41502.28 | < .001\nedu3 [high]         | 41500.72 | < .001\nses [self_employed] | 41509.93 | 0.003 \nses [manager]       | 41509.45 | < .001\nses [white_collar]  | 41519.48 | < .001\nses [house_person]  | 41526.57 | 0.091 \nses [unemployed]    | 41508.04 | < .001\nses [retired]       | 41508.84 | 0.029 \nses [student]       | 41499.53 | < .001\nurban [rural]       | 41517.12 | < .001\nurban [small_town]  | 41512.23 | 0.002 \nmgrowth             |   263.65 | 0.575 \nmunemp              |   252.15 | < .001\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nUncertainty intervals (equal-tailed) and p-values (two-tailed) computed\n  using a Wald t-distribution with Satterthwaite approximation.\n```\n\n\n:::\n:::\n\n\nRead the macro terms first. A one-point rise in a country's unemployment rate goes with a fall of about 0.0054 in an individual's cosmopolitan framing score, net of who they are.\n\nNow read `sesunemployed`, which is the same respondent's own employment status. Being unemployed rather than a manual worker moves the score by -0.028 – roughly 5 times as much per unit. Individual circumstance matters far more to an individual than the national rate does.\n\nThat comparison is the one that people get wrong, so it is worth doing the arithmetic rather than eyeballing it.\n\n## 4. Individual effects and aggregate associations {#sec-composition}\n\nThe two coefficients above are not competing explanations of the same thing, and the units make the difference. The individual effect applies to whoever is unemployed. The contextual effect applies to everyone. So how much of the country-level association could the individual effect account for?\n\nThat depends on a quantity that neither coefficient contains: how much a country's unemployment rate changes *who is in the sample*. Measured on the real respondents, a one-point rise in the published rate adds 0.0074 to the share of respondents who are themselves unemployed – well under one percentage point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_ind  <- fixef(m_cosmo)[[\"sesunemployed\"]]\nb_ctx  <- fixef(m_cosmo)[[\"munemp\"]]\ngrad_w <- grad$gradient[2]\n\ntibble(\n  quantity = c(\"individual effect of being unemployed\",\n               \"extra unemployed share per point of the national rate\",\n               \"compositional contribution to the country-level slope\",\n               \"the country-level slope itself\",\n               \"compositional share of it\"),\n  value = c(b_ind, grad_w, b_ind * grad_w, b_ctx,\n            b_ind * grad_w / b_ctx)) |>\n  mutate(value = signif(value, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  quantity                                                  value\n  <chr>                                                     <dbl>\n1 individual effect of being unemployed                 -0.0278  \n2 extra unemployed share per point of the national rate  0.00743 \n3 compositional contribution to the country-level slope -0.000207\n4 the country-level slope itself                        -0.00544 \n5 compositional share of it                              0.038   \n```\n\n\n:::\n:::\n\n\nSo the compositional path accounts for roughly 4% of the country-level association. An effect several times the size, spread over a group that barely grows, moves the average hardly at all.\n\nOne caution about that figure. It is computed from the coefficients of the twin itself, and the unemployed contrast is where the twin does worst: it comes back at -0.0278 against -0.0350 on the real respondents, the largest single discrepancy in the validation table. Using the real value the compositional share is 4% rather than 4%. Both are small; the conclusion does not depend on which you use, and it is worth seeing a case where the twin is visibly imperfect and the argument survives anyway.\n\nThis is the calculation to demand whenever an aggregate association is explained by 'it must be the people who changed'. It is rarely done, and it usually does not survive being done. Note also what it takes: an individual-level effect, *and* a prevalence gradient. The second is the part that gets assumed, and it is measurable.\n\n## 5. Two designs {#sec-designs}\n\nThe course panel and OA's own model are both defensible readings of the same claim, and they do not agree.\n\n\n::: {#tbl-levels .cell tbl-cap='The unemployment coefficient on cosmopolitan framing under two designs. The aggregate model is C6HJR\\'s published Multi100 specification; the individual model is OA\\'s published one, fitted on the twin.'}\n\n```{.r .cell-code}\nagg <- lm(mcosmo ~ unemp + growth + factor(year) + factor(cntry), data = panel)\n\ntibble(\n  design = c(\"country-year panel, two-way fixed effects\",\n             \"individual, country and country-year random intercepts\"),\n  n = c(nrow(panel), nrow(twin)),\n  estimate = c(coef(agg)[[\"unemp\"]], fixef(m_cosmo)[[\"munemp\"]]),\n  removes_common_year_shocks = c(\"yes\", \"no\")) |>\n  mutate(estimate = signif(estimate, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  design                                       n estimate removes_common_year_…¹\n  <chr>                                    <int>    <dbl> <chr>                 \n1 country-year panel, two-way fixed effec…   270 -0.00356 yes                   \n2 individual, country and country-year ra… 41660 -0.00544 no                    \n# ℹ abbreviated name: ¹​removes_common_year_shocks\n```\n\n\n:::\n:::\n\n\nThe individual-level estimate is about half again as large, and the reason is in the last column. OA's design carries country and country-wave random intercepts but **no year effects**. Nothing in it removes a shock that hit every country at once, and 2009 was exactly that: unemployment rose everywhere and EU framing moved everywhere, for reasons that include but are not limited to unemployment. The two-way fixed-effects design removes it; OA's does not, so its estimate carries some of it.\n\nNeither is wrong. They are answers to different questions, which is the course argument arriving one level down – and it is worth noticing that the difference here is larger than most of the forks on the specification menu.\n\nThe sharper version is the libertarian dimension:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_lib <- fit(\"lib\")\nagg_lib <- lm(mlib ~ unemp + growth + factor(year) + factor(cntry), data = panel)\n\ntibble(design = c(\"country-year panel\", \"individual\"),\n       estimate = c(coef(agg_lib)[[\"unemp\"]], fixef(m_lib)[[\"munemp\"]]),\n       t = c(summary(agg_lib)$coefficients[\"unemp\", \"t value\"],\n             coef(summary(m_lib))[\"munemp\", \"t value\"])) |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  design             estimate     t\n  <chr>                 <dbl> <dbl>\n1 country-year panel 0.000105 0.193\n2 individual         0.00297  3.96 \n```\n\n\n:::\n:::\n\n\nOn the panel it is inert. At individual level it is clearly moving. An effect that exists or does not depending on which defensible design you chose is a strong argument for declaring the design before looking.\n\n## 6. Levels and evidence {#sec-levels}\n\nThe multilevel structure matters here for the standard error, and for what the model is willing to count as information.\n\n\n::: {#tbl-df .cell tbl-cap='One predictor, three random structures, fitted on the twin. The real-data values are read from a committed table produced by the same models on the 416,698 licensed respondents.'}\n\n```{.r .cell-code}\nml <- list(\n  \"country only\"            = cosmo ~ unemp + (1 | cntry),\n  \"country and country-year\" = cosmo ~ unemp + (1 | cntry) + (1 | cy),\n  \"with a random slope\"     = cosmo ~ unemp + (1 + unemp | cntry) + (1 | cy))\nkeys <- c(\"two_level\", \"three_level\", \"slopes\")\n\nimap(ml, \\(f, nm) {\n  m <- lmer(f, data = twin)\n  p <- coef(summary(m))[\"unemp\", ]\n  k <- keys[match(nm, names(ml))]\n  tibble(structure = nm,\n         twin_estimate = p[[\"Estimate\"]], twin_t = p[[\"t value\"]],\n         twin_df = p[[\"df\"]],\n         real_estimate = rv(k, \"unemp\"), real_df = rv(k, \"unemp\", \"df\"))\n}) |>\n  list_rbind() |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  structure                twin_estimate twin_t twin_df real_estimate  real_df\n  <chr>                            <dbl>  <dbl>   <dbl>         <dbl>    <dbl>\n1 country only                  -0.00534  -8.99 28910        -0.00479 391200  \n2 country and country-year      -0.00564  -5.24   251.       -0.00524    253. \n3 with a random slope           -0.00601  -2.95    15.4      -0.00571     18.9\n```\n\n\n:::\n:::\n\n\nIn the first row, declaring only the country level lets the model treat every respondent as fresh information about unemployment, and the degrees of freedom run into the tens of thousands – on the twin, and into the hundreds of thousands on the real file. But the predictor takes only 270 distinct values in the whole dataset. A model reporting six-figure degrees of freedom for a variable that varies 270 times is counting people as though they were countries.\n\nDeclare the country-year level and the same data answer differently: the estimate barely moves, and the degrees of freedom collapse to the order of the number of cells. That is the correct count, and the *t* falls accordingly.\n\nThe variance components tell the same story from the other side.\n\n\n::: {#tbl-vc .cell tbl-cap='Where the variation sits, on the twin and on the real respondents. Standard deviations, from the country and country-year model.'}\n\n```{.r .cell-code}\nm3 <- lmer(cosmo ~ unemp + (1 | cntry) + (1 | cy), data = twin)\nvc <- as.data.frame(VarCorr(m3))\n\ntibble(component = c(\"between countries\", \"between country-years\", \"between people\"),\n       twin = c(vc$sdcor[vc$grp == \"cntry\"], vc$sdcor[vc$grp == \"cy\"], sigma(m3)),\n       real = c(rv(\"three_level\", \"cntry: (Intercept)\"),\n                rv(\"three_level\", \"cy: (Intercept)\"),\n                rv(\"three_level\", \"Residual: NA\"))) |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  component               twin   real\n  <chr>                  <dbl>  <dbl>\n1 between countries     0.0646 0.0613\n2 between country-years 0.0446 0.0385\n3 between people        0.356  0.368 \n```\n\n\n:::\n:::\n\n\nPerson-to-person variation dwarfs everything else – around 95% of the total. That is the same fact as the shape of the outcome at this level, where a respondent who mentions two things and finds one of them cosmopolitan scores exactly one half: a lumpy, bounded, near-categorical variable whose scatter within any cell is enormous compared with the differences between cells. It is also why so many respondents buy so little precision about a country-level predictor.\n\nThe country-year component in the twin runs about a sixth above the real one, and the reason is worth knowing rather than smoothing over: its cells hold a tenth as many respondents, so their means are noisier, and some of that sampling noise is attributed to the cell level rather than to people. The country and residual components sit within a few per cent.\n\nPerson-level sample sizes advertise precision that the design does not possess whenever the predictor lives at a higher level. Two of the five Multi100 analysts fitted person-level models, and this is a large part of why their strengths of evidence differ so much from the other three.\n\n## 7. The limits of the dataset {#sec-limits}\n\nStated plainly, because a synthetic dataset that is trusted for the wrong things is worse than none.\n\n**It will support** the specification validated above and things close to it: the four framing dimensions, the published covariate set, country and country-year random structures, and the composition-against-context arithmetic. Coefficients from those may be quoted with the validation table beside them.\n\n**It will not support** three things. Anything at the survey-**wave** level, because the twin is built on 270 country-years and its finest cluster is the country-year, while the real file has sixteen waves across ten years. The **interacted** form of the published model, which was excluded from the validation deliberately: a synthesis built to reproduce a covariance structure does not reproduce a cross-level interaction unless it is put in. And analyses of **individual framing items**, since the twin reproduces the average salience of each item but not its country-by-country variation – no consequence for any model using the four dimension scores, which is every model here.\n\n**Its weight is not a survey weight.** `w1` reverses a deliberate over-sampling of younger respondents that the generator introduces so that weighting has something to correct. It is a teaching device with a known answer, not the Eurobarometer design weight, and it should not be read as one.\n\n::: {.callout-tip}\n## Try it\n\nFit the model of [section 3](#sec-published-model) again with `ses` removed, and watch what happens to `munemp`. It should barely move, and the reason is [section 4](#sec-composition): the compositional path is a few per cent of the total, so deleting the variable that carries it changes little.\n\nThen do the same with `mgrowth` removed, and with the country-year random intercept removed. One of those three matters far more than the others; find out which, on data whose answer you can check.\n:::\n\n## 8. Claim 2 – the education gap {#sec-claim2}\n\nThe paper's second hypothesis is about people inside countries, and it cannot be put to the 270-row panel at all. Its abstract states the finding in one sentence, and the sentence is the claim card for a second replication exercise, written in the style of the first:\n\n> \"…high unemployment rates affect the EU framing of high-educated citizens to a larger extent…\" (Teney 2016, p. 619), or, in the same abstract's other words, \"high unemployment rates are associated with a smaller gap between high- and low-educated citizens in the way they frame the EU\".\n\n> **Unemployment × high education → cosmopolitan EU framing: b = −0.0031, t = −6.93, p < .001** (Table 3, Model 1), beside an education gap of b = 0.0771 (t = 41.79) and an unemployment slope of b = −0.0034 (t = −4.03) at the lowest education band.\n\nThe estimand statement, in the form the [specification menu](../exercise/spec-menu.qmd#the-estimand-statement) uses: among respondents in the 27 member states surveyed between 2004 and 2013, the difference between high- and low-educated respondents in the association between the national unemployment rate, measured as the World Bank series, and cosmopolitan EU framing, built as the share of a respondent's mentions, comparing each country with itself over time. The quantity is an interaction: not the effect of unemployment, and not the effect of education, but how much the first differs by the second. That is what makes the claim individual-level. Education is a property of respondents, unemployment a property of country-years, and the question is whether people who differ on the first respond differently to the second.\n\n**Three ways to estimate it.** The published model is a three-level random-intercept model with the interaction terms and the full covariate set, fitted on the respondents. The same interaction can be fitted with country and year fixed effects instead of random intercepts, which absorbs the level of unemployment and leaves only its difference between bands identified, from the within-country movement of each band. And the interaction can be fitted on cells rather than respondents: the [education-band panel](../data/EUframes_cy_edu_codebook.md) holds one row per country, year and band, and a fixed-effects regression on its 810 rows, weighted by the respondents behind each mean, asks the same question of the same data one rung up the ladder. The first two were run on the real respondents; the third runs here, on public data, in a few lines:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_edu <- feols(mcosmo ~ edu3 * munemp + edu3 * mgrowth | cntry + year,\n               data = edu, weights = ~n, vcov = ~cntry)\nparameters::model_parameters(m_edu, keep = \"edu3|munemp\") |>\n  as.data.frame() |>\n  select(Parameter, Coefficient, SE, t, p) |>\n  mutate(across(where(is.numeric), \\(x) signif(x, 3))) |>\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_8896snxnh2elr2k0la52 = TinyTable.createTableFunctions(\"tinytable_8896snxnh2elr2k0la52\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '7', j: 1 }, { i: '7', j: 2 }, { i: '7', j: 3 }, { i: '7', j: 4 }, { i: '7', j: 5 } ], css_id: 'tinytable_css_jdvi3h5ca9880x943de4',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_ckrxnurgm8d2bcvscamc',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_8896snxnh2elr2k0la52.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_8896snxnh2elr2k0la52 td.tinytable_css_jdvi3h5ca9880x943de4, #tinytable_8896snxnh2elr2k0la52 th.tinytable_css_jdvi3h5ca9880x943de4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_8896snxnh2elr2k0la52 td.tinytable_css_ckrxnurgm8d2bcvscamc, #tinytable_8896snxnh2elr2k0la52 th.tinytable_css_ckrxnurgm8d2bcvscamc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_8896snxnh2elr2k0la52\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Parameter</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Coefficient</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">SE</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">t</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">p</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">edu3mid</td>\n                  <td data-row=\"1\" data-col=\"2\">0.084900</td>\n                  <td data-row=\"1\" data-col=\"3\">0.005550</td>\n                  <td data-row=\"1\" data-col=\"4\">15.3000</td>\n                  <td data-row=\"1\" data-col=\"5\">1.60e-14</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">edu3high</td>\n                  <td data-row=\"2\" data-col=\"2\">0.164000</td>\n                  <td data-row=\"2\" data-col=\"3\">0.009090</td>\n                  <td data-row=\"2\" data-col=\"4\">18.0000</td>\n                  <td data-row=\"2\" data-col=\"5\">3.34e-16</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">munemp</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.003630</td>\n                  <td data-row=\"3\" data-col=\"3\">0.001100</td>\n                  <td data-row=\"3\" data-col=\"4\">-3.3100</td>\n                  <td data-row=\"3\" data-col=\"5\">2.74e-03</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">edu3mid:munemp</td>\n                  <td data-row=\"4\" data-col=\"2\">0.001650</td>\n                  <td data-row=\"4\" data-col=\"3\">0.001120</td>\n                  <td data-row=\"4\" data-col=\"4\">1.4700</td>\n                  <td data-row=\"4\" data-col=\"5\">1.54e-01</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">edu3high:munemp</td>\n                  <td data-row=\"5\" data-col=\"2\">0.000141</td>\n                  <td data-row=\"5\" data-col=\"3\">0.001480</td>\n                  <td data-row=\"5\" data-col=\"4\">0.0954</td>\n                  <td data-row=\"5\" data-col=\"5\">9.25e-01</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">edu3mid:mgrowth</td>\n                  <td data-row=\"6\" data-col=\"2\">-0.000963</td>\n                  <td data-row=\"6\" data-col=\"3\">0.000955</td>\n                  <td data-row=\"6\" data-col=\"4\">-1.0100</td>\n                  <td data-row=\"6\" data-col=\"5\">3.22e-01</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">edu3high:mgrowth</td>\n                  <td data-row=\"7\" data-col=\"2\">-0.003240</td>\n                  <td data-row=\"7\" data-col=\"3\">0.000986</td>\n                  <td data-row=\"7\" data-col=\"4\">-3.2800</td>\n                  <td data-row=\"7\" data-col=\"5\">2.94e-03</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {#tbl-claim2 .cell tbl-cap='The education gap and its interaction with unemployment on the cosmopolitan scale, under three designs and two rules for the respondents who named nothing. The published model is fitted on the real respondents with OA\\'s covariates and random intercepts for countries and country-waves; the fixed-effects model on the same respondents with errors clustered by country-year; the cell model on the education-band panel, which is built under the zero rule. Coefficient, with t in brackets. The first row is OA\\'s Table 3, Model 1.'}\n\n```{.r .cell-code}\nfitted_rows <- claim2 |>\n  filter(outcome == \"cosmo\",\n         term %in% c(\"unemployment\", \"education: high\", \"mid x unemployment\", \"high x unemployment\")) |>\n  mutate(rule = if_else(grepl(\"dropped\", model), \"no-opinion dropped\", \"no-opinion scored zero\"),\n         design = case_when(grepl(\"^published\", model) ~ \"published model, respondents\",\n                            level == \"respondent\"      ~ \"fixed effects, respondents\",\n                            TRUE                       ~ \"fixed effects, education-band cells\"),\n         value = paste0(fmt(estimate), \" (\", fmt(statistic, 2), \")\")) |>\n  select(design, rule, term, value) |>\n  pivot_wider(names_from = term, values_from = value) |>\n  arrange(design, rule)\noa_row <- tibble(design = \"OA, Table 3 Model 1\", rule = \"no-opinion dropped\",\n                 unemployment = \"−0.0034 (−4.03)\", `education: high` = \"0.0771 (41.79)\",\n                 `mid x unemployment` = \"−0.0014 (−3.23)\", `high x unemployment` = \"−0.0031 (−6.93)\")\nbind_rows(oa_row, fitted_rows) |>\n  select(design, rule, unemployment, `education: high`, `mid x unemployment`, `high x unemployment`) |>\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_h8c19fm2pt3to2kau7iu = TinyTable.createTableFunctions(\"tinytable_h8c19fm2pt3to2kau7iu\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 1 }, { i: '6', j: 2 }, { i: '6', j: 3 }, { i: '6', j: 4 }, { i: '6', j: 5 }, { i: '6', j: 6 } ], css_id: 'tinytable_css_a1mau0v9h7t55u0ziw7j',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_kc29ot1qz6t1ykrd6qz4',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_h8c19fm2pt3to2kau7iu.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_h8c19fm2pt3to2kau7iu td.tinytable_css_a1mau0v9h7t55u0ziw7j, #tinytable_h8c19fm2pt3to2kau7iu th.tinytable_css_a1mau0v9h7t55u0ziw7j {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_h8c19fm2pt3to2kau7iu td.tinytable_css_kc29ot1qz6t1ykrd6qz4, #tinytable_h8c19fm2pt3to2kau7iu th.tinytable_css_kc29ot1qz6t1ykrd6qz4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_h8c19fm2pt3to2kau7iu\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">design</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">rule</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">unemployment</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">education: high</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">mid x unemployment</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">high x unemployment</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">OA, Table 3 Model 1</td>\n                  <td data-row=\"1\" data-col=\"2\">no-opinion dropped</td>\n                  <td data-row=\"1\" data-col=\"3\">−0.0034 (−4.03)</td>\n                  <td data-row=\"1\" data-col=\"4\">0.0771 (41.79)</td>\n                  <td data-row=\"1\" data-col=\"5\">−0.0014 (−3.23)</td>\n                  <td data-row=\"1\" data-col=\"6\">−0.0031 (−6.93)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">fixed effects, education-band cells</td>\n                  <td data-row=\"2\" data-col=\"2\">no-opinion scored zero</td>\n                  <td data-row=\"2\" data-col=\"3\">−0.0036 (−3.31)</td>\n                  <td data-row=\"2\" data-col=\"4\">0.1637 (18.01)</td>\n                  <td data-row=\"2\" data-col=\"5\">0.0016 (1.47)</td>\n                  <td data-row=\"2\" data-col=\"6\">0.0001 (0.10)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">fixed effects, respondents</td>\n                  <td data-row=\"3\" data-col=\"2\">no-opinion dropped</td>\n                  <td data-row=\"3\" data-col=\"3\">−0.0030 (−3.45)</td>\n                  <td data-row=\"3\" data-col=\"4\">0.0943 (27.56)</td>\n                  <td data-row=\"3\" data-col=\"5\">0.0003 (0.48)</td>\n                  <td data-row=\"3\" data-col=\"6\">−0.0014 (−1.75)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">fixed effects, respondents</td>\n                  <td data-row=\"4\" data-col=\"2\">no-opinion scored zero</td>\n                  <td data-row=\"4\" data-col=\"3\">−0.0033 (−4.25)</td>\n                  <td data-row=\"4\" data-col=\"4\">0.1174 (35.61)</td>\n                  <td data-row=\"4\" data-col=\"5\">0.0016 (2.04)</td>\n                  <td data-row=\"4\" data-col=\"6\">−0.0001 (−0.07)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">published model, respondents</td>\n                  <td data-row=\"5\" data-col=\"2\">no-opinion dropped</td>\n                  <td data-row=\"5\" data-col=\"3\">−0.0044 (−5.74)</td>\n                  <td data-row=\"5\" data-col=\"4\">0.0933 (50.01)</td>\n                  <td data-row=\"5\" data-col=\"5\">−0.0011 (−2.77)</td>\n                  <td data-row=\"5\" data-col=\"6\">−0.0029 (−6.82)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">published model, respondents</td>\n                  <td data-row=\"6\" data-col=\"2\">no-opinion scored zero</td>\n                  <td data-row=\"6\" data-col=\"3\">−0.0051 (−6.60)</td>\n                  <td data-row=\"6\" data-col=\"4\">0.1162 (62.81)</td>\n                  <td data-row=\"6\" data-col=\"5\">0.0004 (0.95)</td>\n                  <td data-row=\"6\" data-col=\"6\">−0.0014 (−3.23)</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nRead the table one row at a time, because the rows tell the story in order. The published design under the published rule reproduces OA's interaction almost exactly, −0.0029 against her −0.0031, with the same t to the first decimal, and the other terms of the row sit within the distance one would expect between her Eurostat unemployment series and the course's World Bank series. That row is the reproduction, and it is the one to quote. The next row changes one thing, the rule for the respondents who named no item at all: OA's code dropped them, because dividing by a mentions total of zero left them missing, and the course scores them zero on every scale, as the Multi100 reanalyses did. The interaction halves. The respondents who name nothing are disproportionately low-educated, and scoring them zero pulls the low band's cosmopolitan mean down in every cell in a way that does not move with unemployment, so the gap between the bands and its movement both change. A decision that the [missing-answers module](missingness.qmd) files under measurement moves a coefficient at the top of the claim.\n\nThe fixed-effects rows change the design instead. With country and year effects in the model there is no level of unemployment left to estimate, only its difference between bands, identified from each band's own movement within its country; and under that design the interaction halves again under the published rule and loses conventional significance, and sits at zero under the zero rule. The cell row, fitted on 810 aggregates that anyone can download, agrees with the respondent-level fixed-effects row under the same rule, which is what it should do, and confirms that the aggregate route asks the question the respondent route asks. What the whole table says is that the claim is there under the design and the rule its author used, and thins out step by step as year effects enter and as the respondents who named nothing are kept rather than dropped. That is the finding of [section 5](#sec-designs) again, for a claim that lives one level down: OA's design carries no year effects, 2009 moved unemployment and framing everywhere at once, and the education bands did not move alike.\n\nThe paper's own results carry two qualifications that a replication should keep in view. The interaction holds for the cosmopolitan, communitarian and libertarian scales and not for the utilitarian one, where \"unemployment rate affects to the same extent the level of utilitarian framing of low-, middle-, and high-educated citizens\" (p. 628). And the second sentence of the hypothesis, that the gap would move more on the materialist scales, is contradicted by the paper's own table: \"in contrast to my hypothesis, the interactions between education and unemployment rate are no larger for the materialist dimensions of EU framing\" (p. 628). The [measurement module](measurement.qmd#sec-theory) says why that comparison presupposes a grouping the data only half support. The other three outcomes are in the committed table for anyone who wants to check the first qualification against the real respondents:\n\n\n::: {#tbl-claim2-outcomes .cell tbl-cap='The high × unemployment interaction on all four scales: OA\\'s Table 3, Model 1, and the published model refitted on the real respondents with the no-opinion respondents dropped, as her code dropped them. Coefficient, with t in brackets.'}\n\n```{.r .cell-code}\nclaim2 |>\n  filter(grepl(\"^published\", model), grepl(\"dropped\", model), term == \"high x unemployment\") |>\n  transmute(outcome, refitted = paste0(fmt(estimate), \" (\", fmt(statistic, 2), \")\")) |>\n  left_join(tibble(outcome = c(\"cosmo\", \"util\", \"comm\", \"lib\"),\n                   published = c(\"−0.0031 (−6.93)\", \"−0.0004 (−1.73)\", \"0.0020 (5.63)\", \"0.0015 (4.84)\")),\n            by = \"outcome\") |>\n  select(outcome, published, refitted) |>\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_o8xf9ht2b10njx1psr19 = TinyTable.createTableFunctions(\"tinytable_o8xf9ht2b10njx1psr19\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_pxl1g2a1lrtygb26ezy2',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_s64s0wjs3zst9epw53u9',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_o8xf9ht2b10njx1psr19.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_o8xf9ht2b10njx1psr19 td.tinytable_css_pxl1g2a1lrtygb26ezy2, #tinytable_o8xf9ht2b10njx1psr19 th.tinytable_css_pxl1g2a1lrtygb26ezy2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_o8xf9ht2b10njx1psr19 td.tinytable_css_s64s0wjs3zst9epw53u9, #tinytable_o8xf9ht2b10njx1psr19 th.tinytable_css_s64s0wjs3zst9epw53u9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_o8xf9ht2b10njx1psr19\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">outcome</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">published</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">refitted</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">cosmo</td>\n                  <td data-row=\"1\" data-col=\"2\">−0.0031 (−6.93)</td>\n                  <td data-row=\"1\" data-col=\"3\">−0.0029 (−6.82)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">util</td>\n                  <td data-row=\"2\" data-col=\"2\">−0.0004 (−1.73)</td>\n                  <td data-row=\"2\" data-col=\"3\">−0.0002 (−0.82)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">comm</td>\n                  <td data-row=\"3\" data-col=\"2\">0.0020 (5.63)</td>\n                  <td data-row=\"3\" data-col=\"3\">0.0016 (4.81)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">lib</td>\n                  <td data-row=\"4\" data-col=\"2\">0.0015 (4.84)</td>\n                  <td data-row=\"4\" data-col=\"3\">0.0015 (4.99)</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n**A replication exercise of your own.** The pieces for a second exercise in the style of the first are all on this page: a claim card, an estimand statement, a public dataset on which the aggregate design runs in the browser lab or the workspace, the respondent file for anyone who built it, and OA's published values to reproduce. The menu is smaller than the first claim's and every axis of it is a decision you can defend or not: the frame set, the scoring rule, the rule for the respondents who named nothing, the education coding (the published three bands, or the four bands that keep students separate), the estimator (random intercepts, fixed effects, or cells), the sample, the weight, and whether growth enters beside unemployment. Declare one specification before you run it, run it, and set the interaction you get against the rows of the table above. The table already shows that two of those decisions, the design and the no-opinion rule, decide whether the claim is found, which is the multiverse of the first claim in miniature.\n\n::: {.callout-tip}\n## Try it\n\nRefit `m_edu` above with `edu3 * munemp` replaced by `edu3 * mgrowth` alone, and read the growth interactions against the paper's claim that \"GDP growth impacts mainly on the EU framing of low-educated citizens\" (p. 619). Then refit the cosmopolitan model with the utilitarian scale as the outcome and read the interaction that the paper found absent.\n:::\n\n## Sources {#sec-sources}\n\nThe specification is OA's published Table 3 Model 1 with its cross-level interactions dropped, taken from the author-provided Stata code in the SCORE dossier [@Teney2016DoesEUEconomic]. The twin is generated by `companion/_model-outputs/simulate_person_joint.R` from the public country-year panel and committed calibration files; the calibration was estimated once, locally, from a person-level rebuild of the sixteen GESIS waves that is never committed and never redistributed – [the repositories module](repositories.qmd#sec-gesis) explains that regime. The validation table comes from `validate_twin.R`, the real-data multilevel reference from `fit_person_multilevel.R`, and the prevalence gradient from `fit_person_anchor.R`, all in the same folder. Every model on this page is fitted when it is built, from files that ship with the site.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}